### ISSUE TITLE
additional meta Content-Type is added to HTML5

### ISSUE THREAD

**Issue by stefanneculai** [sparklemotion/nokogiri#1008]
Hello guys,

I have the following HTML file test.html.

``` HTML
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta charset="UTF-8">
  </head>
  <body>
  </body>
</html>
```

I am opening the file with Nokogiri and then write it back to another file.

``` RUBY
doc = Nokogiri::HTML::Document.parse(File.open('test.html').read)
File.open('output.html', 'w') do |f|
  f.puts doc.to_s
end
```

The output file will contain <code>meta http-equiv="Content-Type" content="text/html; charset=UTF-8"</code> although the meta charset for HTML5 is set.

``` HTML
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Test</title>
<meta charset="UTF-8">
</head>
<body>
  </body>
</html>
```

Any idea how I could fix it not to add that meta tag which is for HTML4 and not for HTML5?

I am using nokogiri-1.6.0.

Any help is appreciated. Thanks!

**Comment by XhmikosR** [comment]
Any news on this?

**Comment by flavorjones** [comment]
Hi, apologies for the extremely slow reply. Nokogiri does not support HTML5. You may want to check out the [Nokogumbo](https://github.com/rubys/nokogumbo) project, which aims for HTML5 compatibility with the [Gumbo](https://github.com/google/gumbo-parser#readme) parser.
