### ISSUE TITLE
Does nokogiri support xsd 1.1 now?

### ISSUE THREAD

**Issue by larryzhao** [sparklemotion/nokogiri#1024]
Does nokogiri support new features like `<xs:assert test="metric2 > metric1"/>` ?

**Comment by fidalgo** [comment]
Since I've faced the same question, due the presence of assertions (https://www.w3.org/TR/xmlschema11-1/#cAssertions) in a XSD document, I would like to raise this question too?

**Comment by nobletrout** [comment]
how do you know if the nokogiri you are using is using libxml or something else?

**Comment by flavorjones** [comment]
@nobletrout You can run `nokogiri -v` on the command line, or inspect `Nokogiri::VERSION_INFO`.
