### ISSUE TITLE
Invalid characters in CDATA

### ISSUE THREAD

**Issue by runa** [sparklemotion/nokogiri#1027]
Hello :)
I've found that Nokogiri could generate invalid XML files when strings passed to `cdata` include invalid bytes (for the cdata spec)

For example

``` ruby
builder = Nokogiri::XML::Builder.new(:encoding => 'utf-8') do |xml|

    xml.item(:type => :topping){
      xml.attribute{
        xml.cdata "Sliced Avocado\u0002"
      }
    }

end
puts builder.to_xml
```

Then, when I try to validate the output XML (using xmlstarlet) I get:

```
-:3.37: CData section not finished
Sliced Avoca
  <attribute><![CDATA[Sliced Avocado]]></attribute>
                                    ^
-:3.37: PCDATA invalid Char value 2
  <attribute><![CDATA[Sliced Avocado]]></attribute>
                                    ^
-:3.38: Sequence ']]>' not allowed in content
  <attribute><![CDATA[Sliced Avocado]]></attribute>
                                     ^
-:3.38: internal error: detected an error in element content

  <attribute><![CDATA[Sliced Avocado]]></attribute>
                                     ^
-:3.38: Extra content at the end of the document
  <attribute><![CDATA[Sliced Avocado]]></attribute>
```

I was expecting Nokogiri to cleanup (or at least complain) when invalid content was passed to `cdata`

**Comment by flavorjones** [comment]
Thank you for reporting this, and apologies for taking such a long time to respond.

The behavior you're describing comes from the underlying parser, libxml2, and so there's not much Nokogiri can easily do to change that behavior. For prior conversation on this topic, see this libxml2 mailing list thread:

https://bugzilla.gnome.org/show_bug.cgi?id=739574

In particular, note the responses of the maintainers:

> I don't like the idea of silently dropping characters. When someone use libxml2
> API and it takes an xmlChar * the contract is that the string is UTF-8 with chars
> in the acceptable range for XML.
> If you end up with characters in the tree that are not serializable an error should be raised, either relying on the parser on the receiving end (XML is strict for this) or failing the conversion. Dropping is not acceptable for XML
> it's okay for HTML though.
> 
> Now the question is should libxml2 check all its API entry point to verify 
> that xmlChar* strings handled are compliant. I didn't do that for performance,
> I rely on the client respecting the API contract, it's way easier and cheaper
> for the client side to implement this in general.

and

> I agree with Daniel that we shouldn't change the default behavior of the serializer. Ideally, there would be two new serialization modes. One that checks for UTF-8 and Char validity and returns an error if invalid data was found. Then another one that tries to sanitize invalid data. This is best done by replacing invalid characters with the Unicode replacement character U+FFFD.

I'm sorry that I'm not able to help more.
