### ISSUE TITLE
Parse wbr element as singleton element

### ISSUE THREAD

**Issue by lulalala** [sparklemotion/nokogiri#1044]
Nokogiri treats wbr element as requiring closing tag, but the HTML5 spec says it does not need end tag. http://www.w3.org/TR/html5/text-level-semantics.html#the-wbr-element

We become aware of this when excess number of wbr elements are used, Nokogiri will then hit a nesting limit and discard contents after that.

https://gist.github.com/lulalala/8857130 is an example of this. The original HTML and the parsed version are different in that texts after the long cluster of wbr elements are omitted, probably due to too many nesting of wbr elements.

**Comment by flavorjones** [comment]
Nokogiri's underlying HTML parsers (libxml2 for CRuby, nekoHTML for JRuby) are HTML4 parsers, and so for some time there hasn't been much we can do to help with HTML5 other than to recommend that people use the Nokogumbo gem, which extends Nokogiri's API and provides an HTML5 parser.

I'm happy to let you know that #2204 is driving the merger of Nokogumbo and its HTML5 parser, and so Nokogiri v1.12 will support HTML5 once it is release. Please follow that issue for status updates.
