### ISSUE TITLE
ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by rafaeldl** [sparklemotion/nokogiri#1046]
Hello,

can someone help me with this problem?

OS: Ubuntu 12.04 server

Libs already installed: libxslt-dev libxml2-dev libxslt1-dev libxml2-dev

~~~
$ sudo gem install nokogiri
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb

Gem files will remain installed in /var/lib/gems/1.9.1/gems/nokogiri-1.6.1 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/nokogiri-1.6.1/ext/nokogiri/gem_make.out
~~~

**Comment by flavorjones** [comment]
Hi, many issues with installation were solved over the last year. Can you please let us know if you're still having issues by emailing the `nokogiri-talk` mailing list, as requested at http://www.nokogiri.org/tutorials/getting_help.html ?

Thanks,
-mike
