### ISSUE TITLE
Relative path to compile.log

### ISSUE THREAD

**Issue by p-originate** [sparklemotion/nokogiri#1051]
<pre>
oyster% gem install nokogiri -v '1.6.1'
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

        /home/me/.rbenv/versions/1.9.3-p484/bin/ruby extconf.rb
Extracting libxml2-2.8.0.tar.gz into tmp/x86_64-linux-gnu/ports/libxml2/2.8.0... OK
Running 'configure' for libxml2 2.8.0... OK
Running 'compile' for libxml2 2.8.0... ERROR, review 'tmp/x86_64-linux-gnu/ports/libxml2/2.8.0/compile.log' to see what happened.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/me/.rbenv/versions/1.9.3-p484/bin/ruby
/home/me/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mini_portile-0.5.2/lib/mini_portile.rb:265:in `block in execute': Failed to complete compile task (RuntimeError)
        from /home/me/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mini_portile-0.5.2/lib/mini_portile.rb:257:in `chdir'
        from /home/me/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mini_portile-0.5.2/lib/mini_portile.rb:257:in `execute'
        from /home/me/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mini_portile-0.5.2/lib/mini_portile.rb:69:in `compile'
        from /home/me/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/mini_portile-0.5.2/lib/mini_portile.rb:109:in `cook'
        from extconf.rb:101:in `block in <main>'
        from extconf.rb:119:in `call'
        from extconf.rb:119:in `block in <main>'
        from extconf.rb:109:in `tap'
        from extconf.rb:109:in `<main>'

Gem files will remain installed in /home/me/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/nokogiri-1.6.1 for inspection.
Results logged to /home/me/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/nokogiri-1.6.1/ext/nokogiri/gem_make.out
</pre>

The important line is this:

<pre>

Running 'compile' for libxml2 2.8.0... ERROR, review 'tmp/x86_64-linux-gnu/ports/libxml2/2.8.0/compile.log' to see what happened.
</pre>

That is not an absolute path, therefore I don't know where to find this file.

` find /tmp -name compile.log` finds nothing.

A separate issue is nokogiri appears to build libxml2 when the latter is already installed on my system.

**Comment by flavorjones** [comment]
Hi,

Thanks for asking this question. I apologize for not responding earlier, but there was a period of time where github issues weren't watched closely.

The gem compilation stage is generally done in a directory determined by your Ruby (or your Ruby version manager, e.g. rvm / rbenv / what-have-you). That's generally where you'll need to look for that `compile.log` file.

You may want to ask questions like this on the nokogiri-talk mailing list. Details are at http://www.nokogiri.org/tutorials/getting_help.html
