### ISSUE TITLE
NOKOGIRI_USE_SYSTEM_LIBRARIES is not documented

### ISSUE THREAD

**Issue by p-originate** [sparklemotion/nokogiri#1052]
http://nokogiri.org/tutorials/installing_nokogiri.html says nothing about the subject.

**Comment by flavorjones** [comment]
The `--use-system-libraries` option, along with most of the other available options, is now documented in the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by tibbon** [comment]
That raises an error for me now: 

```
gem install nokogiri --use-system-libraries -v '1.8.4' --source 'https://rubygems.org/'
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --use-system-libraries
```

**Comment by ar7max** [comment]
An example from [this page](http://www.nokogiri.org/tutorials/installing_nokogiri.html):
`gem install nokogiri -- --use-system-libraries`


`

**Comment by flavorjones** [comment]
@tibbon please make sure you've got `--` in your `gem install` command _before_ you use `--use-system-libraries`.

You used:

```
gem install nokogiri --use-system-libraries
```

but the documented syntax is

```
gem install nokogiri -- --use-system-libraries
```

Finally, this issue has been closed for over three years. If you have any further issues, please reach out on the nokogiri-talk mailing list, gitter, IRC, or open a new issue. Thanks!
