### ISSUE TITLE
XML::Text#native_content= should not escape content

### ISSUE THREAD

**Issue by y8** [sparklemotion/nokogiri#1053]
Currently `native_content=` method behaviour is inconsistent.

**Test case**:

``` ruby
require "nokogiri"

doc = Nokogiri::HTML.fragment('Text\n<em>element</em>')
doc.children.first.native_content = "You &amp; Me\n" # Fail
doc.children.last.native_content = "You &amp; Me" # Pass

puts doc.to_html
```

**Expected result**:

``` html
You &amp; Me
<em>You &amp; Me</em>
```
1. XML::Text node content is not escaped

**Actual result**:

``` html
You &amp;amp; Me
<em>You &amp; Me</em>
```
1. XML::Text node content is escaped, but it shouldn't 

**Regression:** n/a

**Comment by flavorjones** [comment]
Well, the C function that implements `Node#native_content=` for both `Text` and `Node` calls [`xmlNodeSetContent`](https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-tree.html#xmlNodeSetContent) which is documented as follows:

> Replace the text content of a node. Sets the raw text content of text, CDATA, comment or PI nodes.
>
> For element and attribute nodes, removes all children and replaces them by parsing @content which is expected to be a valid XML attribute value possibly containing character and entity references.

I acknowledge that this behavior is inconsistent, but we've labeled it as such by naming it _native_ content (meaning, this is the underlying parser's method). The ruby method `Node#content=` is the method that is consistent, treating the input as a raw HTML string and escaping in both Text and Node contexts.

I guess we could introduce a new method that allows you to set non-raw text? Essentially this would be `content = CGI::unescapeHTML(value)`, though, which I think is arguably clearer than inventing a new method like `#escaped_content=`.

**Comment by flavorjones** [comment]
I've tried to improve the documentation in 47626c8a
