### ISSUE TITLE
Apparent memory leak when duping DocumentFragment

### ISSUE THREAD

**Issue by bryanp** [sparklemotion/nokogiri#1063]
Ruby 2.1, Nokogiri 1.6.1

Title explains the issue I'm seeing. Here's a simple case to reproduce:

``` ruby
puts `ps -o rss= -p #{$$}`.to_i
doc = Nokogiri::HTML.fragment('<div>foo<span>bar</span></div>')
10000.times do
  doc.dup
  GC.start
end
puts `ps -o rss= -p #{$$}`.to_i
```

Memory usage goes from 11.9KB to 18.7KB. The contents of the fragment do not seem to matter but the bigger the fragment the bigger the leak (ran it with a large fragment and it peaked at > 1GB).

Having trouble with valgrind on OSX so unable to provide that analysis. It should be clear there's a problem if you run it. Compare to this example, which does not continue to eat up memory (from 11.12KB to 11.16KB):

``` ruby
doc = Nokogiri::HTML::Document.parse('<div>foo<span>bar</span></div>')
puts `ps -o rss= -p #{$$}`.to_i
10000.times do
  doc.dup
  GC.start
end
puts `ps -o rss= -p #{$$}`.to_i
```

Happy to provide more info if necessary.

**Comment by flavorjones** [comment]
Some notes:
* verified this leak with Nokogiri 1.7.0.1 using libxml 2.9.4 with patches
* leak does not occur when re-parsing fragments in a loop
* leak does not occur when duping a full Document
* leak does occur when duping a DocumentFragment

**Comment by flavorjones** [comment]
OK, this is because `DocumentFragment#dup` inherits from `Node`, which is copying the node subtree and rooting it in the doc. These unparented nodes just hang around for the lifetime of the doc.

Suggestion: we could implement `DocumentFragment#dup` to copy the DocumentFragment's parent Document, and thus treat it more like a full-blown Document (which I think is what people generally expect).

**Comment by flavorjones** [comment]
I've addressed this in MRI by copying nodes directly to the new Document. However, I'm having trouble with the java implementation. WIP is on branch `1063-flavorjones-dup-document-fragment`.

Moved this into the 1.8.3 milestone, sorry for the delay.

**Comment by dan42** [comment]
Hello, just chiming in to say I encountered the same memory leak, and I'm using this code to get around it.

```ruby
# Just doing root.dup would result in the duplicate being attached to the
# same document as the original. As long as the original exists, every
# copy is also kept in memory, causing a crippling memory leak.
# So we need to go a roundabout way to create a copy that's disassociated
# from the original's document.
def clone_node(root)
  @empty_doc ||= parse("") #where parse wraps Nokogiri.HTML5
  case root
  when Nokogiri::XML::Element
    e = @empty_doc.dup #create a new document
    deepcopy = root.dup #create a deep copy of the element
    e.root << deepcopy #add it into the new doc, which creates a shallow copy of the element
    e.root.last_element_child #retrieve the copy
  when Nokogiri::XML::Text
    e = @empty_doc.dup #create a new document
    deepcopy = root.dup #create a deep copy of the node
    e.root << deepcopy #add it into the new doc, which changes the document
    deepcopy
  when Nokogiri::XML::DocumentFragment
    e = @empty_doc.dup #create a new document
    f = root.class.new(e) #create a new fragment
    root.children.each do |node| #for each element
      deepcopy = node.dup #create a deep copy
      f << deepcopy #add into the new fragment (which may create a shallow copy of the node)
    end
    f
  else #Document
    root.dup
  end
end
```

But imho the real fix is that when doing a `dup` or `remove`, the node can still reference the document, but the document should no longer reference the node. Although tbh I don't know if that's a libxml issue or not.

**Comment by flavorjones** [comment]
OK - I've got a second branch up in which I punt on trying to implement this optimization in the JRuby implementaiton. branch is `1063-flavorjones-dup-document-fragment-attempt-2` and I'm going to poke @jvshahid about this decision in the morning.

**Comment by flavorjones** [comment]
Chatted with @jvshahid and he agrees we should just address this issue in the libxml2/MRI code base and leave JRuby alone, at least for now. I've created #1832 to track this work for JRuby should eventually decide to do it.

Will ship a PR based on the above mentioned branch.
