### ISSUE TITLE
mini_portile issue on Solaris/Illumos

### ISSUE THREAD

**Issue by geoff-codes** [sparklemotion/nokogiri#1064]
From http://nokogiri.org/tutorials/installing_nokogiri.html:
> Because Nokogiri needs to be compiled and dynamically linked against both libxml2 and libxslt, it has gained a reputation for being complicated to install.

I have isolated/identified three (under various circumstances) bugs / reasons for this.
All of them are due to the dependency on mini_portile. See the [changes and line notes here](https://github.com/pullreq/mini_portile/commit/d9fa29d358bcdff1febe4f63d192d4a137fc9a12#diff-4412014f0bf9b2fbbaa856b0b3722d00).

Unfortunately, my PR to the upstream project was rejected due to the fact that the changes proposed would not work on Windows, and I admit I do not have a solution to that, largely because I do not have a way to test Windows. However, in the particular case of Nokogiri, since:

> Luckily for you, building on Windows is so difficult that we’ve done it for you: Nokogiri comes bundled with all the DLLs you need to be NOKOGIRIFIED.

And therefore mini_portile's Windows support isn't necessary here, would you be open to pulling in a modified mini_portile.rb, since the entire thing is one file (less than 400 LOC)?

**Comment by flavorjones** [comment]
Ah - I can see your branch now. Must have taken github a bit to synchronize. Will look into it.

**Comment by geoff-codes** [comment]
Ack! Sorry I didn't get back to you sooner. Must have slipped by me.

Let me know if you need me to clarify anything on this.

**Comment by flavorjones** [comment]
This is fixed in flavorjones/mini_portile@b48882f, which will be in mini_portile v2.0 that we'll be cutting soon, and that will be pulled into nokogiri 1.6.7.

Thanks for your patience.
