### ISSUE TITLE
Nokogiri::XML::Reader for java keeps whole document in memory

### ISSUE THREAD

**Issue by pablito** [sparklemotion/nokogiri#1066]
I have the following code:

```
require 'nokogiri'

reader = Nokogiri::XML::Reader(File.open('5258513130_report.xml'))
i = 0
reader.each do |node|
  i += 1
  break if i == 5000
end

puts "it's time to dump the heap..."
sleep
```

5258513130.xml is

```
<?xml version="1.0" encoding="utf-8"?>
<BulkDataExchangeResponses xmlns="urn:ebay:apis:eBLBaseComponents">
<ActiveInventoryReport>

<SKUDetails>
<SKU>7544569</SKU>
<Price currencyID="EUR">103.99</Price>
<Quantity>35</Quantity>
<ItemID>111298416963</ItemID>
</SKUDetails>
<SKUDetails>
<SKU>22783396</SKU>
<Price currencyID="EUR">148.35</Price>
<Quantity>9</Quantity>
<ItemID>111298416964</ItemID>
</SKUDetails>
...
</ActiveInventoryReport>
</BulkDataExchangeResponses>
```

as you can see from the following snapshots of the heap dump the reader is keeping in memory all the 5000 nodes it has found, this doesn't happen in MRI ruby 2.0.0p247

nodeQueue.size = 5001
![image](https://f.cloud.github.com/assets/78922/2426718/3db19d44-abcb-11e3-914d-2f6c3bb902da.png)

ReaderNode$ClosingNode 1249 instances
ReaderNode$ElementNode 1252 instances
ReaderNode$TextNode       2502 instances
![image](https://f.cloud.github.com/assets/78922/2426899/a3db1548-abce-11e3-9e2f-59e5c31741be.png)

my config:
nokogiri (1.5.10 java)
jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on OpenJDK 64-Bit Server VM 1.7.0_51-b00 +indy [linux-amd64]

**Comment by flavorjones** [comment]
Closing this in favor of #2224 which describes the same issue in a bit more detail.
