### ISSUE TITLE
How to escape non HTML tags?

### ISSUE THREAD

**Issue by brauliobo** [sparklemotion/nokogiri#1067]
Hello all,

I need to parse a HTML and escape any tag (<>) that is not a standard HTML tag, How can I do that?

regards,
bráulio

**Comment by flavorjones** [comment]
You may want to take a look at [Loofah](https://github.com/flavorjones/loofah) or [rgrove/sanitize: Ruby HTML and CSS sanitizer.](https://github.com/rgrove/sanitize) for sanitizing your HTML.
