### ISSUE TITLE
ArgumentError: unknown encoding name - UTF-8

### ISSUE THREAD

**Issue by elfassy** [sparklemotion/nokogiri#1068]
```
ArgumentError: unknown encoding name - UTF-8;
from /Users/michaelelfassy/.rvm/gems/ruby-2.0.0-p247/gems/nokogiri-1.6.1/lib/nokogiri/xml/node.rb:727:in `find'
```

I'm stuck on this, anyone have an idea what i'm missing? I only get this error when calling `inner_html` 

I've made sure to add `# encoding: UTF-8` at the top of my rake file but it didn't help.

thanks!

**Comment by flavorjones** [comment]
@andrepcg Commenting on an issue that has been closed for over 10 years is not likely to have the outcome you're hoping for. Please open a new issue if you want to have a meaningful discussion. Thanks.
