### ISSUE TITLE
Nokogiri clears out externally set XML handlers

### ISSUE THREAD

**Issue by djmb** [sparklemotion/nokogiri#1075]
In a few places, Nokogiri sets and then unsets the LibXML structured error handler by calling `xmlSetStructuredErrorFunc` (e.g. https://github.com/sparklemotion/nokogiri/blob/669799790067a80ea34f8be5645e52acf434322b/ext/nokogiri/xml_reader.c#L465-L467).

As a result we lose any error handlers set externally to Nokogiri (for example via libxml-ruby's `LibXML::XML::Error.set_handler`).

Instead, it should store the existing error handler and restore it afterwards.

**Comment by flavorjones** [comment]
Worth noting, I just added some measure of test coverage for `libxml-ruby` interactions, so if you'd like to send a PR which contains both a test and fixes, I will happily consider merging it.

**Comment by flavorjones** [comment]
This request has found a new life in https://github.com/sparklemotion/nokogiri/issues/2172
