### ISSUE TITLE
JRuby-Nokogiri errors with “can't modify frozen string”

### ISSUE THREAD

**Issue by ddfreyne** [sparklemotion/nokogiri#1077]
`Nokogiri::XML.fragment` cannot be used on frozen strings. (`Nokogiri::XML.parse` is not affected).

### Steps to reproduce

Execute the following on JRuby and MRI:

```ruby
input = <<-EOS
<?xml version="1.0" encoding="utf-8"?>
<library>
  <book title="I like turtles"/>
</library>
EOS
input.freeze

require 'nokogiri'
::Nokogiri::XML.fragment(input)
```

### Expected output

No exception raised.

### Actual output

```
RuntimeError: can't modify frozen string
    chomp! at org/jruby/RubyString.java:5761
       new at nokogiri/XmlDocumentFragment.java:93
     parse at /Users/ddfreyne/.gem/jruby/1.9.3/gems/nokogiri-1.6.1-java/lib/nokogiri/xml/document_fragment.rb:91
  fragment at /Users/ddfreyne/.gem/jruby/1.9.3/gems/nokogiri-1.6.1-java/lib/nokogiri/xml.rb:69
    (root) at test2.rb:10
```

### Notes

In [XmlDocumentFragment.java lines 115-119](https://github.com/sparklemotion/nokogiri/blob/master/ext/java/nokogiri/XmlDocumentFragment.java#L115-L119), the `#chomp!` method is used on the input argument, which fails for frozen strings:

```java
// strips trailing \n off forcefully
// not to return new object in case of no chomp needed, chomp! is used here.
IRubyObject result;
if (context.getRuntime().is1_9()) result = str.chomp_bang19(context);
else result = str.chomp_bang(context);
```

**Comment by flavorjones** [comment]
We never resolved this issue. #444 seems pretty unimportant relative to the frozen string issue described here, and I'm inclined to remove the `trim` call from `XmlDocumentFragment.java`.

@yokolet, @jvshahid - any thoughts here?

**Comment by jvshahid** [comment]
Merged the `issue-1077-jruby-frozen-string` branch, but changed the fix slightly to use `chomp` insntead of `chomp!` as was suggested in the previous comments.

**Comment by flavorjones** [comment]
LGTM, thanks!

**Comment by jvshahid** [comment]
The change in this pr caused the build to be red. it looks like the two implementations has changed their behavior regarding #444, jruby doesn't include the newline but MRI (as of master) includes a newline character. I'm not sure how to fix this issue other than removing the new `test_444...` that was added. I also want to remove the call to `chomp` from the JRuby implementation. I'm against these kinds of hacks that help fix minor edge cases/differences between the two implementation. Any objections ?

**Comment by flavorjones** [comment]
My vote was originally, and is still today, to remove the trim/chomp from
JRuby. I believe this will make it match MRI behavior, and if so, :shipit:
