### ISSUE TITLE
Unable to install nokogiri gem

### ISSUE THREAD

**Issue by hackjoy** [sparklemotion/nokogiri#1082]
Hi, i'm using OSX 10.9.2 and Ruby 2.1.1 installed with rbenv. 
When running `$ sudo gem install nokogiri -v '1.6.1'` I receive the following error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
    ERROR: Failed to build gem native extension.

    /usr/local/var/rbenv/versions/2.1.1/bin/ruby extconf.rb
Extracting libxml2-2.8.0.tar.gz into tmp/i686-apple-darwin11/ports/libxml2/2.8.0... OK
Running 'configure' for libxml2 2.8.0... ERROR, review 'tmp/i686-apple-darwin11/ports/libxml2/2.8.0/configure.log' to see what happened.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/var/rbenv/versions/2.1.1/bin/ruby
/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:278:in `block in execute': Failed to complete configure task (RuntimeError)
    from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:270:in `chdir'
    from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:270:in `execute'
    from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:65:in `configure'
    from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:108:in `cook'
    from extconf.rb:101:in `block in <main>'
    from extconf.rb:119:in `call'
    from extconf.rb:119:in `block in <main>'
    from extconf.rb:109:in `tap'
    from extconf.rb:109:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.1 for inspection.
Results logged to /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/nokogiri-1.6.1/gem_make.out
```

I am using Homebrew and tried the installation steps listed on the nokogiri site: 
`brew install libxml2 libxslt`
`brew link libxml2 libxslt`
`wget http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.13.1.tar.gz`
`tar xvfz libiconv-1.13.1.tar.gz`
`cd libiconv-1.13.1`
`./configure --prefix=/usr/local/Cellar/libiconv/1.13.1`
`make`
`sudo make install`
Then I tried installing passing in the options as specified below:
`sudo gem install nokogiri -- --with-xml2-include=/usr/local/Cellar/libxml2/2.8.0/include/libxml2 --with-xml2-lib=/usr/local/Cellar/libxml2/2.8.0/lib --with-xslt-dir=/usr/local/Cellar/libxslt/1.1.28 --with-iconv-include=/usr/local/Cellar/libiconv/1.13.1/include --with-iconv-lib=/usr/local/Cellar/libiconv/1.13.1/lib'
`

This shows the same error as per above. 

A google search shows that this can be a common error https://www.google.co.uk/search?q=Running+%27configure%27+for+libxml2+2.8.0...+ERROR%2C+review&oq=Running+%27configure%27+for+libxml2+2.8.0...+ERROR%2C+review&aqs=chrome..69i57j69i59j0.238j0j4&sourceid=chrome&es_sm=91&ie=UTF-8#q=Running+'configure'+for+libxml2+2.8.0...+ERROR%2C+review&safe=off 

Some solutions recommend installing command line tools although I have xcode 5.1.1 which comes with command line tools I believe. 

I have also tried specifying that nokogiri should use the system libraries as one answer suggested:
`$ NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install nokogiri`

**Comment by brekkehj** [comment]
I resolved all the issues (OS X 10.10.1) above by updating my Ruby version through homebrew

```
brew install ruby
echo "export PATH=/usr/local/opt/ruby/bin:\$PATH" >> ~/.bash_profile
source ~/.bash_profile
gem install nokogiri
```

**Comment by jfl913** [comment]
@ahmadajmi  thank you.

**Comment by neilthawani** [comment]
@unimatrixZxero Thanks for the solution.

**Comment by liuchangdong** [comment]
sudo apt-get install libpq-dev
and then
sudo gem install nokogiri
