### ISSUE TITLE
Java version of HTML parser errors with self-closing base or meta tags

### ISSUE THREAD

**Issue by gkellogg** [sparklemotion/nokogiri#1086]
The following simple example generates an error:

    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
      </head>
    </html>

Nokogiri::HTML.parse(File.open("example-files/java-nokogiri-issue.html")).errors
 => [#<Nokogiri::XML::SyntaxError: Missing attribute name.>] 

Make meta not self-close, and the error goes away.

Nokogiri version: 1.6.1
jruby 1.7.11 (1.9.3p392) 2014-02-24 86339bb on Java HotSpot(TM) 64-Bit Server VM 1.7.0_10-b18 [darwin-x86_64]
Mac OS 10.9.2

**Comment by flavorjones** [comment]
Hmm. For me, this particular wart falls under the category of "underlying XML/HTML parsing engine deciding to correct markup differently than you might expect."

For context, there are two different parsing engines that Nokogiri uses: for MRI, we use libxml2; for JRuby we use xerces/nekohtml. Each has its own implementation of markup correction, which often differs.

In this particular case, they actuall both fix the invalid markup identically (and it **is** invalid HTML). The only differente being that one (xerces/nekohtml) decides to point out (correctly!) that this is a syntax error of sorts, while the other one (libxml2) silently handles it.

Unfortunately, there's not obvious or easy way for Nokogiri to modify the behavior of the underlying engines' markup-correction behavior.
