### ISSUE TITLE
Nokogiri's dependency on mini_portile has introduced a dependency on git

### ISSUE THREAD

**Issue by martinb3** [sparklemotion/nokogiri#1102]
Hello!

Apparently, the new release of nokogiri 1.6.2 installs its own version of various xml libraries, and uses mini_portile, which has an undeclared dependency on git being installed, see https://github.com/luislavena/mini_portile/issues/32.

If nokogiri is going to use this other project, it needs to declare some sort of git requirement somewhere.

This is likely the root cause for:

https://github.com/sparklemotion/nokogiri/issues/1095
https://github.com/sparklemotion/nokogiri/issues/1100
https://github.com/sparklemotion/nokogiri/issues/1099
https://github.com/sparklemotion/nokogiri/issues/1098

I know you have quite a few other issues open, and this duplicates them, but I wanted to call this out since many of the other issues had specific workarounds (a version of git apply was broken, or a git config setting was breaking things), but the root issue is the undeclared dependency on git.

Thanks!
@martinb3

**Comment by lfender6445** [comment]
:+1: gerggggggg  - same for me on Amazon Linux AMI release 2014.09

**Comment by flavorjones** [comment]
This issue was addressed and closed in May 2014. If you're experiencing an issue now, please open a new issue.
