### ISSUE TITLE
(JRuby) Nokogiri unable to parse RubyZip's streams in JRuby

### ISSUE THREAD

**Issue by weshatheleopard** [sparklemotion/nokogiri#1124]
When ```s.is_a?(Zip::InputStream)```, ```Nokogiri::XML.parse(s)``` works fine on all platforms, except for JRuby, where it fails:

<pre>
ArgumentError: must be kind_of String or respond to :to_io or :string
           read_io at nokogiri/XmlDocument.java:337
             parse at /home/hk/.rvm/gems/jruby-1.7.13@rubyxl-demo/gems/nokogiri-1.6.3.rc3-java/lib/nokogiri/xml/document.rb:52
[...]
</pre>

For original report by @heisee, see https://github.com/weshatheleopard/rubyXL/pull/124

**Comment by flavorjones** [comment]
Will be in the next Nokogiri release, likely 1.6.7.

**Comment by heisee** [comment]
Ah, very good, thank you all!
