### ISSUE TITLE
Nokogiri::HTML::DocumentFragment removes HTML and body tags

### ISSUE THREAD

**Issue by daliborfilus** [sparklemotion/nokogiri#1132]
I've just lost tens of minutes figuring a bug and then I got to this:

``` ruby
# correct
irb(main):017:0> Nokogiri::HTML.fragment('<body></body>').to_s
=> "<body></body>"

# wrong!
irb(main):018:0> Nokogiri::HTML.fragment('<html></html>').to_s
=> ""

# wrong!
irb(main):016:0> Nokogiri::HTML.fragment('<html><body></body></html>').to_s
=> ""

# wrong!
irb(main):021:0> Nokogiri::HTML.fragment('<html><head></head><body></body></html>').to_s
=> ""
```

How can I just transform few elements in html fragment when this is done to them?

I don't want DOCTYPE and html tags automatically appended/wrapped-with. In some cases I just have the body and it's children. How can I do this with Nokogiri when it does not respect my input?

P.S.: there is a "workaround". Nokogiri::XML.fragment does not do this, but it of course does not support HTML properly, so it is to no use to me at this moment.

**Comment by itsliamegan** [comment]
This is a very old issue, and I recognize per your this is clearly the intended behavior; however, does this mean that there is absolutely no way to parse an independent HTML `<head>` tag into a tree?

**Comment by flavorjones** [comment]
@itsliamegan Thanks for asking - and sorry my answer above wasn't totally clear.

I'm not at all trying to say this is _intended_ behavior, rather that Nokogiri is a thin layer on top of the underlying HTML parser (libxml2) and this behavior is deep within libxml2's state machine. libxml2 treats tags very differently depending on whether they're in the `<head>` or `<body>`, as the HTML spec instructs it to. Ordinarily that's fine, but in the context of a "fragment" it gets confusing. We've had to implement "fragments" as "a subtree of the `<body>` element" and as a result the head tag is invalid in a fragment context.

If you simply want an arbitrary DOM, you could try using the XML parser which doesn't have the same constraints as HTML4.

Or you could parse it as a full document (not just as a document fragment) using `Nokogiri::HTML::Document.parse`.

Without more context from you, it's hard to give more specific advice. I hope this is helpful?
