### ISSUE TITLE
Newlines in XML attributes

### ISSUE THREAD

**Issue by avinmathew** [sparklemotion/nokogiri#1145]
I'm trying to parse newlines in XML attributes, but it seems they are incorrectly converted to spaces:

```ruby
>> require 'nokogiri'
=> true
>> xml = <<EOS
<root attr="value
with
newlines"/>
EOS
=> "<root attr=\"value\nwith\nnewlines\"/>\n"
>> Nokogiri::XML(xml).to_xml
=> "<?xml version=\"1.0\"?>\n<root attr=\"value with newlines\"/>\n"
```
This occurs on both on both MRI and JRuby using Nokogiri 1.6.3.1.

Also see https://groups.google.com/forum/#!topic/nokogiri-talk/CwP1RAISrCw

**Comment by leejarvis** [comment]
Seems like this is what's recommended: http://www.w3.org/TR/1998/REC-xml-19980210#AVNormalize

**Comment by avinmathew** [comment]
According to that link, it looks like my original example was wrong, as it doesn't have normalised values.

```ruby
>> require 'nokogiri';
>> builder = Nokogiri::XML::Builder.new do |xml|
>>   xml.root(attr: "value\nwith\nnewlines")
>> end;
>> xml = builder.doc.root.to_xml
=> "<root attr=\"value&#10;with&#10;newlines\"/>"
>> Nokogiri::XML(xml).root.attributes['attr'].content
=> "value\nwith\nnewlines"
```
