### ISSUE TITLE
Nokogiri's extconf.rb should check checksums of downloaded dependencies

### ISSUE THREAD

**Issue by rtyler** [sparklemotion/nokogiri#1154]
Currently when `ext/extconf.rb` downloads zlib, libxml2, libxslt and libiconv to build on MRI it will download from the distribution sites and start compiling right away.

To ensure that Nokogiri is building known sources, `ext/extconf.rb` should contain some md5 or SHA1 checksums to validate the integrity of the downloaded source code.

**Comment by larskanis** [comment]
This is solved via https://github.com/sparklemotion/nokogiri/commit/1606b36cd082356d33b8b1aff40af9ce8276c793 .
