### ISSUE TITLE
Nokogiri is not correctly handling html5 entities 

### ISSUE THREAD

**Issue by SamSaffron** [sparklemotion/nokogiri#1173]
Many html entities are not being left alone by nokogiri, eg: &itilde; etc etc

```
Nokogiri::HTML.fragment("&aleph;").to_html
=> "&amp;aleph;"
Nokogiri::HTML.fragment("&gt;").to_html
=> "&gt;"
```

**Comment by flavorjones** [comment]
@jdickey - I'm terribly confused by your question -- why would you think we built against anything except Gnome's libxml2? We absolutely **do** use the tarballs provided by the GNOME project at xmlsoft.org.

You can see exactly whence we get our tarballs in `extconf.rb` and `dependencies.yml`:

> https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L455-L456
> https://github.com/sparklemotion/nokogiri/blob/master/dependencies.yml

and that these tarballs get packaged up in the `Rakefile` gem declarations:

> https://github.com/sparklemotion/nokogiri/blob/master/Rakefile#L214-L218

**Comment by flavorjones** [comment]
@jdickey If you'd like to be a part of the conversation about HTML5 support, great! Do you have any suggestions on how to implement this support without breaking backwards compatibility?

**Comment by jdickey** [comment]
I expect to have some free time late this coming week; I expect to be starting to dig into this to the point of at least asking rudimentarily intelligent questions. :)

**Comment by hubgit** [comment]
@flavorjones 

> I'm terribly confused by your question -- why would you think we built against anything except Gnome's libxml2?

@SamSaffron linked to the `https://github.com/ConradIrwin/libxml2/` repository in his comment earlier in this thread, as [the libxml sources](http://xmlsoft.org/sources/) are not published anywhere linkable by line number.

**Comment by hubgit** [comment]
Hopefully someone will add the [HTML5 character references](http://www.w3.org/TR/html5/syntax.html#named-character-references) to libxml's HTML parser (behind an optional flag, perhaps).

**Comment by SamSaffron** [comment]
I managed in some sort of "act of god" to post this on the mailing list. 

https://mail.gnome.org/archives/xml/2015-August/msg00000.html 

My understanding is that Daniel Veilard http://veillard.com/ @veillard is in charge of libxml2, in some sort of weird twist of fate he works with @tenderlove  so who know, we may be able to beg Aaron to ask him for help here :)

**Comment by tenderlove** [comment]
@SamSaffron "works with" is kind of an overstatement, more like "we share an employer". ;)

This patch should do the trick for this particular symbol:

```diff
diff --git a/HTMLparser.c b/HTMLparser.c
index 19c10c3..7986466 100644
--- a/HTMLparser.c
+++ b/HTMLparser.c
@@ -1833,6 +1833,7 @@ static const htmlEntityDesc  html40EntitiesTable[] = {
 { 8476,	"real",	"blackletter capital R = real part symbol, U+211C ISOamso" },
 { 8482,	"trade","trade mark sign, U+2122 ISOnum" },
 { 8501,	"alefsym","alef symbol = first transfinite cardinal, U+2135 NEW" },
+{ 8501,	"alef","alef symbol = first transfinite cardinal, U+2135 NEW" },
 { 8592,	"larr",	"leftwards arrow, U+2190 ISOnum" },
 { 8593,	"uarr",	"upwards arrow, U+2191 ISOnum" },
 { 8594,	"rarr",	"rightwards arrow, U+2192 ISOnum" },
```

Is there a place where we can get a canonical list for HTML 5 so we can do it in one patch?

@flavorjones It seems like [there is a green light for HTML 5 support in libxml2](https://mail.gnome.org/archives/xml/2013-April/msg00006.html), though someone has to do the work. :(

**Comment by hubgit** [comment]
> Is there a place where we can get a canonical list for HTML 5 so we can do it in one patch?

http://www.w3.org/TR/html5/syntax.html#named-character-references

**Comment by tenderlove** [comment]
@hubgit thanks, I think.... :fearful:

**Comment by tenderlove** [comment]
Looks like [there is a JSON version here](http://www.w3.org/TR/html5/entities.json).

**Comment by SamSaffron** [comment]
@tenderlove  :heart: :heart: :heart: 

I just found it incredibly hard to figure out how to submit PRs to libxml, joining the mailing list was mission enough. 

I wonder how we will upstream this fix though, even if we fix libxml are we talking 2 years till this hits nokogiri? or will nokogiri build off a fork?

**Comment by tenderlove** [comment]
> I just found it incredibly hard to figure out how to submit PRs to libxml, joining the mailing list was mission enough.

I don't think libxml2 does PRs.  [We have to submit a patch via bugzilla](https://wiki.gnome.org/Sysadmin/GitHub).

> I wonder how we will upstream this fix though, even if we fix libxml are we talking 2 years till this hits nokogiri? or will nokogiri build off a fork?

Nokogiri will build against whatever you point it at.  If you point it at a libxml2 installation that supports html5 entities, then nokogiri will Just Work™.

**Comment by SamSaffron** [comment]
> Nokogiri will build against whatever you point it at. If you point it at a libxml2 installation that supports html5 entities, then nokogiri will Just Work™.

This makes me soooo happy we ship Discourse as a Docker container, gives us a quick way of patching this :+1:

**Comment by jdickey** [comment]
@tenderlove so in other words, they have an open process, they just make it as non-transparent as they possibly can by using outdated technology. I loved Bugzilla back in the day, but I had hair then, too.

**Comment by flavorjones** [comment]
Closing this with a note that we're looking at pulling in Nokogumbo to make HTML5 parsing better: https://github.com/sparklemotion/nokogiri/issues/2064
