### ISSUE TITLE
SyntaxError when evaluating / compiling XPath

### ISSUE THREAD

**Issue by toshe** [sparklemotion/nokogiri#1180]
I'm using a library that generates odt files - [odf-report](https://github.com/sandrods/odf-report) that utilizes nokogiri to search, replace and generate ODF files. 

`Nokogiri::XML::XPath::SyntaxError at /some/path
.//text:section[@text:name='categorylevel1']
`

Traceback (innermost first)

`nokogiri/XmlXpathContext.java`: in `evaluate`
`JRuby-1715@backend/lib/ruby/gems/shared/gems/nokogiri-1.5.1-java/lib/nokogiri/xml/node.rb`: in `xpath`

```ruby
          ctx.register_namespaces(ns)
          path = path.gsub(/\/xmlns:/,'/:') unless Nokogiri.uses_libxml?

          binds.each do |key,value|
            ctx.register_variable key.to_s, value
          end if binds

          ctx.evaluate(path, handler)...
        }
        return sets.first if sets.length == 1

        NodeSet.new(document) do |combined|
          sets.each do |set|
            set.each do |node|
              combined << node
```

`org/jruby/RubyArray.java:` in `map`
`/JRuby-1715@backend/lib/ruby/gems/shared/gems/nokogiri-1.5.1-java/lib/nokogiri/xml/node.rb`: in `xpath`
```ruby
      #   }.new)
      #
      def xpath *paths
        return NodeSet.new(document) unless document

        paths, handler, ns, binds = extract_params(paths)

        sets = paths.map { |path|...
          ctx = XPathContext.new(self)
          ctx.register_namespaces(ns)
          path = path.gsub(/\/xmlns:/,'/:') unless Nokogiri.uses_libxml?

          binds.each do |key,value|
            ctx.register_variable key.to_s, value
          end if binds
```

`/JRuby-1715@backend/lib/ruby/gems/shared/gems/odf-report-0.5.1/lib/odf-report/section.rb`: in `find_section_node`

  ```ruby
  end # replace_section

  private

    def find_section_node(doc)

      sections = doc.xpath(".//text:section[@text:name='#{@name}']")...

      sections.empty? ? nil : sections.first

    end

  end

```

I've tested both the latest and previous versions: 1.6.3, 1.6.2, 1.6.1, 1.5.11, 1.5.10 and 1.5.1.
I'm using
Torquebox 3.0.2 (also happens in Puma)
JRuby 1.7.15

Further examination/debugging reveals:

The original call from the odf-report library:
```ruby
doc.xpath(".//text:section[@text:name='#{@name}']")

```

`path` then is transformed to (`name = categorylevel1`):
`".//text:section[@text:name='categorylevel1']"`

`handler` is null. 

 `ctx.evaluate(path, handler)` is called and it throws the `Nokogiri::XML::XPath::SyntaxError`.

**Comment by mkristian** [comment]
the main problem here is that the namespaces "office" and "text" are NOT declared. once they are declared the xpath expression works.

**Comment by mkristian** [comment]
```xmllint office.xml --xpath ".//text:section[@text:name='categorylevel1']"```
also fails with
```
XPath error : Undefined namespace prefix
xmlXPathEval: evaluation failed
XPath evaluation failure
```
I would say the given document needs to declare the namespace for xpath to work on it.

**Comment by flavorjones** [comment]
@mkristian Thanks for looking at this. That sounds right; I'd like to close this issue. Objections, anyone?

**Comment by toshe** [comment]
@mkristian The document above is generated with OpenOffice / LibreOffice and should be valid: 
```<?xml version="1.0" encoding="UTF-8"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" ```

this is the beginning of the document. Aren't the namespaces `xmlns:office` and `xmlns:text` already declared?

**Comment by mkristian** [comment]
@toshe maybe you could create gist with a "small" complete document against which you want to execute this xpath statement. which makes it easier to reproduce the problem on my side.

**Comment by toshe** [comment]
@mkristian I'll even go one step further and create a small repo since i'm also using odf-report.

**Comment by flavorjones** [comment]
Although there is ongoing discussion, I didn't hear objections to closing, so I'm closing. Please feel free to reopen if you can provide a reproducible test case.

**Comment by toshe** [comment]
@mkristian 
you can check out the repo here: https://github.com/toshe/nokogiri-xpath-jruby

**Comment by toshe** [comment]
OK, so after debugging and comparing the results under MRI and JRuby I found out that the XPath searching returns different results under the two platforms. The first case is when a searching for a section in a document that doesn't really exist. Take this valid XML which represents an empty document without any text or sections. [LINK](https://gist.github.com/toshe/b36ead6ba23aff4a39e7#file-xml_jruby_no_sections). 

Executing `doc.xpath(".//text:section[@text:name='#{@name}']")` under JRuby will throw an Exception - `Nokogiri::XML::XPath::SyntaxError ` since there is no section present. 
However under MRI the same expression will return an empty `Nokogiri::XML::NodeSet` even if no sections are found. 

-----

The second case is when you actually provide a valid XML document with sections. [LINK](https://gist.github.com/toshe/ade5338194735b656efa#file-xml_doc_jruby)

Executing `doc.xpath(".//text:section[@text:name='#{@name}']")` under MRI will return a `Nokogiri::XML::NodeSet` with the section inside the nodes - everything works as expected.
However the same expression fails under JRuby with an `Nokogiri::XML::XPath::SyntaxError `. :beetle:

**Comment by toshe** [comment]
OK, so I think I found the reason why the library is failing. ODF-Report uses `inner_html` to update the nodes and replace fields.  

`Document.inner_html` seems to behave differently on JRuby and MRI.

[Sample file](https://gist.github.com/toshe/b4405e159b6e33dd5700#file-doc1-xml)

```ruby
file = File.read("doc1.xml")
doc = Nokogiri::XML(file)
sections = doc.xpath(".//text:section[@text:name='Section1']")
txt = doc.inner_html
doc.inner_html = txt # txt != doc.inner_html on JRuby
sections2 = doc.xpath(".//text:section[@text:name='Section1']") # fails on JRuby
doc.inner_html = txt
sections3 = doc.xpath(".//text:section[@text:name='Section1']")
```

Any thoughts on that?

there's something different about how the children are assigned and replaced under MRI and under JRuby.

**Comment by mkristian** [comment]
@toshe I can confirm that ```doc.inner_html``` produces a xpath. and the same doc with ```doc = Nokogiri::XML(doc.to_xml)``` does work again. will see if I can boil down the example a bit further.

@flavorjones either you reopen the issue or I will create a new !?!?

**Comment by mkristian** [comment]
@toshe I can confirm that ```doc.inner_html``` produces a xpath. and the same doc with ```doc = Nokogiri::XML(doc.to_xml)``` does work again. will see if I can boil down the example a bit further.

@flavorjones either you reopen the issue or I will create a new !?!?

**Comment by mkristian** [comment]
```ruby
require 'nokogiri'

doc = Nokogiri::XML(File.read("doc.xml"))
doc.inner_html = doc.inner_html
puts sections = doc.xpath(".//text:section[@name='Section1']").to_xml
```
with doc.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0">
  <text:section name="Section1">[TEXT_INSIDE_SECTION]</text:section>
</document>
```

this fails with jruby but works with MRI

**Comment by mkristian** [comment]
also MRI gives much more helpful error message when using an undefined namespace prefix:
```
nokogiri/xml/searchable.rb:165:in `evaluate': Undefined namespace prefix: .//texts:section[@name='Section1'] (Nokogiri::XML::XPath::SyntaxError)
```
JRuby just gives me ```Nokogiri::XML::XPath::SyntaxError```

**Comment by mkristian** [comment]
@toshe thanx for pushing this here - it was really a bug on nokogiri java side ;)

**Comment by toshe** [comment]
@mkristian don't mention it! thanks for pushing a fix :)
