### ISSUE TITLE
Nokogiri 1.6.4 won't compile

### ISSUE THREAD

**Issue by scalp42** [sparklemotion/nokogiri#1188]
Hi there,

We had to rollback to nokogiri 1.6.3.1 with libxml2 (2.9.0 instead of 2.9.2).

Log incoming.

Ubuntu 12.04 LTS

**Comment by plentz** [comment]
@jonbca thanks, your solution worked (centos 7.1) :)

**Comment by rgraterol** [comment]
@arnaud036 Thanks bro

**Comment by flavorjones** [comment]
The original two problems described in this ticket have been fixed, one by updating compiler flags, and the other by documenting the zlib requirement in the nokogiri.org installation tutorial.

Locking ticket, please open a new one if you're experiencing problems.
