### ISSUE TITLE
Publish a "vulnerability reporting" process

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1191]
We should have done this a long time ago.

**Comment by flavorjones** [comment]
Also see how Pivotal is doing this: http://www.pivotal.io/security

**Comment by yokolet** [comment]
I agree we should have had this earlier. Also, I think it's nice to have how should we, nokogiri team, treat such vulnerability reports. I heard Rails team must notify some sort of security group (authority?) if vulnerability is found. Rails may be a special product and needs to have a strict rule which may not be applied to Nokogiri. If Nokogiri team just fixes the bug and writes back to the reporter, that's all nokogiri team does?

**Comment by flavorjones** [comment]
Hey all, I set up a project profile at https://hackerone.com/ for Nokogiri, and have requested they review the project and put it into production mode.

Using a tool like this would greatly simplify reporting and our reporting policy and process. Rails uses it, though they offer a bounty which we likely will not (without external funding).

Anybody have thoughts here? Otherwise, I'm going to move forward with this plan over the next few days.

**Comment by tenderlove** [comment]
I agree with using hackerone.  It's been nice for the Rails team, and I think it would work well for us.

**Comment by tenderlove** [comment]
Bump @flavorjones.  What's the next step for hackerone?

**Comment by reedloden** [comment]
Hey @flavorjones, anything I can do to help get this moving? :)

**Comment by flavorjones** [comment]
I've submitted Nokogiri to Hackerone as a project for review.

**Comment by reedloden** [comment]
@flavorjones approved! Just shot you an e-mail with some details. Let me know if you have any questions.

**Comment by flavorjones** [comment]
@reedloden Thank you!

**Comment by flavorjones** [comment]
@tenderlove @jvshahid @knu @larskanis I've invited you all to the Hackerone project as team members. Currently it's in "controlled launch" until we handle a few vulnerability reports.

I've also invited everyone I could find in my email and the project's github issues that reported a vulnerability, as "hackers" who can submit vulnerability reports.

Next up:

* create a SECURITY.md file that explain how to report security issues (omitting Hackerone until it's a public project)
* add a security page to nokogiri.org


Once the project is public:

* update SECURITY.md
* update page on nokogiri.org
* tweet, etc.


Anything I've missed?

**Comment by flavorjones** [comment]
Oh, and if anyone else wants to be invited to be a "hacker" on the project to submit vulnerability reports, let me know, happy to send an invite.

**Comment by reedloden** [comment]
@flavorjones I'm happy to move you directly to public if you wish, but the invite-only stage is great for testing out a few (valid) reports. However, I understand that may be hard to do based on the nature of Nokogiri (and it being an open source library), so if you want to go public sooner, just let me know.

**Comment by flavorjones** [comment]
Hi @reedloden, I just emailed you about this. I think it would be really useful to go public sooner, if that's possible.

**Comment by reedloden** [comment]
@flavorjones Totally understand and agree! Replied to your e-mail, but tl;dr is that https://hackerone.com/nokogiri is now public. 💃 🎉

**Comment by flavorjones** [comment]
Here's my checklist of what remains to be done:

1. [ ] copy "policy" from hackerone and put it into a SECURITY.md file
2. [ ] link to SECURITY.md from README
3. [ ] add a security page to nokogiri.org
4. [ ] announce on a github issue
5. [ ] announce via twitter
6. [ ] announce via email

**Comment by flavorjones** [comment]
Security page available at http://www.nokogiri.org/tutorials/security.html

**Comment by flavorjones** [comment]
Done. Thanks, all!
