### ISSUE TITLE
Object created by #dup puts  `validity error` to the console.

### ISSUE THREAD

**Issue by chengguangnan** [sparklemotion/nokogiri#1196]
If you need the background, check https://github.com/flavorjones/loofah/issues/79.

Here is a demo:

```
irb(main):039:0> Nokogiri::HTML("<i id=a></i><i id=a></i>").text
=> ""
irb(main):040:0> Nokogiri::HTML("<i id=a></i><i id=a></i>").dup.text
element i: validity error : ID a already defined
=> ""
```

So the object created by #dup will puts error messages to the console. How to stop this behavior?

**Comment by henry74** [comment]
How do I get the next version - running bundler update still gives me 1.6.5

**Comment by jirutka** [comment]
@henry74 It hasn’t been released yet, 1.6.5 is currently the last release available on RubyGems, that’s way bundler gives it. @flavorjones is currently working on it.

**Comment by flavorjones** [comment]
1.6.6.1 was just released moments ago.

**Comment by henry74** [comment]
Thanks @flavorjones.  When I had looked on github, the latest version was 1.6.6 but I didn't see it on rubygems :-) Just funny timing...

**Comment by Basher52** [comment]
Hi,
I'm still getting this error, version of nokogiri (1.6.6.2, 1.5.5).
Apart from that the parsing seems to be doing what I want.
Any suggestions?

**Comment by zenspider** [comment]
@Basher52 do you have a reproduction? If so, please file a new issue with the reproduction.

**Comment by flavorjones** [comment]
What @zenspider said. This issue has been closed, let's please open a new one if you're seeing something unexpected.

**Comment by Basher52** [comment]
Thanks for the tip!

I'm not quite sure, but it could be caused by nokogumbo instead of nokogiri...
So I've put the issue on the nokogumbo github.
You can take a look at it if you want:
https://github.com/rubys/nokogumbo/issues/21
