### ISSUE TITLE
nokogiri 1.6.5 won't install

### ISSUE THREAD

**Issue by dsaronin** [sparklemotion/nokogiri#1203]
```
ERROR:  Error installing nokogiri:
    invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /home/daudi/.rvm/gems/ruby-2.1.3@projectspace/cache/nokogiri-1.6.5.gem
```

**Comment by tarique313** [comment]
I think RubyGems didn't download the file properly. So, the system is reporting that the gem is corrupt. Delete /home/daudi/.rvm/gems/ruby-2.1.3@projectspace/cache/nokogiri-1.6.5.gem and then install the gem again.

$ sudo rm /home/daudi/.rvm/gems/ruby-2.1.3@projectspace/cache/nokogiri-1.6.5.gem
$ gem install nokogiri
