### ISSUE TITLE
1.6.5 compile issue on Linux Mint

### ISSUE THREAD

**Issue by dpetzel** [sparklemotion/nokogiri#1204]
Running Linux Mint 16, I was getting a compile error (sorry I was an idiot and didn't save the error before I fixed it). The log was alluding to `lzma` being missing.

I was attempting to install per the instructions here: http://www.nokogiri.org/tutorials/installing_nokogiri.html. I needed to install `liblzma-dev` before it would compile. So as requested on that page, it didn't work for me so I'm opening a bug :)

Things worked once I did a `sudo apt-get install liblzma-dev`. Not sure if you wan't add this step to the Ubuntu instructions or not, but figured I'd mention it.

```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="13.10, Saucy Salamander"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 13.10"
VERSION_ID="13.10"
```

**Comment by dpetzel** [comment]
FWIW, I ran into this again tonight, while testing on Travis. You can see the build fails here: https://travis-ci.org/dpetzel/chef-yum_mesosphere/builds/46685406

I updated my travis.yml to install `liblzma-dev` (no other changes were made), and the build then worked as you can bee seen here: https://travis-ci.org/dpetzel/chef-yum_mesosphere/builds/46685537.

In this case since its travis is Ubuntu 12.04 I believe, and not Mint as was the case when I originally reported this.

**Comment by flavorjones** [comment]
For the record, the existing bug report (I believe it's related, anyway) for this condition is #1213. That should be in 1.6.6, soon. If 1.6.6 doesn't address this issue, let's reopen this ticket.

**Comment by silverdr** [comment]
Well, I have both `zlib1g-dev` and `lilzma-dev` installed and I still get the same error about libxml2 2.9.4 'compile' failure on a 16.04 ubuntu..
