### ISSUE TITLE
Support is broken for Ruby 1.9.2

### ISSUE THREAD

**Issue by mdchaney** [sparklemotion/nokogiri#1207]
The issue is on line 77 of extconf.rb:

 https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L77

    if try_compile("int main() {return 0;}", '', werror: true)

"try_compile" takes two arguments and a block:

    def try_compile(src, opt="", &b)
      try_do(src, cc_command(opt), &b)
    ensure
      rm_f "conftest*"
    end

This seems consistent throughout Ruby 1.9.2.  In 1.9.3 there's a change:

    def try_compile(src, opt="", *opts, &b)
      with_werror(opt, *opts) {|_opt, *_opts| try_do(src, cc_command(_opt), *_opts, &b)}
    ensure
      rm_f "conftest*"
    end

Removing the last argument lets compilation proceed in 1.9.2.

**Comment by flavorjones** [comment]
The breaking commit is 2054448233f64858aa43994d45255b148fa798ca.

**Comment by nirvdrum** [comment]
Thanks for calling that out.  I saw GitHub linked to my comment, but it's been drowned out.  Unfortunately, I've just started a new job and haven't managed to scrounge together the time to fix this.

**Comment by flavorjones** [comment]
This will be fixed in v1.6.6.

Note, however, I've officially proposed ending support for Ruby 1.9.2 as of Nokogiri 1.7.0 in #1227.

**Comment by mdchaney** [comment]
Thanks to all for the good work on this.
