### ISSUE TITLE
Can't create 'display' tag with Nokogiri::XML::Builder

### ISSUE THREAD

**Issue by quintencls** [sparklemotion/nokogiri#1222]
I need to build a xml with a 'display' tag but for some reason it fails with the following message:

`nokogiri_test.rb:3:in 'display': undefined method 'write' for {:test=>"test"}:Hash (NoMethodError)`

The script I use is as follows:

`require 'nokogiri'`
`build = Nokogiri::XML::Builder.new do |xml|`
   `  xml.display(this: "does not work")`
   `  xml.send(:"display", "test")`
   `  xml.test(this: "works")`
`end`

The 'test' tag is created without a problem. All help is appreciated, thx!

**Comment by knu** [comment]
This is because the Nokogiri::XML::Builder class has a method `#display` inherited from the Object class.

Try `xml.display_(this: "should work")`.  Please refer to [this document](http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Builder) in the Special Tags section.
