### ISSUE TITLE
Creating instance of XML::Comment with an element segfaults MRI but works fine on JRuby

### ISSUE THREAD

**Issue by YorickPeterse** [sparklemotion/nokogiri#1224]
Consider the following script:

```ruby
require 'nokogiri'

document = Nokogiri::XML('<a></a>')
a_node   = document.at('a')

p Nokogiri::XML::Comment.new(a_node, 'foo')
```

On MRI this segfaults the process, on JRuby this appears to work fine: 

```
#<Nokogiri::XML::Comment:0x9fe "foo">
```

I'm not sure if the usage of `XML::Comment` here is correct, but at least it shouldn't crash MRI.

**Comment by YorickPeterse** [comment]
Crash output: https://gist.github.com/YorickPeterse/7a21392aed7cdd0391b0

**Comment by flavorjones** [comment]
Thanks for reporting. Will look into it.
