### ISSUE TITLE
undefined method 'size' for nil:NilClass

### ISSUE THREAD

**Issue by dev-classified** [sparklemotion/nokogiri#1226]
~$  gem install nokogiri
ERROR:  Error installing nokogiri:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /home/yipl/.rvm/gems/ruby-2.2.0/cache/nokogiri-1.6.5.gem

**Comment by dev-classified** [comment]
remove cache nokogiri and good to go
~$ rm /home/yipl/.rvm/gems/ruby-2.2.0/cache/nokogiri-1.6.5.gem
~$ gem install nokogiri

**Comment by odeloic** [comment]
Thanks, it worked for me.

**Comment by abu-sufian** [comment]
not worked for me

**Comment by sebitoelcheater** [comment]
Thanks! this worked for me. Of course, I had to change the path of the cache file.

**Comment by jeperkins4** [comment]
Works for me as well!

**Comment by abdul-naaser** [comment]
thank you very much, and i wonder how you knew that?

**Comment by RaviSys** [comment]
> remove cache nokogiri and good to go
> ~$ rm /home/yipl/.rvm/gems/ruby-2.2.0/cache/nokogiri-1.6.5.gem
> ~$ gem install nokogiri

Thank this has worked for me also
