### ISSUE TITLE
JRuby 9000 support

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1228]
The weirdness continues with Nokogiri's implementation of `XML::SyntaxError#to_s` under 9.0.0.0.pre1.

Travis fail here:

> https://travis-ci.org/sparklemotion/nokogiri/jobs/47784569#L276

This appears to be the *only* thing that breaks under JRuby 9000. W00t.

**Comment by flavorjones** [comment]
Relevant code is here:

> https://github.com/sparklemotion/nokogiri/blob/master/ext/java/nokogiri/XmlSyntaxError.java#L116-L134

**Comment by yokolet** [comment]
I saw those errors last night. Ruby doesn't have TCO :(  Perhaps, we need to rethink a way of iterating over nodes. Java option may solve, but I don't think that's the good idea.

**Comment by flavorjones** [comment]
@headius helped out, I've got a fix.
