### ISSUE TITLE
Can’t build 1.6.6.2 on Ubuntu 14.10

### ISSUE THREAD

**Issue by penibelst** [sparklemotion/nokogiri#1234]
The sad story again. I have Nokogiri 1.6.5 on my Ubuntu 14.10 installed. If I try to `bundle install` that gemfile:

```ruby
gem "nokogiri", "~>1.6"
```

Bundler tries to install 1.6.6.2 and fails. 

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb 
checking if the C compiler accepts ... yes
Building nokogiri using system libraries.
libxml2 version 2.6.21 or later is required!
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.1
	--help
	--clean
	--use-system-libraries=true
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
	--with-libxml-2.0-config
	--without-libxml-2.0-config
	--with-pkg-config
	--without-pkg-config
	--with-xslt-dir
	--without-xslt-dir
	--with-xslt-include
	--without-xslt-include=${xslt-dir}/include
	--with-xslt-lib
	--without-xslt-lib=${xslt-dir}/lib
	--with-libxslt-config
	--without-libxslt-config
	--with-exslt-dir
	--without-exslt-dir
	--with-exslt-include
	--without-exslt-include=${exslt-dir}/include
	--with-exslt-lib
	--without-exslt-lib=${exslt-dir}/lib
	--with-libexslt-config
	--without-libexslt-config

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20150125-23708-tsnmpq/nokogiri-1.6.6.2/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /tmp/bundler20150125-23708-tsnmpq/nokogiri-1.6.6.2/extensions/x86-linux/2.1.0/nokogiri-1.6.6.2/gem_make.out
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.
```

The trick 

```
sudo apt-get install zlib1g-dev
```

doesn’t help.

**Comment by flavorjones** [comment]
Hello,

Thank you for reporting this, but this is actually the sad story of a user not reading Nokogiri's build output when it emits useful information:

```
Building nokogiri using system libraries.
libxml2 version 2.6.21 or later is required!
```

Please either upgrade your system libraries, or allow Nokogiri to use its bundled libraries.

If you feel I've closed this in error, then you will need to provide more detailed log files. We would actually prefer installation questions to be posted to the `nokogiri-talk` mailing list as discussed here:

> http://www.nokogiri.org/tutorials/getting_help.html

Thank you for using Nokogiri.

**Comment by penibelst** [comment]
Sorry for being distracted.

> or allow Nokogiri to use its bundled libraries

This is something I didn’t know how. After extensive searching I succeed.

> Thank you for using Nokogiri.

I will rethink whether I should start a new project dependent on Nokogiri. Thank you for the hint.

**Comment by NayeemKaka** [comment]
Any one can give solution for below problem?
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot
continue.

**Comment by flavorjones** [comment]
@NayeemKaka,

This issue is closed. Please email the nokogiri-talk mailing list or open a new issue with the contents of your log files.

Thank you

**Comment by dpehrson** [comment]
I also cannot figure out how to get nokogiri 1.6.6.2 installed on Ubuntu 14.04. Been using nokogiri for a long time and am very familiar with it's installation process (normally)

**Comment by Zapotek** [comment]
@penibelst In the interest of avoiding further condescension from the maintainers, could you let us know what you did to solve the issue?

**Comment by penibelst** [comment]
@Zapotek Sorry, I don’t remember the steps. It must have to do with @flavorjones’ hint “allow Nokogiri to use its bundled libraries”.

**Comment by flavorjones** [comment]
@dpehrson @Zapotek @penibelst Honestly, I meant my comment about "sad story" as a joke playing on the original post and not condescension. I would appreciate receiving the benefit of the doubt in the future, in particular when being asked for help. I'll be sure to use a winky-smile emoticon in the future when joking.

I also asked for more information, including log files, and the OP did not provide that information. So I think you're probably blaming the wrong person for something. ;)

You can email the mailing list for additional help on installation. I greatly prefer that discussion happen in the public eye, and not hidden on a github issue. See http://www.nokogiri.org/tutorials/getting_help.html for our rationale on this topic.
