### ISSUE TITLE
p-elements stated to be "block"

### ISSUE THREAD

**Issue by kostia** [sparklemotion/nokogiri#1239]
Hello,

AFAIK the `p`-tags are `inline` elements (see http://www.w3.org/TR/html4/sgml/dtd.html).
But when checking this using Nokogiri it says they are `block` elements:

```ruby
Nokogiri::HTML('<p></p>').css('p').first.description.inline?
# => false
```

Any idea why? Thanks!

Kind regards.
Kostia

**Comment by flavorjones** [comment]
While I agree that the DTD does indicate that `p` is an inline element, the de facto interpretation of `p` has always been as a block element. I refer you to MDN's page on the topic:

> https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements

Moreover, this isn't the interpretation of Team Nokogiri; this value comes directly from libxml2's codebase:

> https://git.gnome.org/browse/libxml2/tree/HTMLparser.c#n962

which initializes the description entry for `p`, whose structure is defined here:

> https://git.gnome.org/browse/libxml2/tree/include/libxml/HTMLparser.h#n41

If you'd like to have a deeper conversation about this, please email nokogiri-talk, as discussed at http://www.nokogiri.org/tutorials/getting_help.html

Thanks,
-m
