### ISSUE TITLE
Are zlib development support files really required?

### ISSUE THREAD

**Issue by gpakosz** [sparklemotion/nokogiri#1241]
In e7c47565323ddcc08355fa1aa62432a9881ca706, you check whether `zlib.h` is present while no native code inside `ext/` includes this header.

This for instance requires package `zlib1g-dev` to be installed on Debian (likely Ubuntu as well) while it seems only `zlib1g` (the actual library) is needed.

**Comment by flavorjones** [comment]
@gpakosz Unfortunately, the compilation of libxml2 does require zlib.h to be present:

```
libxml2 $ ack --type=cc zlib| fgrep include
nanohttp.c:68:#include <zlib.h>
tree.c:25:#include <zlib.h>
parserInternals.c:36:#include <zlib.h>
xlink.c:32:#include <zlib.h>
include/libxml/tree.h:563:    int             compression;/* level of zlib compression */
os400/wrappers.c:114:#include <zlib.h>
os400/wrappers.h:48:#include <zlib.h>
HTMLparser.c:30:#include <zlib.h>
xmlIO.c:36:#include <zlib.h>
xmlIO.c:1343:#include "xzlib.h"
xzlib.c:35:#include <zlib.h>
xzlib.c:41:#include "xzlib.h"
parser.c:81:#include <zlib.h>
```

This, of course, depends on whether you're compiling libxml2/lbxslt from source, but we only check for this header when `--use-system-libraries` is not enabled.

Can you help me understand exactly what you're doing when you see the `zlib.h` check fail? What are your arguments to `gem install`, what flavor of system are you on?

**Comment by flavorjones** [comment]
I commented on the PR at #1314. I'm still not convinced that what you're suggesting is suitable to be merged, since without `zlib.h` on the system, libxml2 will be compiled without zlib support.

Happy to discuss more here, if you like.

**Comment by flavorjones** [comment]
Going to close this. Again, I'm happy to have a conversation about this, if you like.
