### ISSUE TITLE
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

### ISSUE THREAD

**Issue by bkarakashev** [sparklemotion/nokogiri#1242]
I have installed Nokogiri Gem 1.6.6.2 but when I try to do vagrant plugin install vagrant-aws it is keep telling me that "An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling."
But when I do gem list I can see that Nokogiri gem is installed: 
*** LOCAL GEMS ***
nokogiri (1.6.6.2)

Please Help I need this vagrant pluging.

**Comment by flavorjones** [comment]
Hello!

Thanks for asking this question! Your request for assistance using
Nokogiri will not go unanswered!

However, Nokogiri's Github Issues is reserved for reporting bugs or
submitting patches. If you ask your question on the mailing list, Team
Nokogiri promises someone will provide you with an answer in a timely
manner.

If you'd like to read up on Team Nokogiri's rationale for this policy,
please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.
