### ISSUE TITLE
Cannot build in Ubuntu 15.04 development version

### ISSUE THREAD

**Issue by shakaran** [sparklemotion/nokogiri#1244]
I am getting this with sudo gem install nokogiri -v '1.6.4.1'

	cat /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.4.1/gem_make.out
	/usr/bin/ruby2.1 extconf.rb
	checking if the C compiler accepts ... yes
	Building nokogiri using packaged libraries.
	*** extconf.rb failed ***
	Could not create Makefile due to some reason, probably lack of necessary
	libraries and/or headers.  Check the mkmf.log file for more details.  You may
	need configuration options.

	Provided configuration options:
		--with-opt-dir
		--without-opt-dir
		--with-opt-include
		--without-opt-include=${opt-dir}/include
		--with-opt-lib
		--without-opt-lib=${opt-dir}/lib
		--with-make-prog
		--without-make-prog
		--srcdir=.
		--curdir
		--ruby=/usr/bin/ruby2.1
		--help
		--clean
		--use-system-libraries
	/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mini_portile (LoadError)
		from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		from extconf.rb:381:in `<main>'

	extconf failed, exit code 1

**Comment by flavorjones** [comment]
Sorry for not commenting on this earlier, I think I mentally classified it as belonging to a broader class of issues around mini_portile backwards-incompatibilities; however, it looks like you haven't installed mini_portile.

Are you still having this issue? If so, can you help me understand how you're installing nokogiri? `mini_portile` is declared as a dependency of nokogiri in v1.6.4.1, so I'm confused how you got into this state without manually deleting gems from your system.

**Comment by shakaran** [comment]
Hi @flavorjones 

I cannot reproduce in Ubuntu 16.04 (development version) with ruby 2.2.3p173, even installing now, it doesn't require to install mini-portile

	$ sudo gem install nokogiri -v '1.6.4.1'
	Building native extensions.  This could take a while...
	Successfully installed nokogiri-1.6.4.1
	1 gem installed

Because after I can install mini_portile previously not installed:

	$ sudo gem install mini_portile 
	Successfully installed mini_portile-0.6.2
	1 gem installed

So I think that time and other updates solve this problem :)
