### ISSUE TITLE
jruby: namespaces defined elsewhere cannot be added again

### ISSUE THREAD

**Issue by ccutrer** [sparklemotion/nokogiri#1247]
See https://gist.github.com/ccutrer/f49cee7ebcd8a62e2e9e

it works correctly under MRI 2.2, but not under `jruby 1.7.12 (1.9.3p392) 2014-04-15 643e292 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26 +indy [darwin-x86_64]`

The result is simply an empty array.

**Comment by flavorjones** [comment]
@ccutrer Apologies for not responding for such an embarrassingly long time.

Yes, this appears to be a bug. The buggy behavior becomes more visible with this version of your script:

```ruby
#!/usr/bin/env ruby
 
require 'nokogiri'

d = Nokogiri::XML::Document.parse("<root>")
c1 = d.create_element('a', 'xmlns:foo' => 'fooey')
c2 = d.create_element('b', 'xmlns:foo' => 'fooey')
d.root.add_child c1
d.root.add_child c2

puts c1.namespace_definitions.inspect
# jruby => [#<Nokogiri::XML::Namespace:0xfa0 prefix="foo" href="fooey">]
# cruby => [#<Nokogiri::XML::Namespace:0xfdc prefix="foo" href="fooey">]

puts c2.namespace_definitions.inspect
# jruby => []
# cruby => [#<Nokogiri::XML::Namespace:0xff0 prefix="foo" href="fooey">]

puts d.to_xml
# jruby =>
#     <?xml version="1.0"?>
#     <root><a xmlns:foo="fooey"/><b/></root>
#
# cruby =>
#     <?xml version="1.0"?>
#     <root>
#       <a xmlns:foo="fooey"/>
#       <b xmlns:foo="fooey"/>
#     </root>
```

The above was reproduced with Nokogiri v1.13.0

**Comment by flavorjones** [comment]
PR created at #2544 to fix this. Thanks again for your patience.
