### ISSUE TITLE
nokogiri-1.6.6.2-x64-mingw32 - missing ruby 2.2 so

### ISSUE THREAD

**Issue by ABaumgaertner** [sparklemotion/nokogiri#1259]
simple test: require 'nokogiri' fails

```
ruby -v n_test.rb
ruby 2.2.2p86 (2015-03-03 revision 49825) [x64-mingw32]
C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from n_test.rb:1:in `<main>'
```
```gem unpack nokogiri-1.6.6.2-x64-mingw32.gem```
lib\nokogiri\2.2\nokogiri.so is missing

maybe you could bundle the dlls in the gem (would save some space with multiple ruby version support)

**Comment by knu** [comment]
Ruby 2.2.x was not listed in .cross_rubies, so I've just added it.
I'll try cross-building nokogiri for Windows shortly, and if it succeeds the next release will have the file.  Thanks for your patience!

**Comment by ABaumgaertner** [comment]
no problem - if you cross compile, what is the target thread model: posix or win32
ruby on windows uses native win32

**Comment by knu** [comment]
I believe it has always been win32, because our building environment built with Vagrant is dedicated for building ruby extensions.
```
vagrant@precise64:~$ mingw/mingw64/bin/x86_64-w64-mingw32-gcc -v
Using built-in specs.
COLLECT_GCC=mingw/mingw64/bin/x86_64-w64-mingw32-gcc
COLLECT_LTO_WRAPPER=/home/vagrant/mingw/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/4.7.2/lto-wrap
per
Target: x86_64-w64-mingw32
Configured with: /home/ruben/mingw-w64/src/gcc/configure --host=x86_64-linux-gnu --build=x86_64-linu
x-gnu --target=x86_64-w64-mingw32 --with-sysroot=/home/ruben/mingw-w64/linux64mingw64/mingw64 --pref
ix=/home/ruben/mingw-w64/linux64mingw64/mingw64 --with-gmp=/home/ruben/mingw-w64/prereq/x86_64-linux
-gnu/install --with-mpfr=/home/ruben/mingw-w64/prereq/x86_64-linux-gnu/install --with-mpc=/home/rube
n/mingw-w64/prereq/x86_64-linux-gnu/install --with-ppl=/home/ruben/mingw-w64/prereq/x86_64-linux-gnu
/install --with-cloog=/home/ruben/mingw-w64/prereq/x86_64-linux-gnu/install --disable-ppl-version-ch
eck --disable-cloog-version-check --enable-cloog-backend=isl --with-host-libstdcxx='-static -lstdc++
 -lm' --enable-shared --enable-static --enable-threads=win32 --enable-plugins --disable-multilib --e
nable-languages=c,lto,c++,objc,obj-c++,fortran,java --enable-libgomp --enable-fully-dynamic-string -
-enable-libstdcxx-time --disable-nls --disable-werror --enable-checking=release --with-gnu-as --with
-gnu-ld --with-pkgversion=rubenvb-4.7.2-release --with-bugurl=mingw-w64-public@lists.sourceforge.net
 CC= CFLAGS='-O2 -march=nocona -mtune=core2 -fomit-frame-pointer -momit-leaf-frame-pointer' LDFLAGS=
Thread model: win32
gcc version 4.7.2 (rubenvb-4.7.2-release)
```

**Comment by ABaumgaertner** [comment]
judging from the size of the .so files, the 4 dlls are linked in. wouldn't it make more sense to include the dlls and link dynamically to save space (see mysql2 gem - vendor dir https://rubygems.org/downloads/mysql2-0.3.18-x64-mingw32.gem)

**Comment by knu** [comment]
@ABaumgaertner OK, but that sounds like another issue, so if you strongly think so please file a new issue for it.

**Comment by knu** [comment]
I'm currently trying out this PR to cross-build nokogiri with a binary for Ruby 2.2: https://github.com/tjschuck/rake-compiler-dev-box/pull/20

**Comment by knu** [comment]
Looks like we'll have to wait until [this PR](https://github.com/ruby/ruby/pull/848) makes it into trunk and then gets merged to ruby_2_2 for the next patch release of the series (2.2.2), or someone prepares a custom build of ruby 2.2 that incorporates the patch.

**Comment by ABaumgaertner** [comment]
issue  #1260 created for DLL dynamic linking

thanks for your support so far!

**Comment by guillaumemaka** [comment]
Is that include ruby 2.2 on other operating system (Like OS X) ?

**Comment by richpeck** [comment]
Got it working with Ruby 2.2.1 on Ubuntu; I think the current issue is a compilation problem on Windows.

**Comment by flavorjones** [comment]
@richpeck  - Thanks for the enthusiasm, and for updating all the open Windows issues. Obviously you're up to date on what's going on, but just to make sure, I want to remind you and everyone else that we don't currently support compiling native windows binaries. If that's what you want to support, please join the conversation at #1190.

@knu - Thanks for responding. Worth noting is that there was already a ticket I had been treating as the "master" for 2.2 support and closing out reports like this as duplicates, #1256.

@guillaumemaka are you experiencing issues with Ruby 2.2 support on OSX? If so, please open a new ticket.

I'm closing this ticket as there doesn't seem to be any new outstanding action items beyond the two tickets I've reference above. Please let me know if I'm mistaken and we can discuss reopening.

**Comment by edisonrf** [comment]
rollback to ruby version under 2.1.5 will solve this issue

**Comment by jjgh** [comment]
hey guys, is the following error (ruby 2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]) related to what you're discussing here?

```
[1] pry(main)> require 'nokogiri'
LoadError: cannot load such file -- nokogiri/nokogiri
from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```
Is there a quick fix I could I could use in order to not have to switch back to an older Ruby version?
Thanks

**Comment by ginolon** [comment]
+1

C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rails-html-sanitizer-1.0.2/lib/rails-html-sanitizer.rb:2:in `require'

**Comment by emragins** [comment]
Please!  This breaks the "Getting Started" tutorial right out the door (http://guides.rubyonrails.org/getting_started.html).  I am on Windows.  Exact same message as @ginolon

**Comment by Nick-DeSimone** [comment]
+1

```
$ rails generate devise:install
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `<top (required)>'
```
