### ISSUE TITLE
nokogiri x64-mingw32 - link dlls dynamically

### ISSUE THREAD

**Issue by ABaumgaertner** [sparklemotion/nokogiri#1260]
judging by the size of the .so files, the 4 dlls are linked in for each ruby version. it would save space if the dlls were linked dynamically and included only once (see mysql2 gem - vendor dir https://rubygems.org/downloads/mysql2-0.3.18-x64-mingw32.gem)
nokogiri.so around 3Mb per ruby version

**Comment by sodabrew** [comment]
Cool! Yep - see https://github.com/brianmario/mysql2/blob/master/ext/mysql2/extconf.rb#L97-145

In particular, it took a *ton* of work to figure out how to use dlltool generate the libmysql.a interface library that does get linked into mysql2.so so that it would link to libmysql.dll on Win x64.

**Comment by flavorjones** [comment]
Great idea? Anybody want to try putting together a PR demonstrating how to do this?

**Comment by ABaumgaertner** [comment]
run gendef and dlltool just in case the provided lib format is not compatible with ld (see imagemagick binaries compiled with ms visual studio and linked with gnu ld gemhome/rmagick#175)

does the trick for me ...
```
gendef mylib.dll
dlltool --dllname mylib.dll --def mylib.def --output-lib mylib.lib
```

**Comment by flavorjones** [comment]
Hi,

I'm totally excited about making Nokogiri better on windows; but nobody on the core team is familiar with the toolchain, which is why I'm again asking if anyone would like to try to put together a PR demonstrating how to do this.

Unless someone can teach Team Nokogiri, this feature request is unfortunately not going to get much attention.

**Comment by larskanis** [comment]
The windows binary gems are still smaller than the source gem, insofar this is not worth the effort IMHO. Using libxml2, libxslt, libz and libiconv as DLLs can also lead to new issues when these dependent DLLs can not be found or are (already) loaded in different versions.

As long as static linkage is supported by the upstream projects and the size of the resulting binary gems doesn't grow too much, I think it's better to keep it as is.
