### ISSUE TITLE
Can't install nokogiri-1.6.6.2 on Ubuntu 14.10

### ISSUE THREAD

**Issue by holycow001** [sparklemotion/nokogiri#1263]
Method of install:
gem install nokogiri

Output:
ubuntu# gem install nokogiri
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.6.2/gem_make.out

**Comment by flavorjones** [comment]
Hi,

Thanks for asking this question. You haven't told us how you installed Ruby, but this looks like you don't have your Ruby's development packages installed. Generally, if you've installed through `apt-get` these packages will be named something like `ruby-dev` (for 1.9.3) or `ruby2.0-dev` for (2.0).

I'm going to close this, as these questions are better asked (and more promptly responded to) on the mailing list. See http://www.nokogiri.org/tutorials/getting_help.html for our rationale.

Thanks for using nokogiri!
