### ISSUE TITLE
[jruby] Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by belgoros** [sparklemotion/nokogiri#1264]
I tried to read with `JRUBY` a UTF-8 encoded CSV file and to build an XML file and got the below error:

```
Encoding::UndefinedConversionError: ""\xC3\xA9"" from UTF-8 to US-ASCII
            write at org/jruby/ext/stringio/StringIO.java:1140
  native_write_to at nokogiri/XmlNode.java:1220
         write_to at C:/jruby-1.7.18/lib/ruby/gems/shared/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:
686
        serialize at C:/jruby-1.7.18/lib/ruby/gems/shared/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:
618
           to_xml at C:/jruby-1.7.18/lib/ruby/gems/shared/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/builder.
rb:346
           (root) at read_csv.rb:16
```

Here is a content from CSV file:

```
Key|line
key-123|41 r Vallées ||92290 CHATENAY MALABRY
key-123|30 r Appert ||91300 MASSY
```

The code that reads:

```
require 'csv'
require 'nokogiri'

file_name = "xml_entries_csv.csv"

builder = Nokogiri::XML::Builder.new do |xml|
  xml.root {
    CSV.foreach(file_name, headers: true, col_sep: '|', encoding: 'utf-8') do |row|
      puts "#{row[1]}, encoding: #{row[1].encoding}"
      xml.street row[1]
    end
  }
end

puts builder.to_xml
```

When running `jruby read_csv.rb`:

```
41 r Vallées , encoding: UTF-8
30 r Appert , encoding: UTF-8
Encoding::UndefinedConversionError: ""\xC3\xA9"" from UTF-8 to US-ASCII
            write at org/jruby/ext/stringio/StringIO.java:1140
  native_write_to at nokogiri/XmlNode.java:1220
         write_to at C:/jruby-1.7.18/lib/ruby/gems/shared/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:
686
        serialize at C:/jruby-1.7.18/lib/ruby/gems/shared/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:
618
           to_xml at C:/jruby-1.7.18/lib/ruby/gems/shared/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/builder.
rb:346
           (root) at read_csv.rb:16
```

Reproduced on:
- a Windows 7 PC
- jruby: `ruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14 +jit`
- nokogiri version: `nokogiri (1.6.6.2 java)`
- local encoding:

```
irb(main):001:0> Encoding.default_external
=> #<Encoding:Windows-1252>
```

Any idea ? Thank you.

**Comment by yokolet** [comment]
This is OS encoding problem mixed complicated issue. When I tried your code on OS X, JRuby correctly handled the UTF-8 character, but MRI didn't. To print out the Ruby version, I added `puts "RUBY_VERSION=#{ENV['RUBY_VERSION']}"` to your code (not typing manually).
Perhaps @enebo, @tenderlove  may know more about this problem?

![jrubyonosx](https://cloud.githubusercontent.com/assets/193059/6763488/c7ab3902-cf55-11e4-9e57-c3c74f5ced12.png)
![mrionosx](https://cloud.githubusercontent.com/assets/193059/6763489/cc9e69ac-cf55-11e4-9a17-7f21d1227e4a.png)

**Comment by Javix** [comment]
Most probably you are right. Sometimes, event to be able to install a gem (cucumber for example), I have to change Windows code table as follows:
```
chcp 1252
```
The default code tabl is as follows:
```
C:\Windows\system32>chcp
Page de codes active : 850

C:\Windows\system32>chcp 1252
Page de codes active : 1252

C:\Windows\system32>
```
if not, it raises some strange errors. What I've noted is that if often happens on a Windows PC under French Windows OS.
I've heard a lot that the Windows code table is broken and even setting it to `65001` not always solve the problem.

**Comment by enebo** [comment]
It is possible whatever constructs Java strings internally in nokogiri is
doing new String(byte[] stringData) and this form of a Java String will use
file.coding property of JVM.  Since nokogiri is using a Java library for
XML processing I would hope/expect that library itself knows how to cope
with XML-supplied encoding.

On Mon, Mar 23, 2015 at 3:09 AM, Serguei Cambour <notifications@github.com>
wrote:

> Most probably you are right. Sometimes, event to be able to install a gem
> (cucumber for example), I have to change Windows code table as follows:
>
> chcp 1252
>
> The default code tabl is as follows:
>
> C:\Windows\system32>chcp
> Page de codes active : 850
>
> C:\Windows\system32>chcp 1252
> Page de codes active : 1252
>
> C:\Windows\system32>
>
> if not, it raises some strange errors. What I've noted is that if often
> happens on a Windows PC under French Windows OS.
> I've heard a lot that the Windows code table is broken and even setting it
> to 65001 not always solve the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sparklemotion/nokogiri/issues/1264#issuecomment-84875348>
> .
>



-- 
blog: http://blog.enebo.com       twitter: tom_enebo
mail: tom.enebo@gmail.com

**Comment by flavorjones** [comment]
Possibly-related issue at https://github.com/jruby/jruby/issues/2601#issuecomment-78641584

**Comment by Spakman** [comment]
@Javix Did you try telling Nokogiri to explicitly encode the XML as UTF-8?

```builder = Nokogiri::XML::Builder.new(encoding: "UTF-8") do |xml|```

**Comment by flavorjones** [comment]
Can't reproduce. Many fixes have been made over the years to encoding-handling in Nokogiri's java implementation.
