### ISSUE TITLE
Nokogiri should refuse to install on MinGW Ruby 2.2

### ISSUE THREAD

**Issue by marutosi** [sparklemotion/nokogiri#1266]
Rails 4.2 requires Nokogiri.
Redmine got feedbacks that Redmine 3.0.x (Rails 4.2.x) does not work on MinGW Ruby 2.2.
* http://www.redmine.org/issues/19419
* http://www.redmine.org/boards/2/topics/45380
* http://www.redmine.org/boards/2/topics/45991?r=45999#message-45999

It is too hard to know why Redmine 3.0 does not work on MinGW Ruby 2.2.

You can refuse to install gem in gemspec.

```ruby
spec = ::Gem::Specification.new do |spec|
  platforms = [:linux, :mingw]
  case RUBY_PLATFORM
  when /mingw/
    if RUBY_VERSION >= "2.2"
      fail 'This gem does not support MinGW Ruby 2.2'
    end
  else
    platform = :linux
  end
end
```

**Comment by knu** [comment]
I'll handle this.
