### ISSUE TITLE
Ruby 2.2 Windows

### ISSUE THREAD

**Issue by richpeck** [sparklemotion/nokogiri#1267]
I have Windows and will be able to test new builds of Nokogiri.

I believe the problem on this system is the inability for Nokogiri to be compiled. I am not massively experienced with this type of work, but want to learn.

If you need any input etc from Windows x64 users running 2.2.1, I am available.

**Comment by richpeck** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1104431/6770172/7a75dd7a-d0b0-11e4-8160-a374ea9f81f6.png)

Seems to be functional, will keep updated with any info

**Comment by flavorjones** [comment]
Hello,

Thanks for asking this question. We've have multiple open tickets about this, and I'm consolidating them under #1256. Please follow along there!

-m
