### ISSUE TITLE
XSD validation of dateTime with +14:00 time zone fails

### ISSUE THREAD

**Issue by gsmedley** [sparklemotion/nokogiri#1269]
XSD validation of a dateTime with a +14:00 time zone fails with this error:

    '2012-05-17T19:33:59+14:00' is not a valid value of the atomic type 'xs:dateTime'.

The schema definition from here http://www.w3.org/TR/xmlschema11-2/#dateTime says:

    (Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))

Using 13:59 as an offset works fine.

**Comment by gsmedley** [comment]
This looks like a problem in libxml2/xmlschemastypes.c:

    #define VALID_TZO(tzo)          ((tzo > -840) && (tzo < 840))

I'm thinking that should be >=/<= since 14 * 60 == 840

**Comment by flavorjones** [comment]
Agree, this is upstream in libxml2, so I'm going to close this out.
