### ISSUE TITLE
An error occurred while installing nokogiri (1.6.6.2)

### ISSUE THREAD

**Issue by negash** [sparklemotion/nokogiri#1271]
I am trying to run bundle package on Mac os x, and I am getting an error 
" An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling. " 

I try gem install nokogiri also gem install nokogiri -v 1.6.6.2

nokogiri not installing

**Comment by fran-worley** [comment]
Have you tried some of the suggestions in this issue? https://github.com/sparklemotion/nokogiri/issues/1231

**Comment by androbtech** [comment]
@negash Do me a favor. Download the latest version of Tokaido [here](https://github.com/tokaido/tokaidoapp/releases/tag/v2.2).

After installation. Click 'Open In Terminal' and run:

```gem uninstall nokogiri```

Try installing it now. If it works in your machine, then I there is a high probability that most build failures people face when installing Nokogiri on OS X is not libxml nor libxslt, but missing the iconv header files (which Tokaido adds them for you)

**Comment by kenichi** [comment]
i have a perfectly valid libiconv installed on my mac in /usr/local, but this line makes it impossible for me to install the gem without monkeying around:

https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L453

`--with-iconv-dir` is no help in this case. :cry:

**Comment by zulhfreelancer** [comment]
Try this:
https://gist.github.com/zulhfreelancer/c35807df7c8c978611da

**Comment by flavorjones** [comment]
We made updates in 1.6.7 that should address libiconv issues. If you're still having a problem, please comment here and I'll reopen.

**Comment by toopher503** [comment]
I am using Mojave (10.14.5) , and had to do a clean install which broke things. 
I ran this:
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

and it worked.

**Comment by flavorjones** [comment]
@toopher503 you're commenting on an unrelated issue that was closed over three years ago.

It sounds like your issue might be related to #1801 fixed with #1851 and released in v1.10.1 on 2019-01-13. Please upgrade to at least that version and if it doesn't work for you, open a new issue. Thanks.
