### ISSUE TITLE
nokogiri-1.6.6.2, Ubuntu 12.04, Rubinius 2.5.2, Ruby 2.1.0 - Error installing nokogiri - control characters are not allowed

### ISSUE THREAD

**Issue by dcki** [sparklemotion/nokogiri#1273]
# Install packages that some information sources claim are required by Nokogiri. 
    # Using su instead of sudo because my sudo's PATH is not currently correct. (sudo is not used to install Nokogiri itself so I don't think this is the issue.)
    vagrant@precise32:~/test$ sudo su -l root -c 'apt-get install zlib1g-dev ruby-dev libxslt-dev libxml2-dev'
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
    ruby-dev is already the newest version.
    zlib1g-dev is already the newest version.
    libxml2-dev is already the newest version.
    libxslt1-dev is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 179 not upgraded.
    vagrant@precise32:~/test$ uname -a
    Linux precise32 3.2.0-23-generic-pae #36-Ubuntu SMP Tue Apr 10 22:19:09 UTC 2012 i686 i686 i386 GNU/Linux
    vagrant@precise32:~/test$ lsb_release -r
    Release:	12.04
    vagrant@precise32:~/test$ ruby --version
    rubinius 2.5.2 (2.1.0 7a5b05b1 2015-01-30 3.4 JI) [i686-linux-gnu]
    vagrant@precise32:~/test$ gem --version
    2.4.5
    vagrant@precise32:~/test$ gem list
    
    *** LOCAL GEMS ***
    
    bundler (1.7.12)
    bundler-unload (1.0.2)
    daedalus-core (0.2.0)
    executable-hooks (1.3.2)
    ffi2-generators (0.1.1)
    gem-wrappers (1.2.7)
    json (1.8.2)
    minitest (4.7.5)
    psych (2.0.10)
    racc (1.4.12)
    rake (10.4.2)
    rb-readline (0.5.2)
    rdoc (4.2.0)
    redcard (1.1.0)
    rubinius-ast (2.3.1)
    rubinius-build_tools (2.0.0)
    rubinius-compiler (2.3.1)
    rubinius-coverage (2.0.3)
    rubinius-debugger (2.2.0)
    rubinius-developer_tools (2.0.0)
    rubinius-melbourne (2.3.1.0)
    rubinius-processor (2.3.0)
    rubinius-profiler (2.0.1)
    rubinius-toolset (2.3.1)
    rubygems-bundler (1.4.4)
    rubysl (2.1.0)
    rubysl-abbrev (2.0.4)
    rubysl-base64 (2.0.0)
    rubysl-benchmark (2.0.1)
    rubysl-bigdecimal (2.0.2)
    rubysl-cgi (2.0.1)
    rubysl-cgi-session (2.0.1)
    rubysl-cmath (2.0.0)
    rubysl-complex (2.0.0)
    rubysl-continuation (2.0.0)
    rubysl-coverage (2.0.3)
    rubysl-csv (2.0.2)
    rubysl-curses (2.0.1)
    rubysl-date (2.0.9)
    rubysl-delegate (2.0.1)
    rubysl-digest (2.0.3)
    rubysl-drb (2.0.1)
    rubysl-e2mmap (2.0.0)
    rubysl-english (2.0.0)
    rubysl-enumerator (2.0.0)
    rubysl-erb (2.0.2)
    rubysl-etc (2.0.3)
    rubysl-expect (2.0.0)
    rubysl-fcntl (2.0.4)
    rubysl-fiber (2.0.0)
    rubysl-fileutils (2.0.3)
    rubysl-find (2.0.1)
    rubysl-forwardable (2.0.1)
    rubysl-getoptlong (2.0.0)
    rubysl-gserver (2.0.0)
    rubysl-io-console (2.0.0)
    rubysl-io-nonblock (2.0.0)
    rubysl-io-wait (2.0.0)
    rubysl-ipaddr (2.0.0)
    rubysl-irb (2.1.1)
    rubysl-logger (2.1.0)
    rubysl-mathn (2.0.0)
    rubysl-matrix (2.1.0)
    rubysl-mkmf (2.0.1)
    rubysl-monitor (2.0.0)
    rubysl-mutex_m (2.0.0)
    rubysl-net-ftp (2.0.1)
    rubysl-net-http (2.0.4)
    rubysl-net-imap (2.0.1)
    rubysl-net-pop (2.0.1)
    rubysl-net-protocol (2.0.1)
    rubysl-net-smtp (2.0.1)
    rubysl-net-telnet (2.0.0)
    rubysl-nkf (2.0.1)
    rubysl-observer (2.0.0)
    rubysl-open-uri (2.0.0)
    rubysl-open3 (2.0.0)
    rubysl-openssl (2.2.1)
    rubysl-optparse (2.0.1)
    rubysl-ostruct (2.0.4)
    rubysl-pathname (2.1.0)
    rubysl-prettyprint (2.0.3)
    rubysl-prime (2.0.1)
    rubysl-profile (2.0.0)
    rubysl-profiler (2.0.1)
    rubysl-pstore (2.0.0)
    rubysl-pty (2.0.3)
    rubysl-rational (2.0.1)
    rubysl-resolv (2.1.0)
    rubysl-rexml (2.0.4)
    rubysl-rinda (2.0.1)
    rubysl-rss (2.0.0)
    rubysl-scanf (2.0.0)
    rubysl-securerandom (2.0.0)
    rubysl-set (2.0.1)
    rubysl-shellwords (2.0.0)
    rubysl-singleton (2.0.0)
    rubysl-socket (2.0.1)
    rubysl-stringio (2.0.0)
    rubysl-strscan (2.0.0)
    rubysl-sync (2.0.0)
    rubysl-syslog (2.1.0)
    rubysl-tempfile (2.0.1)
    rubysl-test-unit (2.0.3)
    rubysl-thread (2.0.2)
    rubysl-thwait (2.0.0)
    rubysl-time (2.0.3)
    rubysl-timeout (2.0.0)
    rubysl-tmpdir (2.0.1)
    rubysl-tsort (2.0.1)
    rubysl-un (2.0.0)
    rubysl-uri (2.0.0)
    rubysl-weakref (2.0.0)
    rubysl-webrick (2.0.0)
    rubysl-xmlrpc (2.0.0)
    rubysl-yaml (2.1.0)
    rubysl-zlib (2.0.1)
    rvm (1.11.3.9)
    vagrant@precise32:~/test$ gem install nokogiri
    Fetching: mini_portile-0.6.2.gem (100%)
    Successfully installed mini_portile-0.6.2
    Fetching: nokogiri-1.6.6.2.gem (100%)
    ERROR:  Error installing nokogiri:
    	invalid gem: package is corrupt, exception while verifying: (<unknown>): control characters are not allowed at line 1 column 1 (Psych::SyntaxError) in /home/vagrant/.rvm/gems/ext-rbx-2.5.2@test/cache/nokogiri-1.6.6.2.gem

**Comment by flavorjones** [comment]
Sorry for not responding earlier.

This error message is consistent with what happens when a gem file is incompletely downloaded. I imagine that if you delete your local gemfile cache, this problem will do away. And I'm assuming that you never saw it again?

Comment if you'd like to discuss or reopen, but otherwise I'll assume you had a corrupt download.

**Comment by dcki** [comment]
I think you must be right. I just went through the same process with same versions on a clean Ubuntu install in virtualbox on OS X, and it was successful.
