### ISSUE TITLE
Cannot use gem-compile for nokogiri

### ISSUE THREAD

**Issue by jk-shah** [sparklemotion/nokogiri#1274]
We need to pre-compile all gems

While using gem-compiler we hit the following issue
https://github.com/luislavena/gem-compiler/issues/12

Since it deletes the files which were part of original gem-spec.
https://github.com/sparklemotion/nokogiri/blob/v1.6.6.2/ext/nokogiri/extconf.rb#L63-L68

Out here. RPM packages typically are old so we cannot use them.

**Comment by mpapis** [comment]
:+1:

**Comment by sronsiek** [comment]
Same issue here

**Comment by flavorjones** [comment]
Hi all, apologies for only responding now, I missed this GH notification.

You'll need to start by helping me reproduce what you're seeing. The current thread doesn't provide enough information for me to understand what you're trying to do, how you're trying to do it, or what problems you're running into.

**Comment by flavorjones** [comment]
I believe that commit 20d7591983637365d469cd20a7eea663ad78f7ae addresses at least part of the gem-compile problem, based on the conversation at #1275. Not sure what else is open here, so I'm going to close for now.

If you'd like to continue the conversation, the information requested above can convince me to reopen and dig in. Thank you!
