### ISSUE TITLE
remove not removing found node

### ISSUE THREAD

**Issue by gpherguson** [sparklemotion/nokogiri#1276]
Just ran into this using Nokogiri 1.6.6.2.

I need to remove the first `<p>` from an embedded `<div>`. Using `at.('#page-1 p').remove` is removing the child (text) node, not the `<p>` node and its child:

    require 'nokogiri'
    doc = Nokogiri::HTML(<<EOT)
    <html>
      <head>
      </head>
      <body>
        <div id="page-container">
         <div id="page-1">
           <p> abc <p>
           <div>xyz</div>
         </div>
      </body>
    </html>
    EOT

    page_container = doc.at('#page-container')
    page_container.at('#page-1 p').remove

    puts page_container.to_html
    # >> <div id="page-container">
    # >>      <div id="page-1">
    # >>        <p>
    # >>        </p>
    # >> <div>xyz</div>
    # >>      </div>
    # >>   </div>

The same thing occurs using:

    page_container.search('#page-1 p').first.remove

**Comment by flavorjones** [comment]
@gpherguson Sorry for not responding earlier. It's really best to ask usage questions like this on the mailing list, where you're assure of a prompt response.

This code is doing exactly what you're asking it to. You have **two** `<p>` tags, which you can see if you `puts` the parsed document:

```xml
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
  <head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <div id="page-container">
     <div id="page-1">
       <p> abc </p>
<p>
       </p>
<div>xyz</div>
     </div>
  </div>
</body>
</html>
```

and when you remove the first one, you end up with:

```xml
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
  <head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <div id="page-container">
     <div id="page-1">
       <p>
       </p>
<div>xyz</div>
     </div>
  </div>
</body>
</html>
```

You may not have seen that you have **two** `<p>` tags.
