### ISSUE TITLE
Nokogiri::HTML not very strict!

### ISSUE THREAD

**Issue by msroot** [sparklemotion/nokogiri#1277]
Why when u use `:strict` i dont get any errors?

```ruby 
Nokogiri::HTML("<a/><a/><a/>") {|config| config.strict }.errors.any?
```

`
   2.1.3 :001 > Nokogiri::HTML("<a/><a/><a/>") {|config| config.strict }.errors.any?
`
 `
   => false 
`

**Comment by flavorjones** [comment]
Hello!

Thanks for asking this question! Your request for assistance using Nokogiri will not go unanswered!

However, Nokogiri's Github Issues is reserved for reporting bugs or submitting patches. If you ask your question on the mailing list, Team Nokogiri promises someone will provide you with an answer in a timely manner.

If you'd like to read up on Team Nokogiri's rationale for this policy, please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.
