### ISSUE TITLE
Nokogiri::Reader unescape inner html/xml?

### ISSUE THREAD

**Issue by twigbranch** [sparklemotion/nokogiri#1287]
Nokogiri::Node has methods (content, and text) that unescape \&amp;.  Yet, Reader does not appear to have such methods -- inner_xml returned strings remain escaped.

Is there a method in Nokogiri::Reader that will unescape \&amp;.  If not, what is the recommended way to do so?

**Comment by flavorjones** [comment]
Hello!

Thanks for asking this question! Your request for assistance using
Nokogiri will not go unanswered!

However, Nokogiri's Github Issues is reserved for reporting bugs or
submitting patches. If you ask your question on the mailing list, Team
Nokogiri promises someone will provide you with an answer in a timely
manner.

If you'd like to read up on Team Nokogiri's rationale for this policy,
please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.

**Comment by twigbranch** [comment]
OK. Though this is also an enhancement request if the method does not exist.
