### ISSUE TITLE
I can't get the nokogiri-talk Google Group to show my question

### ISSUE THREAD

**Issue by reed9999** [sparklemotion/nokogiri#1288]
Sorry for a total noob problem, but I can't find anywhere else to ask for help. 

I appear to be seeing the latest posts in the nokogiri-talk Google Group (including two topics from today), but I've made two attempts to post a new issue, and I don't see them. I posted once in the Groups UI and once via email, and I don't see either of them showing up. 

Can someone help me get my post to show up in nokogiri-talk?

=====

Here is the content I attempted to post via email with the subject line "I can't seem to find "the chapter on XPath and CSS syntax" (take 2)": 

>I thought I posted this via the Google Groups interface, but I can't see that it showed up, so forgive me if this ends up as a duplicate.

>Here:

>http://www.nokogiri.org/tutorials/searching_a_xml_html_document.html

>it says, "You can use any XPath or CSS query you like (see the chapter on XPath and CSS syntax for more information)."

>Could someone please help me find this chatper? I'm a total noob to Nokogiri, but I made what I think are reasonable attempts to find it (1) in the tutorial (2) with a Google search on site:nokogiri.org (3) in a global Google search.

>Thanks so much!

**Comment by flavorjones** [comment]
As mentioned at

http://www.nokogiri.org/tutorials/getting_help.html#step_1__mail_nokogiri_talk__grasshopper_

the list is set to first-post moderation, so someone needs to approve your first post. I've just done so.


Your other alternative would have been to subscribe to the mailing list.
