### ISSUE TITLE
Chaining after :not in document#css causes CSS::SyntaxError

### ISSUE THREAD

**Issue by MaxLap** [sparklemotion/nokogiri#1292]
When building big selector chain, you cannot add anything after the :not(). The following example should explain clearly. I use nth-child to compare behavior since everything works with it.

    nok = Nokogiri::HTML.parse('<html><body></body></html>')
    nok.css('html body:not(a)') # no exception
    nok.css('html body:not(a):not(b)') # exception
    
    # Yet it works fine with other functions like nth-child, you just can't put a function after a :not()
    nok.css('html body:nth-child(1):nth-child(1n):not(a)') # no exception
    nok.css('html body:nth-child(1):not(a):nth-child(1n)') # exception
   
    # Other things that you can't put after a :not but can put after other pseudo-classes
    nok.css('html body:nth-child(1)#z') # no exception
    nok.css('html body:not(a)#z') # exception

    nok.css('html body:nth-child(1)#z') # no exception
    nok.css('html body:not(a)#z') # exception
    nok.css('html body:nth-child(1).z') # no exception
    nok.css('html body:not(a).z') # exception
    
Note that all the exceptions happen even on a document not maching anything. My guess would be that this is related to :not() being the only pseudo-class that can receive other selector?

Tests were done on 1.6.6.2 with ruby 1.9.3.

**Comment by twalpole** [comment]
This is strange because there is a test for chained nots that passes -  https://github.com/sparklemotion/nokogiri/blob/master/test/css/test_parser.rb#L313

**Comment by twalpole** [comment]
@MaxLap I do however get these errors when testing against nokogiri 1.6.0 and 1.6.1, so maybe your system isn't actually using the 1.6.6.2 you think it is.

**Comment by MaxLap** [comment]
Well crap... I am very confused, but you are right that running those in 1.6.6.2 causes no problems. Maybe i ran the tests on the wrong project.

Sorry for the mistake. This can be closed.
