### ISSUE TITLE
ruby program  error with "require 'nokogiri'"

### ISSUE THREAD

**Issue by systemaker** [sparklemotion/nokogiri#1293]
Hello,
I am using last ruby version 2.2.2 on windows 7 but  I can't run my ruby code (ruby main.rb) when i use nokogiri , i got this error :

C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from C:/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
from C:/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in`require'
from main.rb:4:in `<main>'

**Comment by knu** [comment]
Sorry, but we haven't yet released a binary gem for Windows that contains a binary for Ruby 2.2.
Please follow #1256.
