### ISSUE TITLE
Nokogiri lose &lt; &gt;

### ISSUE THREAD

**Issue by Able1991** [sparklemotion/nokogiri#1294]
xml have a special character &#22; 
if it is not removed from the document all symbols & lt; & gt; after it lost
``` ruby
part = nil;
File.open('part.xml','r') { |f| part = f.read }
File.open('good.xml','wb') do |f|
  f.puts Nokogiri::XML(part.gsub('&#22;','-')).to_xml
end
File.open('bad.xml','wb') do |f|
  f.puts Nokogiri::XML(part).to_xml
end
```
https://gist.github.com/Able1991/030665226c03478747bc - 'part.xml'
This is a known problem? Any other code can lead to errors?

**Comment by twalpole** [comment]
For XML 1.0  the characters below &#32; (&#x20) other than 0x9, 0xA, 0xD are illegal in the document, so technically your XML document is illegal.  That being said the behavior of skipping further elements in the document is strange.

**Comment by flavorjones** [comment]
All, this behavior is dependent on the underlying XML/HTML parsing library, and not Nokogiri.
