### ISSUE TITLE
milestones are confusing

### ISSUE THREAD

**Issue by marutosi** [sparklemotion/nokogiri#1300]
I am waiting new release with #1266.
It is confusing what version will be released as next version.
https://github.com/sparklemotion/nokogiri/milestones?state=open

I don't know why 1.5.1 is still open.
https://github.com/sparklemotion/nokogiri/milestones/1.5.1

**Comment by flavorjones** [comment]
Not sure if you're asking a question, but I've removed the offending issue from 1.5.1.

**Comment by marutosi** [comment]
Could you **close** 1.5.1 and other milestones?

**Comment by marutosi** [comment]
![a](https://cloud.githubusercontent.com/assets/200784/8096277/4a6f5ee0-1010-11e5-9cfb-919734456b3a.png)

**Comment by flavorjones** [comment]
Again, I've closed the offending milestones, but I'm still not sure if you're asking a question.
