### ISSUE TITLE
Nokogiri gem install failing in Capistrano deploy

### ISSUE THREAD

**Issue by abrambailey** [sparklemotion/nokogiri#1309]
When attempting to install Nokogiri via bundler/capistrano I am receiving the error:

    An error occurred while installing nokogiri (1.6.5), and Bundler cannot continue

Digging deeper I can see >> **libxml2 version 2.6.21 or later is required!**

The error message also says `Make sure that gem install nokogiri -v '1.6.5' succeeds before bundling.` 

Well, as you can see this is not a problem:

    vagrant@vagrant:~$ gem install nokogiri -v '1.6.5'
    Building native extensions.  This could take a while...
    Successfully installed nokogiri-1.6.5
    1 gem installed

Sadly, even when this test is passed, the cap deploy still fails with the same error. 

`An error occurred while installing nokogiri (1.6.5), and Bundler cannot continue`

I have I have ensured the latest version of libxml2 is installed on my virtualbox. I even removed my project directory, and rebooted the server:

    $ vagrant ssh
    $ sudo apt-get update
    $ sudo apt-get upgrade libxml2
    $ sudo rm -rf /var/www/rails-devise-capistrano/
    $ sudo reboot

I have also tried added this to `deploy.rb`

    set :bundle_env_variables, { nokogiri_use_system_libraries: 1 }
    
Here is the bundler error

    /home/vagrant/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20150704-1327-1yf3b95.rb extconf.rb
    checking if the C compiler accepts ... yes
    Building nokogiri using system libraries.
    libxml2 version 2.6.21 or later is required!
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.
    
    Provided configuration options:
            --with-opt-dir
            --without-opt-dir
            --with-opt-include
            --without-opt-include=${opt-dir}/include
            --with-opt-lib
            --without-opt-lib=${opt-dir}/lib
            --with-make-prog
            --without-make-prog
            --srcdir=.
            --curdir
            --ruby=/home/vagrant/.rbenv/versions/2.2.2/bin/$(RUBY_BASE_NAME)
            --help
            --clean
            --use-system-libraries=true
            --with-zlib-dir
            --without-zlib-dir
            --with-zlib-include
            --without-zlib-include=${zlib-dir}/include
            --with-zlib-lib
            --without-zlib-lib=${zlib-dir}/lib
            --with-xml2-dir
            --without-xml2-dir
            --with-xml2-include
            --without-xml2-include=${xml2-dir}/include
            --with-xml2-lib
            --without-xml2-lib=${xml2-dir}/lib
            --with-libxml-2.0-config
            --without-libxml-2.0-config
            --with-pkg-config
            --without-pkg-config
            --with-xslt-dir
            --without-xslt-dir
            --with-xslt-include
            --without-xslt-include=${xslt-dir}/include
            --with-xslt-lib
            --without-xslt-lib=${xslt-dir}/lib
            --with-libxslt-config
            --without-libxslt-config
            --with-pkg-config
            --without-pkg-config
            --with-exslt-dir
            --without-exslt-dir
            --with-exslt-include
            --without-exslt-include=${exslt-dir}/include
            --with-exslt-lib
            --without-exslt-lib=${exslt-dir}/lib
            --with-libexslt-config
            --without-libexslt-config
            --with-pkg-config
            --without-pkg-config
    
    extconf failed, exit code 1

**Comment by flavorjones** [comment]
Hello!

Thanks for asking this question! Your request for assistance using
Nokogiri will not go unanswered!

However, Nokogiri's Github Issues is reserved for reporting bugs or
submitting patches. If you ask your question on the mailing list, Team
Nokogiri promises someone will provide you with an answer in a timely
manner.

If you'd like to read up on Team Nokogiri's rationale for this policy,
please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.

**Comment by abrambailey** [comment]
I understand thank you!
