### ISSUE TITLE
Nokogiri do_xinclude (not very good) - consider to change

### ISSUE THREAD

**Issue by etm** [sparklemotion/nokogiri#1321]
xinclude in libxml2 is not very capable. It uses nanohttp, which has no https support.

``` ruby
  require 'openssl'
  require 'open-uri'

  class Node
    def do_xinclude_manual
      ctx = XPathContext.new(self)
      ctx.register_namespaces "xi"=>"http://www.w3.org/2001/XInclude"
      ctx.evaluate('//xi:include').each do |ele|
        name = ele.attributes['href'].value
        content = open(name,{ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE}).read
        insert = begin 
          Nokogiri::XML::parse(content){|config| config.noblanks.noent.nsclean.strict }.root
        rescue
          content
        end
        insert['xml:base'] = name unless File.dirname(ele.attributes['href'].value) == '.' 
        x = ele.replace insert
        if x.is_a? Nokogiri::XML::Element
          x.do_xinclude_manual
        else
          x.each do |n|
            n.do_xinclude_manual if n.is_a? Nokogiri::XML::Element
          end
        end                                                                            
      end
    end
  end
```

the above code implements a simple xinclude. If the result parses as XML, root is inserted -  because xml could include processing instructions which would break the resulting code. If the result does not parse as XML (e.g. text) it is just inserted and we hope for the best ;-)

consider changing to this implementation, after all https becomes more common ;-)

**Comment by etm** [comment]
Note: this method behaves slightly different than the original xinclude in that it includes (files) relative to current path instead of relative to the documents path.

**Comment by flavorjones** [comment]
Hi, @etm. Thanks for suggesting this.

I'm curious why you didn't send this as a PR? Also, do you happen to have any tests that you wrote during implementation?

**Comment by tenderlove** [comment]
I like this, but it needs tests and should use `OpenSSL::SSL::VERIFY_NONE`, and probably should use net/http instead of `open-uri`.  Can you send a PR with tests for this?  Thanks!
