### ISSUE TITLE
Nokogiri looses body-attributes in fragments

### ISSUE THREAD

**Issue by jrz** [sparklemotion/nokogiri#1323]
Nokogiri looses the class="asd" attribute in the folowing example:

```
> Nokogiri::HTML::fragment('<body class="asd">test</body>').to_html
=> "<body>test</body>"
```

It works with spans:
```
> Nokogiri::HTML::fragment('<span class="asd">test</span>').to_html
=> "<span class=\"asd\">test</span>"
```

And also on a complete document:
```
> Nokogiri::HTML('<body class="asd">test</body>').to_html
=> "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">\n<html><body class=\"asd\">test</body></html>\n"
```

**Comment by flavorjones** [comment]
This is an unfortunate artifact of how fragments are parsed: they're wrapped in a `<body>` tag, meaning that if your fragment contains a body tag, it's ignored by the parser.

Though, if you have a body tag, you have a `Document` and not a `Fragment`, so this is expected behavior, IMHO.
