### ISSUE TITLE
Unicode issues

### ISSUE THREAD

**Issue by gottfrois** [sparklemotion/nokogiri#1330]
When parsing the following page https://derstandard.at/jetzt/livebericht/2000020029043/faymann-und-mitterlehner-zur-asylpolitik

```ruby
require 'open-uri'

doc = Nokogiri::HTML(open('https://derstandard.at/jetzt/livebericht/2000020029043/faymann-und-mitterlehner-zur-asylpolitik'))

=> #(Document:0x3fd14531f4d8 {
  name = "document",
  children = [
    #(DTD:0x3fd145327c78 { name = "html" }),
    #(Element:0x3fd14532bc74 {
      name = "html",
      children = [
        #(Element:0x3fd14532f644 {
          name = "body",
          children = [
            #(Element:0x3fd145333424 {
              name = "p",
              children = [
                #(Text "ℼ佄呃偙⁅瑨汭倠䉕䥌⁃ⴢ⼯㍗⽃䐯䑔䠠䵔⁌<U+2E34>\u3130吠慲獮瑩潩慮⽬䔯≎∠瑨灴⼺眯睷眮<U+2E33>牯⽧剔栯浴㑬氯潯敳搮摴㸢格浴...
```

I get some weird unicode content. Any idea what could possibly be wrong?

Thanks

**Comment by daniel-rikowski** [comment]
This could be caused by the fact that the HTML file is declared as utf-16, but the HTTP header say it's utf-8. Looks like it actually is utf-8 encoded, but Nokogiri uses the encoding declared in the file.

**Comment by gottfrois** [comment]
Thanks for looking at this. Is there a way to force utf-8 encoding?

**Comment by daniel-rikowski** [comment]
Yes, there is:

`doc = Nokogiri::HTML(open('https://derstandard.at/jetzt/livebericht/2000020029043/faymann-und-mitterlehner-zur-asylpolitik'), nil, 'utf-8')
`


This might help, too:
http://stackoverflow.com/questions/2572396/nokogiri-open-uri-and-unicode-characters

**Comment by gottfrois** [comment]
Thanks, this should do the trick on my side. Much appreciated :)
