### ISSUE TITLE
Different JRuby behavior

### ISSUE THREAD

**Issue by faucct** [sparklemotion/nokogiri#1331]
I was just trying to understand, why is JRuby Nokogiri swallowing my "xmlns:app" attributes, while MRI does not. I was trying to write a spec which would be failing on JRuby and as a result found this: 
on JRuby it throws a Java exception - 

    Java::OrgW3cDom::DOMException: NAMESPACE_ERR: An attempt is made to create or change an object in a way which is incorrect with regard to namespaces.

    Nokogiri::XML::Builder.new do |xml|
      xml.root {
        xml.send('app:edited')
      }
    end

**Comment by flavorjones** [comment]
Hi @faucct,

Thanks for asking this question. Nokogiri actually uses different parsing engines, depending on whether you're in MRI/Rubinius or in JRuby. For MRI, Nokogiri uses libxml2; for JRuby Nokogiri uses Xerces/NekoHTML. This explains why some of the implementation details are different.

What's the XML or HTML that you're trying to emit? I'd like to help you solve your problem.

**Comment by evanmiller67** [comment]
I've noticed the same problem. This was trying to use [samlr](https://github.com/zendesk/samlr) to create an XML document. Here's the stacktrace from @faucct's example:

```
$ irb
~> Console extensions: wirble hirb ap rails2 rails3 pm interactive_editor
>> require 'nokogiri'
=> true
>> Nokogiri::XML::Builder.new do |xml|
?>       xml.root {
?>           xml.send('app:edited')
>>       }
>>   end
Java::OrgW3cDom::DOMException: NAMESPACE_ERR: An attempt is made to create or change an object in a way which is incorrect with regard to namespaces.
	from org.apache.xerces.dom.ElementNSImpl.setName(Unknown Source)
	from org.apache.xerces.dom.ElementNSImpl.<init>(Unknown Source)
	from org.apache.xerces.dom.CoreDocumentImpl.createElementNS(Unknown Source)
	from nokogiri.XmlNode.init(XmlNode.java:343)
	from nokogiri.XmlNode.rbNew(XmlNode.java:298)
	from nokogiri.XmlNode$INVOKER$s$0$0$rbNew.call(XmlNode$INVOKER$s$0$0$rbNew.gen)
	from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
	from org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:211)
	from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:217)
	from org.jruby.ast.CallTwoArgBlockPassNode.interpret(CallTwoArgBlockPassNode.java:62)
	from org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
	from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	from org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	from org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	from org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:204)
	from org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:211)
... 214 levels...
	from org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	from org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	from org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	from org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	from Users.emiller.$_dot_rvm.rubies.jruby_minus_1_dot_7_dot_19.bin.irb.__file__(/Users/emiller/.rvm/rubies/jruby-1.7.19/bin/irb:13)
	from Users.emiller.$_dot_rvm.rubies.jruby_minus_1_dot_7_dot_19.bin.irb.load(/Users/emiller/.rvm/rubies/jruby-1.7.19/bin/irb)
	from org.jruby.Ruby.runScript(Ruby.java:866)
	from org.jruby.Ruby.runScript(Ruby.java:859)
	from org.jruby.Ruby.runNormally(Ruby.java:728)
	from org.jruby.Ruby.runFromMain(Ruby.java:577)
	from org.jruby.Main.doRunFromMain(Main.java:395)
	from org.jruby.Main.internalRun(Main.java:290)
	from org.jruby.Main.run(Main.java:217)
	from org.jruby.Main.main(Main.java:197)
```


Further, here's an example of how we're using [samlr](https://github.com/zendesk/samlr) to create an XML document (note that some information has been removed for brevity):
```
$ irb
~> Console extensions: wirble hirb ap rails2 rails3 pm interactive_editor
>> require 'samlr'
=> true
>> Samlr::Tools::ResponseBuilder.build({destination: 'foo_url', in_response_to: Samlr::Tools::uuid, name_id: '123456', not_on_or_after: Samlr::Tools::Timestamp.stamp(Time.now + 600), not_before: Samlr::Tools::Timestamp.stamp(Time.now - 600), audience: 'bar_peeps', attributes: { 'attr1' => 'attr1_val', 'attr2' => 'attr2_val'}})
=> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<samlp:Response Destination=\"foo_url\" ID=\"samlr-3c910c40-5d6f-11e5-b55d-44fb42fffe0e\" InResponseTo=\"samlr-3c90e530-5d6f-11e5-b55d-44fb42fffe0e\" IssueInstant=\"2015-09-17T19:06:44Z\" Version=\"2.0\" xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\" xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\"><saml:Issuer>ResponseBuilder IdP</saml:Issuer><samlp:Status><samlp:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Success\"/></samlp:Status><saml:Assertion ID=\"samlr-3c910c40-5d6f-11e5-b55e-44fb42fffe0e\" IssueInstant=\"2015-09-17T19:06:44Z\" Version=\"2.0\"><saml:Issuer>ResponseBuilder IdP</saml:Issuer><saml:Subject><saml:NameID Format=\"urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress\">123456</saml:NameID><saml:SubjectConfirmation Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\"><saml:SubjectConfirmationData InResponseTo=\"samlr-3c90e530-5d6f-11e5-b55d-44fb42fffe0e\" NotOnOrAfter=\"2015-09-17T19:16:44Z\" Recipient=\"foo_url\"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore=\"2015-09-17T18:56:44Z\" NotOnOrAfter=\"2015-09-17T19:16:44Z\"><saml:AudienceRestriction><saml:Audience>bar_peeps</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant=\"2015-09-17T19:06:44Z\" SessionIndex=\"samlr-3c910c40-5d6f-11e5-b55e-44fb42fffe0e\"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement><saml:AttributeStatement><saml:Attribute Name=\"attr1\"><saml:AttributeValue xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"xs:string\">attr1_val</saml:AttributeValue></saml:Attribute><saml:Attribute Name=\"attr2\"><saml:AttributeValue xsi:type=\"xs:string\">attr2_val</saml:AttributeValue></saml:Attribute></saml:AttributeStatement></saml:Assertion></samlp:Response>"
```

The relevant portion is in the AttributeStatement:
```
<saml:AttributeStatement>
  <saml:Attribute Name="attr1">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">attr1_val</saml:AttributeValue>
  </saml:Attribute>
  <saml:Attribute Name="attr2">
    <saml:AttributeValue xsi:type="xs:string">attr2_val</saml:AttributeValue>
  </saml:Attribute>
</saml:AttributeStatement>
```

Notice the difference in the AttributeValue elements. According to the [samlr code](https://github.com/zendesk/samlr/blob/master/lib/samlr/tools/response_builder.rb#L85), we should have namespaces defined, but they are missing.

Shoutout to @jdavidmannukaden for finding this bug. If we can provide any more information, please let us know.

**Comment by flavorjones** [comment]
Hi @evanmiller,

Thanks for posting. I'll ask you the question I asked @faucct: what is the XML you're trying to emit?

If I can't generate your target XML with Builder, then that's a Nokogiri bug, and we'll fix it. But if I *can* generate your target XML, then it may be a bug in samlr, and you'll have working Nokogiri code to demonstrate that fact for the samlr maintainers.

Make sense?

**Comment by evanmiller67** [comment]
Makes great sense. I've created a gist [here](https://gist.github.com/evanmiller67/dbd357f094970111fe3f) where I've tried to demonstrate everything. In there are several files:
* console_output.log
* jruby_example.xml (formatted output from the console_output -- using jruby)
* mri_example.xml (formatted output from the console_output -- using mri)
* nokogiri_example.rb (sample code to generate the bad snippet)
* mri_nokogiri_example.xml (output from the nokogiri_example.rb -- using mri)
* jruby_nokogiri_example.xml (output from the nokogiri_example_rb -- using jruby)

Environment used in these examples:
* jruby-1.7.19 [ x86_64 ]
** nokogiri (1.6.6.2 java)
** samlr (2.1.0)
* ruby-2.1.2 [ x86_64 ]
** nokogiri (1.6.1)
** samlr (1.1.2)

This could also be a misuse of Nokogiri, so I'm all ears on how we should be using it.

**Comment by evanmiller67** [comment]
Hi @flavorjones,

Just wanted to see if you've had a chance to look further into this issue. The attached gist (https://gist.github.com/evanmiller67/dbd357f094970111fe3f) has all the information from my comment above. I'm happy to help provide any more detail if it's helpful.

**Comment by flavorjones** [comment]
Hi @evanmiller67, it's still not clear to me what the *desired* XML is. Can you provide that, just the one XML file, and I'll see if I can generate it in Nokogiri?

**Comment by flavorjones** [comment]
Closing pending more information from OP as requested.
