### ISSUE TITLE
element in incorrect namespace after adding as a child

### ISSUE THREAD

**Issue by ccutrer** [sparklemotion/nokogiri#1332]
```
require 'nokogiri'

doc = Nokogiri::XML('<xml xmlns:a="abc"></xml>')
doc2 = Nokogiri::XML('<more xmlns="abc" />')
doc.root << doc2.root

puts doc
```

I would expect the output to be either

a) it used the outer namespace definition, and moved the element into it
```
<?xml version="1.0"?>
<xml xmlns:a="abc">
  <a:more/>
</xml>
```

or

b) it preserves the namespace that doesn't match on prefix, returning
```
<?xml version="1.0"?>
<xml xmlns:a="abc">
  <more xmlns="abc"/>
</xml>
```

but instead the output is
```
<?xml version="1.0"?>
<xml xmlns:a="abc">
  <more/>
</xml>
```

and more's namespace is no longer "abc".  This seems to be a problem with the `relink_namespace` function, that it removes duplicate namespaces, even if the prefixes don't match (and even if they did, you'd need to make sure the prefix wasn't redeclared between the higher definition and the lower definition)

**Comment by ccutrer** [comment]
This seems mildly related to #1200, but cloning doc2's root does not fix it.

**Comment by flavorjones** [comment]
Hi @ccutrer,

Thanks for asking this question. The issue here is that you're *copying* a node from one document to another, and libxml2 doesn't consider those namespaces "equal" in its implementation. None of the XML specs have anything to say about copying nodes between documents, and so hopefully you'll agree that we're in "undefined behavior" territory.

I'm happy to take a look at making this work in a less-unexpected way.

Can you please help me understand what your use case is for this? I'm curious.

**Comment by ccutrer** [comment]
My actual use case is an XMLSec encrypted element inside a document. xmlsec decrypts it and hands me back a node, which when I put back into the outer document gets changed by nokogiri, thus breaking an xmlsec signature of the unencrypted document (this a SAML assertion).

**Comment by ccutrer** [comment]
I should note that the JRuby version of Nokogiri doesn't have this problem, because it doesn't even attempt to prune seemingly equivalent namespaces.

**Comment by afn** [comment]
Are there any plans to fix this issue? Or are there any known workarounds?

**Comment by sgringwe** [comment]
@afn i have been using a fork by @ccutrer 
```
gem 'nokogiri', '1.6.6.2.20150813143452', require: false, github: 'codekitchen/nokogiri', ref: 'd47e53f885'
```

**Comment by afn** [comment]
Cool! @flavorjones I've created a PR for the bugfix, #1416.

**Comment by flavorjones** [comment]
Please note that the PR addressing this bug is targetted for 1.6.8.

**Comment by flavorjones** [comment]
Please note that the PR addressing this bug is #1333
