### ISSUE TITLE
Xpath in css() function on an Html fragment causes an invalid syntax error

### ISSUE THREAD

**Issue by Shelvetco** [sparklemotion/nokogiri#1335]
A code segment speaks a thousand words... or something like that

    require 'nokogiri'

    frag = Nokogiri::HTML::fragment("<a>test</a>")
    frag.css("//a")

Gives an error with an expanded? selector.

**Comment by flavorjones** [comment]
Hi @shelvetco,

Thanks for asking this question. When invalid CSS is passed to the `#css` method, I think raising an "invalid syntax" error is the right thing to do. What is the behavior you expected?

Perhaps also check out the [Getting Help](http://www.nokogiri.org/tutorials/getting_help.html#step_2___you_got_so_many_issues_you_need_a_magazine_rack__) page on nokogiri.org, which will show you that a code segment is a start, but not a complete bug report.

**Comment by flavorjones** [comment]
I suspect @shelvetco is pointing out that the error message here isn't obvious.

**Comment by Shelvetco** [comment]
I apologize, I did not read the things I should've read.

Since we're here anyway, I was under the assumption that the `css` function actually supported both css and xpath. I don't know where I got this idea, but when tested in irb it works with a full HTML::Document but not fragments.

    Nokogiri::HTML("<a><b>blah</b><b attr='foo'>bar</b></a>").css("//a/b[attr=foo]")
    # => [#<Nokogiri::XML::Element:0xbda204 name="b" attributes=[#<Nokogiri::XML::Attr:0xbda164 name="attr" value="foo">] children=[#<Nokogiri::XML::Text:0xdd9c6c "bar">]>]
    Nokogiri::HTML::fragment("<a><b>blah</b><b attr='foo'>bar</b></a>").css("//a/b[attr=foo]")
    # Nokogiri::XML::XPath::SyntaxError: Invalid expression: .////a/b[@attr = 'foo'] | self:://a/b[@attr = 'foo']

The behavior I expected is to return the element specified by the xpath. If this is not intended, I would expect a clearer error message like you said.

**Comment by flavorjones** [comment]
@Shelvetco The `#search` method will try to guess whether the string is CSS or XPath; but `#css` and `#xpath` require properly formed strings of the appropriate type.
