### ISSUE TITLE
Install fails on PPC-LE 

### ISSUE THREAD

**Issue by mgaudet** [sparklemotion/nokogiri#1341]
The `configure.guess` files bundled with libxslt and libxml2 don't recognize PowerPC Little endian. 

This can be fixed by patching `config.guess` to add stanzas for the following two cases: 

    ppc64le:Linux:*:*)
	echo powerpc64le-unknown-linux-${LIBC}
	exit ;;
    ppcle:Linux:*:*)
	echo powerpcle-unknown-linux-${LIBC}
	exit ;;

**Comment by mgaudet** [comment]
Whoops. Looks like libxml2 has the correct stanza, but libxslt does not.

**Comment by flavorjones** [comment]
@mgaudet Thanks for pointing out this issue!

Given your most recent comment about libxslt, is there anything we can do?

**Comment by mgaudet** [comment]
Sorry about the late reply, long weekend! 

I've prepared a patch for libxslt; The paths are wrong, as I wasn't able to reproduce how the patches in `patches/libxslt` are created, but it suggests a way forward. 

    From a6dc1b383850f4fe1bd469925c860dac69b7739c Mon Sep 17 00:00:00 2001
    From: Matthew Gaudet <matt@mgaudet.ca>
    Date: Tue, 8 Sep 2015 09:53:50 -0400
    Subject: [PATCH] Add PPC-LE stanzas to config.guess

    ---
     .../ports/libxslt/1.1.28/libxslt-1.1.28/config.guess                | 6 ++++++
     1 file changed, 6 insertions(+)

    diff --git a/tmp/x86_64-linux/nokogiri/2.2.2/tmp/x86_64-unknown-linux-gnu/ports/libxslt/1.1.28/libxslt-1.1.28/config.guess b/tmp/x86_64-linux/nokogiri/2.2.2/tmp/x86_64-unknown-linux-gnu/ports/libxslt/1.1.28/libxslt-1.1.28/config.guess
    index 951383e..7f92d97 100755
    --- a/tmp/x86_64-linux/nokogiri/2.2.2/tmp/x86_64-unknown-linux-gnu/ports/libxslt/1.1.28/libxslt-1.1.28/config.guess
    +++ b/tmp/x86_64-linux/nokogiri/2.2.2/tmp/x86_64-unknown-linux-gnu/ports/libxslt/1.1.28/libxslt-1.1.28/config.guess
    @@ -905,6 +905,12 @@ EOF
         or32:Linux:*:*)
        echo or32-unknown-linux-gnu
        exit ;;
    +    ppcle:Linux:*:*)
    +   echo powerpc-unknown-linux-gnu
    +   exit ;;
    +    ppc64le:Linux:*:*)
    +   echo powerpc64-unknown-linux-gnu
    +   exit ;;
         ppc:Linux:*:*)
        echo powerpc-unknown-linux-gnu
        exit ;;
    --
    1.9.1

Another, perhaps more sustainable choice would be to replace `config.guess` and `config.sub` with their current versions. They [can be obtained](https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html) with wget (either as part of the build process, or just on a regular basis)

    $ wget -O config.guess 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
    $ wget -O config.sub 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'

**Comment by flavorjones** [comment]
@mgaudet - Thanks for the work on a patch! Have you submitted this patch upstream to libxslt?

@knu - What are your thoughts about applying a patch like this to libxslt to support PPC?

**Comment by mgaudet** [comment]
`config.guess` doesn't exist in the libxslt source tree (https://git.gnome.org/browse/libxslt/snapshot/libxslt-1.1.28.zip); I can't quite figure out where they get it... it appears as part of `autogen.sh` process.  Given the lack of a trivial patch, I gave up :disappointed: 

Also, it's been three years since they tagged a release, so I didn't keep pursuing this.

**Comment by hernan-erasmo** [comment]
Perhaps [this pull request](https://github.com/sparklemotion/nokogiri/pull/1326) could also fix this issue.

I thought it was never reviewed because it wasn't a priority yet. I'd appreciate some feedback if you've got a minute to spare.

**Comment by flavorjones** [comment]
@hernan-erasmo Looks like you're right on both counts. I'll take a look at the PR.

**Comment by flavorjones** [comment]
PR pulled into master, will be in 1.6.7.rc4
