### ISSUE TITLE
[XML] String Append operation works failed for attribute value:

### ISSUE THREAD

**Issue by macrolee** [sparklemotion/nokogiri#1342]
Demo codes:
```ruby
  node = Nokogiri::XML::Node.new("higher", @foo_xml)
  node['value'] = "hello"
  node['value'] << " world"
  puts node['value']    # output string is "hello",  " world" missed. 
```

Seems the string append operation "<<" does not works for attribute value. Node['value'] is a string class, it should support append operation.

**Comment by flavorjones** [comment]
Hi @macrolee, Thanks for asking this question.

Here's what's going on: `Nokogiri::XML::Node#[]` is a method that returns a *copy* of the `String` that's in the `Nokogiri::XML::Attr` you're referencing. Here's the code:

```ruby
      ###
      # Get the attribute value for the attribute +name+
      def [] name
        get(name.to_s)
      end
```

That string has the `String#<<` method, which will indeed get appended to:

```ruby
doc = Nokogiri::HTML("<div>")
node = Nokogiri::XML::Node.new("div", doc)
node['value'] = "hello"
puts (node['value'] << "world") # => helloworld
```

it's just that you're not reassigning that back to the `Attr` via the `Node#[]=` method.

I'd suggest you use this as a workaround:

```ruby
node['value'] += "hello"
```

Thanks!
