### ISSUE TITLE
Get attribute more clearly

### ISSUE THREAD

**Issue by rusikf** [sparklemotion/nokogiri#1343]
I think It will be interesting if instead

```
parsed_element.at_css('RESULT').attributes['ID']
 ```
I Can write only
```
parsed_element.at_css('RESULT').id
```
What you think about this feature ?

**Comment by flavorjones** [comment]
Thanks for suggesting an improved API!

Unfortunately, creating methods for attributes like this would conflict with Ruby methods, e.g. `Object#class`.

If you'd like to discuss other ways to improve the Nokogiri API, I encourage you to join the mailing list and start a conversation there: https://groups.google.com/forum/#!forum/nokogiri-talk

Cheers,
-mike

**Comment by flavorjones** [comment]
Also worth noting that there is a shorter way to get at attributes, via the `Node#[]` method:

```
parsed_element.at_css("div")["id"]
```
