### ISSUE TITLE
Not properly install rails

### ISSUE THREAD

**Issue by wt111** [sparklemotion/nokogiri#1346]
c:\row\dev\hello_world>rake db:create
rake aborted!
LoadError: cannot load such file -- nokogiri/nokogiri
c:/row/dev/hello_world/config/application.rb:7:in `<top (required)>'
c:/row/dev/hello_world/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- nokogiri/2.2/nokogiri
c:/row/dev/hello_world/config/application.rb:7:in `<top (required)>'
c:/row/dev/hello_world/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

c:\row\dev\hello_world>mysql --user root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7
Server version: 5.6.26 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mydb               |
| mysql              |
| performance_schema |
| test               |
+--------------------+
5 rows in set (0.01 sec)

mysql> exit
Bye

c:\row\dev\hello_world>rails generate  scaffold user first_name:string last_name
:string
c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri
.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x86-mingw32
/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x86-mingw32
/lib/nokogiri.rb:25:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/loofah-2.0.3/lib/loofah.rb:3
:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/loofah-2.0.3/lib/loofah.rb:3
:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/rails-html-sanitizer-1.0.2/l
ib/rails-html-sanitizer.rb:2:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/rails-html-sanitizer-1.0.2/l
ib/rails-html-sanitizer.rb:2:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/sanitize_helper.rb:3:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/sanitize_helper.rb:3:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/text_helper.rb:32:in `<module:TextHelper>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/text_helper.rb:29:in `<module:Helpers>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/text_helper.rb:6:in `<module:ActionView>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/text_helper.rb:4:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_tag_helper.rb:18:in `<module:FormTagHelper>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_tag_helper.rb:14:in `<module:Helpers>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_tag_helper.rb:8:in `<module:ActionView>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_tag_helper.rb:6:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_helper.rb:4:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_helper.rb:4:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers.rb:50:in `<module:Helpers>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers.rb:4:in `<module:ActionView>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers.rb:3:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/legacy_asset_tag_helper.rb:7:in `<module:LegacyAssetTagHelper>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/legacy_asset_tag_helper.rb:6:in `<module:Rails>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/legacy_asset_tag_helper.rb:4:in `<module:Sprockets>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/legacy_asset_tag_helper.rb:3:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:45:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:45:in `<module:Helper>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:7:in `<module:Rails>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:6:in `<module:Sprockets>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:5:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/railtie.rb:6:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/railtie.rb:6:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/ra
ils/railtie.rb:3:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/ra
ils/railtie.rb:3:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/ra
ils.rb:11:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/ra
ils.rb:11:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass-ra
ils.rb:1:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass-ra
ils.rb:1:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:76:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:76:in `block (2 levels) in require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:72:in `each'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:72:in `block in require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:61:in `each'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:61:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.r
b:134:in `require'
        from c:/row/dev/hello_world/config/application.rb:7:in `<top (required)>
'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:141:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:141:in `require_application_and_environment!'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:128:in `generate_or_destroy'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:50:in `generate'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:39:in `run_command!'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

c:\row\dev\hello_world>rails s
c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri
.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x86-mingw32
/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x86-mingw32
/lib/nokogiri.rb:25:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/loofah-2.0.3/lib/loofah.rb:3
:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/loofah-2.0.3/lib/loofah.rb:3
:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/rails-html-sanitizer-1.0.2/l
ib/rails-html-sanitizer.rb:2:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/rails-html-sanitizer-1.0.2/l
ib/rails-html-sanitizer.rb:2:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/sanitize_helper.rb:3:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/sanitize_helper.rb:3:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/text_helper.rb:32:in `<module:TextHelper>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/text_helper.rb:29:in `<module:Helpers>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/text_helper.rb:6:in `<module:ActionView>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/text_helper.rb:4:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_tag_helper.rb:18:in `<module:FormTagHelper>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_tag_helper.rb:14:in `<module:Helpers>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_tag_helper.rb:8:in `<module:ActionView>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_tag_helper.rb:6:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_helper.rb:4:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers/form_helper.rb:4:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers.rb:50:in `<module:Helpers>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers.rb:4:in `<module:ActionView>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/actionview-4.2.4/lib/action_
view/helpers.rb:3:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/legacy_asset_tag_helper.rb:7:in `<module:LegacyAssetTagHelper>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/legacy_asset_tag_helper.rb:6:in `<module:Rails>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/legacy_asset_tag_helper.rb:4:in `<module:Sprockets>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/legacy_asset_tag_helper.rb:3:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:45:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:45:in `<module:Helper>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:7:in `<module:Rails>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:6:in `<module:Sprockets>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/rails/helper.rb:5:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/railtie.rb:6:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sp
rockets/railtie.rb:6:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/ra
ils/railtie.rb:3:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/ra
ils/railtie.rb:3:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/ra
ils.rb:11:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/ra
ils.rb:11:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass-ra
ils.rb:1:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass-ra
ils.rb:1:in `<top (required)>'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:76:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:76:in `block (2 levels) in require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:72:in `each'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:72:in `block in require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:61:in `each'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/r
untime.rb:61:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.r
b:134:in `require'
        from c:/row/dev/hello_world/config/application.rb:7:in `<top (required)>
'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:78:in `require'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:78:in `block in server'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:75:in `tap'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:75:in `server'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands/commands_tasks.rb:39:in `run_command!'
        from c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/com
mands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

c:\row\dev\hello_world>

**Comment by wt111** [comment]
Please fix that problem..!

**Comment by flavorjones** [comment]
@wt111 Nokogiri 1.6.6.2 does not support Ruby 2.2.x on Windows.

If you like, please try Nokogiri 1.6.7.rc3 which is a release candidate for Ruby 2.2.x support on Windows. If you have comments, please let us know at issue #1256.
