### ISSUE TITLE
Address tag with valid flow content generates 'Unexpected end tag : address' error

### ISSUE THREAD

**Issue by adamc00** [sparklemotion/nokogiri#1348]
The following valid HTML5 (as validated by the W3C validator) ...

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Noko nogo</title>
  </head>
  <body>
    <address>
      <ul>
        <li>Noko nogo</li>
      </ul>
    </address>
  </body>
</html>
```

... passed into Nokogiri::HTML with a strict configuration generates the error message ...

```
Unexpected end tag : address
```

Tested with this script: https://gist.github.com/adamc00/f57b1b1a97b2299d6516

**Comment by knu** [comment]
libxml2 does not support HTML5, so it is being strict with HTML4 in mind.  Just a guess but a missing `</li>` may be what it is complaining about.

**Comment by adamc00** [comment]
Thanks @knu, it seems that [inline elements are the only ones allowed](http://www.w3.org/TR/html4/struct/global.html#edef-ADDRESS) inside an `address` element in HTML 4. I've switched to validating my HTML5 with [html5validator](https://github.com/svenkreiss/html5validator).

I've updated my test script to close the `li` to reduce confusion but FYI closing a `LI` is optional in both [HTML5](http://www.w3.org/TR/html/syntax.html#optional-tags) and [HTML4](http://www.w3.org/TR/html4/struct/lists.html#edef-UL).

**Comment by knu** [comment]
> Thanks @knu, it seems that inline elements are the only ones allowed inside an address element in HTML 4. I've switched to validating my HTML5 with html5validator.

Good to know!

> I've updated my test script to close the li to reduce confusion but FYI closing a LI is optional in both HTML5 and HTML4.

Ah, of course. :blush:

**Comment by flavorjones** [comment]
I'm going to go ahead and close this; though there's a larger conversation around HTML5 support in Nokogiri that I've been pushing off. Please ping me if you have thoughts on this topic.
