### ISSUE TITLE
How to use a ruby-core library method as a node name

### ISSUE THREAD

**Issue by KelvinMutuma** [sparklemotion/nokogiri#1350]
```
require 'nokogiri'
require 'digest'

def mine
  xml = Nokogiri::XML::Builder.new{ |xml|
    xml.xforms xmlns: 'http://openrosa.org/xforms/xformsList' do 
      @forms.each do |form|
        xml.xform do 
        #  binding.pry
          xml.formID form.id
          xml.name form.name
          xml.version 1
          xml.hash  Digest::SHA256.file form.survey_xml.survey_xml.file.file
          xml.downloadUrl form.survey_xml.survey_xml.file.file
       end
      end
    end
  }.to_xml
end 

```

When I run that I get an error .. `ArgumentError: wrong number of arguments (1 for 0) from xml.rb:17:in hash`

I know I am getting this error because the node name `hash` is a ruby method, but how do I use it as a node name since the application that I am parsing the xml to expects to have the said node

**Comment by flavorjones** [comment]
@KelvinMutuma Thanks for asking this question.

For future reference, you'll generally get faster responses on the nokogiri-talk mailing list than you will on GH issues -- see http://www.nokogiri.org/tutorials/getting_help.html for information on that.

I think this is documented pretty well at http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Builder in the "Special Tags" section, but in any case the summary is that you can append an underscore to the method you're calling and Nokogiri will know that means you want a tag.

```ruby
#! /usr/bin/env ruby

require 'nokogiri'

xml = Nokogiri::XML::Builder.new{ |xml|
  xml.xforms xmlns: 'http://openrosa.org/xforms/xformsList' do 
    xml.xform do 
      xml.hash_ "hash of the contents"
    end
  end
}.to_xml

puts xml
# => <?xml version="1.0"?>
#    <xforms xmlns="http://openrosa.org/xforms/xformsList">
#      <xform>
#        <hash>hash of the contents</hash>
#      </xform>
#    </xforms>
```
