### ISSUE TITLE
Nokogiri should not ship GPL-licensed file that's distributed with libxslt

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1354]
Background is here: https://mail.gnome.org/archives/xml/2015-September/msg00003.html

`libxslt-1.1.28/doc/tutorial2/libxslt_pipes.c` is GPL licensed, and thus appears to violate the MIT license under which libxslt is distributed. I've [reported this to the libxslt developers](https://mail.gnome.org/archives/xml/2015-September/msg00003.html).

Unfortunately, this file is also getting distributed in some of the Nokogiri gem files, which are also MIT-licensed. That's kind of a bummer, and some big corporations have noticed.

I'd like to propose the removal of this file from the Nokogiri distribution. It's not clear to me how we could best do this, or do this at all in a clean way.

Objections? Thoughts?

**Comment by larskanis** [comment]
IMHO this should be fixed upstream. Interesting that they don't care about this issue, but since they don't, I wouldn't too.

I guess the introduction of GPL licensed example code was more an accident than intended. The file `libxslt/xsltproc.c` , that is claimed to be the base of `doc/tutorial/libxslt_tutorial.c` , is MIT licensed, at least.

**Comment by flavorjones** [comment]
@larskanis - I agree, but in the meantime I'm getting asked about this by some big corporations who happen to be customers of my day job (WORLDS COLLIDING).

I just replied on the libxml2 dev thread, let's see if we can convince them that an upstream change is necessary.

**Comment by flavorjones** [comment]
Worth noting that this was fixed upstream in libxml2:

> https://mail.gnome.org/archives/xml/2015-October/msg00013.html

I'm closing.
