### ISSUE TITLE
Error Installing on Rails 4.2.4

### ISSUE THREAD

**Issue by himenjil** [sparklemotion/nokogiri#1358]
Error installing rails:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/cache/nokogiri-1.6.6.2.gem

**Comment by himenjil** [comment]
I got it working by installing

xcode-select --install

**Comment by flavorjones** [comment]
... as mentioned in the installation tutorial in the [OSX section](http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x). ;)

**Comment by flavorjones** [comment]
Just an FYI -- xcode-select has nothing to do with a corrupt .gem file. These are two separate issues.

**Comment by himenjil** [comment]
Okay thanks sir :) @flavorjones
