### ISSUE TITLE
Only version 1.6.1 is supported in Ubuntu docker

### ISSUE THREAD

**Issue by bean5** [sparklemotion/nokogiri#1359]
I couldn't get version 1.6.6.2 working in a docker. I could only get up to 1.6.1 working. I documented it at https://github.com/sparklemotion/nokogiri/wiki/Running-in-a-docker-(Ubuntu). Unfortunately, it appears that version 1.6.1 functions differently than 1.6.6.2, which means I now need to modify my scripts that use nokogiri.

**Comment by bean5** [comment]
This might be related to the build errors at https://travis-ci.org/sparklemotion/nokogiri

**Comment by flavorjones** [comment]
@bean5 Sorry to hear you're having problems!

I assure you that 1.6.6.2 does work in a Docker container, but maybe not *your* Docker container. ;) Without more information about your rootfs and a description of what you're seeing, I won't be able to help.

Please join the mailing list and ask for help there? We try to reserve GH Issues for bug reports and not user help. See http://www.nokogiri.org/tutorials/getting_help.html for our rationale.

Good luck!

**Comment by bean5** [comment]
Do you have a docker container that has 1.6.6.2 working? I'd love to use it.

**Comment by bean5** [comment]
I'd be happy to update the documentation on how to get it up and running in a docker if I just had 1 Dockerfile where it was working.

**Comment by larskanis** [comment]
@bean5 I did a quick test with my [rake-compiler-dock](https://hub.docker.com/r/larskanis/rake-compiler-dock/) image and installation of nokogiri-1.6.6.2 worked with both rvm and system ruby in a docker container. You maybe need to install additional development tools or -dev packages. Look at the log files written while `gem install nokogiri` - it should point you to the missing dependency.
