### ISSUE TITLE
[jruby] XML::Schema#validate does not work when provided a path

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1361]
Found when I added tests related to #1351, see https://github.com/sparklemotion/nokogiri/commit/ebdb95b7543ac90cd439985c7e0cef6a499348c0

This fails because ParserContext's `setInputSource()` method thinks it's receiving string **data**, and not a path to a file.

Would love if someone comfortable with JRuby would fix this quickly, as the failing test is on master.

/cc @jvshahid @yokolet

**Comment by jvshahid** [comment]
Sure, i'll take a look at it.

**Comment by flavorjones** [comment]
@jvshahid - We received a PR that addresses this, which I just merged. No worries!
