### ISSUE TITLE
Installing on Fedora

### ISSUE THREAD

**Issue by lcjury** [sparklemotion/nokogiri#1371]
Hi, Fedora 23 has ben realeased this week. So I got a fresh instalation of fedora 23 and tried to install Rails, but got troubles installing nokogiri.

the problem was this:  `gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: File or directory doesn't exists`. Remember that last time I installed rails on a fresh (not 100% sure) installation of Fedora 22 without any problem.

On Fedora `rpm-build` is required. So, compared to Redhat installation ( http://www.nokogiri.org/tutorials/installing_nokogiri.html#red_hat___centos), in fedora we must run `sudo dnf install rpm-build`. Please, add that to the installation guide. 

I spend some time trying to fix this. and there is a lot of "incorrect" information about this trouble (Depending on how do you search for this). Is a bit hard to notice that the problem is related to that library (becouse that gcc error is inside a log file, and gem install nokogiri output a lot of errors not related to redhat-hardened-cc1).

**Comment by flavorjones** [comment]
I see you asked this on the mailing list as well as by opening an issue under the tutorial repo.

Let's use the mailing list to work through this issue.

**Comment by lcjury** [comment]
I don't think it's neccesary. I got it working,  on Fedora 23 `rpm-build` is required.

**Comment by brasey** [comment]
Thanks for this, you just saved me a bunch of time!

**Comment by lcjury** [comment]
Glad to hear that brasey. I lost a bunch of time tryin to fix this. 

It would be great if @flavorejones add this to the docs, nobody answered me there.

**Comment by flavorjones** [comment]
Pull request welcome to the docs repository.
