### ISSUE TITLE
Update vendored libxml2 to include latest USN addressed by Canonical in USN-2812-1

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1374]
Context:

> http://www.ubuntu.com/usn/usn-2812-1

The relevant commits are:

* https://git.gnome.org/browse/libxml2/commit/?id=213f1fe0d76d30eaed6e5853057defc43e6df2c9
* https://git.gnome.org/browse/libxml2/commit/?id=a7dfab7411cbf545f359dd3157e5df1eb0e7ce31
* https://git.gnome.org/browse/libxml2/commit/?id=9b8512337d14c8ddf662fcb98b0135f225a1c489
* https://git.gnome.org/browse/libxml2/commit/?id=bd0526e66a56e75a18da8c15c4750db8f801c52d
* https://git.gnome.org/browse/libxml2/commit/?id=41ac9049a27f52e7a1f3b341f8714149fc88d450
* https://git.gnome.org/browse/libxml2/commit/?id=f0709e3ca8f8947f2d91ed34e92e38a4c23eae63

I'd like to get these patches merged if necessary and release as v1.6.6.3 as soon as possible.

**Comment by flavorjones** [comment]
@larskanis is preparing the patches

**Comment by larskanis** [comment]
I pushed the one relevant commit to master. The other two are not necessary.

If you still have a rake-compiler-dev-box available, you could build the windows gems. I would use the rake-compiler-dock in interactive mode (the resulting binaries are the same). However for today I must say goodbye. If you have any issues with the windows build, leave a comment - I'll address this tomorrow.

**Comment by flavorjones** [comment]
@larskanis Well, actually the Manifest.txt commit is necessary to be ported to master, but I'll do it. That file controls what's packaged in the gem when it's built.

**Comment by flavorjones** [comment]
@larskanis Thanks for your help! Will ping you if I don't finish everything today.

**Comment by flavorjones** [comment]
1.6.6.3 has been released.
