### ISSUE TITLE
Nokogiri cannot load such file

### ISSUE THREAD

**Issue by Rui90** [sparklemotion/nokogiri#1379]
Already tried to install it via 

gem install nokogiri and via local installation

either way:

![2015-11-20](https://cloud.githubusercontent.com/assets/6035220/11312378/836f81ce-8fcd-11e5-8396-95fb7b9f3031.png)

**Comment by jvshahid** [comment]
Hi @Rui90, it is better to ask installation related question on the [mailing list](http://groups.google.com/group/nokogiri-talk). Someone might have run into the same issue and be able to assist you. Also, copy pasting the text output from your terminal is good practice and help those with small laptop screen (like mine) be able to read the output.

I'll go ahead and close this issue.

**Comment by larskanis** [comment]
This is a duplication of #1256 .
