### ISSUE TITLE
Error when building nokogiri with java 1.7.0_60

### ISSUE THREAD

**Issue by ianderse** [sparklemotion/nokogiri#1384]
Opening at the request of @jvshahid as per comment in #1114 :

I get the following error when trying to build the gem:

11. ERROR in ext/java/nokogiri/HtmlSaxPushParser.java (at line 181)
public Thread newThread(Runnable r) {
^^^^^^^^^^^^^^^^^^^^^
The method newThread(Runnable) of type new ThreadFactory(){} must override a superclass method

ERROR in ext/java/nokogiri/HtmlSaxPushParser.java (at line 223) public HtmlSaxParserContext call() throws Exception { ^^^^^^^^^^^^^^^^^^^^^^^ The method call() of type HtmlSaxPushParser.ParserTask must override a superclass method
12 problems (2 errors, 10 warnings)rake aborted!
Command failed with status (255): [javac -extdirs "/usr/java/jdk1.7.0_60/jre/...]"

Environment:
JRuby 1.7.19
Redhat enterprise linux 5.11
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

**Comment by jvshahid** [comment]
Just tried this on a centos5.11 docker container and it worked:

```
[root@e0ca3aeb4266 nokogiri]# java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)
[root@e0ca3aeb4266 nokogiri]# jruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.7.0_60-b19 [linux-amd64]
[root@e0ca3aeb4266 nokogiri]# ll pkg/
total 5816
drwxr-xr-x 9 root root    4096 Nov 27 17:06 nokogiri-1.6.7.rc4-java
-rw-r--r-- 1 root root 5949952 Nov 27 17:06 nokogiri-1.6.7.rc4-java.gem
```

**Comment by flavorjones** [comment]
@ianderse Can you help us reproduce what you're seeing? If not, I'll close in a few days.

**Comment by ianderse** [comment]
@flavorjones I'm willing to bet it's some crazy configuration stuff on our servers, which sadly I do not have control of. Unless someone else sees it, I'd say go ahead and close it.

**Comment by jvshahid** [comment]
Closing.
