### ISSUE TITLE
LoadError when deploying to JRuby - Nokogiri 1.6.7

### ISSUE THREAD

**Issue by ianderse** [sparklemotion/nokogiri#1390]
@jvshahid Unfortunately with Nokogiri 1.6.7 release I am seeing a loaderror issue resurfacing (first reported in #1114).

org.jruby.exceptions.RaiseException: (LoadError) load error: nokogiri/nokogiri -- java.lang.NoClassDefFoundError: com/sun/org/apache/xpath/internal/VariableStack

Environment:
JRuby 1.7.19
Redhat enterprise linux 5.11
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

Were your recent changes (#1380) included in the full 1.6.7 release?

**Comment by jvshahid** [comment]
The fix for this issue wasn't included in 1.6.7 but will be included in 1.6.8. Sorry for the confusion. I'll go ahead and close this issue, feel free to open a new one if the problem still exists with 1.6.8 (when it is released).
