### ISSUE TITLE
Ruby version 2.2.3 for Windows - 'config.yml' problem 

### ISSUE THREAD

**Issue by CarlaT4** [sparklemotion/nokogiri#1418]
Hey everyone, 

Firstly, I am COMPLETELY new to programming and trying to install Ruby for the first time on Windows. What looks like should be a fairly seemless process, has become a nightmare (note: for me, as a total novice). Would really appreciate your help to get this fixed, so I can start programming,

So, I have installed Ruby 2.2.3 and the dev kit that supports my 64 bit machine. 

I then get to a message saying the following:

Initialization complete! Please review and modify the auto-generated  'config.yml' file to ensure it contains the root directories to all of the installed rubies you want enhanced by the devkit. 

Please could someone tell me, in exact terms if possible, the remaining steps/commands I need to do here in order to make this work. 

Thanks!

**Comment by flavorjones** [comment]
Hi,

This project is an XML parser, and your problem seems unrelated.

I'd recommend mailing ruby-talk for help with installing Ruby. Good luck!
