### ISSUE TITLE
Problem with 'parse' method

### ISSUE THREAD

**Issue by chumakoff** [sparklemotion/nokogiri#1419]
Why HTML::Document.parse("one < two") returns: 
``` html
<html><body><p>one </p></body></html>'  
```

?

This method cuts off the part of a text that goes after '<' sign.  Because of this, the Ruby on Rails's  #simple_format method works the same way: 

simple_format("text_before < text_after")   =>  "text_before "

**Comment by chumakoff** [comment]
Rails 4.2.4
Nokogiri 1.6.7

**Comment by pixeltrix** [comment]
FYI, this works

``` irb
>> Nokogiri::HTML::Document.parse('one > two').text
=> "one > two" 
```

One thing to bear in mind is that this may well be an issue in libxml2 itself

**Comment by flavorjones** [comment]
Hi,

Thanks for asking this question. Nokogiri uses XML parsing libraries under the hood (libxml2 for MRI, xerces/nekohtml for JRuby) and so we have very little control over how those libraries decide to "fix" broken markup.

**Comment by chumakoff** [comment]
Are you kidding me ?  Your code does not work on a few different servers with different operating systems and you telling me "We don't care, the library is to blame". The "less than" sign is a common case, which can occur in any text.

**Comment by flavorjones** [comment]
The "less than" sign by itself is not valid HTML or XML markup. There's no spec on how to fix broken markup.

So yes, I'm saying that the underlying libraries, written in C or Java, which are responsible for tokenizing and parsing the documents passed into Nokogiri, and most especially for choosing how to "fix" that invalid markup, are beyond the control of Nokogiri.

Lastly, I just want to ask that you keep your tone constructive. I'll point you at our Code of Conduct that's in our [CONTRIBUTING.md](https://github.com/sparklemotion/nokogiri/blob/master/CONTRIBUTING.md) document. It's easy to misinterpret your previous comment as entitled, rude, and judgmental. As a result I've locked this issue down to ensure nobody else will respond to you in kind.

I'm sorry we weren't able to help you in this instance, good luck on future endeavors.

**Comment by flavorjones** [comment]
Final thought, explaining the behavior, is that "one < two" is interpreted by both parsers as the string "one " followed by an incomplete tag "<two".

If you want "one < two" to be treated as "one &lt; two" (that is, a text string) then I'd recommend escaping it first. Perhaps the Rails team, based on the context of `simple_format`, can selectively apply escaping? You'll have to take it up with them.
