### ISSUE TITLE
JRuby: <a href> links are duplicated inside <noscript> tags

### ISSUE THREAD

**Issue by pngdwnld** [sparklemotion/nokogiri#1421]
Here's a barebone example (it would still give the wrong parsing if you expand `noscript` and `a` tags)
```
jruby-9.0.4.0 :044 > puts Nokogiri::HTML('<a><noscript/></a>').to_s

<html><head></head><body><a></a><noscript><a></a></noscript></body></html>
```

Same command in CRuby gives the correct parsing: `<html><body><a><noscript></noscript></a></body></html>`

**Comment by flavorjones** [comment]
Hi,

Thanks for asking this question. My reading of the allowed parent elements of `<noscript`>, as explained here:

> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript

indicates that valid parent elements must accept "phrasing content", whatever that is, but this page:

> https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

indicates that `<a>` is only conditinally part of that class.

My guess here is that libxml2 and xerces/nekohtml have implemented slightly different methods of markup correction, and so you get two different interpretations of the document.

If you feel strongly that the JRuby implementation is incorrect, I'd ask that you submit a bug report upstream to [NekoHTML](http://nekohtml.sourceforge.net/) as Nokogiri is merely a wrapper around that parsing and validation engine.

Thanks, and sorry I couldn't be more helpful.
