### ISSUE TITLE
Can't select <article>?

### ISSUE THREAD

**Issue by sixtyfive** [sparklemotion/nokogiri#1433]
I'm trying to parse a document which uses some of the new HTML5 tags, among them `<article>`. For some reason, `ng.css('div')` works just fine and returns dozens of elements, but `ng.css('article')` contains none, even though plenty are in the HTML. Is this not supported, am I doing something wrong or have I hit a bug?

**Comment by flavorjones** [comment]
Hi @sixtyfive,

Thanks for asking this question. Nokogiri's underlying library, 'libxml2' (which I'm assuming you're using, you haven't provided any information about your system or ruby) doesn't support HTML5.

If you're interested in HTML5 support, check out [nokogumbo](https://github.com/rubys/nokogumbo).

Hope this helps,
-mike

**Comment by sixtyfive** [comment]
Hi @flavorjones, thanks for the answer! Just to clarify, do you mean that Nokogiri does support HTML5 if the underlying libraries support it or do you mean that Nokogiri doesn't support HTML5 at all and only nokogumbo does?
