### ISSUE TITLE
gem-compiler fails to run on nokogiri

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1436]
```
$ gem fetch nokogiri
Fetching: nokogiri-1.6.7.2.gem (100%)
Downloaded nokogiri-1.6.7.2

$ gem compile nokogiri-1.6.7.2.gem
Unpacking gem: 'nokogiri-1.6.7.2' in temporary directory...
Building native extensions.  This could take a while...
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["ports/archives/libxml2-2.9.2.tar.gz", "ports/archives/libxslt-1.1.28.tar.gz"] are not files
```

See related:
- https://github.com/sparklemotion/nokogiri/pull/1275
- https://github.com/luislavena/gem-compiler/issues/12

The key commit here is 12759cf which, though well-intended, deletes files declared in the gemspec manifest, and so breaks an implicit contract that gem-compiler depends upon.

@knu and @larskanis I don't think we want to delete the source tarballs. Thoughts?

**Comment by flavorjones** [comment]
Closing this, as #1437 notes that there's a gem-compiler option that works around this:

> An alternative is gem-compiler's option `--prune`, as described here: https://github.com/luislavena/gem-compiler/issues/12

**Comment by larskanis** [comment]
Another solution would be [this commit](https://github.com/larskanis/nokogiri/commit/fbbb2ca56a2d710e9d8eec6ff59422a4de4df571). @flavorjones is this something you want to merge?
