### ISSUE TITLE
Do not glorify violence

### ISSUE THREAD

**Issue by jspanjers** [sparklemotion/nokogiri#1450]
When I look at https://rubygems.org/gems/nokogiri, in the description of Nokogiri it reads:

' XML is like violence - if it doesn’t solve your problems, you are not using enough of it.'

Obviously, this is humorous. But maybe it is also bad taste. At least it is not useful in the description of this gem.

Please consider removing this line from the description.

**Comment by flavorjones** [comment]
Done, see ddd8e1d.

**Comment by willsu** [comment]
Nice job! You removed (probably) the funniest description of an XML parser on the Internet 👍  ;)
