### ISSUE TITLE
Installation problem - (OSX version - 10.11.3 (15D21) , Xcode Version - 7.3 (7D175))

### ISSUE THREAD

**Issue by ArunPrasanth-R** [sparklemotion/nokogiri#1455]
sudo gem install jazzy

Building native extensions.  This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.
   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
make: *** No rule to make target `"/Applications/Xcode', needed by `autolink.o'.  Stop.

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4/ext/redcarpet/gem_make.out

**Comment by flavorjones** [comment]
Hi,

It's not clear from what you've provided that this is a nokogiri issue. I'm going to close; if you can, please provide details specific to Nokogiri not installing, including:

* command that you ran (preferably `gem install nokogiri` and not through bundler)
* if bundler, then provide bundler configuation options
* output from the command
* additional logfiles (e.g. mkmf.log)

I'm happy to reopen if you can provide additional details.

**Comment by ArunPrasanth-R** [comment]
I have just run the command : "  sudo gem install jazzy " .... As mentioned in the documentation. It throws me the above mentioned error.
