### ISSUE TITLE
Fail install on Ruby 2.3 for Windows

### ISSUE THREAD

**Issue by Sega100500** [sparklemotion/nokogiri#1456]
```gem install rails```
on nokogiri install fail with error: 'nokogiri requires Ruby version < 2.3, >= 1.9.2.'

```gem install nokogiri -v '1.6.5'```
solve problem of installation
but
```gem update```
again fails

**Comment by Javix** [comment]
Not sure but it seems that `2.3` is not supported yet on Windows.
Any way, I tried to install the latest version on Windows 64-bits and ruby 2.3:
```
gem install nokogiri -v 1.6.8.rc3 -N
```
and it was installed successfully:
```
Fetching: pkg-config-1.1.7.gem (100%)
Successfully installed pkg-config-1.1.7
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: nokogiri-1.6.8.rc3-x64-mingw32.gem (100%)
Nokogiri is built with the packaged libraries: libxml2-2.9.3, libxslt-1.1.28, zlib-1.2.8, libiconv-1.14.
Successfully installed nokogiri-1.6.8.rc3-x64-mingw32
3 gems installed
```
But when trying to install `rails` it failed:
```
gem install rails -N
ERROR:  Error installing rails:
        nokogiri requires Ruby version < 2.3, >= 1.9.2.
```

**Comment by Sega100500** [comment]
@Javix 
> Not sure but it seems that 2.3 is not supported yet on Windows.
Already supported... after long time wait
http://rubyinstaller.org/downloads/

**Comment by Javix** [comment]
@Sega100500 I meant 

> that nokogiri and 2.3 is not fully supported
i.e. Nokogiri with Ruby 2.3. You can event try to install `rspec-rails` on Ruby 2.3 to see the same error of nokogiri Ruby version.

**Comment by Sega100500** [comment]
@Javix 
Ruby 2.3 + nokogiri
On Linux it work, on windows - not

**Comment by larskanis** [comment]
Ruby-2.3 cross build targeting Windows RubyInstaller was added in [this commit](https://github.com/sparklemotion/nokogiri/commit/a886503b230b7919f0ab3c23e958f6a62955e3b4) . Please try the latest pre-release:

```sh
gem inst nokogiri --pre
```
or per Gemfile:
```ruby
gem 'nokogiri', '1.6.8.rc3'
```
The source installation should work as well (with nokogiri-1.6.7):
```sh
gem inst nokogiri --platform ruby
```

**Comment by hut8** [comment]
@larskanis Thanks very much :+1:  Perfect timing.

**Comment by Sega100500** [comment]
@larskanis 
Fine. But how about ```gem update```?
Install nokogiri of specific version - is not problem. Problem is when nokogiri update it fail installation.

**Comment by okeyparking** [comment]
A quick workaround is the following (works with ruby 2.3. win64): 

```
gem install nokogiri -v '1.6.6.4'
gem install rails 
gem install nokogiri -v '1.6.8.rc3'
```

After that explictly include 
`gem 'nokogiri', '>=1.6.8.rc3'`
in gemfile

`gem update` works without error

**Comment by Sega100500** [comment]
@okeyparking 
It work! Many thanks!

**Comment by flavorjones** [comment]
As mentioned above, windows is supported in the prerelease and will be in 1.6.8 final.

**Comment by Zbromination** [comment]
@okeyparking 

I'm totally new to this, could you tell me how to:

>After that explictly include 
gem 'nokogiri', '>=1.6.8.rc3'
in gemfile

**Comment by zuckerlinh** [comment]
Same question as Zbromination, Plz explain 

> After that explictly include 
> gem 'nokogiri', '>=1.6.8.rc3'
> in gemfile

**Comment by Javix** [comment]
@okeyparking, @zuckerlinh: Hey, guys, just add `gem 'nokogiri', '>=1.6.8.rc3` in your Rails application Gemfile (outside of the development, test, production group) and run `bundle update nogogiri`.

**Comment by spa46** [comment]
Yes. It works. Thanks. :)

**Comment by ivangabriele** [comment]
Thanks @larskanis & @Javix :)

**Comment by BurstNova** [comment]
@Javix @okeyparking @zuckerlinh  I'm also totally new to this, and I have to ask how do you open my Rails application Gemfile and `add gem 'nokogiri', '>=1.6.8.rc3` in? That's the only thing holding me off right now

**Comment by Javix** [comment]
@BurstNova it would be better not to polute the issue tracker with such kind of questions, try [Stackoverflow](http://stackoverflow.com/) please.
You can open Gemfile as no matter which file in your file system with your preferred text editor.
