### ISSUE TITLE
Unknown encoding name - utf8

### ISSUE THREAD

**Issue by maxiedaniels** [sparklemotion/nokogiri#1457]
Hi,

I'm getting a strange error when I try and access a div element on a webpage (I've tried different elements.. same issue). Error is below:

from /usr/local/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:631:in `serialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:790:in `to_format'
	from /usr/local/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:646:in `to_html'
	from /usr/local/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:517:in `to_s'
	from /Users/maxfarrar/Dropbox/Programming/Ruby/generalScraper.rb:13:in `puts'
	from /Users/maxfarrar/Dropbox/Programming/Ruby/generalScraper.rb:13:in `puts'
	from /Users/maxfarrar/Dropbox/Programming/Ruby/generalScraper.rb:13:in `scrape'

**Comment by gmcnaughton** [comment]
I think the problem is that "utf8" is not a valid encoding, it needs to be "utf-8" (with the dash).

    > "foo".force_encoding("utf-8")
    # => "foo"
  
    > "foo".force_encoding("utf8")
    ArgumentError: unknown encoding name - utf8

Is it possible that the webpage you're parsing uses "utf8" instead of "utf-8" somewhere (maybe in its Content-Type header or meta charset tag)?

**Comment by flavorjones** [comment]
There's not enough information here to diagnose the issue. Please reopen with more information if you're still experiencing issues.
