### ISSUE TITLE
NodeSet#unshift does not exist

### ISSUE THREAD

**Issue by benhass** [sparklemotion/nokogiri#1459]
Hi @flavorjones, @larskanis, @jvshahid,

Would you accept a PR adding in the `NodeSet#unshift` method? I noticed that `NodeSet` has `push`, `pop`, and `shift`, but no `unshift`. Maybe there is a practical reason why not, or maybe this was just simply forgotten, in any case thought I would ask before making a PR.

Thanks,
Ben

**Comment by flavorjones** [comment]
Hi @benhass,

Sorry for not responding sooner. This seems like a perfectly reasonable thing to implement, and I'm not sure why we didn't implement it originally. PR away!
