### ISSUE TITLE
Nokogiri includes <head> content in <body> after <ins> tag jruby, 1.6.7.2 

### ISSUE THREAD

**Issue by toddgardner** [sparklemotion/nokogiri#1464]
jruby:

```
jruby-9.0.4.0 :026 > Nokogiri::HTML::Document.parse("<html><head><ins></ins><title>Foo</title></head><body><p>Bar</p></body></html>").css('body').to_s
 => "<body><ins></ins><title>Foo</title><p>Bar</p></body>" 
```

Note both the ins and the title are in the body, even though they are in the head in the doc.

Here's the MRI 2.1.5, 1.6.6.2:

```
2.1.5 :004 > Nokogiri::HTML::Document.parse("<html><head><ins></ins><title>Foo</title></head><body><p>Bar</p></body></html>").css('body').to_s
 => "<body><p>Bar</p></body>"
```

**Comment by flavorjones** [comment]
This is likely due to the underlying parsing library's behavior, and not Nokogiri's. I'll leave it open in case someone wants to investigate.

**Comment by flavorjones** [comment]
I'm going to close this, as there's nothing Nokogiri can do (at least, nothing easy) to modify NekoHTML's behavior.
