### ISSUE TITLE
gemspec is missing

### ISSUE THREAD

**Issue by mkno** [sparklemotion/nokogiri#1471]
hey guys it seems like somebody messed up because gemspec is missing instead I found a file called y_u_no_gemspec.md. This is not a gemspec file. It appears to be somebody's rant that belongs on a personal blog post or a drive by HN comment. I find it highly unprofessional that somebody took the time to include that but not the actual gemspec file.

How to replicate this issue: install nokogogiri and head over to the gems directory and search for the gemspec file, it will not be present.

Expected Result: .gemspec

**Comment by flavorjones** [comment]
Hello,

Thanks for asking this question, but you should read the contents of that file to discover why we've intentionally not provided a gemspec file.

Thanks,
-mike

**Comment by flavorjones** [comment]
To be clear, this *was* a blog post,

> http://blog.flavorjon.es/2012/03/y-u-no-gemspec.html

and I put it in the repository to inform people who would otherwise open a ticket asking this question.

I'm curious why you find it to be a "rant" and "unprofessional"? I literally know of no other way to communicate our reasoning to Nokogiri users than to both blog about it and provide an explanation in the source code.

**Comment by flavorjones** [comment]
Lastly, maybe you can explain the problem you're trying to solve? Then this ranty and unprofessional maintainer might actually be able to help. :)

**Comment by flavorjones** [comment]
Aaaaand one more comment, because I still don't understand what problem you're trying to solve ...

The installed gem most definitely has a gemspec:

```
$ find /home/flavorjones/.rvm/gems -name 'nokogiri-1*.gemspec'
/home/flavorjones/.rvm/gems/ruby-1.9.3-p551/specifications/nokogiri-1.6.7.1.gemspec
/home/flavorjones/.rvm/gems/ruby-1.9.3-p551/specifications/nokogiri-1.6.7.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.2/specifications/nokogiri-1.6.7.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.1.5@nokogiri.org/specifications/nokogiri-1.6.6.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.3/specifications/nokogiri-1.6.7.1.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.3/specifications/nokogiri-1.6.7.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.3/specifications/nokogiri-1.6.7.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.3/specifications/nokogiri-1.6.6.3.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.3/specifications/nokogiri-1.5.11.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.3/specifications/nokogiri-1.6.6.2.gemspec
/home/flavorjones/.rvm/gems/jruby-9.0.4.0/specifications/nokogiri-1.6.8.rc3-java.gemspec
/home/flavorjones/.rvm/gems/jruby-1.7.19/specifications/nokogiri-1.6.7.rc1-java.gemspec
/home/flavorjones/.rvm/gems/jruby-1.7.19/specifications/nokogiri-1.6.6.2-java.gemspec
/home/flavorjones/.rvm/gems/ruby-2.1.8/specifications/nokogiri-1.6.7.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.0.0-p648/specifications/nokogiri-1.6.7.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.0.0-p648/specifications/nokogiri-1.6.6.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.1.7@nokogiri.org/specifications/nokogiri-1.6.6.2.gemspec
/home/flavorjones/.rvm/gems/jruby-1.7.23/specifications/nokogiri-1.6.7.2-java.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.4/specifications/nokogiri-1.6.7.1.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.4/specifications/nokogiri-1.6.7.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.4/specifications/nokogiri-1.6.6.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.2.2@pivotal-one-network/specifications/nokogiri-1.6.6.4.gemspec
/home/flavorjones/.rvm/gems/ruby-2.3.0/specifications/nokogiri-1.6.7.1.gemspec
/home/flavorjones/.rvm/gems/ruby-2.3.0/specifications/nokogiri-1.6.7.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.3.0/specifications/nokogiri-1.6.6.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.3.0/specifications/nokogiri-1.6.6.4.gemspec
/home/flavorjones/.rvm/gems/ruby-2.1.7/specifications/nokogiri-1.6.6.2.gemspec
/home/flavorjones/.rvm/gems/ruby-2.1.7/specifications/nokogiri-1.6.6.4.gemspec
```

**Comment by flavorjones** [comment]
Seems like a troll, so I'm going to just lock it down now. Here's the history, just for posterity.

Original:
![screenshot from 2016-05-28 13 40 50](https://cloud.githubusercontent.com/assets/8207/15628849/42479a9a-24da-11e6-997c-375ca39eaa5c.png)

Edited:
![screenshot from 2016-05-28 13 28 25](https://cloud.githubusercontent.com/assets/8207/15628853/55706d0e-24da-11e6-8610-c065c6e85ddd.png)
