### ISSUE TITLE
upgrade to libxml2 2.9.4 and libxslt 1.1.29

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1473]
both of which contain security fixes.

**Comment by flavorjones** [comment]
Finally got these libraries to build properly on all our combinations of windows and cross-compiled windows.

This will be in 1.6.8 final, due out later today.

**Comment by saizai** [comment]
After `bundle update nokogiri`, I get this in my git:

`renamed:    vendor/cache/nokogiri-1.6.7.1.gem -> vendor/cache/nokogiri-1.6.8.gem`

Is this expected behavior?

**Comment by flavorjones** [comment]
@saizai You're asking a question about how `git` handles files managed by `bundler` ... this is not a nokogiri-specific question.

But yes, that's expected of bundler and git.

**Comment by flavorjones** [comment]
@saizai to be more specific, if you look at the `git diff` output, you should see something like:

```
diff --git a/vendor/cache/nokogiri-1.6.7.1.gem b/vendor/cache/nokogiri-1.6.8.gem
similarity index 53%
rename from vendor/cache/nokogiri-1.6.7.1.gem
rename to vendor/cache/nokogiri-1.6.8.gem
index d66d597..d8782d9 100644
Binary files a/vendor/cache/nokogiri-1.6.7.1.gem and b/vendor/cache/nokogiri-1.6.8.gem differ
```

which indicates that they're similar enough to be treated as a rename, but they're clearly different files (similarity index 53%).

If you have more questions, I urge you to look into how git handles these cases.

**Comment by saizai** [comment]
@flavorjones Thanks for the explanation. I naïvely thought that "rename" meant "binary equal", not something that fuzzy.
