### ISSUE TITLE
problem with parsing large HTML files

### ISSUE THREAD

**Issue by ivanovaleksey** [sparklemotion/nokogiri#1476]
Hi.

I'm trying to parse [this](http://www.pro-medic.ru/index.php?ht=246&perpage=all) page.
But unfortunately I can't get all items from page.

My simple test code is as following
```
require 'open-uri'
require 'nokogiri'

html = Nokogiri::HTML open('http://www.pro-medic.ru/index.php?ht=246&perpage=all')
p html.css('ul.products-grid-compact li .goods_container').count
```

It returns only 83 items as long as real count is about 186.

I've thought that problem can be in `open` function, but it seems that function read all html page correctly.

Can someone help me?

Thanks.

**Comment by flavorjones** [comment]
Hello!

Thanks for asking this question! Your request for assistance using
Nokogiri will not go unanswered!

However, Nokogiri's Github Issues is reserved for reporting bugs or
submitting patches. If you ask your question on the mailing list, Team
Nokogiri promises someone will provide you with an answer in a timely
manner.

If you'd like to read up on Team Nokogiri's rationale for this policy,
please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.
