### ISSUE TITLE
gem install nokogiri -v 1.6.8 fails also on Mac OS X

### ISSUE THREAD

**Issue by alexharv074** [sparklemotion/nokogiri#1486]
I see a bunch of related issues and I can't tell if this is duplicating them or not but so as to document the workaround I've been able to get my builds green again by adding this to my `Gemfile`:

```
gem 'nokogiri', '< 1.6.8'
```

**Comment by mkmckenzie** [comment]
Hi @alexharv074 - I recently had an issue as well and `brew install coreutils` seemed to fix it for me. My specific error was something along the lines of  `make: /usr/local/bin/gmkdir: No such file or directory`. Hope this helps!

**Comment by BenMorganIO** [comment]
This helped get Nokogiri installed on my Mac:

```shell
gem install nokogiri -- --with-xml2-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 --use-system-libraries
```

**Comment by charaton** [comment]
Thanks @BenMorganIO, that worked for me on OS X 10.11.5 with Xcode 7.3.1.

**Comment by alexharv074** [comment]
The `brew install coreutils` didn't fix it for me, however @BenMorganIO's workaround did work.  I feel that it should just install however.  Will a future release of nokogiri address this?

**Comment by mad-raz** [comment]
incase you are using bundler to install it and it's still failing use
```
bundle config build.nokogiri --with-xml2-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 --use-system-libraries
```
thanks to @BenMorganIO

**Comment by flavorjones** [comment]
Hi all,

I'm curious if anyone who had this problem followed the installation tutorial here:

    http://www.nokogiri.org/tutorials/installing_nokogiri.html

which we believe works for most OSX configurations.

If you did follow all the instructions and it didn't help you, can you please state that fact in this thread?

If you did follow those instructions, it didn't help, and the `coreutils` workaround above worked for you, can someone please send a PR to the [tutorial repo](http://github.com/sparklemotion/nokogiri.org-tutorials)?

If you didn't follow the instructions, can you help me understand how we can better point people at those instructions?

Thanks for your patience, everyone. OSX has become a very complicated platform to support and we need everyone's help to diagnose issues properly.

**Comment by franklinyu** [comment]
Instead of the library provided in

```text
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2
```

provided by @BenMorganIO, simply `/usr/include/libxml2` works, i.e.

```shell
gem install nokogiri -- --use-system-libraries --with-xml2-include=/usr/include/libxml2
```

which is coherent from OS X 10.9 (?) to 10.11.

**Comment by claicham** [comment]
@mkmckenzie thank you very much! Had been going round in circles for 30 mins 😥 

@flavorjones I used the guide on nokogiri, done so many different things but after xcode-select I ran into this:

make "DESTDIR=" install
make: /usr/local/bin/gmkdir: No such file or directory
make: *** [.RUBYARCHDIR.-.nokogiri.time] Error 1

I'm using rvm with ruby 2.2.5 on OSX 10.11.6 - coreutils sorted it.

**Comment by pmatsinopoulos** [comment]
Just my 2 cents here. I had problem installing nokogiri 1.6.8 on my OSX El Capitan 10.11.6. But after `xcode-select --install`, then installation didn't encounter any problem.

**Comment by zvozin** [comment]
On Mac OS Sierra:

`gem install nokogiri -- --with-xml2-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2 --use-system-libraries`

**Comment by franklinyu** [comment]
@zvozin I think `/usr/include/libxml2` would be more future-proof (see [my comment](https://github.com/sparklemotion/nokogiri/issues/1486#issuecomment-236394502).

**Comment by zvozin** [comment]
I'd think so, but it failed for me. 🎱

**Comment by franklinyu** [comment]
> I'd think so, but it failed for me.

That's weird; does the path `/usr/include/libxml2` exist on your system? If it does, where does it points to?

**Comment by zvozin** [comment]
`ls: /usr/include/libxml2: No such file or directory`

**Comment by franklinyu** [comment]
Wow, too bad Apple removed that path. No wonder why Nokogiri didn't find the library on your machine. I consider this a bug of macOS.

**Comment by sammcj** [comment]
Indeed after trying many different suggestions the following worked for me with the latest brew and OSX 11.12 and Xcode builds along with Ruby-2.3.3:

```
bundle config build.nokogiri --with-xml2-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2 --use-system-libraries
```

**Comment by kenguie** [comment]
@pmatsinopoulos had the right idea. At least for me, I had to install the xcode command line tools first.

**Comment by flavorjones** [comment]
Hi everyone who commented on this ticket after it was closed,

Do we need to update the installation instructions at http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x ? If so, I'd like to ask someone to send a PR to https://github.com/sparklemotion/nokogiri.org-tutorials

**Comment by franklinyu** [comment]
@flavorjones `xcode-select --install` is already in the documentation. As for the `--with-xml2-include`, I doubt that is needed when the section [Using Your System Libraries](http://www.nokogiri.org/tutorials/installing_nokogiri.html#using_your_system_libraries) is followed. I think we need more investigation about that.

For example @sammcj do you have Homebrew and `pkg-config` installed?

**Comment by tibbon** [comment]
Today I had to use the following to get around it:

`gem install nokogiri -- --with-xml2-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2 --use-system-libraries`

**Comment by franklinyu** [comment]
@tibbon So the same as @zvozin in https://github.com/sparklemotion/nokogiri/issues/1486#issuecomment-256947755?

**Comment by flavorjones** [comment]
As I asked in [my comment above](https://github.com/sparklemotion/nokogiri/issues/1486#issuecomment-284167524),

Do we need to update the installation instructions at http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x ? If so, I'd like to ask someone to send a PR to https://github.com/sparklemotion/nokogiri.org-tutorials

Otherwise, I expect I'll lock this thread.

**Comment by jskinne3** [comment]
After many unsuccessful attempts to get nokogiri to make use of Xcode files, I coaxed it to work with `sudo xcodebuild -license accept`, then installed again

**Comment by marcpopp** [comment]
Fixing for latest MacOS update:
`sudo gem install nokogiri -- --with-xml2-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2 --use-system-libraries`

**Comment by flavorjones** [comment]
OK, one final time. As I mentioned in [this comment](https://github.com/sparklemotion/nokogiri/issues/1486#issuecomment-284167524) and [this comment](https://github.com/sparklemotion/nokogiri/issues/1486#issuecomment-299666302), I need to know from Mac users whether we need to update the installation instructions.

PLEASE DO NOT UPDATE THIS TICKET WITH MORE ADVICE. INSTEAD, PROVIDE A PROPOSAL FOR HOW THE INSTALLATION TUTORIAL SHOULD BE CHANGED.

Sorry for shouting, but, you know, hey, read the thread, please.

**Comment by marcpopp** [comment]
@flavorjones: this issue is the first thing that shows up as first result, when you google the problem. Honestly I didn’t read the whole thread, but the last comments and I found a somewhat working solution that I could easily fix to work for me. 

Please feel free to use my last comment for your documentation. I’ll glady test it for you then. I think, after that you should post a link to the docu here and close the issue.

**Comment by franklinyu** [comment]
@marcpopp This issue has been closed for long. We are probably discussing to lock the reply. Or at least open another issue at the documentation repository.

Now that you have time testing, could you please check whether the steps in [*Install with system libraries*](http://www.nokogiri.org/tutorials/installing_nokogiri.html#install_with_system_libraries) works for you? It worked for me. If it also works for you, I will add that into the macOS part.

@flavorjones I think we can lock this conversation in 48 hours. This reads are already full of duplicated information.

**Comment by flavorjones** [comment]
@franklinyu Thanks.

**Comment by marcpopp** [comment]
@franklinyu Maybe I got that wrong, but the Documentation has no alternatives for MacOS and the FreeBDS does not work for me:
```
$ pkg-config 
Must specify package names on the command line


$ gem install nokogiri -- --use-system-libraries
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.


$ sudo gem install nokogiri -- --use-system-libraries
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.1/ext/nokogiri
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20171121-16908-z1zqig.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using system libraries.
pkg-config could not be used to find libxml-2.0
Please install either `pkg-config` or the pkg-config gem per

    gem install pkg-config -v "~> 1.1"

pkg-config could not be used to find libxslt
Please install either `pkg-config` or the pkg-config gem per

    gem install pkg-config -v "~> 1.1"

pkg-config could not be used to find libexslt
Please install either `pkg-config` or the pkg-config gem per

    gem install pkg-config -v "~> 1.1"

ERROR: cannot discover where libxml2 is located on your system. please make sure `pkg-config` is installed.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
	--with-libxml-2.0-config
	--without-libxml-2.0-config
	--with-pkg-config
	--without-pkg-config
	--with-xslt-dir
	--without-xslt-dir
	--with-xslt-include
	--without-xslt-include=${xslt-dir}/include
	--with-xslt-lib
	--without-xslt-lib=${xslt-dir}/lib
	--with-libxslt-config
	--without-libxslt-config
	--with-exslt-dir
	--without-exslt-dir
	--with-exslt-include
	--without-exslt-include=${exslt-dir}/include
	--with-exslt-lib
	--without-exslt-lib=${exslt-dir}/lib
	--with-libexslt-config
	--without-libexslt-config

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/nokogiri-1.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.1 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/nokogiri-1.8.1/gem_make.out

```

**Comment by franklinyu** [comment]
@marcpopp Thanks a lot!

 1. Could you please try

    ```shell
    pkg-config --cflags libxml-2.0
    pkg-config --cflags libxslt
    ```

    ?

 2. Is it the system Ruby, Homebrew Ruby or some Ruby in your user space?

**Comment by franklinyu** [comment]
@flavorjones please lock this thread. @marcpopp seems to have lost interest in this one. I would assume that he found the root cause of his issue, which was not related to Nokogiri, so he didn't consider it necessary to share with us.
