### ISSUE TITLE
Mix XML with filled and empty namespaces

### ISSUE THREAD

**Issue by majioa** [sparklemotion/nokogiri#1490]
I have an XML like:

    <ns2:doc>
       <field>
           ...
       </field>
    </ns2:doc>

How can I address it in a single line query? I tried:
  
    context.search("doc field")
    # => []
    context.search("ns2:doc field")
    # => exception
    context.xpath("//ns2:doc/:field")
    # => []
    context.css("doc field")
    # => []
    context.css("ns2:doc field")
    # => exception

Exactly I need to use xpath with relational search from top of node: `/field` or `field`, but `//field` searches always from root of document:

    context.xpath("//ns2:doc/:field")
    # => [field]

or I need to find with css but over namespace tags:

    context.css("ns2:doc field")
    # => [field]

**Comment by flavorjones** [comment]
Hello!

Thanks for asking this question! Your request for assistance using
Nokogiri will not go unanswered!

However, Nokogiri's Github Issues is reserved for reporting bugs or
submitting patches. If you ask your question on the mailing list, Team
Nokogiri promises someone will provide you with an answer in a timely
manner.

If you'd like to read up on Team Nokogiri's rationale for this policy,
please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.

**Comment by majioa** [comment]
@flavorjones it is not a question explicitly, it is a bug report.

**Comment by flavorjones** [comment]
I disagree, please email the list for support.
