### ISSUE TITLE
NodeSet.delete throw exception with its NodeSet.each

### ISSUE THREAD

**Issue by Daverkex** [sparklemotion/nokogiri#1491]
```ruby
doc = Nokogiri::HTML(open("http://www.threescompany.com/"))
extraction = doc.css('example')
extraction.each do |content|
    extraction.delete(content)
end
```
Throw this error:
`node must be a Nokogiri::XML::Node or Nokogiri::XML::Namespace (ArgumentError)`

**Comment by flavorjones** [comment]
Hi,

I can't reproduce what you're seeing using Nokogiri v1.6.8.1 and libxml2 2.9.4 on MRI.

If you'd like help, please open a new ticket explaining what you're trying to do, what version of nokogiri you're running, and the output from `nokogiri -v`.

Thank you!
