### ISSUE TITLE
Attribute names sometimes have namespace prepended under jruby

### ISSUE THREAD

**Issue by torcido** [sparklemotion/nokogiri#1492]
Sorry, I don't yet have a minimal test case (the setup that reveals this issue is quite large), but after some manipulation of the DOM, I'm seeing an element that looks like this:

```
#(Element:0x21da {
  name = "annotation-end",
  namespace = #(Namespace:0x20fa { prefix = "office", href = "urn:oasis:names:tc:opendocument:xmlns:office:1.0" }),
  attributes = [ #(Attr:0x21de { name = "office:name", value = "__Annotation__65_977956481" })]
  }),
```

This is a problem, because the namespace is now included as part of the name in the attribute, and my xpath expressions no longer find the element.

This only happens under jruby and only started happening with 1.6.8. Version 1.6.7.2 was fine (still different from MRI, but the namespace was kept separate from the attribute name).

In 1.6.7.2, the element looks like:

```
#(Element:0x20d0 {
  name = "annotation-end",
  namespace = #(Namespace:0x2066 { prefix = "office", href = "urn:oasis:names:tc:opendocument:xmlns:office:1.0" }),
  attributes = [
    #(Attr:0x20d4 {
      name = "name",
      namespace = #(Namespace:0x2066 { prefix = "office", href = "urn:oasis:names:tc:opendocument:xmlns:office:1.0" }),
      value = "__Annotation__65_977956481"
      })]
  }),
```

I find that when I first load the document the attributes look OK - it's only after some amount of processing (adding, unlinking and duplicating elements) that the issue occurs. I haven't yet been able to narrow it down to a minimal test case.

I suspect that this particular element was already unlinked, then added back into the DOM, probably using add_previous_sibling (though it may have been added from the parent using add_child).

I'll try to write a test case over the next few weeks, but I was hoping this information may be enough to spark a thought in someone reading this :)

**Comment by flavorjones** [comment]
Any luck getting a reproducible test case?

**Comment by flavorjones** [comment]
I'd like to close this issue, unless you can provide a reproducible test case.

**Comment by torcido** [comment]
Sorry - please feel free to close. We ended up switching to oga to do this manipulation in a way consistent between mri and jruby.
Thanks!
