### ISSUE TITLE
line numbers not working as expected

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1493]
(reported on nokogiri-talk by @justinthec)

I haven't had time to look into this, but wanted to capture it so that it wouldn't get forgotten.

---

> Hello,
> 
> Preface/libxml2
> 
> I've come across a bug that popped up once before in libxml2 back in 2008 where XML_TEXT_NODEs would always return 0 as their line number.
> 
> Link: https://mail.gnome.org/archives/xml/2008-July/msg00017.html
> 
> It was however patched that day and should have been fixed.
> 
> Commit: https://git.gnome.org/browse/libxml2/commit/?id=45efd0878aa56efa4291eec2ecdcff66d2f52fc3
> 
> Those three lines that he added still exist in the most current version of libxml2 now just under a conditional check for a (ctxt->linenumbers) flag.
> 
> Current Day libxml2: https://git.gnome.org/browse/libxml2/tree/SAX2.c?id=4472c3a5a5b516aaf59b89be602fbce52756c3e9#n1905
> 
> Nokogiri
> 
> This bug is currently present in Nokogiri 1.6.8.
> 
> I've been looking through the source in an attempt to find a fix and I'd appreciate some guidance:
> 
> Possibly relevant files:
> https://github.com/sparklemotion/nokogiri/blob/8e305e4e3d0ab697d1c6bc506398fb3007baf874/ext/nokogiri/xml_node.c#L1258
> https://github.com/sparklemotion/nokogiri/blob/027a151102083258f5e297c4fecfddca56904a2a/ext/nokogiri/xml_sax_parser_context.c#L171
> 
> Any ideas?
> 
> Thanks in advance,
> 
> Justin

**Comment by justinthec** [comment]
Thanks Mike, if you have any ideas but don't have time to try them out I'd be happy to take it on.

The farthest I've gotten so far is `xmlGetLineNo()` being called, but the source for that function is nowhere to be found, most likely in the compiled source of whichever version of libxml you guys are using.

**Comment by Xliff** [comment]
Is anyone still interested in this?

If so, it looks like xmlGetLineNo just returns the results of xmlGetLineNoInternal, which you can find, here:
**https://github.com/GNOME/libxml2/blob/master/tree.c#L4593**

**Comment by flavorjones** [comment]
This will be fixed in v1.13.
