### ISSUE TITLE
Build and compile libxml2 2.7.8 with xslt manually for Ubuntu 16.04 and Nokogiri 1.5.x

### ISSUE THREAD

**Issue by emilkarl** [sparklemotion/nokogiri#1494]
I have an old app running ruby 1.9.3 and are dependent on gems depending on Nokogiri 1.5.11. There are compability issues on Nokogiri 1.5.x and libxml 2.9.x, as pointed out here #829. After moving to a new server (Ubuntu 16.04 LTS) this has no older version of libxml available other than 2.9.x. It seems that a downgrade of libxml is the only option to make this work?

Has anyone done this and could guide me on what steps need to be taken.

Is it possible and worth a try?

**Comment by flavorjones** [comment]
I think your interpretation of #829 is incorrect. Have you tried building Nokogiri 1.5.11 against libxml 2.9.2 or later? If so, what did you discover?

**Comment by flavorjones** [comment]
Nokogiri 1.5.11 built against Ubuntu's libxml2 2.9.3+dfsg1-1ubuntu0.1 passes all tests except for two edge cases around DTD syntax errors.

You should be fine with that combination.
