### ISSUE TITLE
Please drop the pkg-config dependency from the precompiled gems

### ISSUE THREAD

**Issue by voxik** [sparklemotion/nokogiri#1496]
Not sure if that is possible, but there is no reason the precompiled versions of gem should depend on pkg-config. The java version does not depend on it, so hopefully this dependency can be avoided also for the other platforms.

**Comment by flavorjones** [comment]
There's another issue opened objecting to the license, and so we may remove
it entirely. Stay tuned.

**Comment by md5** [comment]
@voxik The other issue is #1488

**Comment by flavorjones** [comment]
Will be fixed in 1.6.8.1
