### ISSUE TITLE
Incorrect error reported when tag or tag-like used in textarea

### ISSUE THREAD

**Issue by ppannuto** [sparklemotion/nokogiri#1499]
If I read the [specification for textarea](https://www.w3.org/TR/html-markup/textarea.html) correctly, then textareas are defined to contain [replaceable character data](https://www.w3.org/TR/html-markup/syntax.html#replaceable-character-data), which should not be parsed as tags.

Given the following example

```html
<!DOCTYPE html>
<html>
  <head><title>Test</title></head>
  <body>
    <textarea id="source">
      Tags should not be parsed in textareas, thus something like

      ```c
      #include <stdio.h>
      printf("Hello World\n");
      ```

      Should not throw an error.
    </textarea>

  </body>
</html>
```

Nokogiri reports an invalid tag error:

```bash
$ nokogiri foo.html
Your document is stored in @doc...
irb(main):001:0> @doc.errors
=> [#<Nokogiri::XML::SyntaxError: Tag stdio.h invalid>]
```

when it should not.

Tested used Nokogiri version 1.6.8

**Comment by flavorjones** [comment]
I agree with your interpretation of the specification. Unfortunately, this behavior is not controlled by Nokogiri, but by the underlying HTML parser being used (nekohtml on JRuby, or libxml2 on MRI).

Are you running on JRuby or MRI? The best thing to do may be to submit a bug report upstream.

**Comment by flavorjones** [comment]
OK, I've reproduced what you're seeing using Nokogiri 1.6.8.1 on MRI.

Would you mind submitting this bug upstream?

**Comment by ppannuto** [comment]
Sure thing, I assume https://bugzilla.gnome.org/buglist.cgi?product=libxml2 is the right place?

Traveling currently, but will submit upstream in a day or two when I get back and will add a pointer here.

**Comment by flavorjones** [comment]
Yes, that's the right URL. I also generally like to follow up with an email to the mailing list at xml@gnome.org when I'm reporting upstream.

**Comment by ppannuto** [comment]
Upstreamed here: https://bugzilla.gnome.org/show_bug.cgi?id=774655

**Comment by flavorjones** [comment]
Thank you!
