### ISSUE TITLE
gem install nokogiri fails on OS X El Capitan: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by arielelkin** [sparklemotion/nokogiri#1508]
(Follow up from https://github.com/sparklemotion/nokogiri/issues/1504)

OS X v10.11.5 (15F34)
Xcode Version 7.3.1 (7D1014)
Ruby v2.3.1p112
Homebrew 0.9.9
RubyGems v2.5.1

```
$ sudo gem install nokogiri
Password:
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
```

Couldn't find an `mkmf.log` file:

```
$ find ~/ -name mkmf.log
$ 
```

**Comment by flavorjones** [comment]
Can you please show the output from `gem install -V nokogiri`?

**Comment by arielelkin** [comment]
fixed via https://github.com/rubygems/rubygems/issues/1668
