### ISSUE TITLE
Improve OS X installation instructions

### ISSUE THREAD

**Issue by arielelkin** [sparklemotion/nokogiri#1509]
Follow up from https://github.com/sparklemotion/nokogiri/issues/1504

Nokogiri installation instructions here: 
http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x

Should assume that you're on a fresh OS X installation. 

Suggestions:

* If Xcode and Xcode command line tools are not installed, then instruct downloading it from Mac App Store and then `$ xcode-select --install`
* if RVM is required, instruct to install it.
* Instructions should work for new OS X El Capitan (v10.11.x) installations (currently they're supported for up till OS X Yosemite (v10.10.x))

**Comment by fhwang** [comment]
Are you aware that the installation instructions are open-source and open to pull requests? https://github.com/sparklemotion/nokogiri.org-tutorials

I got a PR merged a while ago, and it was really fun! Well, not really fun. But maybe good for my karma.

**Comment by arielelkin** [comment]
Shouldn't this stay open till https://github.com/sparklemotion/nokogiri.org-tutorials/pull/48 is resolved?
