### ISSUE TITLE
Nokogiri crashes Rails Commands

### ISSUE THREAD

**Issue by SamuelNLerner** [sparklemotion/nokogiri#1513]
I've installed nokogiri 1.6.8 on El Capitan as a gem on my app. Every time I run a rails command, I get the following error:

`/Users/name/RubyWorkspace/app/vendor/bundle/gems/nokogiri-1.6.8/lib/nokogiri.rb:32:in `require': incompatible library version - /Users/name/RubyWorkspace/app/vendor/bundle/gems/nokogiri-1.6.8/lib/nokogiri/nokogiri.bundle (fatal)
`

I've tried uninstalling and installing with and without all combinations of system libraries, libxml2, libxslt, and libiconv at least 20 times. How do I get the libraries to actually sync?

**Comment by jrafanie** [comment]
Can you try the steps here and report what you tried and your results? http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x

**Comment by SamuelNLerner** [comment]
I get the same error message as before.

**Comment by eukalyptus88** [comment]
I am getting the same error in the same circumstances... any ideas yet?

**Comment by michaelhwan** [comment]
@jrafanie @SamuelNLerner @eukalyptus88 I followed steps 2 - 4 and it worked for me.

**Comment by YesThatAllen** [comment]
I can confirm the solution is to re-launch Xcode.

The question remains.. why isn't an error thrown when something hits this dependency wall.
