### ISSUE TITLE
Ubuntu 12.04 build error ./install command not found

### ISSUE THREAD

**Issue by arielstt** [sparklemotion/nokogiri#1522]
Hi,

I'm unable to build nokogiri in Ubuntu, I've the following error:

```
make "DESTDIR=" install
./install -m 0755 nokogiri.so ./.gem.20160802-15911-174e5df/nokogiri
make: ./install: Command not found
make: *** [install-so] Error 127
ERROR:  Error installing nokogiri:
    ERROR: Failed to build gem native extension.
```

I've found in a Google Group, someone that has the same problem, here's the link

[https://groups.google.com/forum/#!msg/nokogiri-talk/XfPPROD249c/RWa4NCjGBQAJ](https://groups.google.com/forum/#!msg/nokogiri-talk/XfPPROD249c/RWa4NCjGBQAJ)

I'm using rvm.

**Comment by flavorjones** [comment]
Hi,

Can you please provide the full command you're running, the full output from the run, along with the relevant log files?
