### ISSUE TITLE
html parsing removes everything after a chevron

### ISSUE THREAD

**Issue by jvenezia** [sparklemotion/nokogiri#1527]
In my local machine, it works as I expected: 
```
$ Nokogiri::HTML.fragment('some < text').to_s
=> "some &lt; text"
```

In another machine (heroku): 
```
$ Nokogiri::HTML.fragment('some < text').to_s
=> "some "
```

Do you have any idea ? This breaks the `sanitize` method of loofah and rails.

I'm using nokogiri 1.6.8

**Comment by flavorjones** [comment]
Likely this is due to differences in libxml2 version between your prod and dev environments. You can confirm this by looking at the output of `nokogiri -v` on each system.

**Comment by jvenezia** [comment]
Thanks @flavorjones .
So Heroku is using `libxml 2.9.1` which means that this version has an issue ?
I'm using `libxml 2.9.4` on my machine, and it seems to work.

**Comment by flavorjones** [comment]
To be clear, "some < text" is not valid markup, and so the underlying XML
engine is going to try to "fix it up", which is a critical part of the
value of loofah's sanitization process.

In this case, libxml 2.9.1 is choosing to clean up this fragment by
treating everything following the "<" as an incomplete tag and pruning it
from the DOM.

libxml 2.9.4 is doing a better job and recognizing that it's not an
incomplete tag, it's an improperly escaped entity.

you might be able to have nokogiri install libxml 2.9.4 on heroku by
setting appropriate environment variables, you'll have to check with heroku
support on details of how to do this within their buildpack.

**Comment by jvenezia** [comment]
Thanks for the details @flavorjones. I'm actually discussing this with Heroku teams.

**Comment by kevinbmccall14** [comment]
Hey @jvenezia, was Heroku able to provide a solution? I too need to upgrade heroku libxml to 2.9.4 as well because of parsing differences from 2.9.1 

Thanks @flavorjones

**Comment by lizdenhup** [comment]
I've had this same issue and upgrading my stack to Heroku-16 fixed the problem. (Heroku-16 comes bundled with libxml 2.9.3, and the behavior does not exist in that version to my knowledge).
