### ISSUE TITLE
Canonicalization doesn't works with no root tag in xml document

### ISSUE THREAD

**Issue by RafaelFerraro** [sparklemotion/nokogiri#1530]
I'm trying to canonicalize something like this:

`<foo></foo><baz></baz>`

But, Nokogiri#canonicalize returns only the foo portion: `<foo></foo>`

When I wrapped this with another tag, this works properly:

`<foo><baz></baz></foo>` 

So, I wonder if this is the right way the nokogiri does canonicalize, or if this is in fact a mistake.

**Comment by flavorjones** [comment]
XML with multiple root tags is an invalid document. Nokogiri makes it valid by dropping all but the first root tag.

If you have multiple roots, try parsing it as a fragment, not as a document.
