### ISSUE TITLE
nokogiri install failing

### ISSUE THREAD

**Issue by willvictor** [sparklemotion/nokogiri#1532]
It seems like somehow I don't have the right libraries. Here's the error messages. In previous threads, some people have said that running `xcode-select --install` works for them; however, when I run that command, I get: `xcode-select: error: command line tools are already installed, use "Software Update" to install updates` And I think I have the most updated version of x-code (Version 8.0). Any help with this?

`xmlIO.c:1450:52: error: use of undeclared identifier 'LZMA_OK'
    ret =  (__libxml2_xzclose((xzFile) context) == LZMA_OK ) ? 0 : -1;
                                                   ^
1 error generated.
make[2]: *** [xmlIO.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
`

**Comment by flavorjones** [comment]
Have you followed the instructions in the installation tutorial?

**Comment by flavorjones** [comment]
Closing.
