### ISSUE TITLE
Version 1.6.8.1 breaks semantic versioning

### ISSUE THREAD

**Issue by ianbamforth** [sparklemotion/nokogiri#1539]
Version 1.6.8.1 includes a commit that removes support for several Ruby versions.  This seems like it should be a Major version kind of thing - it has probably broken quite a lot of things.

**Comment by ianbamforth** [comment]
Specifically this commit:
https://github.com/sparklemotion/nokogiri/commit/84870381847cb83b6a530f5eef2460026ade49f6

**Comment by flavorjones** [comment]
You are mistaken, this commit has not yet been released:

```
git tag --contains 84870381847cb83b6a530f5eef2460026ade49f6
```
(no output)

I specifically branched from the tag `v1.6.8` to create branch `v1.6.8.x` which is where the tag `v1.6.8.1` lives.

**Comment by ianbamforth** [comment]
My mistake, sorry - misread the diff.
