### ISSUE TITLE
Gem Remotefetcher error

### ISSUE THREAD

**Issue by luke-hill** [sparklemotion/nokogiri#1546]
When I run the `bundle update` command on my current branch I get the following error.
```
Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read
server certificate B: certificate verify failed
(https://rubygems.org/gems/nokogiri-1.6.8.1-x86-mingw32.gem)
An error occurred while installing nokogiri (1.6.8.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8.1'` succeeds before bundling.
```

When I run the command in question I get the following issue
```
ERROR:  Could not find a valid gem 'nokogiri' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems
.org/specs.4.8.gz)
```

**Comment by larskanis** [comment]
The error message points at a SSL certificate verification failure between your local rubygems installation and https://rubygems.org . This is no nokogiri issue. You should try if other gems are affected similar.

To fix the certificate issue, you could check the trusted certificates in your local ruby installation. The `pem` files are usually stored in `C:/Ruby/lib/ruby/2.3.0/rubygems/ssl_certs/` by the Windows RubyInstaller. See also https://gist.github.com/luislavena/f064211759ee0f806c88

To work around of this issue you could disable ssl by use of http://rubygems.org .
