### ISSUE TITLE
Installation failure on Sierra

### ISSUE THREAD

**Issue by dret** [sparklemotion/nokogiri#1549]
## If you're having trouble installing Nokogiri ...

**Have you tried following [the installation tutorial][tutorial]?**

I am simply trying to get Jekyll up and running, which worked on a different Mac, but there I had installed things before upgrading to Sierra.

**What is the output of `gem install`?**

```
dretpro:website dret$ gem install nokogiri -v '1.6.8'
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: pkg-config-1.1.7.gem (100%)
Successfully installed pkg-config-1.1.7
Fetching: nokogiri-1.6.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.8
Parsing documentation for mini_portile2-2.1.0
Installing ri documentation for mini_portile2-2.1.0
Parsing documentation for pkg-config-1.1.7
Installing ri documentation for pkg-config-1.1.7
Parsing documentation for nokogiri-1.6.8
Installing ri documentation for nokogiri-1.6.8
Done installing documentation for mini_portile2, pkg-config, nokogiri after 2 seconds
3 gems installed
```

the problem is that doing `bundle install` then reports `Installing nokogiri 1.6.8 with native extensions`, and at the end i get this message:

```
Errno::EACCES: Permission denied -
/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/nokogiri-1.6.8/gem_make.out
An error occurred while installing nokogiri (1.6.8), and Bundler
cannot continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.
```
which is odd since i thought i did install nokogiri successfully. but apparently not.

**What are the contents of the `mkmf.log` file?**

where is this file located?

**What operating system are you using?**

macOS Sierra 10.12.1

```
dretpro:website dret$ uname -a
Darwin dretpro.home 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

**Comment by dret** [comment]
maybe one more data point: it looks confusing to me that there is a permission error about `/Library` (which i try to avoid using by using `rbenv`), but that some other commands look at a different location. is it possible that some config data is inconsistent?

```
Errno::EACCES: Permission denied -
/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/nokogiri-1.6.8.1/gem_make.out
An error occurred while installing nokogiri (1.6.8.1), and Bundler
cannot continue.
Make sure that `gem install nokogiri -v '1.6.8.1'` succeeds before bundling.
dretpro:website dret$ which ruby
/Users/dret/.rbenv/shims/ruby
dretpro:website dret$ which gem
/Users/dret/.rbenv/shims/gem
dretpro:website dret$ which gem nokogiri
/Users/dret/.rbenv/shims/gem
/Users/dret/.rbenv/shims/nokogiri
dretpro:website dret$
```

**Comment by flavorjones** [comment]
As I mentioned in the other issue you commented on, this is not a nokogiri problem, but a problem with file permissions on your machine.
