### ISSUE TITLE
SVG Parsing Error

### ISSUE THREAD

**Issue by jdguzman** [sparklemotion/nokogiri#1552]
We have an svg with a large base64 encoded image (attached) that is not parsing correctly.

```ruby
file = Nokogiri::XML(File.read('DM_V3-front.svg'))
file.remove_namespaces!

file.xpath('//image/@href').count             # => 0 (should be 1)
file.xpath('//image').count                   # => 1 (it is finding the image like this)
```

The problem is that when the svg is parsed it turns the href attribute into text outside of the image tag for some reason.  This only happens when the base64 data is quite large, smaller base64 encoded images work fine as far as we can tell.

The sample file below illustrates the issue and has only one image to facilitate reproducing this.  I would be happy to look into this issue further if someone could point me in the right direction.

[DM_V3-front.svg.zip](https://github.com/sparklemotion/nokogiri/files/564557/DM_V3-front.svg.zip)

**Comment by larskanis** [comment]
libxml and therefore nokogiri have some hardcoded limits about the maximum sizes of elements. You can disable them by:
```ruby
file = Nokogiri::XML(File.read('DM_V3-front.svg'), nil, nil, Nokogiri::XML::ParseOptions::HUGE)
```
This should solve your issue.

**Comment by jdguzman** [comment]
Out of curiosity is this documented somewhere that I missed. I don't recall seeing anything about that option but I may have just missed it in the docs. In all honestly I probably should have dug into the source a bit.

**Comment by flavorjones** [comment]
It's an implementation detail of libxml2, so although the parse options are documented, this particular option is not mentioned in the tutorials.
