### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by gomme9396** [sparklemotion/nokogiri#1557]
When i try to install nokogiri, this error occur and remain this messages..

What can i do to solve this error?

------------------------------------------

ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8.1/ext/nokogiri
/Users/seojonghyeon/.rbenv/versions/2.3.1/bin/ruby -r ./siteconf20161108-21048-24v7fv.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/seojonghyeon/.rbenv/versions/2.3.1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
	from /Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/mkmf.rb:522:in `with_werror'
	from /Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:139:in `nokogiri_try_compile'
	from extconf.rb:163:in `block in add_cflags'
	from /Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/mkmf.rb:629:in `with_cflags'
	from extconf.rb:162:in `add_cflags'
	from extconf.rb:415:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/nokogiri-1.6.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8.1 for inspection.
Results logged to /Users/seojonghyeon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/nokogiri-1.6.8.1/gem_make.out

**Comment by flavorjones** [comment]
When you can created this issue, there was an issue template in the text box that you ignored and deleted, but which would have helped you either diagnose the issue yourself or else prompted you for enough information that someone could help you.

Closing. If you open a new issue, please follow the template instructions.
