### ISSUE TITLE
Fails to compile of FreeBSD11

### ISSUE THREAD

**Issue by Alvaroisit** [sparklemotion/nokogiri#1559]
/usr/local/lib/ruby/site_ruby/2.2/rubygems/dependency.rb:308:in `to_specs': Could not find 'pkg-config' (~> 1.1.7) among 36 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.2:/usr/local/lib/ruby/gems/2.2', execute `gem env` for more information
	from /usr/local/lib/ruby/site_ruby/2.2/rubygems/dependency.rb:320:in `to_spec'
	from /usr/local/lib/ruby/site_ruby/2.2/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from extconf.rb:112:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/ports/basejail/usr/ports/textproc/rubygem-nokogiri/work/stage/usr/local/lib/ruby/gems/2.2/gems/nokogiri-1.6.8 for inspection.
Results logged to /var/ports/basejail/usr/ports/textproc/rubygem-nokogiri/work/stage/usr/local/lib/ruby/gems/2.2/extensions/amd64-freebsd-11/2.2/nokogiri-1.6.8/gem_make.out
*** Error code 1

Stop.
make: stopped in /basejail/usr/ports/textproc/rubygem-nokogiri

===>>> make stage failed for textproc/rubygem-nokogiri
===>>> Aborting update

===>>> You can restart from the point of failure with this command line:
       portmaster <flags> textproc/rubygem-nokogiri devel/rubygem-pkg-config

**Comment by flavorjones** [comment]
This is not a nokogiri compilation error, this is a rubygems dependency error.

Not sure how you're installing Nokogiri, but if you use Bundler this won't happen. If you're manually installing gems, install the missing gem.

Or, upgrade to 1.6.8.1 which removes this dependency.
