### ISSUE TITLE
Fixnum is deprecated warning under Ruby 2.4.0 and Nokogiri 1.6.8.1

### ISSUE THREAD

**Issue by memoht** [sparklemotion/nokogiri#1564]
Upgraded to Ruby 2.4.0 last night and upon launching app in development was greeted with the following in the console: `nokogiri-1.6.8.1/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated`

Thought this was solved in #1545 but seeing a red`x` in the commit history for this merge, so guessing something still isn't resolved.

**Using:** macOS Sierra 10.12.2
**App is using:** Rails 5.0.1
```
| => nokogiri -v
# Nokogiri (1.6.8.1)
    ---
    warnings: []
    nokogiri: 1.6.8.1
    ruby:
      version: 2.4.0
      platform: x86_64-darwin16
      description: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/memoht/Sites/ppipub/.gem/ruby/2.4.0/gems/nokogiri-1.6.8.1/ports/x86_64-apple-darwin16.3.0/libxml2/2.9.4"
      libxslt_path: "/Users/memoht/Sites/ppipub/.gem/ruby/2.4.0/gems/nokogiri-1.6.8.1/ports/x86_64-apple-darwin16.3.0/libxslt/1.1.29"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.4
      loaded: 2.9.4
```

**Comment by larskanis** [comment]
This is already fixed on the git master branch and will be part of the next release. The red X is only about a failed test, but the PR #1545 is merged nevertheless.
