### ISSUE TITLE
release a version that avoids Ruby 2.4.0 deprecation warnings

### ISSUE THREAD

**Issue by matthewrudy** [sparklemotion/nokogiri#1565]
With Ruby 2.4.0 released yesterday, it'd be great to have a release of Nokogiri that avoids deprecation warnings.

The fix was added a while ago.
https://github.com/sparklemotion/nokogiri/pull/1545

And primed ready for a 1.7.0 release
https://github.com/sparklemotion/nokogiri/commit/7f8b7b2bf55829e02cd11c2eb25814c3ed458676

Warnings look like:

<img width="841" alt="screenshot 2016-12-26 23 53 00" src="https://cloud.githubusercontent.com/assets/8659/21487653/7cdfefa2-cbc6-11e6-9882-7c4ec0228b04.png">

**Comment by matthewrudy** [comment]
@flavorjones thanks for the quick response, and appropriate title change.

**Comment by flavorjones** [comment]
@matthewrudy No sweat, running valgrind now, will cut a release tonight unless I hit a blocker.

**Comment by flavorjones** [comment]
1.7.0 has shipped.
