### ISSUE TITLE
1.7.0 in OpenBSD doesn't install

### ISSUE THREAD

**Issue by vtamara** [sparklemotion/nokogiri#1569]
## If you're having trouble installing Nokogiri ...

**Have you tried following [the installation tutorial][tutorial]?**
Yes

**What is the output of `gem install`?**
Although I already installed GCC from ports as tutorial suggests it complains with:

Please install gcc 4.9+ from ports using `pkg_add -v gcc`

**What are the contents of the `mkmf.log` file?**
find_executable: checking for egcc... -------------------- yes

--------------------

**What operating system are you using?**
OpenBSD

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by larskanis** [comment]
Can you please post the full output of `gem install` and the mkmf.log ?

**Comment by vtamara** [comment]
Full output of ```$ doas gem install nokogiri ```:

<pre>
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.4/gems/nokogiri-1.7.0/ext/nokogiri
/usr/local/bin/ruby24 -r ./siteconf20161229-10357-1yvoleq.rb extconf.rb
checking for egcc... yes
Please install gcc 4.9+ from ports using `pkg_add -v gcc`
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)24
        --help
        --clean

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.4/extensions/x86_64-openbsd/2.4/nokogiri-1.7.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.4/gems/nokogiri-1.7.0 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.4/extensions/x86_64-openbsd/2.4/nokogiri-1.7.0/gem_make.out
</pre>

Full output of ```/usr/local/lib/ruby/gems/2.4/extensions/x86_64-openbsd/2.4/nokogiri-1.7.0/mkmf.log```:

<pre>
find_executable: checking for egcc... -------------------- yes

--------------------
</pre>

**Comment by vtamara** [comment]
I just sent pull request that possibly fixes. https://github.com/sparklemotion/nokogiri/pull/1570

**Comment by vtamara** [comment]
Anyway while you apply, I'm staying in 1.6.8.1 that works fine

**Comment by larskanis** [comment]
Fixed typo on master branch.
