### ISSUE TITLE
Why is the blank namespace been removed after XML parse

### ISSUE THREAD

**Issue by SonlyF5020** [sparklemotion/nokogiri#1584]
**What problems are you experiencing?**
We got a production issue due to there is an empty namespace inside one of the XML tags. But according to the log, seems we can not found the issue part.

As an example, if we run 
`Nokogiri.XML("<a xmlns:v1=\"\">test</a>").to_s`

then we got 
`"<?xml version=\"1.0\"?>\n<a>test</a>\n"`

but we can found that the important `xmlns:v1=\"\"` part is missing !

Our current code base is using Nokogiri to format the soap request xml and then put them in the log. but somehow this kind of blank namespaces is missing .

I am thinking we need either an option to ensure it's not missed after the parse or we need to at lease provide another warning message or log to let us known there are some information been removed after the parse.

**What's the output from `nokogiri -v`?**
1.7.0.1 

**Can you provide a self-contained script that reproduces what you're seeing?**
`Nokogiri.XML("<a xmlns:v1=\"\">test</a>").to_s`

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by flavorjones** [comment]
@SonlyF5020 Can you please provide the full output from `nokogiri -v` as requested? It's important to know whether you're running libxml2 or xerces, and what version.

**Comment by flavorjones** [comment]
The XML spec says that blank namespace declarations on a node are intended to be used to "bring an element into the global namespace", which is the behavior you're seeing. "This has the same effect, within the scope of the declaration, of there being no default namespace."

Some resources for you to check out:

* https://stackoverflow.com/questions/1587891/is-xmlns-a-valid-xml-namespace
* https://www.w3.org/TR/xml-names/#defaulting
