### ISSUE TITLE
Unable to install nokogiri using Ruby 1.9.3

### ISSUE THREAD

**Issue by ana3ela** [sparklemotion/nokogiri#1587]
I'm using ruby 1.9.3 on my app and I'm unable to run bundle because nokogiri requires a Ruby version >= 2.1.0. I've already tried the following command line with no success.

gem install nokogiri -- --use-system-libraries=true --with-xml2-include=/usr/include/libxml2 
ERROR:  Error installing nokogiri:
	nokogiri requires Ruby version >= 2.1.0.

PS: At the moment I cannot upgrade my ruby version and I really need to install nokogiri otherwise my app won't run.

**Comment by larskanis** [comment]
You can force a Ruby-1.9.3 compatible nokogiri version by setting
```ruby
gem "nokogiri", "<1.7.0"
```
in your Gemfile. But note, that Ruby versions below 2.1 are [no longer maintained](https://www.ruby-lang.org/en/downloads/) and no longer supported by nokogiri.

**Comment by flavorjones** [comment]
It's probably worth noting here that Ruby 1.9.3 reached end-of-life on 2015-02-23, nearly two years ago.
