### ISSUE TITLE
resurrect the GC / memory pressure test suite

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1603]
The file `test/test_memory_leak.rb` and the teardown behavior controlled by the `NOKOGIRI_GC` env var could be useful.

Consider resurrecting these.

Acceptance criteria:

* suite needs to finish in a reasonable amount of time (currently many are looping literally forever)
* suite needs to be runnable under valgrind (so, not a separate rake task, but possibly controlled by an environment variable for use with the `test:valgrind` task from `hoe-debugging`)
* tests must clearly pass or fail. previously I'd just run a single test and watch the process heap size to see if it increased. It would be great to run under valgrind and use those metrics for something.
* suite should be run in the main concourse pipeline

**Comment by rubarb666** [comment]
[[

**Comment by flavorjones** [comment]
After a little bit of work in #2658 I'm forming some more concrete opinions on this.

I think we could make this a runnable suite if we use:

- the value returned from `MemInfo.rss` (introduced in af99c52)
- and Minitest::BenchSpec (introduced in 46dcc60)

to ensure that memory usage isn't increasing after some number of iterations.

**Comment by flavorjones** [comment]
ZOMG see #3050
