### ISSUE TITLE
Memleak Issue with sample program using Nokogiri

### ISSUE THREAD

**Issue by rahulroot** [sparklemotion/nokogiri#1609]
Hello,

I am facing a memleak on this sample program of adding/removing nodes using nokogiri.
I have put my code at https://gist.github.com/rahulroot/dca9a06a73d9b29f7a329ae0e72001a4, 
I am using Jmeter to fire the attached xml over a 100 tps. Memory grows from 14m to 3.7g in 12 hours...

First I thought there might be issue with EM, then I removed parsing logic and just bypassing request to response...and memory remains constant for that time duration....

This is my nokogiri..
nokogiri -v
# Nokogiri (1.7.0.1)
    ---
    warnings: []
    nokogiri: 1.7.0.1
    ruby:
      version: 2.3.1
      platform: x86_64-linux
      description: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/tmp/tmp.2ySTDWyTqM/vendor/ruby/2.3.0/gems/nokogiri-1.7.0.1/ports/x86_64-pc-linux-gnu/libxml2/2.9.4"
      libxslt_path: "/tmp/tmp.2ySTDWyTqM/vendor/ruby/2.3.0/gems/nokogiri-1.7.0.1/ports/x86_64-pc-linux-gnu/libxslt/1.1.29"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.4
      loaded: 2.9.4

It is SLES 11 sp3 VM box.

Please look.

Br,
Rahul

**Comment by flavorjones** [comment]
Thanks for reporting! I'll take a look.

**Comment by flavorjones** [comment]
I'm spending some time to try to reproduce this, and I don't understand some things about the code in your gist. On line 52 of your gist, this code:

```
         node =  Nokogiri::XML::Node.new(node_name, @document)
```

is suspicious. Where is `@document` being set? Unless there's some EM magic going on, it looks like that value should be `nil`, and an exception should be getting raised. Am I missing something? Are you checking what the responses look like from your server? Do they match what you want to see? Help me understand what you're trying to do.

**Comment by rahulroot** [comment]
Hello Mike,

My apologies, it was cut/paste. I updated, I removed the instance @document
and replace it with document.
It is updated now.

Br,
Rahul Gupta.

**Comment by rahulroot** [comment]
Hello Mike,

I send attached xml into this program, i receive it as @http_post_content in request_handler, I use the same request as response and I parse this response in response_handler, I removed some nodes with(//pdpContext) and add some nodes with my name(rahul).

Please let me know if you have any problem in running this.

Br,
Rahul.

**Comment by rahulroot** [comment]
I have updated the code also with exception handling on namespace prefix.

Br,
Rahul.

**Comment by rahulroot** [comment]
Hello Mike,

I found the Issue in posted code, it was line number 36, if root.search throws an exception it will leak the memory....I put it under rescue and exit...I see no memleak now....

I guess next issue 1610 is valid now...

Thanks,
Rahul.
