### ISSUE TITLE
Node search method vs customized functtion

### ISSUE THREAD

**Issue by rahulroot** [sparklemotion/nokogiri#1614]
Hello,

I am trying to write a customized function to search for an attribute in node, instead of using search method, could you please check if it is correct.

This is my XML node.

 <pdpContext>
            <id>30</id>
            <type>4</type>
            <qosProfile>service</qosProfile>
            <apn>service</apn>
            <apnArea>HPLMN</apnArea>
            <extType>5</extType>
 </pdpContext>

And My XML can have hundred's of these XML node.

This is how I was using for finding other attributes also..
node is above node having above attributes..
if node.search('type').first
   return node
end

This is my customized search...
def find_first node, attr_to_add
    node.children.each do | n |
      if n.element?()
          return true if n.name == attr_to_add
      end
    end
    false
end

Is this correct approach...Why I am doing this, because search method is reducing the Performance of my application....

BR,
Rahul

Nokogiri I am using...
# Nokogiri (1.7.0.1)
    ---
    warnings: []
    nokogiri: 1.7.0.1
    ruby:
      version: 2.3.1
      platform: x86_64-linux
      description: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.7.0.1/ports/x86_64-pc-linux-gnu/libxml2/2.9.4"
      libxslt_path: "/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.7.0.1/ports/x86_64-pc-linux-gnu/libxslt/1.1.29"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.4
      loaded: 2.9.4

**Comment by flavorjones** [comment]
Hello!

Thanks for asking this question! Your request for assistance using Nokogiri will not go unanswered!

However, Nokogiri's Github Issues is reserved for reporting bugs or submitting patches. If you ask your question on the mailing list, Team Nokogiri promises someone will provide you with an answer in a timely manner.

If you'd like to read up on Team Nokogiri's rationale for this policy, please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.
