### ISSUE TITLE
Default to NOKOGIRI_USE_SYSTEM_LIBRARIES=true

### ISSUE THREAD

**Issue by fulldecent** [sparklemotion/nokogiri#1619]
Lots of Ruby scripts and other software depends on Nokogiri. And all of those end-user programs will make a [note like this](https://github.com/gjtorikian/html-proofer).

 > NOTE: When installation speed matters, set NOKOGIRI_USE_SYSTEM_LIBRARIES to true in your environment. This is useful for increasing the speed of your Continuous Integration builds.

Please make `NOKOGIRI_USE_SYSTEM_LIBRARIES` default to true. Or instead attempt to use system libraries if they exist but then fall back to whatever the opposite of using system libraries is.

**Comment by flavorjones** [comment]
Hi,

Thanks for suggesting this. The core contributors have obviously discussed it in the past, and in fact I formally proposed this change to nokogiri-talk almost exactly a year ago:

> https://groups.google.com/d/msg/nokogiri-talk/WdYThAT0jIo/P8_QVxdXAwAJ

and at the time **nobody bothered to respond**.

If you feel strongly about this topic, I'd ask you to join nokogiri-talk and participate in the community decision-making by responding to that thread. It's complex enough that we should take the time to try to build consensus around this decision before just ripping the metaphorical band-aid off.

Make sense?

**Comment by fulldecent** [comment]
Thank you for the explanation and your prior dedication to this issue. I see #1619 is a duplicate of #1220. I will close now and discuss there.
