### ISSUE TITLE
Frozen string literal regression

### ISSUE THREAD

**Issue by MOZGIII** [sparklemotion/nokogiri#1623]
From the commits history I've seen there was some work done to make `nokogiri` compatible with `--enable-frozen-string-literal`.

However, this fails for me on ruby `2.3.3` on `ubuntu xenial`:
```shell
$ export RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
$ gem install nokogiri -v '1.7.1'                                                                                                                                       
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/mnovichkin/.rvm/gems/ruby-2.3.3/gems/nokogiri-1.7.1/ext/nokogiri
/home/mnovichkin/.rvm/rubies/ruby-2.3.3/bin/ruby -r ./siteconf20170323-28235-1jnrn5d.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/mnovichkin/.rvm/rubies/ruby-2.3.3/bin/$(RUBY_BASE_NAME)
	--help
	--clean
extconf.rb:422:in `<main>': can't modify frozen String, created at extconf.rb:161 (RuntimeError)
yes

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/mnovichkin/.rvm/gems/ruby-2.3.3/extensions/x86_64-linux/2.3.0/nokogiri-1.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/mnovichkin/.rvm/gems/ruby-2.3.3/gems/nokogiri-1.7.1 for inspection.
Results logged to /home/mnovichkin/.rvm/gems/ruby-2.3.3/extensions/x86_64-linux/2.3.0/nokogiri-1.7.1/gem_make.out

```
As you can see: `extconf.rb:422:in `<main>': can't modify frozen String, created at extconf.rb:161 (RuntimeError)`.

Seems `extconf.rb` used to be  `--enable-frozen-string-literal` compatible (hence https://github.com/sparklemotion/nokogiri/commit/53f9b66ee60342a639ff1c1e60b75558ea3be4ac). But now it isn't, so I deduce it's a regression.

I propose adding frozen string literal comment to every existing file in the project, and settling up the rule to have one in each new ruby file.

So, I've made a PR #1622. It's just all the comments added, but nothing else changed. Seems like it would break stuff. I won't be doing anything more in there, so it's more like a starting point to start with.
I guess only core nokogiri maintainers can solve this regression once and for all. Please, do something.

**Comment by larskanis** [comment]
This is a bug in ruby-2.3. Several libraries delivered with ruby-2.3.x are broken in regards to frozen string literals. You must upgrade to ruby-2.4 in order to use this feature.

Nokogiri is [already fully compatible](53f9b66ee60342a639ff1c1e60b75558ea3be4ac) to frozen string literals and we're running all tests on ruby-2.4 with frozen string literals [enabled](2fae671984a1fe60ff36871ddc0215b397a3979e). There is no need to add comment lines to each and every file.
