### ISSUE TITLE
error when parse and define options

### ISSUE THREAD

**Issue by ccarruitero** [sparklemotion/nokogiri#1625]
When parse a string and define [parseOptions](http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/ParseOptions), nokogiri returns an error. Using a block for define the options works fine.
```
2.3.1 :001 > require 'nokogiri'
 => true 
2.3.1 :002 > Nokogiri.XML('<content>Chapter 1</content>', options: Nokogiri::XML::ParseOptions.new.noblanks)
TypeError: no implicit conversion of Hash into String
	from /home/zeka/.rvm/gems/ruby-2.3.1@nokogiri/gems/nokogiri-1.7.1/lib/nokogiri/xml/document.rb:61:in `read_memory'
	from /home/zeka/.rvm/gems/ruby-2.3.1@nokogiri/gems/nokogiri-1.7.1/lib/nokogiri/xml/document.rb:61:in `parse'
	from /home/zeka/.rvm/gems/ruby-2.3.1@nokogiri/gems/nokogiri-1.7.1/lib/nokogiri/xml.rb:34:in `XML'
	from (irb):2
	from /home/zeka/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :003 > Nokogiri.XML('<content>Chapter 1</content>') {|config| config.noblanks}
 => #<Nokogiri::XML::Document:0xe9b7a4 name="document" children=[#<Nokogiri::XML::Element:0xe9b3d0 name="content" children=[#<Nokogiri::XML::Text:0xe9b1f0 "Chapter 1">]>]> 
```

I tested in ruby 2.3 and 2.1 with the same result

**Comment by flavorjones** [comment]
Thanks for asking this question.

Unfortunately, you're trying to use this API in a way that it doesn't support. You can't use named parameters when calling this method. Instead try

```
Nokogiri.XML('<content>Chapter 1</content>', nil, nil, Nokogiri::XML::ParseOptions.new.noblanks)
```

You can read the [documentation](http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri#XML-class_method) or the [tutorial](http://www.nokogiri.org/tutorials/parsing_an_html_xml_document.html#from_a_string) for more information.

Obviously, once we ship the release in which we officially stop supporting Ruby 1.9 syntax, we can invest in supporting named parameters.
