### ISSUE TITLE
Failed to install nokogiri with native extensions...

### ISSUE THREAD

**Issue by iamclaytonray** [sparklemotion/nokogiri#1626]
## Have you tried following [the installation tutorial][tutorial]?
Yes.

## What is the output of `gem install`?
<img width="1366" alt="screen shot 2017-03-25 at 4 35 21 pm" src="https://cloud.githubusercontent.com/assets/16495816/24325899/31331e0a-1179-11e7-9357-9139bf5de804.png">
<img width="1440" alt="screen shot 2017-03-25 at 4 35 41 pm" src="https://cloud.githubusercontent.com/assets/16495816/24325898/3131bbaa-1179-11e7-940d-ce8c990b1903.png">
<img width="1440" alt="screen shot 2017-03-25 at 4 35 46 pm" src="https://cloud.githubusercontent.com/assets/16495816/24325897/312cbe84-1179-11e7-9d13-546bd6fd6a4e.png">

## What are the contents of the `mkmf.log` file?
Check out this <a href="https://gist.github.com/iamclaytonray/ce4c23e1e428b095de203e9db01c8553">gist</a>.

## What operating system are you using?
Mac OS Sierra - 10.12.3

## What problems are you experiencing?
Nokogiri is failing to install native extensions in my rails projects.

## What's the output from `nokogiri -v`?
The output can be found at this <a href="https://gist.github.com/iamclaytonray/42c29fb44659aed48f01669c20e0fd14">gist</a>.

## Can you provide a self-contained script that reproduces what you're seeing?
I simply ran `rails new project -d postgresql` on both Ruby 2.3.3 and 2.4.0 with Rails 5.0.2. Both outputs were the exact same for the different Ruby versions.

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html

# EDIT
I am able to create a new rails application, `cd` into it, and run `bundle` to with success. But that's not the ideal situation. Also, it's hit or miss. That method only worked once and I've tried about 4 other times, both in 2.3.3 and 2.4.0. The version it did work in was 2.3.3 but there were 2 other cases where that method did not work. Just wanted to throw that out there.

**Comment by giedriusr** [comment]
Same here.

**Comment by StephenEsser** [comment]
I am also seeing a similar error when attempting to bundle 1.7.1

**Comment by flavorjones** [comment]
@iamclaytonray Thanks for opening this issue, hopefully we can get you up and running.

In your original description, you indicated you had followed the installation tutorial. The error message you've posted (btw, we prefer text and not screenshots, for future reference) indicates that the issue may be the one covered in the tutorial's "Troubleshooting MSX Installation" section, entitled, "Error Message About Undeclared Identifier LZMA_OK".

Can you please double-check that the advice in that tutorial does **not** fix your symptoms?

**Comment by kevin-jj** [comment]
@flavorjones   same issue after upgrade to MacOS  10.12.4

**Comment by kevin-jj** [comment]
brew install libxml2

bundle config build.nokogiri --use-system-libraries \
>   --with-xml2-include=$(brew --prefix libxml2)/include/libxml2

bundle install

**Comment by flavorjones** [comment]
I'm going to close this ticket in two days, unless I hear back from the OP that the tutorial does not cover this case.

**Comment by flavorjones** [comment]
Closing, as I'm confident the tutorial addresses this case.
