### ISSUE TITLE
Not able to parse facebook group

### ISSUE THREAD

**Issue by waaadim** [sparklemotion/nokogiri#1630]
I have tried both css and xpath, guess I'm just doing something wrong, or maybe the selectors are supposed to work different:

Here's what I'm doing:
```
dom = Nokogiri::HTML(File.read('/tmp/fb-test-1.html'))

# output 1
dom.xpath("//div[@id='contentArea']").size

# output 0
dom.xpath("//div[@id='contentArea']//div[@class='_4-u2 mbm _4mrt _5jmm _5pat _5v3q _4-u8']").size

# same with
dom.css("#contentArea").size
dom.css("#contentArea ._5jmm._4-u2").size
```

and the file:
[fb-test-1.html.zip](https://github.com/sparklemotion/nokogiri/files/895230/fb-test-1.html.zip)

**Comment by flavorjones** [comment]
Hi,

Thanks for asking this question. You haven't, unfortunately provided enough information for someone to quickly help you. You should have specified what result you're looking for.

That said, I opened the file, and I believe the structure of the document is not what you think it is. All occurrences of the class `_5jmm` are present in comments, and not as elements in the DOM.

I recommend you use [SelectorGadget](http://selectorgadget.com/) to discover what in the DOM you're trying to find.

**Comment by waaadim** [comment]
thanks, I got it working with your inspector, but I still don't understand why the previous search-query doesn't work. I use a chrome extension for css  [Live CSS Editor](https://chrome.google.com/webstore/detail/live-css-editor/oelggcmknbjmhkpgjfhakedcfnkgbdpg)
and I was able to apply styles with it just fine, but couldn't get the elements with nokogiri

> All occurrences of the class `_5jmm` are present in comments, and not as elements in the DOM.
do you mean that all the `_5jmm`'s are commented out ? if you do then that's not the case here

I'm clearly missing something, this would make sense if there were a div somewhere above in the DOM with the same id, but this is not the case here

Is there a way to make a sandbox project with ruby & gems like people do with js ?

**Comment by flavorjones** [comment]
> do you mean that all the _5jmm's are commented out?

Yes. When I pull up the html file you attached to the original post, all occurrences of the string `_5jmm` are in an HTML comment.

I strongly encourage you to continue this conversation on nokogiri-talk, you can find details at http://bit.ly/nokohelp.

**Comment by flavorjones** [comment]
for example:

![image](https://cloud.githubusercontent.com/assets/8207/24820520/7c0086be-1bb7-11e7-8fcc-dcbb179c75f2.png)
