### ISSUE TITLE
mutant compatibility

### ISSUE THREAD

**Issue by betesh** [sparklemotion/nokogiri#1635]
The mutant gem depends on all classes defining a singleton_method called `name` that returns a String or nil.  XPath and XPath::HTML don't follow that convention.

It would be helpful if nokogiri could fix this on their end so that mutant could be used on projects that depend on nokogiri.

See https://github.com/mbj/mutant/issues/338 for more details

I am using nokogiri 1.7.1 (indirectly--I wouldn't need it at all except that it is a dependency of rails)

**Comment by flavorjones** [comment]
Hi @betesh,

I'm sorry, but I don't what `mutant` is, nor why it expects this, nor what it expects this method to return for these objects. Some people have told me I'm pretty ignorant, but this seems to me like a silly thing for a gem to expect of the universe.

**Comment by flavorjones** [comment]
To be clear, your request doesn't make sense to me:

```
$ ruby -rnokogiri -e "puts Nokogiri::XML::XPath.name"
Nokogiri::XML::XPath

$ ruby -rnokogiri -e "puts Nokogiri::XML::XPath::HTML"
-e:1:in `<main>': uninitialized constant Nokogiri::XML::XPath::HTML (NameError)
```

In the first case, I think we're doing what you want; in the second, you're referencing a nonexistent class.

Perhaps if you submitted code so that we could reproduce what you're seeing, I could be of more help.

**Comment by mbj** [comment]
Mutant simply expects `Class#name` contract not to be broken. This is reasonable expectation mutant has on any Ruby class / module. Any ruby out there could should reasonably expect to be able to call `#name` on a `Class/Module` instance and get back a `String` instance or `nil`. In your case it raises an exception.

I'd even argue that the `String` instance should be resolvable to a constant, but its definitively not expected to raise an exception.

**Comment by backus** [comment]
There have been similar one off requests for other gems. For example in bundler: https://github.com/bundler/bundler/issues/5292

**Comment by mbj** [comment]
Also the NR agent gem was recently fixed. I do not recall the issue reference.

**Comment by backus** [comment]
Oh great. They don't let you open github issues so I had to make a forum post: https://discuss.newrelic.com/t/fix-class-name-convention-violations-in-ruby-library/38060

**Comment by flavorjones** [comment]
Once more, I want to ask someone to help me reproduce the issue, as I mentioned above the classes called out by the OP a) exist and behave as expected, and b) do not exist.

Help me help you, and I'll reopen.

**Comment by backus** [comment]
I only responded because I saw the corresponding mutant issue and wanted to help out. As far as I can tell on further investigation though, I think the OP meant to open this issue for the [`XPath`](https://github.com/jnicklas/xpath) gem that does violate this convention.
