### ISSUE TITLE
Failed to install on Windows RubyInstaller 2.4.1

### ISSUE THREAD

**Issue by Sega100500** [sparklemotion/nokogiri#1645]
Gem nokogiri failed to install on Windows RubyInstaller 2.4.1
When install Ruby on Rails then error message: 'required ruby < 2.4'

When gem will support Ruby 2.4.x on Windows?

RubyInstaller for Windows:
https://github.com/oneclick/rubyinstaller2/releases

**Comment by larskanis** [comment]
RubyInstaller-2.4 will be supported with nokogiri-1.8.0 as described in https://github.com/sparklemotion/nokogiri/issues/1618 .

For now use:
```sh
  ridk exec pacman -S mingw-w64-x86_64-libxslt
  gem install nokogiri --platform ruby -- --use-system-libraries
```

Also see the https://github.com/oneclick/rubyinstaller2/wiki/FAQ

**Comment by Sega100500** [comment]
@larskanis 
Anyway
gem install rails -v '5.0.3'
output: 'nokogiri required ruby < 2.4'

**Comment by Sega100500** [comment]
@larskanis 
after 'ridk install', choice 3
all work!
Thanks!
