### ISSUE TITLE
Create API for /setting/ line number

### ISSUE THREAD

**Issue by fulldecent** [sparklemotion/nokogiri#1657]
There is a desire to /set/ line numbers on XML nodes. This is for constructed nodes.

Please see downstream discussion at https://github.com/rubys/nokogumbo/issues/53#issuecomment-309504802

Related, also see discussion on libxml and line numbers greater than 65535 (and workarounds) at:

 - https://github.com/rubys/nokogumbo/issues/53#issuecomment-309504802
 - https://github.com/rubys/nokogumbo/pull/55
 - https://github.com/sparklemotion/nokogiri/issues/533

---

PR coming

**Comment by fulldecent** [comment]
PR added at https://github.com/sparklemotion/nokogiri/pull/1658

**Comment by flavorjones** [comment]
@fulldecent you seem to be bringing up two distinct issues here:

* a feature request, to set line numbers on nodes.
* a bug report about line numbers being limited to a `short int`, which is unfortunately a limitation in libxml2's data structure; Nokogiri here is behaving exactly as the libxml2 maintainers wish/constrain it to.

The first is being addressed in your PR at #1658, which is where I'd like to focus the conversation about that feature request.

The second has been discussed in the issue you reference, and so unless there's new information or a concrete suggestion on how to address this behavior (I don't see one here?), I'd prefer to not reopen that discussion.

So, I'm going to close this issue out -- let's continue the API conversation at #1658.

**Comment by fulldecent** [comment]
Got it. I understand the short int issue and am not looking to rock the boat on libxml.
