### ISSUE TITLE
Support pkg-config gem 1.2.x?

### ISSUE THREAD

**Issue by swills** [sparklemotion/nokogiri#1660]
The [1.2.x version of pkg-config](https://rubygems.org/gems/pkg-config/versions/1.2.3) seems to work fine in my testing. But [extconf.rb limits to 1.1.x](https://github.com/sparklemotion/nokogiri/blame/master/ext/nokogiri/extconf.rb#L119). Any reason not to change to limit to 1.x?

**Comment by flavorjones** [comment]
Fair enough. Committed that change.
