### ISSUE TITLE
nokogiri mismanages misnested tags

### ISSUE THREAD

**Issue by dfabulich** [sparklemotion/nokogiri#1664]
Misnested tags such as `<b>bold <i>bold italic</b> italic</i>` are not being handled in accordance with the HTML parsing spec.

```ruby
require 'rubygems'
require 'nokogiri'
html_doc = Nokogiri::HTML("<!DOCTYPE html><p>1<b>2<i>3</b>4</i>5</p>")
puts html_doc.to_html
```

Actual:

```
<!DOCTYPE html>
<html><body><p>1<b>2<i>3</i></b>45</p></body></html>
```

Expected:

```
<!DOCTYPE html>
<html><body><p>1<b>2<i>3</i></b><i>4</i>5</p></body></html>
```

The HTML parsing spec has a section explaining how this sample is supposed to work: https://www.w3.org/TR/html5/syntax.html#misnested-tags:-b-i-/b-/i

**What's the output from `nokogiri -v`?**

```
$ nokogiri -v
# Nokogiri (1.8.0)
    ---
    warnings: []
    nokogiri: 1.8.0
    ruby:
      version: 2.4.1
      platform: x86_64-darwin16
      description: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.4
      loaded: 2.9.4
```

**Comment by dfabulich** [comment]
Nokogumbo does the right thing.

```
require 'rubygems'
require 'nokogumbo'
html_doc = Nokogiri::HTML5("<!DOCTYPE html><html><body><p>1<b>2<i>3</b>4</i>5</p></body></html>")
puts html_doc.to_html
```

**Comment by flavorjones** [comment]
libxml2 (which is what Nokogiri uses for parsing) doesn't support HTML5, so that spec is perhaps not relevant. If you want to parse HTML5, I definitely advise that you use Nokogumbo.

If you feel strongly this is a bug in parsing, I'd ask that you file the bug upstream with libxml2.
