### ISSUE TITLE
`write_to` ingores the indent option

### ISSUE THREAD

**Issue by Shamaoke** [sparklemotion/nokogiri#1668]
I want to get the indented HTML document

    <!DOCTYPE html>
    <html>
      <head>
        <title>Sample</title>
      </head>
      <body>
        <header></header>
        <main>
          <div>This is a sample.</div>
        </main>
        <footer></footer>
      </body>
    </html>

from a source with no indentation, using the following script:

    require 'nokogiri' # 1.8.0
    
    data = DATA.read
    
    html_document = Nokogiri::HTML data
    xml_document  = Nokogiri::XML data
    
    html_document.write_to $>, indent: 2
    
    puts '---'
    
    xml_document.write_html_to $>, indent: 2
    
    __END__
    <!DOCTYPE html>
    <html>
    <head>
    <title>Sample</title>
    </head>
    <body>
    <header></header>
    <main>
    <div>This is a sample.</div>
    </main>
    <footer></footer>
    </body>
    </html>

However, the `write_to` and `write_html_to` methods ignore the _indent_ option, so I get output in the same form as input.

**Comment by flavorjones** [comment]
Hi! Thanks for asking this question. I'm tagging @tenderlove to keep me honest in my reponse.

Nokogiri relies on libxml2 for parsing and serialization (among other things). And unfortunately, libxml2 doesn't support indentation in its formatting of HTML documents.

If you're thinking to yourself, "that's crazy," well, I tend to agree. You can see it yourself in the libxml2 source if you take a look:

* All of the write-to-io family of methods eventually call `native_write_to`  in `xml_node.c`.
* This function calls the libxml2 method `xmlSaveTree` in `xmlsave.c`
* which calls `xmlNodeDumpOutputInternal`
* which then notices this is an HTML doc and calls `htmlNodeDumpOutputInternal`,
* which finally calls `htmlNodeDumpFormatOutput` in `HTMLtree.c`, and that's the workhorse of HTML serialization.

You'll notice the word "indent" doesn't even appear in this function or file.

That said, though, I've personally found that libxml2's conventions around serialization and formatting are hard to predict and understand, even for XML serialization which nominally supports it. One example of this is that if you have all your tags on one line with no intervening whitespace, indentation works well:

```
doc = Nokogiri::XML('<root><foo><bar/></foo></
doc.write_xml_to STDOUT, :indent => 5
```
outputs
```
<?xml version="1.0"?>
<root>
     <foo>
          <bar/>
     </foo>
</root>
```

but throw some whitespace (or newlines) in there and:

```
doc = Nokogiri::XML('<root> <foo> <bar/></foo></root>')
doc.write_xml_to STDOUT, :indent => 5
```
outputs
```
<?xml version="1.0"?>
<root> <foo> <bar/></foo></root>
```

The origin of this behavior is unclear to me; though probably a related comment from the libxml2 FAQ:

> Libxml2 will not invent spaces in the content of a document since all spaces in the content of a document are significant. If you build a tree from the API and want indentation:
> 
> 1. the correct way is to generate those yourself too.
> 2. the dangerous way is to ask libxml2 to add those blanks to your content modifying the content of your document in the process. The result may not be what you expect. There is NO way to guarantee that such a modification won't affect other parts of the content of your document. See xmlKeepBlanksDefault () and xmlSaveFormatFile ()

I'm sorry I can't help more here.

**Comment by Shamaoke** [comment]
Thank you for taking the time to figure all this out.

**Comment by emilebosch** [comment]
This seems to work 🌮 


```
doc = Nokogiri.XML(x) do |config|
  config.default_xml.noblanks
end
puts doc.to_xml(:indent => 5)
```
