### ISSUE TITLE
Ruby64 - Class not registered error for BlueZone emulator.

### ISSUE THREAD

**Issue by Dave567** [sparklemotion/nokogiri#1675]
We are using Rocket BlueZone Terminal Emulator. But issue is, Ruby64 is not able to create BlueZone object  but same code runs perfectly fine with Ruby32. Can someone please help to fix Ruby64?
OS - Windows 10.

Code - 
require 'win32ole'
class BZExtra

  def start_extra_sys
      @system = WIN32OLE.new('BlueZone.System') #Fail on this line .
      sessions = @system.Sessions
      session = sessions.Open('path')
      session.WindowState = window_state
      session.Visible = visible
  end
end

Error - 
WIN32OLERuntimeError: failed to create WIN32OLE object from `BlueZone.System'
    HRESULT error code:0x80040154
      Class not registered

Note- For some reason only this BlueZone is failing, when I try Excel application it works fine.

**Comment by larskanis** [comment]
This project is about nokogiri - a XML/HTML processing library. Your issue is probably better placed at https://github.com/oneclick/rubyinstaller2 ?
