### ISSUE TITLE
Fails to parse <html ⚡> (as found in AMP pages)

### ISSUE THREAD

**Issue by rlue** [sparklemotion/nokogiri#1679]
**What problems are you experiencing?**

Nokogiri does not recognize the "Unicode high voltage" symbol (used to indicate AMP pages) as a valid XML attribute. (It does not recognize any other emoji/multi-byte unicode characters for that matter, though I don't know of any such valid attributes other than "⚡").

**What's the output from `nokogiri -v`?**

```
# Nokogiri (1.8.0)
    ---
    warnings: []
    nokogiri: 1.8.0
    ruby:
      version: 2.4.1
      platform: x86_64-darwin15
      description: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.2
      loaded: 2.9.2
```

**Can you provide a self-contained script that reproduces what you're seeing?**

```ruby
[1] pry(main)> require 'nokogiri'
[2] pry(main)> doc = Nokogiri::HTML('<html ⚡ lang="en">')
=> #(Document:0x3fc70d09ffc4 { name = "document", children = [ #(DTD:0x3fc70d0973b0 { name = "html" }), #(Element:0x3fc70d08b7f4 { name = "html", attributes = [ #(Attr:0x3fc70d08ac3c { name = "lang", value = "en" })] })] })
[3] pry(main)> doc.children.last.attributes
=> {"lang"=>#(Attr:0x3fc70d08ac3c { name = "lang", value = "en" })}
```

Note the absence of a `⚡` attribute. If an emoji or multi-byte unicode character is used as an attribute _with an assigned value_, the resulting attribute-value pair is omitted from the node data entirely:

```ruby
[4] pry(main)> doc = Nokogiri::HTML('<html ⚡="foo" lang="en">')
=> {"lang"=>#(Attr:0x3fc70d4c3bb4 { name = "lang", value = "en" })}
```

**Comment by flavorjones** [comment]
Well, let's take a look at the errors being emitted by the parser (if any):

```
doc = Nokogiri::HTML('<html ⚡ lang="en">')
puts doc.to_html
puts "---"
puts doc.errors
```

outputs

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html lang="en"></html>
---
1:7: ERROR: error parsing attribute name
```

So libxml2 is raising an error during parsing, which is beyond the control of Nokogiri. If you believe this is incorrect behavior, you're welcome to file a bug report upstream, but before doing that you may want to review some of the extant conversation about the practice of using attributes that aren't defined in the HTML4 spec:

https://stackoverflow.com/questions/925994/what-characters-are-allowed-in-an-html-attribute-name

You may also want to browse the HTML4 spec to see if you can spot where it indicates this attribute type is allowed or disallowed (I tried and couldn't (committee specs, amirite?)).

Sorry I can't help more, Nokogiri relies heavily on the underlying parsing libraries for this sort of functionality.
