### ISSUE TITLE
XSD Validation Error with files including themselves. 

### ISSUE THREAD

**Issue by BobbyMcWho** [sparklemotion/nokogiri#1683]
We have a group of xsd's with a base overarching file that includes all the other files into 1 single namespace. Names have been changed due to proprietary files. Whenever we try to run Nokogiri::XML::Schema#validate on a valid XML file against the overarching.xsd, we get an error: 
```
ERROR: Element '{http://www.w3.org/2001/XMLSchema}include': The schema document '/path/to/file/structures.xsd' cannot include itself..
```

overarching.xsd :
```
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="version">
	<xsd:include schemaLocation="datatypes.xsd"/>
	<xsd:include schemaLocation="ecl.xsd"/>
	<xsd:include schemaLocation="structures.xsd"/>
	<xsd:include schemaLocation="foo.xsd"/>
	<xsd:include schemaLocation="bar.xsd"/>
```

structures.xsd :
```<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="version">
	<xsd:include schemaLocation="datatypes.xsd"/>
	<xsd:include schemaLocation="ecl.xsd"/>
	<xsd:include schemaLocation="structures.xsd"/>
...
```
I don't seem to be getting this error when validating using the XMLEdita tool gui tool, nor Oxygen XML Editor to validate the file against the XSD. Is this an issue with Nokogiri, or can you point me to where that error rule is specified in the W3 rules as I can't seem to locate where it says it can't reference itself?

Thank you!

**Comment by flavorjones** [comment]
@BobbyMcWho I'm terribly sorry I haven't responded to this earlier. Thanks for asking this question.

What you're describing here is behavior that Nokogiri inherits from libxml2 ([code is here](https://github.com/GNOME/libxml2/blob/master/xmlschemas.c#L10973-L10977)) and so there's nothing Nokogiri can easily to do avoid this.

If you'd like to understand why libxml2 is doing this, my advice would be to ask this on the upstream libxml2 mailing list; or a more general XML forum where perhaps someone who knows the spec better than I can answer you.

Sorry I can't be more helpful. :neutral_face:
