### ISSUE TITLE
Nokogiri and xpointer?

### ISSUE THREAD

**Issue by dredknight** [sparklemotion/nokogiri#1686]
Dear everyone!

 I have been messing with Nokogiri for the last week and it helped me a lot in extracting huge library of XML files. There is one thing I stumbled upon and could not find and information.
There are XML files looking like this:
```XML
<Creature>
	<AttackSkill>2</AttackSkill>
	<DefenceSkill>2</DefenceSkill>
	<Visual href="/GameMechanics/CreatureVisual/Creatures/Academy/Gremlin.xdb#xpointer(/CreatureVisual)"/>
</Creature>
```

As you can see there is a namespace called **visual** that points to a namespace in another file.
How can I use this information to make Nokogiri access the namespace in the other file?

The other file looks like this:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<CreatureVisual>
	<CreatureNameFileRef href="/Text/Game/Creatures/Academy/3rd/Gremlin_Name.txt"/>
	<CreatureAbilitiesFileRef href="/Text/Game/Creatures/Academy/3rd/Gremlin_Abils.txt"/>
	<DescriptionFileRef href="/Text/Game/Creatures/Academy/3rd/Gremlin_Desc.txt"/>
</CreatureVisual>
```
My goal is to get CreatureNameFileRef message "/Text/Game/Creatures/Academy/3rd/Gremlin_Name.txt"

I think there is something important about the **xpointer** but I could not find any relation in the Nokogiri tutorials about it (nor anywhere on the net).

Thank you for your time!

**Comment by tenderlove** [comment]
`Visual` isn't a namespace, but a regular XML node.  You'll have to write some custom code to access that file as it isn't an XML specific thing.  It should be easy with Nokogiri, just find the node, extract the `href`, and read the file. 😄
