### ISSUE TITLE
About sending an issue to a document

### ISSUE THREAD

**Issue by 723gt** [sparklemotion/nokogiri#1691]
Should I clarify how to send a problem to a document or markdown file?
Should I follow the instructions for getting into the mailing list like code and bug reports?

**Comment by 723gt** [comment]
How to send a bug report is written ,  (http://www.nokogiri.org/tutorials/getting_help.html)
I do not think there is a way to discuss documents

**Comment by flavorjones** [comment]
@723gt I'm not sure which documents you'd like to discuss? Feel free to discuss here.
