### ISSUE TITLE
rubygem-nokogiri is not available in any RHEL7 repos

### ISSUE THREAD

**Issue by GeraldScott** [sparklemotion/nokogiri#1695]
I am having trouble installing Nokogiri on a RHEL 7 server because it is only available from an older RHEL 6 repo 'rhel-6-server-sam-rpms'

I installed it by downloading it from that repo and then did a yum localinstall, but obviously that is not ideal.

**Comment by yokolet** [comment]
@GeraldScott Did you see any error message when you failed to install on RHEL 7? If so, would you paste the error here?

**Comment by GeraldScott** [comment]
yum -y install opennebula-server opennebula-sunstone opennebula-ruby opennebula-gate opennebula-flow
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package opennebula-flow.x86_64 0:5.4.1-1 will be installed
---> Package opennebula-gate.x86_64 0:5.4.1-1 will be installed
---> Package opennebula-ruby.x86_64 0:5.4.1-1 will be installed
--> Processing Dependency: rubygem-nokogiri for package: opennebula-ruby-5.4.1-1.x86_64
---> Package opennebula-server.x86_64 0:5.4.1-1 will be installed
--> Processing Dependency: opennebula = 5.4.1 for package: opennebula-server-5.4.1-1.x86_64
---> Package opennebula-sunstone.x86_64 0:5.4.1-1 will be installed
--> Running transaction check
---> Package opennebula.x86_64 0:5.4.1-1 will be installed
---> Package opennebula-ruby.x86_64 0:5.4.1-1 will be installed
--> Processing Dependency: rubygem-nokogiri for package: opennebula-ruby-5.4.1-1.x86_64
--> Finished Dependency Resolution
Error: Package: opennebula-ruby-5.4.1-1.x86_64 (opennebula)
           Requires: rubygem-nokogiri
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Package: opennebula-ruby-5.4.1-1.x86_64 (opennebula)
           Requires: rubygem-nokogiri
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by GeraldScott** [comment]
yum repolist
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
repo id                                                                              repo name                                                                                                               status
Webmin                                                                               Webmin Distribution Neutral                                                                                                279
cf-me-5.8-for-rhel-7-rpms/x86_64                                                     Red Hat CloudForms Management Engine 5.8 (RPMs)                                                                            114
opennebula                                                                           opennebula                                                                                                                  11
pgdg96/7Server/x86_64                                                                PostgreSQL 9.6 7Server - x86_64                                                                                            464
rhel-7-server-extras-rpms/x86_64                                                     Red Hat Enterprise Linux 7 Server - Extras (RPMs)                                                                          710
rhel-7-server-optional-rpms/7Server/x86_64                                           Red Hat Enterprise Linux 7 Server - Optional (RPMs)                                                                     13,030
rhel-7-server-rpms/7Server/x86_64                                                    Red Hat Enterprise Linux 7 Server (RPMs)                                                                                17,720
rhel-7-server-supplementary-rpms/7Server/x86_64                                      Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)                                                                   238
rhel-server-rhscl-7-eus-rpms/7Server/x86_64                                          Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 RHEL 7 Server EUS                                       7,117
repolist: 39,683

**Comment by yokolet** [comment]
@GeraldScott I see rh-ruby23-rubygem-nokogiri package in cf-me-5.8-for-rhel-7-rpms  repo. This repo is listed in your repolist. So, I believe you can use this version.

I installed rh-ruby23 and rh-ruby23-rubygem-nologiri on RHEL 7.4 and confirmed Nokogiri worked. The hard part would be Nokogiri is in a dependency, which sees another version.

**Comment by GeraldScott** [comment]
Thanks @yokolet , yes, I tried that, but it still failed. I also tried installing the gem nokogiri manually. 

Installing the RHEL 6 version from the 'rhel-6-server-sam-rpms' repo works, so I guess the solution is to get rubygem-nokogiri into the rhel-7-server-optional-rpms repo (the equivalent of EPEL).

**Comment by yokolet** [comment]
@GeraldScott I got this info from my co-worker. The rubygem-nokogiri is already in EPEL repo. It installs ruby 2.0.0 and nokogiri 1.6.1, older versions, but you can install the rubygem-nokogiri package on RHEL 7.

```bash
// enable EPEL repo
$ sudo yum install http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm

// temporary disable it
$ sudo sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo

// install nokogiri 
$ sudo yum -y --enablerepo=epel install rubygem-nokogiri

  ...
Installed:
  rubygem-nokogiri.x86_64 0:1.6.1-1.el7.1
  ...

$ rpm -qa |grep nokogiri
rubygem-nokogiri-1.6.1-1.el7.1.x86_64

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

$ /usr/bin/irb
irb(main):001:0> require 'nokogiri'
=> true
irb(main):002:0> Nokogiri
=> Nokogiri
```
Does above work for you?

**Comment by GeraldScott** [comment]
It worked perfectly and is a more elegant solution. Thank you @yokolet. 

Who is responsible to get rubygem-nokogiri into the RHEL equivalent of the EPEL repo instead of using the Fedora repo? Will you raise an issue with Redhat?

**Comment by yokolet** [comment]
@GeraldScott That sounds nice.

I'm not sure how the package gets in. I suspect even @flavorjones doesn't know. I'll research a bit. If I get some, I'll post an update.
If you have a valid RHEL subscription, you'd better to file a ticket at the Red Hat customer portal. It may work better.

**Comment by GeraldScott** [comment]
Yes, I have a RHEL Developer's Subscription, so I will file a ticket with them..

Thanks again for your assistance!

**Comment by flavorjones** [comment]
@GeraldScott thanks for following up.
