### ISSUE TITLE
unexpected memory bloat from Nokogiri::XML::Node.new

### ISSUE THREAD

**Issue by wlipa** [sparklemotion/nokogiri#1703]
While using the SAX parser to convert large HTML docs from one form to another, I encountered high memory bloat for large documents.  I eventually traced it down to the following pattern causing an arbitrarily large number of Nokogiri::XML::Element objects being held for the lifetime of the associated Nokogiri::HTML::Document even if they are unlinked.  My assumption was that unlinking the node would allow it to be fully garbage collected, but it seems not.

Mimimization:

    require 'nokogiri'
    require 'objspace'  # for debug purposes
    doc = Nokogiri::HTML::Document.new
    # make 1000 as large as you like to consume more and more memory despite the unlink
    1000.times{ Nokogiri::XML::Node.new('foo', doc).unlink }
    GC.start
    ObjectSpace.count_tdata_objects(Nokogiri::XML::Element)
    # shows 1000 held references

Node info:

    # Nokogiri (1.8.1)
        ---
        warnings: []
        nokogiri: 1.8.1
        ruby:
          version: 2.3.5
          platform: x86_64-darwin17
          description: ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin17]
          engine: ruby
        libxml:
          binding: extension
          source: packaged
          libxml2_path: "/Users/wlipa/.gem/ruby/2.3.0/gems/nokogiri-1.8.1/ports/x86_64-apple-darwin17.0.0/libxml2/2.9.5"
          libxslt_path: "/Users/wlipa/.gem/ruby/2.3.0/gems/nokogiri-1.8.1/ports/x86_64-apple-darwin17.0.0/libxslt/1.1.30"
          libxml2_patches: []
          libxslt_patches: []
          compiled: 2.9.5
          loaded: 2.9.5

**Comment by flavorjones** [comment]
Hi @wlipa, thanks for asking this question.

The short answer is that unlinked nodes are kept for the life of the document, for the reason that there may exist a ruby object that still references the underlying C struct. This is one of many compromises the Nokogiri maintainers adopted to work around libxml2's memory management model.

The code behind this can be seen in `xml_node.c`'s `unlink_node` method:

```C
/*
 * call-seq:
 *  unlink
 *
 * Unlink this node from its current context.
 */
static VALUE unlink_node(VALUE self)
{
  xmlNodePtr node;
  Data_Get_Struct(self, xmlNode, node);
  xmlUnlinkNode(node);
  nokogiri_root_node(node);
  return self;
}
```

which calls `nokogiri_root_node`, defined in `nokogiri.c`:

```C
void nokogiri_root_node(xmlNodePtr node)
{
  xmlDocPtr doc;
  nokogiriTuplePtr tuple;

  doc = node->doc;
  if (doc->type == XML_DOCUMENT_FRAG_NODE) doc = doc->doc;
  tuple = (nokogiriTuplePtr)doc->_private;
  st_insert(tuple->unlinkedNodes, (st_data_t)node, (st_data_t)node);
}
```

These "unlinked nodes" are later freed when the Document is cleaned up. This mechanism is setting `xml_document.c:dealloc` as the cleanup method when we wrap the Document struct:

```C
VALUE Nokogiri_wrap_xml_document(VALUE klass, xmlDocPtr doc)
{
  nokogiriTuplePtr tuple = (nokogiriTuplePtr)malloc(sizeof(nokogiriTuple));

  VALUE rb_doc = Data_Wrap_Struct(
      klass ? klass : cNokogiriXmlDocument,
      0,
      dealloc,
      doc
  );

  VALUE cache = rb_ary_new();
  rb_iv_set(rb_doc, "@decorators", Qnil);
  rb_iv_set(rb_doc, "@node_cache", cache);

  tuple->doc = rb_doc;
  tuple->unlinkedNodes = st_init_numtable_with_size(128);
  tuple->node_cache = cache;
  doc->_private = tuple ;

  rb_obj_call_init(rb_doc, 0, NULL);

  return rb_doc ;
}
```

and the `dealloc` method then cleans it up, referencing the hash table via the `DOC_UNLINKED_NODE_HASH` macro:

```c
static void dealloc(xmlDocPtr doc)
{
  st_table *node_hash;

  NOKOGIRI_DEBUG_START(doc);

  node_hash  = DOC_UNLINKED_NODE_HASH(doc);

  st_foreach(node_hash, dealloc_node_i, (st_data_t)doc);
  st_free_table(node_hash);

  free(doc->_private);

  /* When both Nokogiri and libxml-ruby are loaded, make sure that all nodes
   * have their _private pointers cleared. This is to avoid libxml-ruby's
   * xmlDeregisterNode callback from accessing VALUE pointers from ruby's GC
   * free context, which can result in segfaults.
   */
  if (xmlDeregisterNodeDefaultValue)
    remove_private((xmlNodePtr)doc);

  xmlFreeDoc(doc);

  NOKOGIRI_DEBUG_END(doc);
}
```

I'm open to other solutions; notably we could try to track Ruby objects that are reference the C struct, but that would add considerable complexity to the codebase for what is a rather narrow edge case.

I'll leave this issue open for a few more days to hear comments and continue the conversation.

**Comment by wlipa** [comment]
Thanks for the explanation.  It would be nice if the unlink documentation mentioned that the nodes would not be GC-eligible until the document went away.

I doubt it would be worth it to add some complicated mechanism to track Ruby objects, but might it be possible to add a destroy method on Node when you're sure there aren't any other references?

**Comment by tenderlove** [comment]
IIRC the reason we can't just free nodes is that libxml2 interns strings, and will try to free interned strings when you free a node.  The interned string map is held on the XML document, and I don't think there is a way for us to tell if the Node shares strings with the interned string map.  So yes it's possible for us to add a method that would actually free the node, but I don't think you could actually be sure there are no references, so you could introduce segvs.

**Comment by flavorjones** [comment]
OK, I'm going to go ahead and close this issue.

**Comment by BlackNightFury** [comment]
@flavorjones , thanks for these explanation. I am also facing the problem which memory usage is increased highly when I use nokogiri::xml::builder.

Can you please describe in more details how I can reduce it in ruby?

Thanks
