### ISSUE TITLE
I text node contains Ampersand it is missing in a parsed document

### ISSUE THREAD

**Issue by tarvit** [sparklemotion/nokogiri#1705]
I text node contains Ampersand it is missing in a parsed document
```ruby
Nokogiri::XML('<a>Tom & Jerry</a>').to_xhtml
# "<a>Tom  Jerry</a>\n" 
```

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by ar7max** [comment]
I assume this is not valid string, so it should be something like &amp; instead.
`p Nokogiri::XML('<a>Tom & Jerry</a>').errors`
outputs 
`[#<Nokogiri::XML::SyntaxError: 1:9: FATAL: xmlParseEntityRef: no name>]`
but
`p Nokogiri::XML('<a>Tom &amp; Jerry</a>').errors`
outputs 
[]
and
`p Nokogiri::XML('<a>Tom & Jerry</a>').to_xhtml`
prints
`<a>Tom &amp; Jerry</a>\n`
as expected

**Comment by tarvit** [comment]
I know that `Nokogiri::XML('<a>Tom &amp; Jerry</a>')` will work. 
But why is single ampersand invalid? I was looking for a solution to safely process such text nodes through nokogiri. In my case this single ampersand is important

**Comment by ar7max** [comment]
But as described here https://github.com/sparklemotion/nokogiri/issues/1581 

> Ampersand is excluded here, of course, because it is the character that introduces a Reference -- the other fork in the production. The name that forms an entity reference (the characters after the '&') must be a valid name, but attribute values themselves do not need to be made up only of valid XML names.

So u can try to use HTML instead of XML constructor.

**Comment by tarvit** [comment]
Thank you @ar7max 
I've found such workaround which is good enough for me
```ruby
doc = Nokogiri::XML('<a></a>')
doc.css('a').first.add_child('Tom & Jerry')
doc.to_xhtml
# "<a>Tom &amp; Jerry</a>\n" 
```

**Comment by flavorjones** [comment]
Thanks all for helping support Nokogiri users.
