### ISSUE TITLE
suggestion: package only files that are needed at runtime in the gem

### ISSUE THREAD

**Issue by stevecrozz** [sparklemotion/nokogiri#1711]
I noticed that the nokogiri gem distribution published on rubygems.org contains files that are not strictly necessary for nokogiri at runtime. I suggest we follow the lead of the rails family of gems and only package those files that are needed at runtime:
Example: https://github.com/rails/rails/blob/v5.1.4/activesupport/activesupport.gemspec#L18

My interest is in cutting down the size of the docker images that I maintain so that moving images across the internet becomes faster (especially helpful during deploys). I introduced this topic on the mailing list first  and @flavorjones recommended we open this topic for discussion here on github.

I'd love to hear any arguments for/against this idea.

**Comment by flavorjones** [comment]
Thanks for opening this issue for discussion, @stevecrozz.

For context, I'll repeat what I said on the mailing list, which is that it's been occasionally useful to install the tests to determine if Nokogiri is _really_ working on a system, particularly if using an old version of libxml2/libxslt. (In fact, this is in part how I determine if an RC is working properly on, e.g. windows.)

That said, I don't feel strongly about it and would like to know if other people thing gems should be limited to distributing just the runtime bits.

**Comment by larskanis** [comment]
I usually remove [the test -> compile dependency](https://github.com/sparklemotion/nokogiri/blob/master/Rakefile#L306) in the git working directory to verify that the current installed gem works as expected. So IMHO we can remove the files in question.

Maybe it makes sense then to remove the test -> compile dependency above in the Rakefile permanently and call `rake compile test` in cases when we used to run `rake test` before?

**Comment by stevecrozz** [comment]
There's not a whole lot of activity here, but I'm happy to advocate for this idea a bit to help push it forward. There is some value in having all the source files on a system in order to run tests. And there's also value in trimming the size of the gem. I'm not sure how to weigh these values relatively. Maybe we could mitigate the potential damage by providing an alternate method for getting the test files when needed. Is it tenable to ask users to git clone the source code at a specific tag when they need to run tests? That's what I would do if I wanted to run tests.

Even if that doesn't work for some users, it still **could** be more valuable to trim the gem than to package files in the release that will be so rarely used. But I recognize that's an easy thing for me to say, not having to support nokogiri users :)

**Comment by stevecrozz** [comment]
Btw, I am happy to prepare the PR if that helps sweeten the deal.

**Comment by flavorjones** [comment]
@stevecrozz if you wanted to provide a PR I would absolutely consider merging it. Thanks for helping nudge this along!

**Comment by stevecrozz** [comment]
@flavorjones I've not yet worked on a gem that uses hoe. Is it simply a matter of altering Manifest.txt? Or is there more to it?

**Comment by flavorjones** [comment]
@stevecrozz Ah, sometimes Hoe gets in the way as much as it helps. I think I need to go stare at the docs myself ...

**Comment by flavorjones** [comment]
I've merged this manually! Will be in v1.9.0. Thanks again for your patience and for submitting this PR!
