### ISSUE TITLE
Nokogiri doesn't install on windows

### ISSUE THREAD

**Issue by graywolf** [sparklemotion/nokogiri#1726]
Recent security update to `gem` executable has broken nokogiri fat gem on windows (tested on windows 7, 64bit, 2.5.0 rubyinstaller). Error is:

	ERROR:  While executing gem ... (Gem::Package::PathError)
		installing into parent path bin/nokogiri of C:/dev/Ruby25-x64/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.2-x64-mingw
	32 is not allowed

I suspect this https://www.ruby-lang.org/en/news/2018/02/17/multiple-vulnerabilities-in-rubygems/ is relevant because it installs fine without that update.

**Comment by larskanis** [comment]
I can not reproduce this so far. Both fat binary gem and source gem install fine for me.
When is the error raised? If it's while gem install, could you please re-run
```
gem env
gem inst nokogiri --verbose --backtrace
```
and post the output?

**Comment by graywolf** [comment]
Just to make sure, did you first upgrade ruby gems usinggem update --system?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Lars KanisSent: Saturday, February 24, 2018 23:36To: sparklemotion/nokogiriReply To: sparklemotion/nokogiriCc: W.; AuthorSubject: Re: [sparklemotion/nokogiri] Nokogiri doesn't install on windows (#1726)I can not reproduce this so far. Both fat binary gem and source gem install fine for me.
When is the error raised? If it's while gem install, could you please re-run
gem env
gem inst nokogiri --verbose --backtrace

and post the output?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sparklemotion/nokogiri","title":"sparklemotion/nokogiri","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sparklemotion/nokogiri"}},"updates":{"snippets":[{"icon":"PERSON","message":"@larskanis in #1726: I can not reproduce this so far. Both fat binary gem and source gem install fine for me.\r\nWhen is the error raised? If it's while gem install, could you please re-run\r\n```\r\ngem env\r\ngem inst nokogiri --verbose --backtrace\r\n```\r\nand post the output?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/sparklemotion/nokogiri/issues/1726#issuecomment-368265722"}}}

**Comment by larskanis** [comment]
@graywolf Of course, I upgraded to rubygems-2.7.6 before. However I noticed a very similar issue [on appveyor](https://ci.appveyor.com/project/flavorjones/nokogiri/branch/master/job/6htl5u3rcq9y28md), which I can not reproduce locally too.

**Comment by graywolf** [comment]
Tomorrow when I get back to my windows machine I'll provide the requested information :)

**Comment by graywolf** [comment]
Sorry for wasting your time, I figured it out and it's not nokogiri issue. Will make bug report with ruby gems directly when I have some time.

**Comment by larskanis** [comment]
I've done a little bit of [printf debugging on Appveyor](https://ci.appveyor.com/project/larskanis/nokogiri/build/1.0.58) and found the root cause. It happens if you use rubygems-2.7.6 and set a `GEM_HOME` with different upper/lower case characters than the directory has on the filesystem. Possibly there are even more settings which result in this error, like rubygems config files, etc.

I'll file a bug report on rubygems.

**Comment by flavorjones** [comment]
@graywolf @larskanis thanks to both of you for following up!

**Comment by graywolf** [comment]
@larskanis Just for when you are reporting it: For me it's issue with TOPDIR in general, not with GEM_HOME. `RbConfig::TOPDIR` points to `C:/dev/Ruby25-x64` while it should be `C:/Dev/Ruby25-x64`. So when making the bugreport, could you mention that you cannot really rely on `__FILE__` in `/lib/ruby/2.5.0/x64-mingw32/RbConfig.rb` having correct casing of folders.
