### ISSUE TITLE
HTML(string) produces different structures on very similar inputs

### ISSUE THREAD

**Issue by jesteracer** [sparklemotion/nokogiri#1730]
I encountered a strange (in my opinion) behavior - when creating a new nokogiri html document. 
It normalizes the html but it does it differently for strings, that start with a text node and strings that start with a tag.
```ruby
require 'nokogiri'

test = "<a href='https://ya.ru'>link</a>text node"
doc = Nokogiri::HTML(test)
p doc.inner_html

test2 = "text node<a href='https://ya.ru'>link</a>"
doc2 = Nokogiri::HTML(test2)
p doc2.inner_html
```
So the output for this script is
```
<html><body>\n<a href=\"https://ya.ru\">link</a>text node</body></html>
<html><body><p>text node<a href=\"https://ya.ru\">link</a></p></body></html>
```
if a string starts with text node - it will be wrapped inside `p` node

And of course the structure of doc and doc2 is different. 
So if it is not a bug, I will be grateful if someone clarifies this behavior.

PS. I now know, that for this example `Nokogiri::HTML.fragment` is a prefered method, but it is not mentioned in the tutorials and since `Nokogiri::HTML` works out of the box without any notices, I only found out that it works differently in production :)  So maybe it is a good idea to mention it in tutorials.

**Comment by flavorjones** [comment]
Hi, thanks for asking these questions.

You're exploring a topic, "fixing up markup", that Nokogiri has very little control over, unfortunately. Nokogiri wraps either libxml2 (for MRI/CRuby) or xerces (for JRuby) and relies entirely on those underlying libraries to parse and "fix up" the markup.

And you're correct that you're passing an "html fragment", and so using `.fragment` is more appropriate. We should add that to the tutorial! If you'd like to give it a try, you can see the docs here:

http://github.com/sparklemotion/nokogiri.org-tutorials

and I would certainly consider any PR that introduced the concept of fragment parsing.

Sorry I can't help more, if you have more questions feel free to comment below or email nokogiri-talk!
