### ISSUE TITLE
NOKIGIRI IS HARD PLEZ HELP 

### ISSUE THREAD

**Issue by Thebaconduke** [sparklemotion/nokogiri#1736]
am trying to make a script to search by user by entering in there first name it should display the detail of that user this interacts with the file email.xml please help me !!! 
i can get it to read the xml doc and display all users i just need someone to give some exmaple code or show me how the hell i am supposed to do this thanks :)

**Comment by flavorjones** [comment]
Hello!

Thanks for asking this question! Your request for assistance using
Nokogiri will not go unanswered!

However, Nokogiri's Github Issues is reserved for reporting bugs or
submitting patches. If you ask your question on the mailing list, Team
Nokogiri promises someone will provide you with an answer in a timely
manner.

If you'd like to read up on Team Nokogiri's rationale for this policy,
please go to http://bit.ly/nokohelp.

Thank you so much for understanding! And thank you for using Nokogiri.

**Comment by Thebaconduke** [comment]
uuhhhh there was a bug with nokogiri its a scuffed gem ???? and annoying
and not very user friendly for something that claims to be user friendly
