### ISSUE TITLE
Drop support for JRuby 1.7

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1741]
See https://github.com/jruby/jruby/issues/4112 for background on JRuby 1.7 reaching EOL last year.

Also see our [CI builds going red](https://ci.nokogiri.org/builds/3799) because Rake has ended support for "ruby 1.9" which is what JRuby self-identifies as.

**Comment by flavorjones** [comment]
Things to do here:

- remove from Concourse CI (see 308d70c which was reverted)
- remove from Travis CI
- update gem spec which currently says `:required_ruby_version => '>= 1.9.3' # JRuby >= 1.7`\
- look at ext/java/nokogiri/XmlSyntaxError.java and ext/java/nokogiri/internals/NokogiriHelpers.java which appear to have 1.7-specific code that can be removed

**Comment by flavorjones** [comment]
Note: JRuby 1.7 was removed from the CI pipelines when `concourse-gem` v0.19.0 dropped in September.

Note: the `.travis.yml` file hasn't been changed since Feb 2018 which reinforces my belief that it's unused and unnecessary. Also, I turned off Travis builds 10 months ago and nobody has noticed. I am going to delete the travis config file.

So the updated punch list is:

* [ ] delete Travis config file
* [ ] update gem spec
* [ ] look at code that has 1.7-specific handling

**Comment by flavorjones** [comment]
@jvshahid I'm curious if you see any other JRuby code that's specific to 1.7 support (or Ruby 1.9 support)?

Notably, in `ext/java/nokogiri/XmlSyntaxError.java` the `to_s19` method appears to still be required on JRuby 9.2.x.x despite being explicitly commented as specific to JRuby 1.7 and named after Ruby 1.9 string handling.

**Comment by flavorjones** [comment]
@jvshahid bumping this. I think what I have on master is OK and so if you can't take a look I'll probably proceed anyway.

**Comment by jvshahid** [comment]
I took a quick look and couldn't find anything besides the few comments we had.  I'm not sure if there is an easy way to discover things that we can remove other than trying them out.  I made a few changes locally to stop using deprecated JRuby APIs.  I don't think it is a blocker though.  I will probably push those to a PR in the next few hours to test the changes in CI.

**Comment by flavorjones** [comment]
Word, OK. I'm going to close this, then. Thanks, @jvshahid!

**Comment by kares** [comment]
> Notably, in ext/java/nokogiri/XmlSyntaxError.java the to_s19 method appears to still be required on JRuby 9.2.x.x despite being explicitly commented as specific to JRuby 1.7 and named after Ruby 1.9 string handling.

most of the `is1_9` checking (and pre 1.9 missing encoding logic etc) was already gone, recall did update the above mentioned piece and it should be working fine on 9K but we should also change the signature to avoid (future) deprecation warnings. guess @jvshahid already has those.

btw. I did notice CI builds missing :) https://github.com/sparklemotion/nokogiri/commit/1edf50305370ce2dedcc4bafdc252839d8483e97 ... what's the status there, would you guys care to get Travis builds back or are they problematic to manage (we could simplify or allow failures)?

**Comment by flavorjones** [comment]
Can you help me understand what you're perceiving as "missing" with respect to CI? We have CI running a multi-ruby cross-platform build suite on every commit on master and every PR at https://ci.nokogiri.org/.

**Comment by kares** [comment]
@flavorjones sorry I did not know that ... what I am missing is smt to run if I do an experiment in a fork.
guess that won't work with the custom CI, right? its not crucial, now that I know smt would run in a PR.

**Comment by flavorjones** [comment]
@kares As I mentioned in the commit you referenced, the Travis builds have been turned off for nearly a year.

If you want to run tests on a fork, `rake compile test` should be sufficient. Deeper tests will run against PRs and you can see the status in the PR status update.
