### ISSUE TITLE
XSLT with output method="text" should not include <?xml decl

### ISSUE THREAD

**Issue by rcrews** [sparklemotion/nokogiri#1750]
Using XSLT to write JSON, I get incorrect output due to the erroneous inclusion of an XML declaration: `<?xml version="1.0"?>`. Running the same XSLT with the same XML using `xsltproc`, the output is as expected, without an XML declaration. This short program demonstrates the problem:

```ruby
require 'nokogiri'
doc = Nokogiri::XML('<g>Greetings</g>')
xslt = Nokogiri::XSLT(<<-STYLESHEET
  <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="text"/>
  </xsl:stylesheet>
  STYLESHEET
  )
print xslt.transform(doc)
```

Due to `<xsl:output method="text"/>` the output should be simply

```
Greetings
```

but is actually

```xml
<?xml version="1.0"?>
Greetings
```

Here's a minitest for the problem. It can possibly be placed after `test_transform2` in `test/test_xslt_transforms.rb`:

```ruby
  def test_assure_no_xml_decl_when_method_equals_text
    assert doc = Nokogiri::XML('<g>Greetings</g>')
    assert xslt = Nokogiri::XSLT(<<-STYLESHEET
      <xsl:stylesheet version="1.0"
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
        <!-- Because method="text", the result should not contain an XML
          declaration regardless of the setting or existance of the
          omit-xml-declaration attribute. See
          https://www.w3.org/TR/xslt-10/#output -->
        <xsl:output method="text" omit-xml-declaration="yes"/>
      </xsl:stylesheet>
      STYLESHEET
      )
    assert result = xslt.transform(doc)
    refute_match(/\A<\?xml/, result.to_s)
  end
```

**Comment by flavorjones** [comment]
Thanks for reporting. If you can, please tell us the output from `nokogiri -v` (which is asked in the issue template that you must have erased).

**Comment by rcrews** [comment]
Couple notes that might help:

* Changing to `method="html"` did not help me.

* Possibly the problem stems from the C "transform" function returning a value wrapped as an XML document without knowing if the output method is XML or text:
https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/xslt_stylesheet.c#L183

* Again, @ar7max was very helpful in pointing to this thread about LibXML/LibXSLT:
https://mail.gnome.org/archives/xslt/2009-July/msg00005.html
Seems we are encountering the expected behavior when the results are returned as an XML document. A lower-level API could get around this by having the XSLT result written to a stream. I don't see an API for this in Nokogiri. Not sure Nokogiri needs one since a lot of its beauty is that is is a high-level API. But I will be pleased to contribute thoughts and assistance if it is decided to pursue this in Nokogiri.

* My brute-force workaround is to remove the XML declaration with a regex:
```ruby
require 'nokogiri'
doc = Nokogiri::XML('<g>Greetings</g>')
xslt = Nokogiri::XSLT(<<-STYLESHEET
  <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="text"/>
  </xsl:stylesheet>
  STYLESHEET
  )
print xslt.transform(doc).to_s.sub(/\A<\?xml[^>]+>\s*/m, '')
```

**Comment by flavorjones** [comment]
Thanks for the additional information. It's highly likely that the behavior you're seeing is inherited from libxml2, and so there's not much we can do about it in Nokogiri.

Notably, running this in JRuby, which uses Xerces instead of libxml2, what you're doing is raising an exception:

```
$ ~/foo.rb
RuntimeError: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
  transform at nokogiri/XsltStylesheet.java:231
     <main> at /home/flavorjones/foo.rb:13
```

which tells me that the document being assembled by Xerces is similarly an xml document ... I'm not an XSLT expert, but does any of this suprise your, or jog any ideas?

**Comment by nwellnhof** [comment]
I think you simply have to use the stylesheet's serializer like

    xslt.serialize(xslt.transform(doc))

**Comment by flavorjones** [comment]
@nwellnhof You're right, of course :facepalm: 

I'll update the docs and then close this.
