### ISSUE TITLE
Allow to set NONET for schema validation

### ISSUE THREAD

**Issue by gucki** [sparklemotion/nokogiri#1752]
There's NONET for Nokogiri::XML to prevent nokogiri from using the network. However it seems there's no NONET (or configuration ability at all) for Nokogiri::XML::Schema. I tried to work around it like this:

    doc = Nokogiri::XML(File.read(xsd_path)) do |config|
      config.options = Nokogiri::XML::ParseOptions::NONET
    end
    schema = Nokogiri::XML::Schema.from_document(doc)

However nokogiri seems to ignore the config options and still uses the network.

**Comment by flavorjones** [comment]
Hi,

Thanks for reporting this. Can you please let us know the output from nokogiri -v?

I'll try to reproduce over the weekend, in the meantime if you have a test case handy, that would speed things up a bit.

**Comment by flavorjones** [comment]
I expect this will be addressed in the next v1.11.0 release candidate. I don't plan on backporting it to a v1.10.x release.

Tagging other issue: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-vr8q-g5c7-m54m

You'll be partially credited in the CVE advisory that's coming out. Thank you!

**Comment by flavorjones** [comment]
This issue was addressed in v1.11.0, but I neglected to close it out until now.
