### ISSUE TITLE
LoadError: incompatible library version - /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.so

### ISSUE THREAD

**Issue by manohar-nyros** [sparklemotion/nokogiri#1753]
Trying to run rake assets precompile with production mode as follows.

`rake assets:precompile`

It is working fine for ubuntu 14.04 (32 bit) and 16.06(32 bit.) But getting Load Error on `16.04(64` bit) in aws ec2.

Please help me regarding this.

Thanks in advance.

`rake aborted!
LoadError: incompatible library version - /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.so /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/nokogiri-1.8.2/lib/nokogiri.rb:32:in rescue in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/nokogiri-1.8.2/lib/nokogiri.rb:28:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/loofah-2.2.2/lib/loofah.rb:3:in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in block in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:inload_dependency' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/rails-html-sanitizer-1.0.4/lib/rails-html-sanitizer.rb:2:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/helpers/sanitize_helper.rb:2:in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in block in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:inload_dependency' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/helpers.rb:58:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/helpers.rb:4:in <module:ActionView>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/helpers.rb:3:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/base.rb:5:in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in block in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:inload_dependency' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/public_activity-1.5.0/lib/public_activity/utility/view_helpers.rb:25:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/public_activity-1.5.0/lib/public_activity/utility/view_helpers.rb:2:in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in block in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:inload_dependency' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/public_activity-1.5.0/lib/public_activity.rb:68:in' /home/ubuntu/learnmusicco/config/application.rb:7:in <top (required)>'
/home/ubuntu/learnmusicco/Rakefile:4:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/rake-12.3.1/exe/rake:27:in `'

Caused by: LoadError: cannot load such file -- nokogiri/2.3/nokogiri /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/nokogiri-1.8.2/lib/nokogiri.rb:30:in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in block in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:inload_dependency' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/loofah-2.2.2/lib/loofah.rb:3:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/rails-html-sanitizer-1.0.4/lib/rails-html-sanitizer.rb:2:in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in block in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:inload_dependency' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/helpers/sanitize_helper.rb:2:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/helpers.rb:58:in <module:Helpers>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/helpers.rb:4:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/helpers.rb:3:in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in block in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:inload_dependency' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/actionview-5.0.1/lib/action_view/base.rb:5:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/public_activity-1.5.0/lib/public_activity/utility/view_helpers.rb:25:in <module:PublicActivity>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/public_activity-1.5.0/lib/public_activity/utility/view_helpers.rb:2:in' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in require'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inblock in require' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:inrequire' /home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/public_activity-1.5.0/lib/public_activity.rb:68:in <top (required)>'
/home/ubuntu/learnmusicco/config/application.rb:7:in' /home/ubuntu/learnmusicco/Rakefile:4:in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1@lm5/gems/rake-12.3.1/exe/rake:27:in'`

**Comment by flavorjones** [comment]
Hello,

Thanks for asking this question. This is not a Nokogiri-specific issue, but I'll try to help.

The error message `LoadError: incompatible library version` is generally emitted by Ruby when the library was compiled against another version or Ruby or on another architecture. I'd recommend that you uninstall Nokogiri and then try reinstalling it.

I'll leave this issue open for a day or so in case you need more guidance.

**Comment by oxtian** [comment]
@flavorjones: I am also facing the exact issue. 
It seems like nokogiri 1.8.2 doesn't match the ubuntu version. How can we fix this if the issue pops up on the deployment server but not on my local machine given that the deployment server doesn't allow me to run `bundle install` again?

**Comment by flavorjones** [comment]
@oxtian I'm not sure what you mean by "nokogiri 1.8.2 doesn't match the ubuntu version," and I don't fully understand your deployment process.

This error message is saying that Nokogiri was compiled on another system. My advice for you is to figure out where Nokogiri is being compiled and how it's being deployed on the system that's emitting this error. The solution will be to make sure that it's compiled for the same system on which its deployed. I hope that makes sense?
