### ISSUE TITLE
DOM2DTMExt nextNode fails when running in J9

### ISSUE THREAD

**Issue by Taywee** [sparklemotion/nokogiri#1759]
Running this simple script in IBM J9 on AIX:

```ruby
require 'nokogiri'
Nokogiri::XML.fragment('<root/>')
```

gives the following error:

```
    java.lang.IllegalAccessError: Class org/apache/xml/dtm/ref/dom2dtm/DOM2DTMExt illegally accessing "package private" member of class org/apache/xml/dtm/ref/dom2dtm/DOM2DTMdefaultNamespaceDeclarationNode
                   nextNode at org/apache/xml/dtm/ref/dom2dtm/DOM2DTMExt.java:564
                   _firstch at org/apache/xml/dtm/ref/DTMDefaultBase:-1
```

It seems like J9 is having issues actually seeing these classes as being in the same package.  Instead of this sort of package hack, I think it might make more sense to actually inherit DOM2DTM from DOM2DTMExt and only override and replace methods as necessary than to replicate the class and patch methods.  I'm not sure if this is a possibility, but I'll be doing some experimentation and making a pull request if I crack it.

# Version information

```sh
$ ./jruby/bin/nokogiri -v
# Nokogiri (1.8.2)
    ---
    warnings: []
    nokogiri: 1.8.2
    ruby:
      version: 2.3.3
      platform: java
      description: jruby 9.1.17.0-SNAPSHOT (2.3.3) 2018-05-11 d8b1ff9 IBM J9 VM 2.6 on
        pap6470sr10fp10-20170726_05 (SR10 FP10) +jit [aix-ppc64]
      engine: jruby
      jruby: 9.1.17.0-SNAPSHOT
    xerces: XML4J 4.5.28
    nekohtml: NekoHTML 1.9.21
```

**Comment by flavorjones** [comment]
Thank you for reporting, and for submitting a PR addressing this. Looking at the PR.

**Comment by flavorjones** [comment]
Your PR commits were merged! This will be fixed in the next release, which should happen in the next few days. Watch https://github.com/sparklemotion/nokogiri/milestone/16 to gauge progress.

Thanks again!
