### ISSUE TITLE
nokogiri to complete metasploit instalation

### ISSUE THREAD

**Issue by daebae** [sparklemotion/nokogiri#1766]
## If you're having trouble installing Nokogiri ...

**Have you tried following [the installation tutorial][tutorial]?**

**What is the output of `gem install`?**

**What are the contents of the `mkmf.log` file?**

**What operating system are you using?**

## If this isn't an installation issue ...

**What problems are you experiencing?**

**What's the output from `nokogiri -v`?**

**Can you provide a self-contained script that reproduces what you're seeing?**

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by daebae** [comment]
??Says nokogiri cant be found run bundle install did that also ran gem fetch,install nokogiri 1.8.1 said susessful install so what the prob??

**Comment by flavorjones** [comment]
@daebae Can you provide more information about your problem, please?
