### ISSUE TITLE
Please release a new version with the latest leak fixes

### ISSUE THREAD

**Issue by brauliobo** [sparklemotion/nokogiri#1775]
I'm experiencing a leak with a long-running process which is hard to debug. We fetch data from several different websites using Mechanize + Nokogiri and nokogiri is the top memory user when analyzing memory through `memory_profiler`.

I see there is a few commits unreleased yet. As I can't use the git version without a gemspec, could you please release the latest git?

**Comment by flavorjones** [comment]
Sure! Give me a few hours.

**Comment by flavorjones** [comment]
v1.8.4 has been unleashed upon the world

**Comment by flavorjones** [comment]
I'm curious what you see with 1.8.4 in `memory_profiler` for your use case. It's worth noting that libxml2, which is the underlying parser, allocates quite a bit of memory for use in "pools" and in "dictionaries", both of which are intended (though perhaps unobvious) behavior that will show up as chunky memory usage.

**Comment by brauliobo** [comment]
It is still unclear what exactly is the memory leak, as I don't have much experience with `memory_profiler`.
What is somewhat clear now is that memory usage of nokogiri is lower as the sequence: 1.6.8.1 < 1.7.2 < 1.8.4

**Comment by brauliobo** [comment]
@flavorjones the issue was likely with mechanize https://github.com/sparklemotion/mechanize/issues/528
