### ISSUE TITLE
Rebuild ci.nokogiri.org

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1793]
Current configuration is expensive, and the latest concourse-deployment and bbl have options that are cheaper. Also, not sure I can admin the cluster anymore without lost creds.

**Comment by flavorjones** [comment]
See https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/concourse.md

And https://github.com/concourse/concourse-bosh-deployment

**Comment by flavorjones** [comment]
I've lost access to the current environment and it looks like I may have lost a few months of data. :-(

**Comment by flavorjones** [comment]
I've enlisted help from @osis who may be able to recover build history.

**Comment by osis** [comment]
Howdy!

Was able to grab the snapshot, spin up a new VM, attach mount the snapshot as disk, install Postgres, and pgdump to victory! 🎉

Hoping to see the site up again soon!

**Comment by flavorjones** [comment]
I think everything's mostly working, except for:

- windows workers
- scale up all workers
- container placement strategy
- x-frame options

And I haven't tested this yet:

- PR triggers / status
- IRC notifications

Should get to it all in the next day or so.

**Comment by flavorjones** [comment]
https://github.com/concourse/concourse-bosh-deployment/pull/99

**Comment by flavorjones** [comment]
Closing this. Windows workers are blocked on https://github.com/sparklemotion/nokogiri/issues/1729
