### ISSUE TITLE
Why does Nokogiri::HTML close <u> tag immediately?

### ISSUE THREAD

**Issue by Nakilon** [sparklemotion/nokogiri#1798]
```
$ cat Gemfile
source "https://rubygems.org"
gem "nokogiri"

$ bundle exec gem list
*** LOCAL GEMS ***
bundler (1.16.1)
mini_portile2 (2.3.0)
nokogiri (1.8.4)

$ cat temp.rb 
require "nokogiri"
puts Nokogiri::HTML "
  <u> <p></p> </u>
  <u> <p></p> </u>
  <u> <p></p> </u>
"

$ bundle exec ruby temp.rb 
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body>
<u> </u><p></p> 
  <u> </u><p></p> 
  <u> </u><p></p> 
</body></html>
```

**Comment by flavorjones** [comment]
Nokogiri does not do this explicitly; the underlying parser (libxml2 in your case, I'm guessing) parses the markup this way.

It looks like libxml2 has an implicit rule that <p> tags can't be present within a <u> tag, and so closes the currently-open <u> tag when it spots the opening <p> tag.

If you look at https://github.com/GNOME/libxml2/blob/master/HTMLparser.c#L1085 you'll see a line like:

```
static const char * const htmlStartClose[] = {
...
"p",		"p", "head", "h1", "h2", "h3", "h4", "h5", "h6", FONTSTYLE, NULL,
...
```

which tells us which tags should be closed when a <p> opening tag is seen. The macro FONTSTYLE contains "u" among other tags: 

```
#define FONTSTYLE "tt", "i", "b", "u", "s", "strike", "big", "small"
```

and so the logic in `htmlCheckAutoClose` will cause an open <u> to be closed when it sees a <p>.
