### ISSUE TITLE
attribute.value = attribute.value changes output

### ISSUE THREAD

**Issue by bananarne** [sparklemotion/nokogiri#1800]
**What problems are you experiencing?**
doing attribute.value = attribute.value makes it "boolean"/"minimized"

**What's the output from `nokogiri -v`?**
# Nokogiri (1.8.4)
    ---
    warnings: []
    nokogiri: 1.8.4
    ruby:
      version: 2.4.4
      platform: x86_64-linux
      description: ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/usr/local/lib64/ruby/gems/2.4.0/gems/nokogiri-1.8.4/ports/x86_64-pc-linux-gnu/libxml2/2.9.8"
      libxslt_path: "/usr/local/lib64/ruby/gems/2.4.0/gems/nokogiri-1.8.4/ports/x86_64-pc-linux-gnu/libxslt/1.1.32"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      libxslt_patches: []
      compiled: 2.9.8
      loaded: 2.9.8

**Can you provide a self-contained script that reproduces what you're seeing?**
```
doc = Nokogiri::HTML('<!doctype html><html><body><img alt=""></body></html>')
doc.xpath('//*/@*').each { |a| a.value = a.value } # this is the code that changes something while it shouldn't?
doc.to_html
```

**Comment by flavorjones** [comment]
PR is in #1827, going through CI now.

**Comment by flavorjones** [comment]
I'll note that that PR works like this:

```ruby
#! /usr/bin/env ruby

require 'nokogiri'

doc = Nokogiri::HTML('<!doctype html><html><body><div bar="x" foo="x"></div></body></html>')
puts doc.to_html
# => <html><body><div bar="x" foo="x"></div></body></html>

doc.at_css("div").tap do |node|
  node.attributes['bar'].value = nil
  node.attributes['foo'].value = ""
end

puts doc.to_html
# => <html><body><div bar foo=""></div></body></html>
```

**Comment by flavorjones** [comment]
Will be fixed in the next release, hopefully in the next few days.

**Comment by bananarne** [comment]
Wow, thanks!

**Comment by brendon** [comment]
Sorry to slightly resurrect this. Sometimes it's desirable to add a new attribute that has no value. The only way I can see to do this is:

```
node['bar'] ='anything'
node.attributes['bar'].value = nil
```

Is there a better way?

**Comment by flavorjones** [comment]
@brendon The second way you mention is what Nokogiri currently supports:

```
node.attributes['bar'].value = nil
```

 If you're thinking that's not a great syntax to have to type, I agree with you, but it's what we're stuck with now for fear of introducing a backwards-incompatible change to the API.

FWIW, if this is something you do often, and you're up for it, I'd be open to a PR proposing a new method to do this. Something like `Node#add_empty_attribute` seems like a reasonable name.

**Comment by brendon** [comment]
Hi @flavorjones, that sounds like a great plan. Thank you for being open to that possibility. I'll let you know once I've done the PR.
