### ISSUE TITLE
How to validate a HTML snippet?

### ISSUE THREAD

**Issue by Qqwy** [sparklemotion/nokogiri#1806]
Hey all!

I want to use Nokogiri in my (rspec) tests to make sure that the HTML snippet that the `planga-ruby` gem builds, is indeed correct.

While I am able to use Nokogiri successfully to check for the existence/ommission of certain tags and their attributes, I also want to check in general if the HTML snippet is well-formed:

- Self-closing tags should not have a separate closing tag.
- No unclosed open tags.
- No malformed tags (like `<<div>` ).
- No tags that are unrecognized in HTML5 (like `<scriipt>`).

I tried to use `Nokogiri::HTML(snippet) {|config| config.strict}` but it did not give the required feedback.
Then I tried `Nokogiri::XML(snippet) {|config| config.strict}` which barks about trailing whitespace or something, or maybe it did not work properly because it is a snippet rather than a complete document.

So, I altered it to

`Nokogiri::XML.fragment(snippet) {|config| config.strict}` and `Nokogiri::HTML.fragment(snippet) {|config| config.strict}`, which again did not raise any errors on any of above cases.

How can Nokogiri be used to do this?

**Comment by flavorjones** [comment]
Can you please provide a specific snippet (or snippets) and tell us what warnings or errors you expect to see?

**Comment by flavorjones** [comment]
Closing.
