### ISSUE TITLE
tests failing on jruby 9.2.x

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1818]
see https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/jruby-9.2/builds/1

```
  1) Failure:
Nokogiri::HTML::TestDocumentFragment#test_error_propagation_on_fragment_parse_in_node_context_should_not_include_preexisting_errors [/tmp/build/4d9a0f57/nokogiri/test/html/test_document_fragment.rb:279]:
errors should be on the context node's document


  2) Failure:
Nokogiri::HTML::TestDocumentFragment#test_error_propagation_on_fragment_parse_in_node_context [/tmp/build/4d9a0f57/nokogiri/test/html/test_document_fragment.rb:270]:
errors should be on the context node's document
```

this doesn't appear to have been introduced into nokogiri recently; as far back as v1.8.0 this test fails on jruby-9.2.

**Comment by flavorjones** [comment]
OK, narrowed this down. in `XmlNode.java` function `in_context`, after parsing:

```
        System.out.println("MIKE: in_context: after parse: doc: " + docErrors);
        System.out.println("MIKE: in_context: length=" + docErrors.getLength());
        for (int i = 0; i < docErrors.getLength(); i++) {
            System.out.println("MIKE: in_context: error " + i + " " + docErrors.get(i));
        }
```

emits the following in jruby 9.2:

```
# 9.2
MIKE: in_context: after parse: doc: [#<Nokogiri::XML::SyntaxError: Tag hello invalid>]
MIKE: in_context: length=1
MIKE: in_context: error 0 null
```

but this in jruby 9.1.17.0:

```
MIKE: in_context: after parse: doc: [#<Nokogiri::XML::SyntaxError: Tag hello invalid>]
MIKE: in_context: length=1
MIKE: in_context: error 0 Tag hello invalid
```

that is, the `get` call returns `null` intead of the `SyntaxError`.

I have no idea why. Maybe @jvshahid can look at it tomorrow with me.

**Comment by flavorjones** [comment]
If anyone wants to take a look, I've pushed my debug trace branch `flavorjones-fix-jruby-9.2-failures`

**Comment by flavorjones** [comment]
Thanks as always, @jvshahid

**Comment by kares** [comment]
> that is, the `get` call returns `null` intead of the `SyntaxError`

that just seems weird - @jvshahid you should open up a ticket in JRuby

would take a closer look, at some point. 
your fix is definitely correct, `get` (doing `toJava`) shouldn't be used but still weird that this changed in JRuby -> except `nil` we shall no `get` anything else as **null**
