### ISSUE TITLE
use `xmlFreeNode` in xml_document.c to deallocate unparented nodes of all types

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1826]
As @stevecheckoway pointed out in https://github.com/sparklemotion/nokogiri/issues/1784 we might be able to avoid the case statement in `dealloc_node_i` and let `xmlFreeNode` take care of it for us.

This change would be a simplification, but I need to spend some time digging into:

* why we call xmlFreePropList on XML_ATTRIBUTE_NODEs 
* why we reparent most nodes back into the document instead of just freeing them.

Both of these features have been around since 2009 (1aa012a7) and I couldn't quickly find a clear reason why. Let's be careful here not to introduce an inadvertent memory leak.

**Comment by rubarb666** [comment]
So far so good🌆🌋🌀🌀🌀👙👙🌀🌀🌀

**Comment by flavorjones** [comment]
@rubarb666 can you explain a bit more about your comment?

**Comment by rubarb666** [comment]
]

**Comment by rubarb666** [comment]
@flavorjones 0


_Sent from my F8331 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flavorjones** [comment]
Hey! The memory leak suite has been back in effect since 6326caa3 (2023-12-10) so let's do this.

**Comment by flavorjones** [comment]
Yeah, so this didn't work -- it either leaked memory or segfaulted. I'm not going to spend time on figuring out why, though, since the code it would simplify is pretty minimal and hopefully more generally we can get rid of the nonstandard memory lifecycle of nodes (as Nick suggested in https://github.com/sparklemotion/nokogiri/issues/1952#issuecomment-2315993692).
