### ISSUE TITLE
Enhancement: Add #key? #value? predicates to Node

### ISSUE THREAD

**Issue by MatzFan** [sparklemotion/nokogiri#1838]
Was gonna PR you this with (of course) tests, but couldn't figure out why my new methods were not found and the whole `tmp` folder builds thing. And then I read [Y_U_NO_GEMSPEC](https://github.com/sparklemotion/nokogiri/blob/master/Y_U_NO_GEMSPEC.md).

**Rationale:**
Rubocop [bugs me](https://github.com/rubocop-hq/rubocop/issues/6215#issuecomment-446942753) that instead of iterating a `Nokogiri::XML::Node` using `.keys.include?` or `.values.include?` I should be using hash `#key?` or `#value?` methods. As Node is a hash-like object I figured why not add them.

**Code**
```
def  keys?(key)
  keys.include? key
end

def value?(value)
  values.include? value
end
```

**Comment by MatzFan** [comment]
@knu - quite right, just `#value?` missing. Re a use case, it is quite possible what I was trying to do can be accomplished a better way with existing functionality - FWIW I was trying to find a node with a particular attribute value. Nevertheless, I just felt it may be good practice for hash-like objects to, as far as possible, replicate Ruby's `Hash` interface.

Thanks @flavorjones think I figured it out, PR on the way.

**Comment by flavorjones** [comment]
Will be in v1.11.0.
