### ISSUE TITLE
ensure all DocumentFragment parse methods take ParseOptions and an options-configuration block

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1844]
See #1692 for the beginning of this work on HTML::DocumentFragment

See #1843 for a rebase of this work onto a modern `master`

See branch `1844-fragment-parse-options-overhaul` for the start of adding tests to HTML::DocumentFragment which are more thorough than the current test approach

Things I'd like to do as a result of this issue:

1) [net new behavior] have all XML::Document and HTML::Document underlying parse methods (e.g., `#read_io`, `#read_memory`) save the ParseOptions as a Document attribute, to make testing a bit easier
2) [partially implemented by #1692 ] have all XML::DocumentFragment and HTML::DocumentFragment parse methods take options and an options-configuration block
3) [fixes] ensure the JRuby impl matches the CRuby behaviors

**Comment by GreSuh** [comment]
Does this only apply for parsing http fragments or did I miss he change for  Nokogiri::XML::DocumentFragment.parse ?

**Comment by flavorjones** [comment]
@GreSuh thanks for asking this question. From the description above:

> 2. have all XML::DocumentFragment and HTML::DocumentFragment parse methods take options and an options-configuration block

Hope this response helps.

**Comment by flavorjones** [comment]
See #2399 for an updated version of this branch.
