### ISSUE TITLE
DocumentFragment > selector broken

### ISSUE THREAD

**Issue by MaxLustig** [sparklemotion/nokogiri#1853]
**What problems are you experiencing?**
Using DocumentFragment > selector produces undefined method error.

**What's the output from `nokogiri -v`?**
# Nokogiri (1.8.5)
    ---
    warnings: []
    nokogiri: 1.8.5
    ruby:
      version: 2.4.5
      platform: x86_64-darwin17
      description: ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin17]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/max/.gem/ruby/2.4.5/gems/nokogiri-1.8.5/ports/x86_64-apple-darwin17.7.0/libxml2/2.9.8"
      libxslt_path: "/Users/max/.gem/ruby/2.4.5/gems/nokogiri-1.8.5/ports/x86_64-apple-darwin17.7.0/libxslt/1.1.32"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Fix-nullptr-deref-with-XPath-logic-ops.patch
      - 0003-Fix-infinite-loop-in-LZMA-decompression.patch
      libxslt_patches: []
      compiled: 2.9.8
      loaded: 2.9.8

Note: also repros on 1.10.0

**Can you provide a self-contained script that reproduces what you're seeing?**
```
document = Nokogiri::HTML.fragment("<div class='klass'></div>")
nodes = document > "klass"
```

Results:
```
NoMethodError: undefined method `namespaces' for nil:NilClass
```

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by flavorjones** [comment]
See #2395 for a fix addressing the root cause here.
