### ISSUE TITLE
1.10.0 - jruby 9.13.0-p0 memory leak very fast.

### ISSUE THREAD

**Issue by WoolenWang** [sparklemotion/nokogiri#1873]
**Do not report Security Vulnerabilities here**

If you intend to report a security vulnerability, please do so at [HackerOne](https://hackerone.com/nokogiri) following the process detailed in [`SECURITY.md`](https://nokogiri.org/SECURITY.html). Do not report it through GitHub.

**Describe the bug**
Use jruby 9.13.0-p0 with nokogiri 1.10.0 parse the one xml file (pretty big file [4MB/ 3.5W line])

use xpath to locate the node. and then get very fast memory leak

![image](https://user-images.githubusercontent.com/3388253/53221067-ac9bbc00-36a2-11e9-8fd5-3962a84f4abf.png)

![image](https://user-images.githubusercontent.com/3388253/53221096-d05f0200-36a2-11e9-9b2c-d442875a38dc.png)

![image](https://user-images.githubusercontent.com/3388253/53221161-2633aa00-36a3-11e9-91ce-4a0900082d1f.png)

**To Reproduce**

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "Node#css" do
    it "should find a div using chained classes" do
      if File.exist? index_file
          index_xml = Nokogiri::XML(File.open(index_file))
          all_file = index_xml.xpath("//compound[@kind='file']")
          all_file.each do |one_file|
            file_name = "#{one_file.xpath('./name').first.inner_text}"
            if CODE_LOGGER_CFG['doxygen']['filter_header']
              if file_name =~ /.*\.(h|hpp|h\+\+|hh)$/
                next
              end
            end
            one_file_hash = {
              :name => file_name,
              :id => one_file['refid'],
              :functions => {}
            }
            file_hash[one_file['refid']] = one_file_hash
            functions = one_file.xpath('./member[@kind="function"]')
            functions.each do |one_func|
              one_func_hash = {
                :name => "#{one_func.xpath('./name').first.inner_text}",
                :id => one_func['refid'],
                :file => one_file_hash
              }
              function_hash[one_func['refid']] = one_func_hash
            end
          end
      
      assert_equal 1, 1
    end
  end
end
```
[index.xml.docx](https://github.com/sparklemotion/nokogiri/files/2892455/index.xml.docx)

If you haven't included a test, please provide whatever code you can, the inputs if any, along with the output that you're seeing. We need to reproduce what you're seeing to be able to help.

**Expected behavior**

memory not leak.

**Environment**

nokogiri 1.10.0 - jruby 9.13.0-p0

**Additional context**

**Comment by WoolenWang** [comment]
it seems like the bug was bring back from #1792

the patch manager is very Disaster

**Comment by WoolenWang** [comment]
.... oh i figure it out , the logstash Entrance use the old version 1.8.5 nokogiri which has this problem, but the new 1.10.0 is fix, but the jruby has two version of nokogiri the logstash has gemfile lock to 1.8.5, make it to 1.10.0 the problem fix.

**Comment by jvshahid** [comment]
Sounds like you figured out what the problem was.  I will go ahead and close this issue.
