### ISSUE TITLE
Nokogiri parser removes child element from anchor tag and add them as a separate element.

### ISSUE THREAD

**Issue by rmishra-ror** [sparklemotion/nokogiri#1876]
Nokogiri parser removes child element of anchor tag and add them as a separate element.

**To Reproduce**

Here's an example:
```
parse_data =  Nokogiri::HTML.parse "<a> <table> <tr> </tr></table> </a>"

parse_data.to_html
"<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">\n<html><body>\n<a> </a><table> <tr> </tr>\n</table> </body></html>\n" 
```
So it removes table from anchor tag and add them as a separate tag`<a> </a><table> <tr> </tr>\n</table>`
It seems the problem is with parser(Nokogiri::HTML.parse) which not correctly add child element of anchor tag

Nokogiri version: "1.10.1"

**Comment by flavorjones** [comment]
Hi! Thanks for asking this question. The short answer is that Nokogiri is inheriting this behavior from the underlying parser, libxml2, and so there's unfortunately very little that nokogiri can easily do to modify this behavior. But read on for a suggestion (hint: nokogumbo).

The slightly longer version: the [HTML4 spec for an `A` anchor element](https://www.w3.org/TR/html4/struct/links.html#edef-A) defines only "[inline](https://www.w3.org/TR/html4/sgml/dtd.html#inline)" elements as valid subelements. If you recurse through the inline definition, I think you'll find that only these elements are valid within an `A` element:

* "abbr"
* "acronym"
* "applet"
* "b"
* "basefont"
* "bdo"
* "big"
* "br"
* "button"
* "cite"
* "code"
* "dfn"
* "em"
* "embed"
* "font"
* "i"
* "iframe"
* "img"
* "input"
* "kbd"
* "label"
* "map"
* "object"
* "q"
* "s"
* "samp"
* "script"
* "select"
* "small"
* "span"
* "strike"
* "strong"
* "sub"
* "sup"
* "textarea"
* "tt"
* "u"
* "var"

and this is in fact what [libxml2 does](https://github.com/GNOME/libxml2/blob/master/HTMLparser.c#L625).

Now you may be saying to yourself, "But [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) says that [`table` is a valid subelement](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content)!" and this is a very good point. I'll further note that Nokogiri, when run on JRuby (using the nekoHTML parsing library) does allow that `table` within the `a` element.

This can be traced to the fact that this was introduced in [the HTML5 spec](https://www.w3.org/TR/2011/WD-html-markup-20110525/a.html), which nekoHTML appears to at least partially support. However libxml2 does NOT support HTML5, and so Nokogiri-on-libxml2 inherits this limitation.

You may want to take a look at using [NokoGumbo](https://github.com/rubys/nokogumbo), which aims to bring HTML5 support to Nokogiri.

I hope this explanation helps?
