### ISSUE TITLE
Converts integer to float for google docs xlsx

### ISSUE THREAD

**Issue by rockandruby** [sparklemotion/nokogiri#1878]
When I create .xlsx file via google docs all my integer values transforms to float(e.g. 1 -> 1.0). However when I create file locally - it's ok. What's the reason of such behavior and how to avoid it?
P.S. tested with different nokogiri versions incluing fresh one.

**Comment by flavorjones** [comment]
Hi @rockandruby, thanks for asking this question.

Can you help me reproduce what you're doing and seeing? I'm afraid I don't quite understand the problem you're describing.

**Comment by rockandruby** [comment]
@rockandruby Ok, I'll try to explain. When I do
`f = ::File.open(path, 'rb') do |file|
        ::Nokogiri::XML(file)
      end
f.remove_namespaces!.xpath('/worksheet/sheetData/row/c').map do |cell_xml|
 p cell_xml.content
end
`
I get 1.0 instead 1 if cell contains integer. Actually I faced with that in another gem and as I worked it out the reason in Nokogiri. Here's a [link](https://github.com/roo-rb/roo/issues/498) to issue for this gem with explanation and table example.

**Comment by rockandruby** [comment]
@flavorjones don't know wether it helps but I compared 2 files(local and google doc table) and I found out that my local table with correct values has cells(for numbers) and each cell has attribute `#(Attr:someID { name = "t", value = "n" })` but cells in google docs don't have such attribute

**Comment by flavorjones** [comment]
Can you provide a sample file so I can reproduce what you're seeing, please?

**Comment by rockandruby** [comment]
@flavorjones u can get via [link](https://uploadfiles.io/bmgrf)

**Comment by flavorjones** [comment]
Sorry, I'm asking for a small, reproducible test case. If you could please provide that, it would mean that I can provide help more quickly. Something like this would be appropriate:

```
#! /usr/bin/env ruby

require "nokogiri"

XML = <<EOXML
<root>
  <element>contents</element>
</root>
EOXML

doc = Nokogiri::XML.parse(XML)
puts doc.xpath("/root/element").text # => "contents"
```

Thanks.

**Comment by flavorjones** [comment]
OK, specifically, the xlsx file you pointed me to is a zip file:

```
$ unzip ex.xlsx 
Archive:  ex.xlsx
  inflating: xl/drawings/drawing1.xml  
  inflating: xl/worksheets/sheet1.xml  
  inflating: xl/worksheets/_rels/sheet1.xml.rels  
  inflating: xl/sharedStrings.xml    
  inflating: xl/styles.xml           
  inflating: xl/workbook.xml         
  inflating: xl/_rels/workbook.xml.rels  
  inflating: _rels/.rels             
  inflating: [Content_Types].xml     
```

I can try to run your ruby script on it, but I get this far:

```
#! /usr/bin/env ruby

require "nokogiri"

path = "#{ENV["HOME"]}/Downloads/ex.xlsx"

f = ::File.open(path, "rb") do |file| ::Nokogiri::XML(file) end
puts f.errors.inspect
```

and it emits the error:

```
[#<Nokogiri::XML::SyntaxError: 1:1: FATAL: Start tag expected, '<' not found>]
```

which is kinda what I expect from a binary file.

I need your help reproducing exactly what you're seeing. Otherwise I'll close this in a few days.

**Comment by rockandruby** [comment]
@flavorjones sorry for disturb, the first one - I gave u a wrong link(not raw xml file) and the other thing - seems it's an issue in roo gem, because it gives raw xml file to nokogiri with wrong type casting. So I'll proceed with roo. Thanks for assistance!
