### ISSUE TITLE
Cant install nokogiri gem. Please advice

### ISSUE THREAD

**Issue by acidphuck** [sparklemotion/nokogiri#1884]
"arm-linux-androideabi-clang -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.6.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.6.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.6.0 -I. -I/data/data/com.termux/files/usr/include    -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -fPIC  conftest.c  -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -march=armv7-a -landroid-support -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby  -lm   -lc "
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"arm-linux-androideabi-clang -I/data/data/com.termux/files/usr/include/ruby-2.6.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.6.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.6.0 -I. -I/data/data/com.termux/files/usr/include    -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -fPIC    -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main() {return 0;}
/* end */

"pkg-config --exists libxml-2.0"
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
| pkg-config --libs libxml-2.0
=> "Warning: linker: Unsupported flags DT_FLAGS_1=0x8\n"
=> "-L/data/data/com.termux/files/usr/lib -lxml2\n"
"arm-linux-androideabi-clang -o confteI/data/data/com.termux/files/usr/include/ruby-2.6.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.6.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.6.0 -I. -I/data/data/com.termux/files/usr/include    -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -fPIC  -g -DXP_UNIX conftest.c  -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -march=armv7-a -landroid-support -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
-L/data/data/com.termux/files/usr/lib -lxml2 -lm   -lc "
clang-7: error: no such file or directory: 'WARNING:'
clang-7: error: no such file or directory: 'linker:'
clang-7: error: no such file or directory: 'Unsupported'
clang-7: error: no such file or directory: 'flags'
clang-7: error: no such file or directory: 'DT_FLAGS_1=0x8'
sh: 2: -L/data/data/com.termux/files/usr/lib: not found
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

package configuration for libxml-2.0 is not found
have_package: checking for libxml-2.0... -------------------- yes

--------------------

**Comment by andrewmcodes** [comment]
Don’t want to open a new issue that duplicates this but wish some more context had been added here as I am also experiencing this issue. 

I’m on the latest version of MaOS and cannot bundle or gem install the latest release of this gem with a very similar error. Happy to provide more info if needed.

**Comment by flavorjones** [comment]
Hi, I wish you had used the template offered by github for installation issues. There are both helpful hints in it and it asks the appropriate questions for us to be able to start helping you.

It appears you're trying to build Nokogiri on an ARM platform of some sort; can you please answer the questions from the issue template:

---

**Have you read and followed the advice in the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

**What is the complete output of `gem install`?**

Please make sure the escape the file contents with triple-backticks.


**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

Please make sure the escape the file contents with triple-backticks.


**What operating system are you using?**

Are you using Linux, MacOS, Windows, a BSD variant, or something else entirely?

If MacOS, please note the version of XCode you have installed.

If Linux, please include the output of `uname -a` and the contents of `/etc/lsb-release`.

If Windows, please note whether you're installing the precompiled gems, or compiling yourself with DevKit. Also please note the version of RubyInstaller you've installed.

**Comment by flavorjones** [comment]
@andrewmcodes your issue most certainly was not the same as the OP if you are on MacOS. The issue you probably ran into, and that the linked issue addresses, was fixed in v1.9.0 (see #1812 and #1813).

**Comment by andrewmcodes** [comment]
@flavorjones gotcha! My issue popped up after upgrading some brew packages and then trying to bundle v1.10.2 but looks like it was just bc of my local setup
