### ISSUE TITLE
Documentation is misleading

### ISSUE THREAD

**Issue by akimd** [sparklemotion/nokogiri#1902]
Hi,

The documentation (https://nokogiri.org/rdoc/Nokogiri/XML/ParseOptions.html) reads:

```ruby
Nokogiri.XML('<content>Chapter 1</content', options: Nokogiri::XML::ParseOptions.new((1 << 0) | (1 << 1)))
```

but that won't work since the declaration of XML is:

```ruby
# Parse an XML document using the Nokogiri::XML::Reader API.  See
# Nokogiri::XML::Reader for mor information
def Reader string_or_io, url = nil, encoding = nil, options = ParseOptions::STRICT
```
so one has to pass nil, nil, and then the options.

Cheers.

**Comment by flavorjones** [comment]
Hi! Thanks for reporting this. These docs were introduced in #1451 and I'll be happy to merge #1903 this morning to fix it.

**Comment by flavorjones** [comment]
Updated: https://nokogiri.org/rdoc/Nokogiri/XML/ParseOptions.html
