### ISSUE TITLE
Nokogiri on SketchUp 2019

### ISSUE THREAD

**Issue by jeremieberthillot** [sparklemotion/nokogiri#1905]
Hello,

I work to create plugins on SketchUp. Recently SketchUp launch a new version (SketchUp 2019) and Nokogiri can’t be use. When I load the bundle, an error is writing:
**Error: #<LoadError: cannot load such file -- racc/parser.rb>**

It happened each time I’m using the line:  « require ‘nokogiri’ »

SketchUp use ruby 2.5.1, I use Nokogiri 1.10.1.

I try to change the file “parser.rb” in your plugin. I add a dependency on my “racc” plugin in 1.4.9 instead of just require”parser.rb” and it’s work but it’s hard to deploy my plugin with this solution because I can’t choose any version of “racc” plugins in SketchUp.

I would like to ask you if one day Nokogiri will be compatible with SketchUp 2019 or if I do something wrong on the install and the way of use for Nokogiri.

If you have any idea, thanks :)

**Comment by flavorjones** [comment]
Hi! Thanks for asking this question.

I'm curious to know more about the version of Ruby you're running. What platform are you on? How did you install that version of Ruby?

Racc is part of Ruby's standard library, and so it's curious to me that you're seeing this error. I suspect that Ruby is not completely installed on your machine, or that parts of your stdlib have been deleted.

**Comment by jeremieberthillot** [comment]
The version ruby is 2.5.1. I didnt install something, all is containt in SketchUp pro 2019 and my script is load on the start of SketchUp. I try to reinstall the entire app but the problem is still the same.
I have no control of the version of ruby in this app and on every standard library. 

Old version of SketchUp run on oldversion of ruby and I could use Nokogiri 1.8.2 so it worked. But know I have to upgrade the version because Nokogiri doesn't run on Ruby 2.5.1, so I tried Nokogiri 1.9 or 1.10.1 but none of theme worked.

**Comment by flavorjones** [comment]
OK - you may want to file a bug report with SketchUp, I'm not familiar with that software, asking them to ensure they've included `racc` in their distirbution. For example, when I look at my `rvm`-installed ruby, I see:

```
 $ find /home/flavorjones/.rvm/src/ruby-2.5.3/lib/racc
/home/flavorjones/.rvm/src/ruby-2.5.3/lib/racc
/home/flavorjones/.rvm/src/ruby-2.5.3/lib/racc/rdoc
/home/flavorjones/.rvm/src/ruby-2.5.3/lib/racc/rdoc/grammar.en.rdoc
/home/flavorjones/.rvm/src/ruby-2.5.3/lib/racc/parser.rb
```

As a potential workaround, you may want to try using a gem version of `racc` using whatever SketchUp provides as a gem installer (e.g., `/path/to/sketchup/bin/gem install racc`).

Please let me know how you get on, I'll leave this open for now.

**Comment by jeremieberthillot** [comment]
Racc is include in SketchUp I found it, but when I call  ` require 'parser.rb' ` in my code I always have this message : **Error: #<LoadError: cannot load such file -- parser.rb>**
I think SketchUp cant found the path

I ll modify myself the path on Nokogiri plugin but for the deployment and for the futur version that complicated everything.

**Comment by flavorjones** [comment]
@jeremieberthillot Thanks for following up. Again, this appears to be something wrong with SketchUp's ruby environment; it's not the responsibility of any gem to manage the calling process's load path.

I'd suggest submitting a bug report to SketchUp showing that the following ruby script:

```ruby
require 'racc/parser'
```

fails, and show the error message.
