### ISSUE TITLE
Included files referenced by relative paths in xml schemas can't be found.

### ISSUE THREAD

**Issue by jmcnevin** [sparklemotion/nokogiri#191]
I'm trying to validate a document against the ONIX 2.1 reference schema, which includes the following lines...

```
<xs:include schemaLocation="ONIX_BookProduct_CodeLists.xsd"/>
<xs:include schemaLocation="ONIX_XHTML_Subset.xsd"/>
```

When running the validation, I receive this error:

```
Nokogiri::XML::SyntaxError: Element '{http://www.w3.org/2001/XMLSchema}include': Failed to load the document 'ONIX_BookProduct_CodeLists.xsd' for inclusion.
```

All of the schema files reside in the same directory.  I see a closed ticket that says this problem has been fixed, but I'm still not having any luck on my end.

**Comment by iwan** [comment]
Good! Works for me!
Thnx
