### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by Trenix25** [sparklemotion/nokogiri#1928]
I can no longer build nokogiri which has destroyed my copy of Metasploit.  It used to work, but then nokogiri was updated, and now it doesn't.  The requested output is very lengthy so I have uploaded it to https://github.com/Trenix25/Termux/tree/master/Metasploit/nokogiri/ for inspection.  gcc has no trouble finding C library functions.

**What operating system are you using?**
Android Linux 5.0.0 (Lollipop) Intel Atom (x86)(i686) CPU.
There is absolutely nothing wrong with using a tablet running Lollipop 5.0, nothing.

If Linux, please include the output of `uname -a` and the contents of `/etc/lsb-release`.
Information not available.  /etc/lsb-release: No such file or directory.

**Comment by Trenix25** [comment]
I tried to mention this, but it got deleted.  I'm using Termux v0.73.

**Comment by Trenix25** [comment]
I tried to mention this, but it got deleted.  I'm using Termux v0.73.
I just went and gathered this...
/data/data/com.termux/files/home >> uname -a
Linux localhost 3.10.20-x86_64_moor #1 SMP PREEMPT Tue Apr 19 18:19:38 CST 2016 x86_64 Android
/data/data/com.termux/files/home >>

**Comment by flavorjones** [comment]
Hi, let me start by noting that termux isn't a supported platform for Nokogiri, but I'll do my best to help.

Looking at the [log file you linked to above](https://github.com/Trenix25/Termux/blob/master/Metasploit/nokogiri/issue.txt), this looks to me like you may not have Ruby installed correctly (or fully). The contents of `mkmf.log` are telling:

```
/data/data/com.termux/files/home >> cat /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/x86-linux/2.6.0/nokogiri-1.10.4/mkmf.log
"i686-linux-android-clang -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.6.0/i686-linux-android -I/data/data/com.termux/files/usr/include/ruby-2.6.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.6.0 -I. -I/data/data/com.termux/files/usr/include    -march=i686 -msse3 -mstackrealign -mfpmath=sse -Oz -fstack-protector-strong -fPIC  conftest.c  -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -Wl,-z,relro,-z,now -landroid-support -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby  -lm   -lc "
/data/data/com.termux/files/usr/bin/i686-linux-android-ld: /data/data/com.termux/files/usr/lib/libruby.so: undefined reference to `fchown@LIBC'
/data/data/com.termux/files/usr/bin/i686-linux-android-ld: /data/data/com.termux/files/usr/lib/libruby.so: undefined reference to `raise@LIBC'
/data/data/com.termux/files/usr/bin/i686-linux-android-ld: /data/data/com.termux/files/usr/lib/libruby.so: undefined reference to `__strlcpy_chk@LIBC'
/data/data/com.termux/files/usr/bin/i686-linux-android-ld: /data/data/com.termux/files/usr/lib/libruby.so: undefined reference to `select@LIBC'

...

clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

The code being compiled is part of the `mkmf` system examining your system. Here it is simply trying to link a trivial `main` against the ruby runtime and failing to find C libraries.

This isn't anything Nokogiri has control over at installation time. If you previously had success installing Metasploit, I'd recommend looking at the version of Ruby you used then, and are using now. I'd also suggest asking this question in a more general Ruby forum, or a Termux forum.
