### ISSUE TITLE
Race condition in Nokogiri::CSS::Parser

### ISSUE THREAD

**Issue by ioquatix** [sparklemotion/nokogiri#1935]
```
#!/usr/bin/env ruby

require 'nokogiri'

parser = Nokogiri::CSS::Parser.new

puts Nokogiri::CSS::Parser.cache_on?

threads = []

threads << Thread.new do
	Nokogiri::CSS::Parser.without_cache do
		sleep 1
	end
end

threads << Thread.new do
	sleep 0.1
	
	Nokogiri::CSS::Parser.without_cache do
		sleep 2
	end
end

threads.each(&:join)

puts Nokogiri::CSS::Parser.cache_on?

# Prints false, but should be true.
```

**Comment by flavorjones** [comment]
Thanks for reporting, I'll take a look as soon as I can.

**Comment by ioquatix** [comment]
The reason why it happens is because there is no locking around `@cache_on` which is shared global state:

https://github.com/sparklemotion/nokogiri/blob/24a2b5eb862fab0c63b68c00c67e6a47745e5bfe/lib/nokogiri/css/parser_extras.rb#L34-L39

**Comment by ioquatix** [comment]
The solution is to use `Thread.current[:nokogiri_cache_on]` and assign to it directly rather than trying to read/write shared mutable state.

**Comment by flavorjones** [comment]
@ioquatix Can I ask how you found this bug? The `#without_cache` method was added in 8b9daef, and is only used in the `Slop` node decorator ... are you using `#without_cache` for something? I'm just curious.

You're right, of course, and we'll fix it.

**Comment by ioquatix** [comment]
I found it by manual analysis supported by some tools like grep and custom scripts to narrow down on potential issues.
