### ISSUE TITLE
Nokogiri empty brackets while parsing

### ISSUE THREAD

**Issue by MinosFenn** [sparklemotion/nokogiri#1946]
Hi everyone,
I am creating a scrapper to analyse the consumer reviews of the following website: influenster
https://www.influenster.com/reviews/toblerone-swiss-milk-chocolate
Following this tutorial: https://www.youtube.com/watch?v=b3CLEUBdWwQ
(I already did a scraper for rentalcar following this method that was working perfectly fine!)
To do so, I am using Ruby and Nokogiri and other gems as you will see below.

So I have been writing the following piece of code:

> require 'nokogiri'
> require 'httparty'
> require 'byebug'
> require 'pry'
> require 'csv'
> require 'json'
> require 'open-uri'
> require 'useragent'
>  
> string = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.56 Safari/536.5'
> user_agent = UserAgent.parse(string)
> user_agent.browser
> # => 'Chrome'
> user_agent.version
> # => '19.0.1084.56'
> user_agent.platform
> # => 'Macintosh'
>  
> def scraper
>    url = "https://www.influenster.com/reviews/toblerone-swiss-milk-chocolate/"
>    unparsed_page = HTTParty.get(url)
>    parsed_page = Nokogiri::HTML(unparsed_page)
>    byebug
> end
>  
> scraper

Then, I wanted to try it and see in my terminal if I could access the “**div.review-text**” but unfortunately, **it sends me back an empty bracket** as you can see:
![terminal capture](https://user-images.githubusercontent.com/45685449/69736957-cc7d7600-1133-11ea-9a12-765bf5882c10.PNG)

I also noticed that when I ask for my parsed_page that the message contain:

> "Attention Required! | Cloudflare">]>, #<Nokogiri::XML::Text:0x2ae7aa421fb4 "\n">, #<Nokogiri::XML::Element:0x2ae7aa421d34 name="meta" attributes=[#<Nokogiri::XML::Attr:0x2ae7aa421bcc name="name" value="captcha-bypass">

So my first thought is that I am blocked by a captcha but when I go on the website I am never asked to fulfill a captcha… 
So I wanted to ask you if you had any idea of how I could solve that or even just where could be the problem coming from.

Thank you very much in advance,
Have a nice day,
Simon

**Comment by flavorjones** [comment]
Hi - Thanks for asking this question, and I'm sorry you're having trouble scraping this data.

Unfortunately, I'm not sure the Nokogiri maintainers can help -- Nokogiri is doing its job here!

I also am seeing the captcha information in the returned page, and so you'll likely need to use a different strategy to load this page. You may want to look into a more complete browser agent like Mechanize or even Selenium.

My advice would be to ask these questions on a more general Ruby or web-scraping forum. Sorry we can't be of more help.
