### ISSUE TITLE
Nokogiri online testing

### ISSUE THREAD

**Issue by EddieOne** [sparklemotion/nokogiri#1947]
Is there an online tool like jsfiddle for nokogiri? It would be helpful to test the project's API via a website. In my case, it's not super easy for me to test the project I'm working on.

**Comment by flavorjones** [comment]
Thanks for asking this question. At the moment, there are no plans to make an online version of Nokogiri available.

**Comment by flavorjones** [comment]
Can I help me understand why Nokogiri is hard to test for you? We're always trying to make Nokogiri easier to use.

**Comment by EddieOne** [comment]
The example is a different language, it shows the advantage though. https://jsfiddle.net/ the jquery API is very easy to test online. It gives a big advantage for projects like CheerioJs compared to Nokogiri.

**Comment by flavorjones** [comment]
I googled "sandbox ruby" and found this site, which appears to support Nokogiri: https://repl.it/languages/ruby

**Comment by flavorjones** [comment]
@EddieOne I'm curious if the site I mentioned above meets your needs.

**Comment by EddieOne** [comment]
Nice find, thank you
