### ISSUE TITLE
error in install TermUX

### ISSUE THREAD

**Issue by skycat2216** [sparklemotion/nokogiri#1951]
my goodness,i just want change my phone to Aiden's one

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/ext/nokogiri    /data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0 -r ./siteconf20191202-31542-1e27xgm.rb extconf.rb            checking if the C compiler accepts ... *** extconf.rb failed ***                                            Could not create Makefile due to some reason, probably lack of necessary                                    libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
        from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:532:in `with_werror'
        from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
      from extconf.rb:138:in `nokogiri_try_compile'         from extconf.rb:162:in `block in add_cflags'          from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:643:in `with_cflags'                            from extconf.rb:161:in `add_cflags'                   from extconf.rb:416:in `<main>'                                                                     To see why this extension failed to compile, please ch
eck the mkmf.log which can be found here:             
  /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/aarch64-linux/2.6.0/nokogiri-1.10.5/mkmf.lo
g                                                                                                           extconf failed, exit code 1                           ~

**Comment by flavorjones** [comment]
Hi - termux isn't a supported platform for nokogiri, but I'll do what I can to help.

Have you looked at the previous termux issues or asked this question on a termux forum?

* https://github.com/sparklemotion/nokogiri/issues/1939
* https://github.com/sparklemotion/nokogiri/issues/1928
* https://github.com/sparklemotion/nokogiri/issues/1816
* https://github.com/sparklemotion/nokogiri/issues/1884
* https://github.com/sparklemotion/nokogiri/issues/1739

**Comment by skycat2216** [comment]
yes,but is looks a little different,
My system is try to find something is not C lib(mkmf says lot of things never been define) 
also,i found something not exist in gem lib,maybr that's the answer

**Comment by skycat2216** [comment]
i give up
i gonna to switch my OS to arch

**Comment by larskanis** [comment]
For me the following sequence worked on a fresh termux:
```
$ pkg install ruby clang make pkg-config libxslt
$ gem inst nokogiri -- --use-system-libraries
```

**Comment by flavorjones** [comment]
@larskanis thanks, I'll add that to the installation docs on nokogiri.org.

**Comment by flavorjones** [comment]
see https://nokogiri.org/tutorials/installing_nokogiri.html#termux

**Comment by MrS0n1CTF** [comment]
> my goodness,i just want change my phone to Aiden's one
> 
> current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/ext/nokogiri /data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0 -r ./siteconf20191202-31542-1e27xgm.rb extconf.rb checking if the C compiler accepts ... *** extconf.rb failed *** Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers. Check the mkmf.log file for more details. You may need configuration options.
> 
> Provided configuration options: --with-opt-dir --without-opt-dir --with-opt-include --without-opt-include=${opt-dir}/include --with-opt-lib --without-opt-lib=${opt-dir}/lib --with-make-prog --without-make-prog --srcdir=. --curdir --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME) --help --clean /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first. from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile' from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:532:in `with_werror' from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile' from extconf.rb:138:in `nokogiri_try_compile' from extconf.rb:162:in `block in add_cflags' from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:643:in `with_cflags' from extconf.rb:161:in `add_cflags' from extconf.rb:416:in `
> 
> ' To see why this extension failed to compile, please ch
> eck the mkmf.log which can be found here:
> /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/aarch64-linux/2.6.0/nokogiri-1.10.5/mkmf.lo
> g extconf failed, exit code 1 ~

Hi! 🛡️ I noticed you're having trouble with Metasploit dependencies on Termux. 🛠️ I've developed a professional toolkit specifically to automate environment repairs (Nokogiri/Gumbo fixes) and provide a stable workspace for MSF on Android. 🚀 It might be exactly what you need! Check it out here: https://github.com/MrS0n1CTF/MSF-repair_Toolkit 🦅✨"

**Comment by MrS0n1CTF** [comment]
> see https://nokogiri.org/tutorials/installing_nokogiri.html#termux

Hi! 🛡️ I noticed you're having trouble with Metasploit dependencies on Termux. 🛠️ I've developed a professional toolkit specifically to automate environment repairs (Nokogiri/Gumbo fixes) and provide a stable workspace for MSF on Android. 🚀 It might be exactly what you need! Check it out here: https://github.com/MrS0n1CTF/MSF-repair_Toolkit 🦅✨"

**Comment by MrS0n1CTF** [comment]
> For me the following sequence worked on a fresh termux:
> 
> ```
> $ pkg install ruby clang make pkg-config libxslt
> $ gem inst nokogiri -- --use-system-libraries
> ```

Hi! 🛡️ I noticed you're having trouble with Metasploit dependencies on Termux. 🛠️ I've developed a professional toolkit specifically to automate environment repairs (Nokogiri/Gumbo fixes) and provide a stable workspace for MSF on Android. 🚀 It might be exactly what you need! Check it out here: https://github.com/MrS0n1CTF/MSF-repair_Toolkit 🦅✨"
