### ISSUE TITLE
OS Catalina I get an error

### ISSUE THREAD

**Issue by orest-kostiuk** [sparklemotion/nokogiri#1955]
after bundle install

ruby 2.0.0

./siteconf20191208-743-6s5n6b.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... yes
checking if the C compiler accepts
-Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using system libraries.
libxml2 version 2.6.21 or later is required!
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/orestkostuk/.rvm/rubies/ruby-2.0.0-p648/bin/ruby
	--help
	--clean
	--use-system-libraries
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
	--with-libxml-2.0-config
	--without-libxml-2.0-config
	--with-pkg-config
	--without-pkg-config
	--with-xslt-dir
	--without-xslt-dir
	--with-xslt-include
	--without-xslt-include=${xslt-dir}/include
	--with-xslt-lib
	--without-xslt-lib=${xslt-dir}/lib
	--with-libxslt-config
	--without-libxslt-config
	--with-exslt-dir
	--without-exslt-dir
	--with-exslt-include
	--without-exslt-include=${exslt-dir}/include
	--with-exslt-lib
	--without-exslt-lib=${exslt-dir}/lib
	--with-libexslt-config
	--without-libexslt-config

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/Users/orestkostuk/Vertalab/promoter2/path/ruby/2.0.0/extensions/x86_64-darwin-19/2.0.0/nokogiri-1.6.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/orestkostuk/Vertalab/promoter2/path/ruby/2.0.0/gems/nokogiri-1.6.5 for
inspection.
Results logged to
/Users/orestkostuk/Vertalab/promoter2/path/ruby/2.0.0/extensions/x86_64-darwin-19/2.0.0/nokogiri-1.6.5/gem_make.out

An error occurred while installing nokogiri (1.6.5), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.5' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  savon was resolved to 2.10.1, which depends on
    akami was resolved to 1.2.2, which depends on
      nokogiri

**Comment by shairyar** [comment]
I am also getting an error on Catalina https://stackoverflow.com/questions/59245644/not-able-to-install-nokogiri-because-of-gcc-on-macos-catalina

Could you share the content of your log file as well?

**Comment by flavorjones** [comment]
Hi @Ckazo4nik, thanks for asking this question, and I'm sorry you're having troubles.

The error message you posted contains this line:

> libxml2 version 2.6.21 or later is required!

Which tells me that you either have an old version of libxml2 installed on your system, or that Nokogiri is having trouble finding libxml2. Unfortunately I cannot tell you more without you answering the questions in the issue template (which you seem to have ignored). Please answer these questions:

-----

**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

**What is the complete output of `gem install`?**

Please make sure to escape the file contents with triple-backticks.


**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

Please make sure to escape the file contents with triple-backticks.


**What operating system are you using?**

Are you using Linux, MacOS, Windows, a BSD variant, or something else entirely?

If MacOS, please note the version of XCode you have installed.

If Linux, please include the output of `uname -a` and the contents of `/etc/lsb-release`.

If Windows, please note whether you're installing the precompiled gems, or compiling yourself with DevKit. Also please note the version of RubyInstaller you've installed.

**Comment by benhunt29** [comment]
I solved this previously on Mojave by following the accepted answer [here](https://stackoverflow.com/questions/52514791/after-upgrading-to-macos-mojave-gem-update-is-failing). But since upgrading to Catalina, I've hit it again and the old answer doesn't work as the header installer referenced in the old solution doesn't exist in Catalina (or I just can't find it).

I had the `libxml2` error as well, but the warning went away after re-installing command line tools from xcode.  Now on Catalina I just get a generic error:

**Complete output of `gem install`**
```gem install nokogiri -v '1.6.6.2' --source 'https://rubygems.org/'
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /Users/ben/.rvm/gems/ruby-2.2.2@blender/gems/nokogiri-1.6.6.2/ext/nokogiri
/Users/ben/.rvm/rubies/ruby-2.2.2/bin/ruby -I /Users/ben/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0 -r ./siteconf20200120-86805-1g35wdf.rb extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
-----
The file "/usr/include/iconv.h" is missing in your build environment,
which means you haven't installed Xcode Command Line Tools properly.

To install Command Line Tools, try running `xcode-select --install` on
terminal and follow the instructions.  If it fails, open Xcode.app,
select from the menu "Xcode" - "Open Developer Tool" - "More Developer
Tools" to open the developer site, download the installer for your OS
version and run it.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/ben/.rvm/rubies/ruby-2.2.2/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ben/.rvm/gems/ruby-2.2.2@blender/extensions/x86_64-darwin-18/2.2.0/nokogiri-1.6.6.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ben/.rvm/gems/ruby-2.2.2@blender/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /Users/ben/.rvm/gems/ruby-2.2.2@blender/extensions/x86_64-darwin-18/2.2.0/nokogiri-1.6.6.2/gem_make.out

```
**What are the complete contents of the `mkmf.log` file generated during the failed installation?**
```
"gcc -o conftest -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/x86_64-darwin18 -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/backward -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe  conftest.c  -L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl/lib -L. -L/Users/ben/.rvm/rubies/ruby-2.2.2/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl/lib      -lruby.2.2.0  -lpthread -lgmp -ldl -lobjc  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/x86_64-darwin18 -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/backward -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe    -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main() {return 0;}
/* end */

"gcc -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/x86_64-darwin18 -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/backward -I/Users/ben/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe  -Wno-error=unused-command-line-argument-hard-error-in-future   -Werror -c conftest.c"
error: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Werror,-Wunknown-warning-option]
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main() {return 0;}
/* end */
```

**What operating system are you using?**
MacOS (Catalina)
Xcode 11.3.1

**Comment by benhunt29** [comment]
as a followup to my previous post, I tried running it using system libraries and specifying the libxml2 dirs but after examining a line in the new `mkmf.log` that said `libxml/xmlversion.h` not found, I came upon [this post](https://github.com/mitmproxy/mitmproxy/issues/68) which suggested a symlink.

`sudo ln -s /usr/local/opt/libxml2/include/libxml2/libxml /usr/local/include/libxml`

This seemed to work

**Comment by flavorjones** [comment]
I'm seeing now that the version of Nokogiri being asked about here is quite old - @orest-kostiuk  asking about Nokogiri 1.6.5 and @benhunt29 about 1.6.6.2. The Ruby versions are 2.0.0 and 2.2.2 -- also out of support.

We've done work to make Nokogiri install and run on modern operating systems, but these changes will not be backported. Please upgrade! We cannot support folks with modern operating systems and old versions of Nokogiri.
