### ISSUE TITLE
Installation difficulties - Nokogiri fails to install, mkmf.log is very short

### ISSUE THREAD

**Issue by joelmclean** [sparklemotion/nokogiri#1956]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**
Yes. I have tried installing different versions of Nokogiri, and have completely blown away ruby and rvm and reinstalled them. I even tried sudoing, even though I know I shouldn't, and re-reinstalled ruby and rvm afterwards.

**What is the complete output of `gem install`?**
```
[joel.mclean@lin-kil-o-125 selfhelp]$ gem install nokogiri -v '1.8.0' --source 'https://rubygems.org/'
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /home/joel.mclean/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.0/ext/nokogiri
/home/joel.mclean/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20191212-25855-4fig88.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/joel.mclean/.rvm/rubies/ruby-2.4.1/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/home/joel.mclean/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /home/joel.mclean/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
        from /home/joel.mclean/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
        from /home/joel.mclean/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /home/joel.mclean/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:407:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/joel.mclean/.rvm/gems/ruby-2.4.1/extensions/x86_64-linux/2.4.0/nokogiri-1.8.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/joel.mclean/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.0 for inspection.
Results logged to /home/joel.mclean/.rvm/gems/ruby-2.4.1/extensions/x86_64-linux/2.4.0/nokogiri-1.8.0/gem_make.out
```

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**
It's very short!?
```
[joel.mclean@lin-kil-o-125 selfhelp]$ cat /home/joel.mclean/.rvm/gems/ruby-2.4.1/extensions/x86_64-linux/2.4.0/nokogiri-1.8.0/mkmf.log
" -o conftest -I/home/joel.mclean/.rvm/rubies/ruby-2.4.1/include/ruby-2.4.0/x86_64-linux -I/home/joel.mclean/.rvm/rubies/ruby-2.4.1/include/ruby-2.4.0/ruby/backward -I/home/joel.mclean/.rvm/rubies/ruby-2.4.1/include/ruby-2.4.0 -I.    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format  -fPIC  conftest.c  -L. -L/home/joel.mclean/.rvm/rubies/ruby-2.4.1/lib -Wl,-R/home/joel.mclean/.rvm/rubies/ruby-2.4.1/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,'/../lib' -Wl,-R'/../lib' -lruby  -lpthread -ldl -lcrypt -lm   -lc "
sh: -o: command not found
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**What operating system are you using?**
Centos7: uname -a output below
`Linux lin-kil-o-125.micron21.com 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`cat /etc/centos-release: CentOS Linux release 7.7.1908 (Core)`

I'm using RVM, with Ruby 2.4.1
`ruby -v: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`
`rvm -v: rvm 1.29.9 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`

My main issue is that all the other similar failures suggest simply installing a bunch of devel/requirements, which I think I have everything:
```
[joel.mclean@lin-kil-o-125 selfhelp]$ sudo yum install libxslt-devel libxml2-devel zlib-devel ruby-devel gcc gmp-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.as24220.net
 * epel: fedora.melbourneitmirror.net
 * extras: mirror.as24220.net
 * updates: centos.mirror.ausnetservers.net.au
Package libxslt-devel-1.1.33-4.1.cf.rhel7.x86_64 already installed and latest version
Package libxml2-devel-2.9.10-1.2.cf.rhel7.x86_64 already installed and latest version
Package zlib-devel-1.2.7-18.el7.x86_64 already installed and latest version
Package ruby-devel-2.0.0.648-36.el7.x86_64 already installed and latest version
Package gcc-4.8.5-39.el7.x86_64 already installed and latest version
Package 1:gmp-devel-6.0.0-15.el7.x86_64 already installed and latest version
Nothing to do
```

I'm stumped. I'm sure this is something really obvious but I'm out of ideas!

**Comment by flavorjones** [comment]
Hi @joelmclean, thanks for asking these questions and sorry you're having problems.

The command being run appears in your mkmf.log file as ` -o conftest ...` but in reality should be a compiler command line. For comparison, my local mkmf.log file starts with:

```
"gcc -o conftest -I/home/flavorjones/.rvm/rubies/ruby-2.6.3/include/ruby-2.6.0/x86_64-linux -I/home/flavorjones/.rvm/rubies/ruby-2.6.3/include/ruby-2.6.0/ruby/backward ...
```

Nokogiri's build system will use the same compiler that was used to compile your ruby executable, unless you have the `CC` environment variable set (see https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L407-L411).

I can reproduce what you're seeing if I run `CC="" gem install nokogiri`. Is it possible that you've got this env var set to `""` or something similar?

**Comment by joelmclean** [comment]
I did notice that, but I didn't have enough nous to work out whether missing the compiler was just an artifact of what was captured in the log.

Digging into this specifically further, I think I've nailed it down to the fact that "gcc" (/usr/bin/gcc) had bad permissions somehow (root:root:750, instead of root:root:755 which is meant to be the default)

executing `which gcc` told me that I had no gcc in path, but when I checked gcc and gcc-c++ and all the other good requirements they were all there. 

executing `gcc --version` gave a permission denied problem (I'm running as a non-root user), and seemingly fixing the permissions has now allowed me access to the compiler.

I'm sure I made trouble for myself in earlier stages by using the compiler with `sudo` which you can't do with `bundle install`. (nor should you, I am told)

Thanks for your advice, @flavorjones . Bundle install worked today, and I learned a lot.

**Comment by flavorjones** [comment]
Thanks for closing the loop here, I'm glad you were able to work it out.
