### ISSUE TITLE
Add support for Ruby-2.7 on Windows

### ISSUE THREAD

**Issue by francesco-loreti** [sparklemotion/nokogiri#1961]
```
ERROR:  Error installing nokogiri:
        The last version of nokogiri (>= 0) to support your Ruby & RubyGems was 1.10.7. Try installing it with `gem install nokogiri -v 1.10.7`
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.dev.
```

**Comment by flavorjones** [comment]
@francesco-loreti thanks for opening this issue. You don't mention it, but I'm going to assume that you're trying to install the "fat binary" gem that contains precompiled DLLs (and not compiling the vanilla gem using DevKit).

I'm planning to ship a version of Nokogiri later this week that contains precompiled DLLs for Ruby 2.7 (rake-compiler v1.0.9 was released last week for this support). Hold tight until then! And thanks for your patience as we try to ensure the best user experience we can for you.

**Comment by francesco-loreti** [comment]
Thanks you for your job!!!
The instructions for installation on Windows using DevKit, linked into your [Wiki page](https://nokogiri.org/tutorials/installing_nokogiri.html#windows), not working. There is other way?
Regards and Good Year!!!

**Comment by flavorjones** [comment]
Hi - we don't provide instructions for compiling with DevKit, because it's a rather advanced topic. If you've never used DevKit before, I'd advise waiting until support arrives in nokogiri v1.11.0.

If you've used DevKit before and you're seeing something odd, please open a new github issue and make sure to answer the questions in the issue template. Thank you!

**Comment by larskanis** [comment]
Happy new year for everyone who counts according to the Gregorian calendar!

@francesco-loreti There are two ways to install nokogiri as non binary gem on Windows:
```sh
gem install nokogiri --platform=ruby
```
installs nokogiri with builtin libxml sources and
```sh
ridk exec pacman -S mingw-w64-x86_64-libxslt
gem install nokogiri --platform=ruby -- --use-system-libraries
```
installs nokogiri with MSYS2 libraries. We need to update the install instructions for Windows. They are outdated.

@flavorjones I already updated the pull request for fat binary gems to ruby-2.7 here: https://github.com/sparklemotion/nokogiri/pull/1571 But I didn't release rake-compiler-dock-1.0.0 yet. This will follow in the next days. So keep calm and sparkle on!

**Comment by larskanis** [comment]
@flavorjones https://github.com/sparklemotion/nokogiri/pull/1571 is finished from my point of view. My proposal is, that we merge it, but don't push linux fat binary gems for now. That would safe me the time to update both (Windows and Windows+Linux) branches. What do you think?

**Comment by slonopotamus** [comment]
I also hit this issue when trying to run `bundle install` for [skoji/gepub](https://github.com/skoji/gepub) on Ruby 2.7 + Windows. I'm not sure how "fat binary" applies in this case since gepub just [declared a runtime dependency on nokogiri](https://github.com/skoji/gepub/blob/master/gepub.gemspec#L18).

**Comment by gencer** [comment]
Any news on this? I can install via cmd but its need to be installed via `bundle` which is failing...

**Comment by HarshdipD** [comment]
Hi, is this issue fixed? I don't want to downgrade to ruby 2.6 just because this issue...

**Comment by slonopotamus** [comment]
> is this issue fixed?

![image](https://user-images.githubusercontent.com/92637/73397075-c18dc000-42f3-11ea-8e3d-6ddc36aa8671.png)

> I don't want to downgrade to ruby 2.6 just because of this issue...

If you don't want to do something, just don't do it.

**Comment by flavorjones** [comment]
@larskanis I agree, I'll merge #1571. Thanks for your patience.

@HarshdipD @slonopotamus @francesco-loreti this will be fixed when Nokogiri v1.11.0 is shipped. Please watch the [milestone](https://github.com/sparklemotion/nokogiri/milestone/18) for progress, but I'm hopeful this will happen in the next few weeks.

**Comment by flavorjones** [comment]
OK, the work done by @larskanis on #1571 has been merged onto master. I will try to cut a release candidate today so windows users will have _something_ to use on Ruby 2.7.

**Comment by flavorjones** [comment]
v1.11.0.rc1 has been released with precompiled native libraries for Windows and Ruby 2.7. Please give it a whirl and let me know if you have any problems. I'll close this in a few days unless someone has issues.

**Comment by francesco-loreti** [comment]
> Nokogiri release candidate [v1.11.0.rc1](https://github.com/sparklemotion/nokogiri/releases/tag/v1.11.0.rc1) has been released with precompiled native libraries for Windows and Ruby 2.7. Please give it a whirl and let me know if you have any problems.

Work!! Thanks you for your great job!!!

**Comment by Shahrukhhashmi** [comment]
Hi - I'm still getting the same error after running the command "gem install nokogiri -v 1.11.0.rc1 --prerelease". However, the rc version is installed, but the error is same.

**Comment by larskanis** [comment]
@Shahrukhhashmi Can you please open a new issue with all necessary details?

**Comment by Shahrukhhashmi** [comment]
@larskanis Thanks for writing back. Sure, I can do that but, the issue and details are same as mentioned by @francesco-loreti. 
ERROR:  Error installing nokogiri:
The last version of nokogiri (>= 0) to support your Ruby & RubyGems was 1.10.7. Try installing it with `gem install nokogiri -v 1.10.7` nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.dev.

**Comment by larskanis** [comment]
@Shahrukhhashmi You shouldn't put a space before "prerelease". This should work:
```sh
gem inst nokogiri --pre
```

**Comment by Shahrukhhashmi** [comment]
@larskanis I have also ran this command. Nokogiri RC is successfuly installed, but when I try to install rails, it producess the same error.

**Comment by malohtie** [comment]
any update ? 

```
ERROR:  Error installing nokogiri:
        The last version of nokogiri (= 1.10.8) to support your Ruby & RubyGems was 1.10.8. Try
installing it with `gem install nokogiri -v 1.10.8`
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.0.
```

**Comment by slonopotamus** [comment]
@malohtie You do not need to ask if there's any update. That triggers a email to everyone who subscribed to this issue. You can just read comments and see that there were no messages in last 8 days.

Also, @larskanis explicitly asked to open new issue if there are still some problems.

**Comment by malohtie** [comment]
@slonopotamus i saw the updates, i still got problem when trying to install it even with pre release , also you can unsubscribe if you don't want to see a simple email
cheers

**Comment by flavorjones** [comment]
All - this issue is driving whether the prerelease, v1.11.0.rc1, can be installed and run on windows. It can, and is closed. Subsequent comments above indicate that Gemfiles and/or other gems' dependencies are still on 1.10.8. That's not something the Nokogiri project can solve, please report upstream as necessary.

**Comment by flavorjones** [comment]
PLEASE NOTE: Nokogiri v1.10.10 supports Ruby 2.7 on Windows.
