### ISSUE TITLE
Fix code coverage calculation

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1965]
Sometime between Sept 8 and Sept 15, 2019, code coverage broke and is being calculated before tests are actually run.

**Comment by flavorjones** [comment]
You can see this at https://codeclimate.com/github/sparklemotion/nokogiri/trends/test_coverage_total

![image](https://user-images.githubusercontent.com/8207/71828450-5e03d000-3070-11ea-867b-a7201a9ee74f.png)

**Comment by flavorjones** [comment]
I've determined this is an issue in Hoe v3.18.0 and higher. Sending a PR.

**Comment by flavorjones** [comment]
PR submitted at https://github.com/seattlerb/hoe/pull/102

**Comment by flavorjones** [comment]
Pinning hoe to v3.17.x temporarily fixes this:

![image](https://user-images.githubusercontent.com/8207/73177821-f7f1f200-40dd-11ea-963a-a39c36a66f8d.png)

**Comment by zenspider** [comment]
Released! Unpin, update, and you should be good.

**Comment by flavorjones** [comment]
Unpinned in f56cbc6 on 2020-02-10. Closing.
