### ISSUE TITLE
XmlNodeSet.to_s return value conflicts with JRuby 9.2.9

### ISSUE THREAD

**Issue by headius** [sparklemotion/nokogiri#1968]
XmlNodeSet defines a `to_a` method here: https://github.com/sparklemotion/nokogiri/blob/84a554f0c7b78bf82bdd928d27ae038cf29dd0bb/ext/java/nokogiri/XmlNodeSet.java#L395

JRuby originally defined a superclass `to_a` method (in RubyBasicObject) that did not take a `ThreadContext` parameter. However in JRuby 9.2.9, we made another set of changes to pass `ThreadContext` through more methods, including the `to_a` in RubyBasicObject. This added a new signature `RubyArray to_a(ThreadContext)` with the old `RubyArray to_a()` left deprecated.

As a result, the method in XmlNodeSet no longer compiles because it attempts to return a more general type (IRubyObject as opposed to RubyArray).

**Comment by headius** [comment]
Originally reported in a comment to #1253.

**Comment by flavorjones** [comment]
PR merged, will be fixed in v1.11.0.
