### ISSUE TITLE
What Exceptions Does Nokogiri::HTML::Document.parse Raise

### ISSUE THREAD

**Issue by sshaw** [sparklemotion/nokogiri#1973]
Hi, [the docs](https://rdoc.info/gems/nokogiri/Nokogiri/HTML/Document#parse-class_method) don't say what errors this raises. I'd like to assume that means none but I gotta think an `IOError`, `SystemCallError`, `Nokogiri::SyntaxError`, something 🤷‍♂️

**Comment by sshaw** [comment]
Oh I see it's using [`DEFAULT_HTML`](https://rdoc.info/gems/nokogiri/Nokogiri/XML/ParseOptions) but so no `Nokogiri::*` errors but _maybe_ IO or other?

**Comment by flavorjones** [comment]
Hi @sshaw, thanks for asking this question. Ruby doesn't require methods to declare what exceptions might be raised, and so I find it's rare that libraries will completely document everything that might happen.

If the underlying parsing engine returns an unexpected error code, Nokogiri should raise a standard `RuntimeError` with the error message from the library as payload. You might also get a `Nokogiri::XML::SyntaxError`.

Can I ask what you're trying to do that you're asking for a canonical list of exceptions that might be returned? I may be able to provide a more direct answer.

**Comment by sshaw** [comment]
Hello,

>  so I find it's rare that libraries will completely document everything that might happen.

Yes, me too. It's unfortunate 😿

> ... what you're trying to do that you're asking for a canonical list of exceptions that might be returned? 

Really this is basic question that everyone should have before using an API. But yes, Ruby....

In my case I'm stripping HTML tags from a document and showing only the text (after some additional processing). 

If the parsing fails then no big deal, we can show the text and process it _with_ the HTML. But doing something like 

```rb
begin
  text = Nokogiri::HTML(html).text
rescue => e
  text = html
end
```

If a bit problematic as maybe there's a `NoMethodError` or some bug in Nokogiri that I'm swallowing, amongst other things.

**Comment by flavorjones** [comment]
The `#parse` methods should only return a `Nokogiri::SyntaxError`, and even then only if it's a blank document, or if you're parsing in `strict` mode.

Beyond that, you will get a `RuntimeError` if libxml2 encounters any sort of fatal error (like `malloc` failing to allocate memory), or for that matter I suppose you could get something like a `NoMemoryError` from Ruby itself.

I feel like providing a canonical list of potential exceptions has pretty low value unless you're able and willing to write different handlers to respond to them in different ways.

Hope this helps.

**Comment by sshaw** [comment]
🤝
