### ISSUE TITLE
Multi-line strikeout preview and post differ

### ISSUE THREAD

**Issue by FabrizioMarana** [sparklemotion/nokogiri#1975]
**Describe the bug**
As per https://meta.discourse.org/t/multi-line-strikethrough-not-covering-quotes/64808/12 raising a bug here as this is still not fixed after 2 years *over there* and I can't seem to find this bug here on this repository's issue list.  **¯\\_(ツ)_/¯**

As Discourse is using Nokogiri, the preview and the eventual post over there are not matching up as Nokogiri does not Reconstruct the active formatting elements of the `<s>Strikethrough</s>` tags 

**To Reproduce**
https://meta.discourse.org/t/multi-line-strikethrough-not-covering-quotes/64808

**Expected behavior**
for:
```
<s>Strikethrough begin
Strikethrough end</s>
```
to actually display strikethrough over 2 lines instead of just the first one.

**Environment**

Please paste the output from `nokogiri -v` here, escaped by triple-backtick.

I'm an and-user bringing this to your attention.  Please follow up with https://meta.discourse.org/u/sam

**Additional context**

<s>It's just bloody annoying</s> Cosmetic, User Interface only.  **0:-)**

**Comment by SamSaffron** [comment]
The feature request here is to implement non normative 12.2.9.2 in nokogiri per: 

https://html.spec.whatwg.org/multipage/parsing.html#misnested-tags:-b-p-/b-/p

I am betting github has the same issue? or it somehow leaves html un-normoalized

<b>
test

test
</b>

**Comment by flavorjones** [comment]
Hi all, thanks for opening this issue.

The behavior being described is inherited from the underlying parsing/serialization library -- either libxml2 or xerces. There's no easy way for Nokogiri to change the behavior of how these libraries work, and in fact the Nokogiri core maintainers have identified doing so as an anti-goal.

I'd invite you to submit this feedback upstream to libxml2 or xerces. Sorry I can't be of more help here.

**Comment by FabrizioMarana** [comment]
Mike,

Thanks for the feed-back.  As I'm just a dumb end-user now who hasn't
written a single line of C in the last 15 years, could you please provide
me with a link to (libxml2 OR Xerces) and which one of the two I should try
first in your professional opinion?

Thanks for that last bit of help!

Fabrizio

**Comment by flavorjones** [comment]
Hi @FabrizioMarana, libxml2 is what's used by CRuby (Xerces-J is only used on JRuby) and so is the dominant xml parser used.

You can file an issue upstream at https://gitlab.gnome.org/GNOME/libxml2/issues

Good luck!

**Comment by FabrizioMarana** [comment]
Mike / Sam,

Issue #144 opened with libxml2 here:
https://gitlab.gnome.org/GNOME/libxml2/issues/144

Please feel free to subscribe your own e-mail address to this issue so
you'll see any follow-up for this issue yourself so you can:
* Re-open any closed bugs as "depends on upstream fix" for your respective
projects
* Close your side of the bug after the libxml project closes theirs and you
pull their respective changes downstream

so this tenacious end-user can finally have multi-line together with
another bunch of less tenacious end-users.

😂😎

Sam,

I'll post the link to the Discourse meta as well so other users (lots of ❤
in that conversation) are aware that upstream is going to fix it and it'll
dribble down *eventually*...

HTH,

Fabrizio

**Comment by FabrizioMarana** [comment]
Feed-back from the gnome project is:
> There weren't any major features added [to libxml2] in the last ~10 years and libxml2 is only barely maintained. Have a look at [Gumbo](https://github.com/google/gumbo-parser) if you need a HTML5 parser written in C with bindings for many languages like Ruby.

[Original here](https://gitlab.gnome.org/GNOME/libxml2/issues/144#note_700235)

**Comment by flavorjones** [comment]
@FabrizioMarana the nokogumbo project uses the gumbo parser on top of nokogiri, please try that if you like.

**Comment by FabrizioMarana** [comment]
My apologies for never replying to you until now.  :-(  *Thanks **yet again** for your wonderful help!*  :-)

My lord and master Sam is already using nokogumbo on the Discourse project for something else and will use this "in the next few months" which is still better than the 2 years this (cosmetic) bug has been open on their side.

*Live long and prosper!*
