### ISSUE TITLE
CI should use the rake-compiler-dock docker images to build gems for testing

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1984]
Currently CI uses the same docker images created for running tests, namely https://hub.docker.com/r/flavorjones/nokogiri-test/tags which are generated by the rake tasks in `tasks/docker.rb` and the Dockerfiles in `concourse/images`.

Specifically for JRuby, this means we're building our test gem on an image (`flavorjones/nokogiri-test:jruby-9.2`) that is different from the image used to build the final shipped gems (`larskanis/rake-compiler-dock-jruby` via `rake-compiler-dock`). That introduces an opportunity for inconsistent results, or for shipping a gem that doesn't work as tested.

Here are the docker images generated for use with rake-compiler-dock:

  * `larskanis/rake-compiler-dock-mri-x86-mingw32`
  * `larskanis/rake-compiler-dock-mri-x64-mingw32`
  * `larskanis/rake-compiler-dock-mri-x86-linux`
  * `larskanis/rake-compiler-dock-mri-x86_64-linux`
  * `larskanis/rake-compiler-dock-jruby`

I'd like to introduce testing for the native linux gems, and it seems like we should start using the `rake-compiler-dock` docker images in CI; and when (if?) we automate pushing gems to rubygems.org (#1845); as well as when (if?) we get windows tests running again (#1729).

---

Anyway, this issue is to drive the following work:

* Convert existing CI task `gem-test-java` (specifically `concourse/tasks/gem-test/gem-build-java.sh`) to build the gem using `larskanis/rake-compiler-dock-jruby` as the image.
  * Note: We should continue to run tests against that built gem using `flavorjones/nokogiri-test:jruby-X`.
* Add new CI tasks to build native linux gems using `larskanis/rake-compiler-dock-mri-x86{,_64}-linux`
  * Note: We should run the 64-bit tests in `flavorjones-nokogiri-test:mri-X`
  * Note: I'm not sure what image we should use for the 32-bit tests. Who still uses 32-bit OSes? Maybe we should just test the 64-bit gem and trust it as a proxy for the 32-bit gem.

/cc @larskanis for visibility

**Comment by larskanis** [comment]
> as well as when (if?) we get windows tests running again (#1729).

Windows tests [still succeed](https://ci.appveyor.com/project/larskanis/nokogiri) on Appveyor. But I noticed that Appveyor was disconnected from this repository. @flavorjones Could you please re-enable Appveyor until we have another CI solution for Windows? Badge icon and `appveyor.yml` are still in place.

> * I'm not sure what image we should use for the 32-bit tests. Who still uses 32-bit OSes? Maybe we should just test the 64-bit gem and trust it as a proxy for the 32-bit gem.

In `pg` gem we use [docker with multiarch images](https://github.com/ged/ruby-pg/blob/master/.travis.yml#L14-L18) to run on i386 and in `ffi`gem on [big endian powerpc and armhf](https://github.com/ffi/ffi/blob/master/.travis.yml#L29-L42). It allows to run on [many architectures](https://github.com/multiarch/qemu-user-static) as long as the operating system is Linux. Nevertheless I think it's enough to have 32 bit tests on Windows and binary gem tests (in addition to current CI).

**Comment by flavorjones** [comment]
@larskanis I've re-enabled the Appveyor webhook.

**Comment by flavorjones** [comment]
Just added jobs to the CI pipelines to build the test gems using rake-compiler-dock images, for jruby and 64-bit linux.

**Comment by flavorjones** [comment]
Remaining work on this issue: build a native 32-bit gem and test it.

**Comment by flavorjones** [comment]
Closing this ticket, remaining work on testing Linux native 32-bit gems will be done in https://github.com/sparklemotion/nokogiri/pull/2120
