### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by Shahrukhhashmi** [sparklemotion/nokogiri#1987]
Hi @larskanis , 
https://github.com/sparklemotion/nokogiri/issues/1961#issue-544187468

I'm still getting the same error after running the command "gem install nokogiri -v 1.11.0.rc1 --prerelease". However, the rc version is installed, but the error is same.

**Comment by taichi-ishitani** [comment]
I was able to install the RC release by this command.

```
gem install nokogiri -v 1.11.0.rc1
```

**Comment by Shahrukhhashmi** [comment]
@taichi-ishitani Nokogiri RC is successfuly installed, but when I try to install rails, it producess the same error.

**Comment by larskanis** [comment]
@Shahrukhhashmi Probably you need to enable nokogiri prerelease in your Gemfile. However for the next time you open a github issue: Please use the issue template and provide complete details!
