### ISSUE TITLE
precompiled gems should not have a runtime dependency on `mini_portile2`

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1991]
As pointed out by @voxik in #1983, any gems that are precompiled don't need `mini_portile2` and so we should remove that as a dependency from those gemspecs.

**Comment by larskanis** [comment]
It's already there #1989 !

**Comment by flavorjones** [comment]
I've merged in @larskanis's PR at #1989. Will be in v1.11.0.rc2.

**Comment by flavorjones** [comment]
Reopening, see my comments in #1989.

**Comment by flavorjones** [comment]
@larskanis Cross-posting here (from #1989) that the change in that PR doesn't seem to work for me. I don't see the `cross_compiling` block being executed when compiling native linux gems (though it _is_ executed when cross-compiling windows gems).

**Comment by larskanis** [comment]
I tested this but probably only with the Windows gems. I'll check this issue this weekend.
