### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by Kenyia** [sparklemotion/nokogiri#1994]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

**What is the complete output of `gem install`?**

Please make sure to escape the file contents with triple-backticks.

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

Please make sure to escape the file contents with triple-backticks.

**What operating system are you using?**

Are you using Linux, MacOS, Windows, a BSD variant, or something else entirely?

If MacOS, please note the version of XCode you have installed.

If Linux, please include the output of `uname -a` and the contents of `/etc/lsb-release`.

If Windows, please note whether you're installing the precompiled gems, or compiling yourself with DevKit. Also please note the version of RubyInstaller you've installed.

**Comment by zenspider** [comment]
Zero details. Please close.
