### ISSUE TITLE
GitHub Actions (three platforms), pre-compiled Windows gems

### ISSUE THREAD

**Issue by MSP-Greg** [sparklemotion/nokogiri#2010]
Don't know if there's an interest in Actions CI.  See:
https://github.com/MSP-Greg/nokogiri/runs/502131943
Three jobs each on Ubuntu, macOS, & Windows, total time 2:56.

Re pre-compiled Windows gems, some gems ship the dependency dll's and use Fiddle to load them.  This could possibly be done with any needed MSYS2 dll's not included with Ruby, allowing the Nokogiri gem to work without an MSYS2 installation...

**Comment by MSP-Greg** [comment]
See PR https://github.com/sparklemotion/nokogiri/pull/2011 for Actions update.

**Comment by flavorjones** [comment]
Closing to continue conversation at #2011.
