### ISSUE TITLE
installation fails on fedora via bundler

### ISSUE THREAD

**Issue by ai** [sparklemotion/nokogiri#2014]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

Yeap, I called `sudo dnf install -y rubygem-nokogiri` according to [Fedora section](https://nokogiri.org/tutorials/installing_nokogiri.html) in tutorial

**What is the complete output of `sudo dnf install -y rubygem-nokogiri`?**

```
➜ sudo dnf install -y rubygem-nokogiri
[sudo] password for ai: 
keybase                                         118 kB/s | 3.3 kB     00:00    
Dependencies resolved.
================================================================================
 Package              Arch       Version              Repository           Size
================================================================================
Installing:
 rubygem-nokogiri     x86_64     1.10.9-1.fc32        updates-testing     158 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 158 k
Installed size: 513 k
Downloading Packages:
rubygem-nokogiri-1.10.9-1.fc32.x86_64.rpm       908 kB/s | 158 kB     00:00    
--------------------------------------------------------------------------------
Total                                           392 kB/s | 158 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : rubygem-nokogiri-1.10.9-1.fc32.x86_64                  1/1 
  Running scriptlet: rubygem-nokogiri-1.10.9-1.fc32.x86_64                  1/1 
  Verifying        : rubygem-nokogiri-1.10.9-1.fc32.x86_64                  1/1 

Installed:
  rubygem-nokogiri-1.10.9-1.fc32.x86_64                                         

Complete!
```

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

When I call `bundle install` I have

```
…
Fetching nokogiri 1.10.9 (was 1.10.7)
Installing nokogiri 1.10.9 (was 1.10.7) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/ai/Dev/autoprefixer-rails/.bundle/ruby/2.7.0/gems/nokogiri-1.10.9/ext/nokogiri
/usr/bin/ruby -I /usr/share/rubygems -r
./siteconf20200323-204764-hjg6v0.rb extconf.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in
`require': cannot load such file -- did_you_mean (LoadError)
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in
`require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'

extconf failed, exit code 1

Gem files will remain installed in
/home/ai/Dev/autoprefixer-rails/.bundle/ruby/2.7.0/gems/nokogiri-1.10.9
for inspection.
Results logged to
/home/ai/Dev/autoprefixer-rails/.bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.10.9/gem_make.out

An error occurred while installing nokogiri (1.10.9), and
Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.9' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rails was resolved to 6.0.2.2, which depends on
    actioncable was resolved to 6.0.2.2, which depends on
      actionpack was resolved to 6.0.2.2, which depends on
        actionview was resolved to 6.0.2.2, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            nokogiri
```

Here is `nokogiri-1.10.9/gem_make.out` content:

```
current directory: /home/ai/Dev/autoprefixer-rails/.bundle/ruby/2.7.0/gems/nokogiri-1.10.9/ext/nokogiri
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20200324-80037-93a4dr.rb extconf.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- did_you_mean (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'

extconf failed, exit code 1
```

**What operating system are you using?**

Fedora 32 (I had the same problem on Fedora 31).

```
Linux foxbat 5.6.0-0.rc7.git0.2.fc32.x86_64 #1 SMP Mon Mar 23 18:38:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by flavorjones** [comment]
@ai Thanks for opening this issue, and sorry you're having issues.

The error you're getting is this:

```
.../kernel_require.rb:92:in `require': cannot load such file -- did_you_mean (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
```

Nokogiri doesn't use the `did_you_mean` gem, which tells me this might be an issue with how your Ruby is installed (`did_you_mean` is a vendored gem as of Ruby 2.4).

Are you able to install earlier versions of Nokogiri on this same system? (It looks like you previously had installed 1.10.7 successfully, and the changes between v1.10.7 and v1.10.9 aren't obviously going to result in this error.)

**Comment by ai** [comment]
Nokogiri 1.10.7 was from Fedora 30, where I was able to install Nokogiri with Bundle and some `*-devel` rpm packages.

The problem happens only with Bundler.

```
➜ gem install nokogiri
Fetching mini_portile2-2.4.0.gem
WARNING:  You don't have /home/ai/.gem/ruby/bin in your PATH,
	  gem executables will not run.
Successfully installed mini_portile2-2.4.0
Fetching nokogiri-1.10.9.gem
Building native extensions. This could take a while...
Successfully installed nokogiri-1.10.9
Parsing documentation for mini_portile2-2.4.0
Installing ri documentation for mini_portile2-2.4.0
Parsing documentation for nokogiri-1.10.9
Installing ri documentation for nokogiri-1.10.9
Done installing documentation for mini_portile2, nokogiri after 1 seconds
2 gems installed
```

**Comment by flavorjones** [comment]
OK, thanks for that additional context. If you can `gem install` nokogiri, then we've done our job, and I think this problem is not something we can solve within the gem packaging. I'd like to close it out unless you have objections.

The error message you're seeing seems to indicate the issue is with some combination of ruby, bundler, and your rubygems path ... that's just a guess, though. You may want to take a look at your `bundle config` to see if there are any odd settings (such as paths being overridden). If that fails to provide clues, then I think you should look for help on a more general bundler or ruby forum.

**Comment by ai** [comment]
> OK, thanks for that additional context. If you can gem install nokogiri, then we've done our job

My issue was not about my case, bug about the issue in the documentation.

The main use case for using Nokogiri (as I think) is installing it with `bundle install`. Docs that recommend install `.rpm` will not work for real use cases. At least, because Nokogiri in `Gemfile.lock` will be different from rpm version.

> The error message you're seeing seems to indicate the issue is with some combination of ruby, bundler, and your rubygems path

My config is very simple

```
➜ cat .bundle/config 
---
BUNDLE_PATH: ".bundle"
```

I have the same issue on different Fedora installations (Fedora 31 and Fedora 32) in different projects [Autoprefixer Rails](https://github.com/ai/autoprefixer-rails) and [rails-sass-image](https://github.com/ai/rails-sass-images).

It is not very likely that it is project’s configuration problem.

**Comment by flavorjones** [comment]
@ai I don't know how to help you at this point. Can you help me help you? What would you like me to do?

> issue in the documentation

I'd like to suggest that you're actually a much more practiced Fedora expert than the Nokogiri maintainers and we could really use your help to improve this documentation! I'd be very appreciative if you submitted a pull request to the docs repo (https://github.com/sparklemotion/nokogiri.org). Are you up for doing that work on behalf of other Fedora users?

> It is not very likely that it is project’s configuration problem.

OK, let's do this. I can install nokogiri on a fresh fedora 32 system with bundler:

```
nokogiri $ docker run -it fedora:32 /bin/bash
[root@c9a56fee68d3 /]# dnf install -qy @development-tools redhat-rpm-config ruby-devel zlib-devel
[root@c9a56fee68d3 /]# cat >> Gemfile <<EOF
> source "https://rubygems.org"
> gem "nokogiri"
> EOF
[root@c9a56fee68d3 /]# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your
bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/..................
Resolving dependencies...
Using bundler 2.1.2
Fetching mini_portile2 2.4.0
Installing mini_portile2 2.4.0
Fetching nokogiri 1.10.9
Installing nokogiri 1.10.9 with native extensions
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
[root@c9a56fee68d3 /]# nokogiri -v
# Nokogiri (1.10.9)
    ---
    warnings: []
    nokogiri: 1.10.9
    ruby:
      version: 2.7.0
      platform: x86_64-linux
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/usr/share/gems/gems/nokogiri-1.10.9/ports/x86_64-redhat-linux-gnu/libxml2/2.9.10"
      libxslt_path: "/usr/share/gems/gems/nokogiri-1.10.9/ports/x86_64-redhat-linux-gnu/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
[root@c9a56fee68d3 /]# 
```

So: if we can identify what's different between your system and project, and what I've demonstrated above, we can nail down what's going wrong during your `bundler install`. Any thoughts on what that might be?

**Comment by ai** [comment]
Thanks. This commit was what I talked about in this issue https://github.com/sparklemotion/nokogiri.org/commit/8ddf7c53c05ae16fe2e9e0c6424002331a5df8e8

Yeap seems like I was wrong and `did_you_mean` is my local problem. Sorry. But at least Fedora docs now better.

P. S. Nokogiri is an example of great support in open source. You are doing great work.

**Comment by ai** [comment]
Seems like Fedora’s Ruby stopped to work with `--path` option in Bundler. Bundler enables `BUNDLE_DISABLE_SHARED_GEMS` when you set local path with `--path`. And with `BUNDLE_DISABLE_SHARED_GEMS` Ruby can’t find it’s own gems in system folders.
