### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by mtrussell** [sparklemotion/nokogiri#2019]
I am on Windows and running Ruby 2.7.0.
I used RubyInstaller + Devkit 2.7.0-1

Also, everything was working fine with Ruby 2.6.5. I did uninstall it, remove it from the Path, and restart my machine before going forward with Ruby 2.7.0, however.

When running gem install rails I get this error:

`
ERROR:  Error installing rails: 
        The last version of nokogiri (>= 1.6) to support your Ruby & RubyGems was 1.10.9. 
        Try installing it with `gem install nokogiri -v 1.10.9` and then running the current command again
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.0.
When I run gem install nokogiri -v '1.10.9' I get the same exact error.
`

I have installed gem install nokogiri -v 1.11.0.rc1 --pre , but I'm still getting the same errors.

`
$ nokogiri -v 
# Nokogiri (1.11.0.rc1) 
    ---
    warnings: []
    nokogiri: 1.11.0.rc1
    ruby:
      version: 2.7.0
      platform: x64-mingw32
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x64-mingw32]       
      engine: ruby
    libxml:
      source: packaged
      patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      compiled: 2.9.10
      loaded: 2.9.10
    libxslt:
      source: packaged
      patches: []
      compiled: 1.1.34
      loaded: 1.1.34
`

So, I understand that Ruby 2.7.0 is later than 2.7.dev, but I have the nokogiri 1.11.0.rc1 gem installed. That should be good enough to install the Rails 6.0.2.2 gem, right?

**Comment by larskanis** [comment]
You can use `nokogiri-1.11.0.rc2` on RubyInstaller-2.7 but have to add something like this to your project `Gemfile` in order to use a prerelease gem:
```
  gem "nokogiri", "~> 1.10.pre"
```
Elsewise bundler will use stable releases of nokogiri only.

**Comment by mtrussell** [comment]
I tried installing nokogiri-1.11.0.rc2 also, but that didn't work either.

This error is thrown when I run 'gem install rails', so altering the Gemfile isn't something I can do without even having a rails project started.

**Comment by larskanis** [comment]
Plain `gem install rails` doesn't work with prereleases, but you can use a minimal `Gemfile` like this
```ruby
source "https://rubygems.org"
gem "nokogiri", "~>1.10.pre"
gem "rails"
```
and run `bundle install` to install Rails.

`rails new` then fails at the `bundle install` step, but you can add the nokogiri line to the newly created project and run `bundle install` and `rake webpacker:install` inside the project directory manuelly.

It should then work with the nokogiri prerelease binary gem for ruby-2.7. Also note the [rails notes in the RubyInstaller-FAQ](https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-rails).

**Comment by mtrussell** [comment]
Oh, I see. That's a great idea. I'll try that. I wasn't aware that rails wouldn't work with pre-releases. Thank you.

**Comment by flavorjones** [comment]
Closing! Please ping us if you need us.

**Comment by aenad** [comment]
hi, i have this error but this different 
Nokogiri (1.11.0.rc2)
    ---
    warnings: []
    nokogiri: 1.11.0.rc2
    ruby:
      version: 2.7.0
      platform: x64-mingw32
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x64-mingw32]
      engine: ruby
    libxml:
      source: packaged
      patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      compiled: 2.9.10
      loaded: 2.9.10
    libxslt:
      source: packaged
      patches: []
      compiled: 1.1.34
      loaded: 1.1.34
and the 
source "https://rubygems.org"
gem "nokogiri", "~>1.10.pre"
gem "rails" 
not work for me and show:
 'source' is not recognized as an internal or external command,
operable program or batch file.
please help me.
