### ISSUE TITLE
Implement '+' CSS selector

### ISSUE THREAD

**Issue by lem0nify** [sparklemotion/nokogiri#2021]
'x + y' CSS selector, which means "get y next to x" doesn't work in Nokogiri.

For example:
```Ruby
doc = Nokogiri::HTML(open("https://docs.microsoft.com/en-us/windows/win32/api/winuser/"))
puts doc.css('h2#functions + div')
```
doesn't output anything but should output a `<div class="table-scroll-wrapper">` which contains the table of functions from winuser.h Win32 header.

**Comment by flavorjones** [comment]
Hi @lem0nify, thanks for asking about this functionality.

Nokogiri has implemented the CSS `+` selector!
* see [tests for converting CSS queries into XPath queries](https://github.com/sparklemotion/nokogiri/blob/master/test/css/test_parser.rb#L223-L229)
* see [tests asserting on the results of CSS queries](https://github.com/sparklemotion/nokogiri/blob/master/test/css/test_css_integration.rb#L237-L254)

I haven't looked more deeply at your example of unexpected behavior, but is it possible that libxml2 is parsing that document differently than you expect (and differently from your browser) because it's malformed? And thus the resulting DOM is different enough to make this query return different results?

_/me types for a minute ..._

Looks like that's a reasonable conclusion, see:

```
$ nokogiri "https://docs.microsoft.com/en-us/windows/win32/api/winuser/"
Your document is stored in @doc...
2.7.0 :001 > puts @doc.errors
157:86: ERROR: Tag header invalid
174:65: ERROR: Tag nav invalid
227:323: ERROR: Tag nav invalid
254:385: ERROR: htmlParseEntityRef: expecting ';'
254:395: ERROR: htmlParseEntityRef: expecting ';'
333:116: ERROR: Tag nav invalid
336:89: ERROR: Tag section invalid
342:96: ERROR: Tag main invalid
350:105: ERROR: Tag time invalid
356:147: ERROR: Tag nav invalid
4030:165: ERROR: Tag nav invalid
4081:76: ERROR: Tag footer invalid
4104:28: ERROR: Tag svg invalid
4105:71: ERROR: Tag rect invalid
4106:76: ERROR: Tag rect invalid
4107:75: ERROR: Tag rect invalid
4108:75: ERROR: Tag rect invalid
4109:76: ERROR: Tag rect invalid
4110:75: ERROR: Tag rect invalid
4111:83: ERROR: Tag rect invalid
4112:83: ERROR: Tag rect invalid
4128:28: ERROR: Tag svg invalid
4129:71: ERROR: Tag rect invalid
4130:76: ERROR: Tag rect invalid
4131:75: ERROR: Tag rect invalid
4132:75: ERROR: Tag rect invalid
4133:76: ERROR: Tag rect invalid
4134:75: ERROR: Tag rect invalid
4135:83: ERROR: Tag rect invalid
4136:83: ERROR: Tag rect invalid
4152:28: ERROR: Tag svg invalid
4153:71: ERROR: Tag rect invalid
4154:76: ERROR: Tag rect invalid
4155:75: ERROR: Tag rect invalid
4156:75: ERROR: Tag rect invalid
4157:76: ERROR: Tag rect invalid
4158:75: ERROR: Tag rect invalid
4159:83: ERROR: Tag rect invalid
4160:83: ERROR: Tag rect invalid
4220:159: ERROR: Tag nav invalid
4223:108: ERROR: Tag nav invalid
4235:123: ERROR: Tag aside invalid
4245:109: ERROR: Tag footer invalid
4258:56: ERROR: ID theme-menu already defined
4268:28: ERROR: Tag svg invalid
4269:71: ERROR: Tag rect invalid
4270:76: ERROR: Tag rect invalid
4271:75: ERROR: Tag rect invalid
4272:75: ERROR: Tag rect invalid
4273:76: ERROR: Tag rect invalid
4274:75: ERROR: Tag rect invalid
4275:83: ERROR: Tag rect invalid
4276:83: ERROR: Tag rect invalid
4292:28: ERROR: Tag svg invalid
4293:71: ERROR: Tag rect invalid
4294:76: ERROR: Tag rect invalid
4295:75: ERROR: Tag rect invalid
4296:75: ERROR: Tag rect invalid
4297:76: ERROR: Tag rect invalid
4298:75: ERROR: Tag rect invalid
4299:83: ERROR: Tag rect invalid
4300:83: ERROR: Tag rect invalid
4316:28: ERROR: Tag svg invalid
4317:71: ERROR: Tag rect invalid
4318:76: ERROR: Tag rect invalid
4319:75: ERROR: Tag rect invalid
4320:75: ERROR: Tag rect invalid
4321:76: ERROR: Tag rect invalid
4322:75: ERROR: Tag rect invalid
4323:83: ERROR: Tag rect invalid
4324:83: ERROR: Tag rect invalid
```

If I'm incorrect in that conclusion, and you can provide a [small, self-contained way to reproduce this issue](https://nokogiri.org/tutorials/getting_help.html#step-3-bug-reporting), I'd be happy to look more deeply.

**Comment by lem0nify** [comment]
@flavorjones It's ok for me:
```cmd
C:\Users\lem0nify>nokogiri "https://docs.microsoft.com/en-us/windows/win32/api/winuser/"
Your document is stored in @doc...
irb(main):001:0>
```

Also, if I write like this:
```Ruby
doc = Nokogiri::HTML(open("https://docs.microsoft.com/en-us/windows/win32/api/winuser/"))
puts doc.css('h2#functions').first.next_element
```
instead of
```Ruby
doc = Nokogiri::HTML(open("https://docs.microsoft.com/en-us/windows/win32/api/winuser/"))
puts doc.css('h2#functions + div')
```
it works fine.

**Comment by flavorjones** [comment]
@lem0nify OK, I'm guessing that I didn't explain myself as clearly as I could, so I'll do work I was asking you to do to further investigate.

```ruby
#! /usr/bin/env ruby

require "nokogiri"
require "open-uri"

html = URI.open("https://docs.microsoft.com/en-us/windows/win32/api/winuser/")

doc = Nokogiri::HTML(html)

File.open("bar.html", "w") { |f| f.write doc.to_html(:indent => 2) }

doc.at_css("h2#functions").parent.children.map(&:name)
# => ["text",
#     "h1",
#     "text",
#     "ul",
#     "text",
#     "nav",
#     "text",
#     "comment",
#     "text",
#     "p",
#     "text",
#     "ul",
#     "text",
#     "h2",
#     "text",
#     "table",
#     "text",
#     "h2",
#     "text",
#     "table",
#     "text",
#     "h2",
#     "text",
#     "table",
#     "text",
#     "h2",
#     "text",
#     "table",
#     "text",
#     "comment",
#     "text"]

doc.css("h2#functions").first.next_element.name
# => "table"
```

The first query demonstrates that there are no sibling `div` elements.

The second query demonstrates that the code you wrote above (`css().first.next_element`) is a `table`, which is specifically not what the CSS query is searching for.

Nokogiri is performing CSS queries using `+` correctly, as far as I can tell; nothing in this issue demonstrates anything that would cause me to investigate further.

**Comment by lem0nify** [comment]
@flavorjones Ok I see.
But then why do I see `div` element in Chrome dev tools on this page? Do they really wrap `table` into `div` or not depending on the User-Agent? 🤔

**Comment by flavorjones** [comment]
From my comment above:

> is it possible that libxml2 is parsing that document differently than you expect (and differently from your browser) because it's malformed? And thus the resulting DOM is different enough to make this query return different results?

**Comment by flavorjones** [comment]
HTML and XML parsers, generally speaking, will parse _well-formed_ markup identically, because there's a spec. There is no spec and no formal W3C guidance on how to correct or "fix up" malformed markup, and so every parser seems to do it differently. You're likely seeing differences between your browser's parser and libxml2 (which is what Nokogiri uses). There's nothing we can easily do to change this behavior, unfortunately.

**Comment by flavorjones** [comment]
Oh, and one other possibility: libxml2 does not handle HTML5, and so there are likely to be differences between your browser's DOM and Nokogiri's DOM for any HTML5 document. If this is the case here, you may want to try using https://github.com/rubys/nokogumbo to parse the doc!

**Comment by flavorjones** [comment]
Oh! And one more possibility: this site looks like it might be using javascript to add wrapper elements to the DOM.

**Comment by flavorjones** [comment]
Confirmed: if I turn off javascript in my browser, the `<div>` element is not present (is not created).

I hope I've been able to help?

**Comment by lem0nify** [comment]
> Confirmed: if I turn off javascript in my browser, the `<div>` element is not present (is not created).
I hope I've been able to help?

Yes. Thank you!
