### ISSUE TITLE
Installation difficulties post retrospective. A request to update the tutorials documentation for Ubuntu.

### ISSUE THREAD

**Issue by DariaNico** [sparklemotion/nokogiri#2023]
**Mission Statement**
Before anything else, I've found a fix to my nokogiri installation problems. I just wanted to submit this issue to update the documentation to help others who might run into this specific installation problem.

I'm running a fresh install of Ubuntu 18.04 and was in the process of setting up my dev enviroment. When I tried to `gem install nokogiri` it failed, even after following everything in the installation tutorials docs. The solution that ended up working for me was having install libxml2 and libxslt by hand. In your docs, it says that nokogiri includes its own version of these, which didn't seem to be the case for me as I had to run

`sudo apt-get install libxml2-dev`
and
`sudo apt-get install libxslt-dev`

in order to get nokogiri to install on my computer.

The documentation doesn't really mention anything along these lines, so I was wondering if the documentation could be updated to include something along these lines?

Thank you!

**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**
Yes. I followed all the extra suggestions at the end and nokogiri still failed to install. I had to try a bunch of things, before coming upon a solution. I'm requesting an update of the installation documentation to include this possible fix for my problem.

**What is the complete output of `gem install`?**
As this is a post issue retrospective, I am unable to post the contents of the gem install during the failure. It had something to do with being unable to create the Makefile and providing a huge list of configuration options.

Please make sure to escape the file contents with triple-backticks.

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**
```
"gcc -o conftest -I/usr/share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/x86_64-linux -I/usr/share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/ruby/     
  ...backward -I/usr/share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -     
  ...Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-       
  ...noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-      
  ...packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-   
  ...attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  conftest.c  -L. -L/usr/share/rvm/rubies/ruby-2.7.0/lib -Wl,-rpath,/usr/  
  ...share/rvm/rubies/ruby-2.7.0/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -       
  ...lruby  -lm   -lc "
  checked program was:
  /* begin */
  1: #include "ruby.h"
  2: 
  3: int main(int argc, char **argv)
  4: {
  5:   return !!argv[argc];
  6: }
  /* end */
  
  "gcc -I/usr/share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/x86_64-linux -I/usr/share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/ruby/backward -I/usr/ 
  ...share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-  
  ...declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-       
  ...function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat - 
  ...Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-
  ...attribute=noreturn -Wunused-variable  -fPIC    -Werror -c conftest.c"
  checked program was:
  /* begin */
  1: #include "ruby.h"
  2: 
  3: int main() {return 0;}
  /* end */
  
  "pkg-config --exists libxml-2.0"
  package configuration for libxml-2.0 is not found
  have_package: checking for libxml-2.0... -------------------- no

  --------------------
  
  "pkg-config --exists libxslt"
  package configuration for libxslt is not found
  have_package: checking for libxslt... -------------------- no
  
  --------------------
  
  "pkg-config --exists libexslt"
  package configuration for libexslt is not found
  have_package: checking for libexslt... -------------------- no
  
  --------------------
  
  "gcc -E -I/usr/share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/x86_64-linux -I/usr/share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0/ruby/backward -I/  
  ...usr/share/rvm/rubies/ruby-2.7.0/include/ruby-2.7.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-       
  ...function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-   
  ...cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-    
  ...compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format - 
  ...Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  -g -DXP_UNIX -O3 -Wall -Wcast-qual -Wwrite-strings -Wmissing-noreturn -Winline  conftest.  
  ...c -o conftest.i"
  conftest.c:3:10: fatal error: libxml/xmlversion.h: No such file or directory
   #include <libxml/xmlversion.h>
            ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  checked program was:
  /* begin */
  1: #include "ruby.h"
  2: 
  3: #include <libxml/xmlversion.h>
  /* end */

```
Please make sure to escape the file contents with triple-backticks.

**What operating system are you using?**
Ubuntu 18.04.4 LTS

Are you using Linux, MacOS, Windows, a BSD variant, or something else entirely?

Linux nyango 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
If Linux, please include the output of `uname -a` and the contents of `/etc/lsb-release`.

**Comment by flavorjones** [comment]
@DariaNico Sorry you had problems installing nokogiri.

The code path you're seeing in your mkmf.log file (using `pkg-config`) should only be invoked if you've set options asking Nokogiri to compile and link against system libraries. So I'm a little confused.

Can you post the output of `gem env` to see if, perhaps, you've got your gem environment set up to use system libraries?

If you're using bundler, can you post the output of `bundler env` for the same reason?

**Comment by flavorjones** [comment]
Installation docs have been rewritten since this post, and the OP hasn't responded. Closing.
