### ISSUE TITLE
Please add support for versions of RUby 2.7.1.X on Windows RubyInstaller

### ISSUE THREAD

**Issue by hpigula** [sparklemotion/nokogiri#2025]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

**What is the complete output of `gem install`?**

ERROR:  Error installing nokogiri:
        ```The last version of nokogiri (= 1.10.9) to support your Ruby & RubyGems was 1.10.9. Try installing it with `gem install nokogiri -v 1.10.9`
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.1.83.
```
**What are the complete contents of the `mkmf.log` file generated during the failed installation?**
None it's package instal problem


**What operating system are you using?**
Windows 10 Home x64

rubyinstaller-devkit-2.7.1-1-x64.exe

Please add support for this Ruby versions

**Comment by flavorjones** [comment]
Hi, sorry you're having problems. Please install the v1.11.0.rc2 prerelease which supports Ruby 2.7 on windows. See #1961, #2017, #2019, etc. for more information.
