### ISSUE TITLE
Ignoring nokogiri-1.10.4 because its extensions are not built.

### ISSUE THREAD

**Issue by ashleymader** [sparklemotion/nokogiri#2026]
**Describe the bug**

Constant error "Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4"

**Expected behavior**

After I run this  `gem pristine nokogiri --version 1.10.4`

`Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored nokogiri-1.10.4`

Expect error to resolve

**Environment**

`nokogiri -v
# Nokogiri (1.10.9)
    ---
    warnings: []
    nokogiri: 1.10.9
    ruby:
      version: 2.6.1
      platform: x86_64-darwin19
      description: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin19]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/ashleymader/.rvm/gems/ruby-2.6.1/gems/nokogiri-1.10.9/ports/x86_64-apple-darwin19.3.0/libxml2/2.9.10"
      libxslt_path: "/Users/ashleymader/.rvm/gems/ruby-2.6.1/gems/nokogiri-1.10.9/ports/x86_64-apple-darwin19.3.0/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10`

**Additional context**

**Comment by flavorjones** [comment]
Hi @ashleymader, thanks for asking this question and sorry you're having difficulty with Nokogiri.

This seems like something is wrong with the local gem installation on your system, is it possible you upgraded your OS since the original gem installation, or that some files were deleted from your system?

Can I ask you try to uninstall all versions of Nokogiri with something like `gem uninstall -a -x --force nokogiri` and then reinstall?

**Comment by ashleymader** [comment]
@flavorjones When I installed the gem I was up to date with my OS. I did just recently upgrade to bundler 2 and that's when the issues began.  After uninstalling all versions and reinstalling that cleared the issue. Thanks for the help!
