### ISSUE TITLE
Windows + Ruby 2.7 installation

### ISSUE THREAD

**Issue by aenad** [sparklemotion/nokogiri#2029]
hi i inexperienced with ruby and gem and when i put  "gem install rails"  this message show:
ERROR:  Error installing rails:
        The last version of nokogiri (>= 1.6) to support your Ruby & RubyGems was 1.10.9. Try installing it with `gem install nokogiri -v 1.10.9` and then running the current command again
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.0.
whereas i install nokogiri whit issues in github and when i put : "nokogiri -v", shows it:
# Nokogiri (1.11.0.rc2)
    ---
    warnings: []
    nokogiri: 1.11.0.rc2
    ruby:
      version: 2.7.0
      platform: x64-mingw32
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x64-mingw32]
      engine: ruby
    libxml:
      source: packaged
      patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      compiled: 2.9.10
      loaded: 2.9.10
    libxslt:
      source: packaged
      patches: []
      compiled: 1.1.34
      loaded: 1.1.34
and when i gem install nokogiri
ERROR:  Error installing nokogiri:
        The last version of nokogiri (>= 0) to support your Ruby & RubyGems was 1.10.9. Try installing it with `gem install nokogiri -v 1.10.9`
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.0.
 i dont know how to fix it.:(

**Comment by aenad** [comment]
and when i put : gem install racc
this show:
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing racc:
        ERROR: Failed to build gem native extension.

    current directory: A:/*/install_ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/racc-1.5.0/ext/racc/cparse
A:/*\ */install_ruby/Ruby27-x64/bin/ruby.exe -I A:/*\ */install_ruby/Ruby27-x64/lib/ruby/2.7.0 -r ./siteconf20200506-12312-1vqif0d.rb extconf.rb
checking for rb_ary_subseq()... yes
creating Makefile

current directory: A:/*/install_ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/racc-1.5.0/ext/racc/cparse
make "DESTDIR=" clean
Makefile:269: *** multiple target patterns.  Stop.

current directory: A:/*/install_ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/racc-1.5.0/ext/racc/cparse
make "DESTDIR="
Makefile:269: *** multiple target patterns.  Stop.

make failed, exit code 2

Gem files will remain installed in A:/*/install_ruby/Ruby27-x64/lib/ruby/gems/2.7.0/gems/racc-1.5.0 for inspection.
Results logged to A:/*/install_ruby/Ruby27-x64/lib/ruby/gems/2.7.0/extensions/x64-mingw32/2.7.0/racc-1.5.0/gem_make.out

please help for it,too.thanks

**Comment by eccobln** [comment]
Alexandrinenstraße 30 zieht es OG BARON
Von meinem iPhone gesendet

**Comment by eccobln** [comment]
Von meinem iPhone gesendet

**Comment by flavorjones** [comment]
@aenad Thank you for asking this question, and I'm sorry you're having difficulties.

Ruby 2.7 on Windows is supported in Nokogiri v1.11.0.rc1 and .rc2. You should be able to use these versions by adding this line to your Gemfile:

```
  gem "nokogiri", "~> 1.11.pre"
```

For more information, please see this issue comment: https://github.com/sparklemotion/nokogiri/issues/2019#issuecomment-609457132

**Comment by kenhys** [comment]
Hi, @flavorjones 

I've hit this issue recently.
It will be happy if there is  no need to use `~> 1.11.pre` workaround anymore.
When nokogiri 1.11 will be shipped?

**Comment by flavorjones** [comment]
I'm considering shipping a 1.10.x patch release which will support Ruby 2.7 on Windows. Would that meet your needs?

**Comment by kenhys** [comment]
@flavorjones 
It's ok for me, thank you for taking care of it!

**Comment by TeroPihlaja** [comment]
> 
> 
> I'm considering shipping a 1.10.x patch release which will support Ruby 2.7 on Windows. Would that meet your needs?

This would solve my issue as well.

**Comment by flavorjones** [comment]
v1.10.10 has been released with precompiled support for Ruby 2.7 on Windows.
