### ISSUE TITLE
An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue

### ISSUE THREAD

**Issue by aenad** [sparklemotion/nokogiri#2030]
hi, i install Rails by http://railsinstaller.org and version of it is 5.1

and i install with http://installrails.com/steps/  that i get error when i put  "gem install rails --no-ri --no-rdoc" in git bash and show:

ERROR:  Error installing rails:
        zeitwerk requires Ruby version >= 2.4.4
and i continue until that i put "rails new sample_app" and get this error:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
c:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.4.2/ext/sqlite3
c:/RailsInstaller/Ruby2.3.3/bin/ruby.exe -r ./siteconf20200506-13776-1jedq20.rb
extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=c:/RailsInstaller/Ruby2.3.3/bin/$(RUBY_BASE_NAME)
        --with-sqlcipher
        --without-sqlcipher
        --with-sqlite3-config
        --without-sqlite3-config
        --with-pkg-config
        --without-pkg-config
        --with-sqlcipher
        --without-sqlcipher
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

c:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/sqlite3-1.4.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
c:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.4.2 for
inspection.
Results logged to
c:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/sqlite3-1.4.2/gem_make.out

An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.4.2'` succeeds before bundling.

In Gemfile:
  sqlite3

can help me?

**Comment by flavorjones** [comment]
Hi, unfortunately you've posted this question on a page related to the Nokogiri project, and we don't know how to help you.

You may want to ask on a more general ruby forum, or on a windows-specific ruby forum. I'm sorry I can't be of more help.
