### ISSUE TITLE
@inos123 please stop spamming this project with fake issues and PRs

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2052]
Hi @inos123,

Over the past few weeks you've opened several fake PRs and Issues using what appear to be automated scripts. Here's a link to a search showing this:

https://github.com/sparklemotion/nokogiri/issues?q=author%3Ainos123+

and here's a screenshot of those results:

![image](https://user-images.githubusercontent.com/8207/87315015-f2546100-c4f1-11ea-8ca1-04637b2ffe8e.png)

@inos123, every time you open an issue or comment on an issue, I and many other people get email or other notifications. Every time you open a PR, in addition to those notifications, you use computing resources to run a lengthy and CPU-intense testing pipeline.

In these tickets, I've offered help and asked what you were trying to do, assuming you were testing some automation or mistakenly/accidentally using this project. I hoped that I could provide a welcoming voice and help you find a constructive way to accomplish your goals. @inos123, you have not responded. Instead, you've continued to open more fake issues and PRs.

I'm formally asking you, @inos123, in this ticket for the world to see, to please stop. I consider what you're doing to be an abuse of the project's resources and a waste of time, attention, and money, and a violation of the project's [Code of Conduct](https://github.com/sparklemotion/nokogiri/blob/master/CODE_OF_CONDUCT.md).

If you want to test automated scripts, please open your own sandbox repository and populate it with whatever data you need, instead of using this active project as your playground.

If you continue to spam this or any other project I'm connected to, I will consider taking additional actions including blocking you from contributing to the github org and potentially reporting you for spammy behavior and violation of CoC. This issue will serve as demonstration that I've attempted, multiple times, to communicate directly with you about your behavior.

And shame on you, @inos123 for putting me in this position, and forcing me to write this issue to communicate this to you -- __it is common sense that you shouldn't be spamming an active project with fake issues and PRs.__

Thanks for reading.

**Comment by flavorjones** [comment]
Ok, @inos123, I see you opened #2503 in response to this, and so I'm unfortunately going to move forward with blocking you and reporting you.

I sincerely hope you figure out how to collaborate effectively in the future, because creating software is -- despite conventional wisdom -- a human collaboration problem.

**Comment by larskanis** [comment]
@flavorjones You always have an abundance of patience! Thank you for providing this guidance how to handle such cases. Hopefully blocking works.
