### ISSUE TITLE
Installation difficulties: Installing to `vendor/bundle`

### ISSUE THREAD

**Issue by luke-hill** [sparklemotion/nokogiri#2065]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

**What is the complete output of `gem install`?**
It works

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**
```
$ cat /home/luke/Code/design-system/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/nokogiri-1.10.10/mkmf.log
"gcc -o conftest -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0/x86_64-linux -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0/ruby/backward -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  conftest.c  -L. -L/usr/share/rvm/rubies/ruby-2.6.5/lib -Wl,-rpath,/usr/share/rvm/rubies/ruby-2.6.5/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lm   -lc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0/x86_64-linux -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0/ruby/backward -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC    -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main() {return 0;}
/* end */

"pkg-config --exists libxml-2.0"
package configuration for libxml-2.0 is not found
"pkg-config --exists libxslt"
package configuration for libxslt is not found
"pkg-config --exists libexslt"
package configuration for libexslt is not found
"gcc -E -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0/x86_64-linux -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0/ruby/backward -I/usr/share/rvm/rubies/ruby-2.6.5/include/ruby-2.6.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  -g -DXP_UNIX -O3 -Wall -Wcast-qual -Wwrite-strings -Wmissing-noreturn -Winline  conftest.c -o conftest.i"
conftest.c:3:10: fatal error: libxml/xmlversion.h: No such file or directory
 #include <libxml/xmlversion.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <libxml/xmlversion.h>
/* end */
```

**What operating system are you using?**
Ubuntu 16.04LTS
`Linux luke-VirtualBox 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by luke-hill** [comment]
I'm not going to investigate "why" / "how" this was able to work. But for some reason I was missing some packages - Which let me install it onto my own gemset inside rvm, but not inside vendor. The following commands helped me fix it, I don't know which one specifically did it, but it seems this combination fixed it! Possibly one worth documenting somewhere?

```
snap install libxslt
sudo apt-get install zlib1g-dev
gem uninstall nokogiri # option3 all
sudo apt-get install libxslt-dev libxml2-dev
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
```

Sorry for timewasting @sparklemotion but yeh seems like I've fixed my own issue. With thanks to my colleague @baseonmars

**Comment by flavorjones** [comment]
Hi @luke-hill, sorry you had problems, and thanks for opening this issue. I'm glad you were able to figure it out.

I just wanted to ask: did the [Installation docs](https://nokogiri.org/tutorials/installing_nokogiri.html#ubuntu-debian) for Ubuntu not address your needs? Were they hard to find? What could we be doing better to help future Nokogiri installers?

**Comment by flavorjones** [comment]
I'll also note that it looks (based on the behavior of the installation scripts) that you're trying to compile against system libraries, which is generally harder to get right than compiling using the bundled libraries. You may want to check your bundler config for something like `--use-system-libraries` or your environment for `NOKOGIRI_USE_SYSTEM_LIBRARIES`.

I suspect this would have been a clean installation if you had not opted into using system libraries.

**Comment by luke-hill** [comment]
The issue was installing to `vendor/bundle` - I could install nokogiri normally without any issues. But when installing to vendor bundle, thats when issues came cropping up.

The advice given was "to" use system libraries in a variety of threads and guides. If I remove that (Not sure how), would that improve things?

**Comment by flavorjones** [comment]
I'm not sure I understand the problem you're describing. Can you help me reproduce it? What command(s) did you run, and what does your bundler config look like?

**Comment by luke-hill** [comment]
`gem install nokogiri` works fine.

`bundle` did not work, when I tried to install to vendor/bundle. I did this by having a single file in `./bundle/config which looked like this

```
---
BUNDLE_PATH: "vendor/bundle"
```
