### ISSUE TITLE
HTML::DocumentFragment.parse should be able to accept an IO object

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2069]
**Describe the bug**

`HTML4::Document.parse`, `HTML5::Document.parse`, and `HTML5::DocumentFragment.parse` all accept IO objects.

But `HTML4::DocumentFragment.parse` raises an unobvious exception when we do this.

**To Reproduce**

```ruby
#! /usr/bin/env ruby
puts Nokogiri::HTML4::DocumentFragment.parse(StringIO.new("<div>hello</div>"))
```

emits:

```
/home/flavorjones/code/oss/nokogiri/lib/nokogiri/html4/document_fragment.rb:40:in `match?': no implicit conversion of StringIO into String (TypeError)

          path = if /^\s*?<body/i.match?(tags)
                                         ^^^^
        from /home/flavorjones/code/oss/nokogiri/lib/nokogiri/html4/document_fragment.rb:40:in `initialize'
        from /home/flavorjones/code/oss/nokogiri/lib/nokogiri/html4/document_fragment.rb:24:in `new'
        from /home/flavorjones/code/oss/nokogiri/lib/nokogiri/html4/document_fragment.rb:24:in `parse'
        from (irb):5:in `<main>'
```

**Expected behavior**

I'd like the `HTML4::DocumentFragment.parse` method(s) be able to handle an IO object, even if that means we just `#read` the whole string into a `String`.

**Comment by flavorjones** [comment]
@sharvy This might be a good first issue! There shouldn't be any C coding necessary, and it should be straightforward to write a test based on the reproduction script above.

I think the solution is basically something like what we have in the `read_and_encode` method in `lib/nokogiri/html5.rb`:

```ruby
if tags.respond_to?(:read)
  tags = if encoding.nil?
    tags.read
  else
    tags.read(encoding: encoding)
  end
end
```

and I'd want to test both branches of that (with and without encoding specified).

**Comment by sharvy** [comment]
@flavorjones Thanks. Looks like a neat one. I'm on it.
