### ISSUE TITLE
Native gems: centos6 support

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2081]
(Originally mentioned at https://github.com/sparklemotion/nokogiri/issues/2075#issuecomment-689063142)

On Centos6, running a version of Ruby compiled [like this](https://gitlab.com/gitlab-org/gitlab-omnibus-builder/-/blob/5523332b2cd3a14b4f4a4aa2b215465499ea3617/docker/Dockerfile_centos_6#L85), we see the following error message when loading the nokogiri.so shared library:

```
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/lib/nokogiri/2.6/nokogiri.so)
```

I'm not deeply familiar with our glibc requirements, but if we go back to the early days of Linux native gems, in #1571, @larskanis  mentions that we need GLIBC 2.17 or later (and we check for this [here](https://github.com/sparklemotion/nokogiri/blob/master/tasks/cross-ruby.rb#L139-L147)).

It looks like CentOS/6.10 is based on glibc 2.12 which might explain why this isn't working -- but the error message is a little confusing if this is the case. @larskanis can you take a look and confirm my understanding?

## To Reproduce

```
host $ docker pull registry.gitlab.com/gitlab-org/gitlab-omnibus-builder/centos_6:0.0.72
...

host $ docker run -t registry.gitlab.com/gitlab-org/gitlab-omnibus-builder/centos_6:0.0.72 /bin/bash

guest # gem install --prerelease nokogiri
Fetching: nokogiri-1.11.0.rc3-x86_64-linux.gem (100%)
Nokogiri is built with the packaged libraries: libxml2-2.9.10, libxslt-1.1.34, zlib-1.2.11, libiconv-1.15.
Successfully installed nokogiri-1.11.0.rc3-x86_64-linux
Parsing documentation for nokogiri-1.11.0.rc3-x86_64-linux
Installing ri documentation for nokogiri-1.11.0.rc3-x86_64-linux
Done installing documentation for nokogiri after 2 seconds
1 gem installed

guest # nokogiri -v
# nokogiri -v
Traceback (most recent call last):
	7: from /usr/local/bin/nokogiri:23:in `<main>'
	6: from /usr/local/bin/nokogiri:23:in `load'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/bin/nokogiri:6:in `<top (required)>'
	4: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	3: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/lib/nokogiri.rb:13:in `<top (required)>'
	1: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:55:in `require': /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/lib/nokogiri/2.6/nokogiri.so) - /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/lib/nokogiri/2.6/nokogiri.so (LoadError)
	8: from /usr/local/bin/nokogiri:23:in `<main>'
	7: from /usr/local/bin/nokogiri:23:in `load'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/bin/nokogiri:6:in `<top (required)>'
	5: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	4: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/lib/nokogiri.rb:11:in `<top (required)>'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/lib/nokogiri.rb:15:in `rescue in <top (required)>'
	1: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:55:in `require': libruby.so.2.5: cannot open shared object file: No such file or directory - /usr/local/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.0.rc3-x86_64-linux/lib/nokogiri/nokogiri.so (LoadError)
```

**Comment by flavorjones** [comment]
tagging @twk3 so he can follow along as the original reporter

**Comment by twk3** [comment]
Now that centos 6 has hit its EOL, this is likely isn't very important. We no longer ship centos 6 packages for GitLab (which is where I ran into this), so I am no longer in need of a fix.

**Comment by flavorjones** [comment]
@twk3 Thanks for closing the loop here. I'd still like to see if we can make this fail a little more gracefully on systems with older glibc versions, so I'll leave it open until I can investigate.

**Comment by larskanis** [comment]
I first used manylinux2010 for rake-compiler-dock-1.1.0 which produced a centos-6 compatible binary, but switched to manylinux2014 [later on](https://github.com/rake-compiler/rake-compiler-dock/commit/352202124a28153cbb88bd28b4db4547df79a6b5), since I don't think we want to support systems that are EOL.

Regarding the error message, I don't think it's too bad. I understood it at the very first reading.

**Comment by flavorjones** [comment]
I've created a PR at #2156 to try to be more helpful for folks who are in this situation. If they're used to Nokogiri "just working" on their system, they may not understand how to address the situation (even if they understand the exception message).
