### ISSUE TITLE
ci: Introduce CI coverage for TruffleRuby

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2089]
I'd like to introduce test coverage, both as a sign of solidarity with TruffleRuby and to learn a bit more about it.

- [x] Build base TruffleRuby OCI images for stable and nightly
- [x] Build nokogiri-test images for stable and nightly
- [x] Add a non-release-blocking job to the CI pipelines (master and PR)
- [x] Get the tests to run without errors (at this point some failures are still expected)

Then we can triage existing failures and potentially create a separate issue.

Also see related issue #1882 which will drive upstreaming of TR patches into Nokogiri.

**Comment by flavorjones** [comment]
Note that I've created some base images at https://github.com/flavorjones/docker-truffleruby

**Comment by flavorjones** [comment]
LGTM!

- stable: https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/truffle-stable/builds/2
- nightly: https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/truffle-nightly/builds/2

/cc @eregon @chrisseaton for visibility.

**Comment by eregon** [comment]
@flavorjones Thank you for adding TruffleRuby in CI!
And for the Docker images too :)
