### ISSUE TITLE
Pathname objects are treated as IO and corrupt input on parse

### ISSUE THREAD

**Issue by doriantaylor** [sparklemotion/nokogiri#2110]
I just ran into a situation where `Pathname` objects get treated as `IO` instead of a file path.

The problem is that a `Pathname` object will be passed to [`io_read_callback`](https://github.com/sparklemotion/nokogiri/blob/104a3459cb00546dc06661b8c97c9109b59195a2/ext/nokogiri/xml_io.c#L14) where `read` is called on it, but since `Pathname` objects have no state, the first ~4000 (4096?) bytes of the file get read in over and over until silently kiboshed by the parser (assuming default flags).

The solution would be to put a branch in the parser logic to pull out `Pathname` objects for special treatment, either by flattening them to locations or explicitly opening them as file handles. This is a straightforward fix I am offering to do; I am registering this issue beforehand to gauge interest.

**Comment by flavorjones** [comment]
Hi @doriantaylor! Thanks for opening this issue.

There's already a PR open -- see https://github.com/sparklemotion/nokogiri/pull/1821 -- which describes the problem and also outlines some of the challenges in solving it well. Maybe we can have the conversation about this approach there?

**Comment by doriantaylor** [comment]
ah damn shoulda checked. ;) okay schlepping over there…

**Comment by doriantaylor** [comment]
Reopening this issue because that other patch is silly. Looks like `master` fails a bunch of tests. What should I branch against?

**Comment by flavorjones** [comment]
@doriantaylor Hey again.

> that other patch is silly

Well, it wasn't what I wanted and I said so, but I'd like to encourage you to avoid using terms that imply absolute judgement on other folks' work, particularly when it's a submission from a first-time contributor. I want people to have a thoroughly enjoyable time when they start contributing! Thanks for understanding.

> Looks like master fails a bunch of tests

I'm not sure I understand what you mean, master is green except for experimental TruffleRuby builds that are non-blocking: https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri

It looks like you submitted a PR at #2111 so we can continue the conversation there!

**Comment by doriantaylor** [comment]
Apologies, I just meant there wasn't enough of it to save. As for `master` failing tests, that might just be my side. See you in #2111.
