### ISSUE TITLE
[install] Super long install time on Apple MacBook Pro M1

### ISSUE THREAD

**Issue by mzagaja** [sparklemotion/nokogiri#2128]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [X] Yes!

**What is the complete output of `gem install` or `bundle install`?**

This does not complete (so far).

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

This has not yet generated.

**Tell us about your system!**

What is the output from `ruby -v`?

ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

What is the output from `gem -v`?

3.1.2

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.7.1 (2020-03-31 patchlevel 83) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Users/mzagaja/.rvm/gems/ruby-2.7.1
  - USER INSTALLATION DIRECTORY: /Users/mzagaja/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/mzagaja/.rvm/rubies/ruby-2.7.1/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/mzagaja/.rvm/gems/ruby-2.7.1/bin
  - SPEC CACHE DIRECTORY: /Users/mzagaja/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/mzagaja/.rvm/rubies/ruby-2.7.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /Users/mzagaja/.rvm/gems/ruby-2.7.1
     - /Users/mzagaja/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/mzagaja/.rvm/gems/ruby-2.7.1/bin
     - /Users/mzagaja/.rvm/gems/ruby-2.7.1@global/bin
     - /Users/mzagaja/.rvm/rubies/ruby-2.7.1/bin
     - /Users/mzagaja/.rvm/bin
     - /bin
     - /Users/mzagaja/.config/nvm/15.2.1/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /usr/local/share/dotnet
     - ~/.dotnet/tools
     - /usr/local/MacGPG2/bin
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
```

If you're using Bundler:
- what is the output from `bundle version`?
Bundler version 2.1.4 (2020-12-06 commit unknown)
- what is the output from `bundle config`? (Take care to redact any credentials)

```
Settings are listed in order of priority. The top value will be used.
build.libv8
Set for the current user (/Users/mzagaja/.bundle/config): "--with-system-v8"

build.therubyracer
Set for the current user (/Users/mzagaja/.bundle/config): "--with-v8-dir=/usr/local/opt/v8@3.15"
```

If you're on MacOS, please note:
- the version of XCode you have installed (if you know)
- the output of `gcc -v` or `clang -v`
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
```
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I have an Apple MacBook Pro M1 and am compiling Nokogiri native extensions for the first time on an application and it is taking 30+ minutes which seems, unexpected.

**Comment by mzagaja** [comment]
I ended up interrupting this after about an hour with no update in the UI.

**Comment by flavorjones** [comment]
@mzagaja Sorry you're having issues. You win some kind of prize, I think, for being the first person to try this on an M1.

Can you help me understand what you're seeing -- you didn't include any logs. Can you please tell us what you're seeing on stdout/stderr during gem installations (preferably `gem install --verbose nokogiri`) and -- even if you're interrupting it -- the `mkmf.log` file (which should be somewhere like `/path/to/ruby-installation-dir/gems/ruby-2.7.2/gems/nokogiri-1.10.10/ext/nokogiri/mkmf.log`).

Can you also please try installing a more-trivial C extension to make sure this isn't something wrong with the Ruby/compiler toolchain? Tell us what happens when you `gem install --verbose bcrypt`

**Comment by mzagaja** [comment]
Hi Mike,

Thanks for getting back to me. I figured someone has to go first 😉. So I didn't include any logs because none ended up generating from that attempt, I used CTRL+C to kill it. I got a signal interrupted message in the terminal but then had to manually kill the Ruby process in Activity Monitor as well.

At your advice I am now doing `gem install --verbose nokogiri` and it worked fine! I will note the version difference in this is 1.10.10 v. 1.10.8 in the bundle I'm trying.

This finally lead me to try `bundle update nokogiri` and predictably it worked fine.

For shits and giggles I also tried `gem install --verbose bcrypt` as suggested and it worked fine as well.

While the issue reproduced with 1.10.8, the fact it works with 1.10.10 makes me feel ok closing this and bumping my Gemfile up.

**Comment by flavorjones** [comment]
Thanks for closing the loop here. It's really strange that you're able to reproduce this with v1.10.8 but not v1.10.10, because the differences between those two versions are very small, and not obviously related to compilation/installation.

**Comment by mzagaja** [comment]
Agreed. https://github.com/Homebrew/brew/issues/7857 notes there was an issue with mkmf on the M1, and so it's possible this was related. I tried Googling and searching the repo for more details on this comment but wasn't able to surface the commit based on the reference they provided.

**Comment by flavorjones** [comment]
@mzagaja I have an experimental ARM64 Darwin native gem. If you want to help test in the next couple of days, ping me. If not, I'll ship it in the next RC and try to get feedback that way.

**Comment by mzagaja** [comment]
@flavorjones happy to give a try. Just let me know how to get connected and what might be useful to test. Otherwise I'll plug into existing app and run test suite.

**Comment by flavorjones** [comment]
Hey all - v1.11.0.rc4 has been released with pre-compiled native gem support for arm64-darwin. If you get a chance, please kick the tires and let me know here or at #2075 how it goes for you.

`gem install nokogiri --prerelease` should result in seeing something like:

```
$ gem install nokogiri --prerelease
Fetching nokogiri-1.11.0.rc4-x86_64-darwin.gem
Successfully installed nokogiri-1.11.0.rc4-x86_64-darwin
1 gem installed
```

except, you know, it should say `arm64-darwin` instead of `x86_64-darwin`.
