### ISSUE TITLE
[install]

### ISSUE THREAD

**Issue by dstiers11** [sparklemotion/nokogiri#2158]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [ ] Yes!

**What is the complete output of `gem install` or `bundle install`?**

```
your output goes here
```

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

```
your mkmf.log file contents go here
```

**Tell us about your system!**

What is the output from `ruby -v`?

What is the output from `gem -v`?

What is the output from `gem env`?

```
gem env output goes here
```

If you're using Bundler:
- what is the output from `bundle version`?
- what is the output from `bundle config`? (Take care to redact any credentials)

```
bundle config output goes here
```

If you're on MacOS, please note:
- the version of XCode you have installed (if you know)
- the output of `gcc -v` or `clang -v`

If Linux or a BSD variant, please note:
- the distro you're using
- the output of `uname -a`
- the contents of `/etc/lsb-release`.

If Windows, please note:
- whether you're installing the precompiled gems, or compiling yourself with DevKit
- the version of RubyInstaller you've installed
- or if you're not using RubyInstaller, how did you install Ruby?

**Comment by flavorjones** [comment]
@dstiers11 If you're having an installation problem, please open a new issue and fill out the template.

**Comment by eccobln** [comment]
torsten wozniak
torsten@don-rondo.com
www.don-rondo.com/Barbier

Office :+49302170909

**Comment by eccobln** [comment]
torsten wozniak
torsten@don-rondo.com
www.don-rondo.com/Barbier

Office :+49302170909
