### ISSUE TITLE
nokogiri should drop the dependency on "racc"

### ISSUE THREAD

**Issue by rpjday** [sparklemotion/nokogiri#2180]
As I read it, racc became a Ruby core module a long time ago, so there is no point in it still being listed as a run-time dependency. In fact, this causes an install error if you try to use this module in a Yocto Project build, as racc and ruby both try to install the executable /usr/bin/racc, causing the install to fail.

**Comment by flavorjones** [comment]
Hi, @rpjday, thanks for opening this issue.

The original discussion about this can be found at https://github.com/sparklemotion/nokogiri/issues/1988. The TL;DR is that although racc is part of the standard library, it is installed by Ruby as a "default gem" that is still versioned and as such may break backwards compatibility at some point in the future.

There was also discussion recently about Racc as a dependency here: https://github.com/sparklemotion/nokogiri/issues/2166

If you're running into problems installing Racc and Ruby on Yocto, I'd suggest filing an issue with the maintainer of the Ruby package for the distro.
