### ISSUE TITLE
[bug]Doesn't parse last element of a 14MB big file

### ISSUE THREAD

**Issue by ngiger** [sparklemotion/nokogiri#2187]
**Please describe the bug**

The rubygem oddb2xml fails to correctly emit the last root element RESULT. See
[oddb2xml issue 46](https://github.com/zdavatz/oddb2xml/issues/46)
I do not know what [producer HIN](http://download.hin.ch/download/oddb2xml/oddb_article.xml) of the 119MB changed, but it is failing since January 6 of this year.

But most probably HIN ran just the oddb2xml executable installed via rubygem oddb2xml version 2.7.0. 

**Help us reproduce what you're seeing**
I just ran in (git clone https://github.com/zdavatz/oddb2xml.git) directory the commands
```
bundle install
bundle exec ruby bin/odbb2xml
```
under linux with ruby 3.0.0

**Expected behavior**

Under https://github.com/ngiger/oddb2xml/commit/eea50622a7806ea6ac0ea393e5bbddc3a0f11a58 you find a workaround, where I just use REXML to add this element

**Environment**
```
niklaus@oddb-ci2 ~/g/oddb2xml> bundle exec nokogiri -v
# Nokogiri (1.11.1)
---
warnings: []
nokogiri:
version: 1.11.1
cppflags:
- "-I/home/niklaus/git/oddb2xml/vendor/bundles/ruby/3.0.0/gems/nokogiri-1.11.1-x86_64-linux/ext/nokogiri"
- "-I/home/niklaus/git/oddb2xml/vendor/bundles/ruby/3.0.0/gems/nokogiri-1.11.1-x86_64-linux/ext/nokogiri/include"
- "-I/home/niklaus/git/oddb2xml/vendor/bundles/ruby/3.0.0/gems/nokogiri-1.11.1-x86_64-linux/ext/nokogiri/include/libxml2"
ruby:
version: 3.0.0
platform: x86_64-linux
gem_platform: x86_64-linux
description: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
engine: ruby
libxml:
source: packaged
precompiled: true
patches:
- 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
- 0002-Remove-script-macro-support.patch
- 0003-Update-entities-to-remove-handling-of-ssi.patch
- 0004-libxml2.la-is-in-top_builddir.patch
- 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
- 0006-htmlParseComment-treat-as-if-it-closed-the-comment.patch
- 0007-use-new-htmlParseLookupCommentEnd-to-find-comment-en.patch
- '0008-use-glibc-strlen.patch'
- '0009-avoid-isnan-isinf.patch'
libxml2_path: "/home/niklaus/git/oddb2xml/vendor/bundles/ruby/3.0.0/gems/nokogiri-1.11.1-x86_64-linux/ext/nokogiri"
iconv_enabled: true
compiled: 2.9.10
loaded: 2.9.10
libxslt:
source: packaged
precompiled: true
patches: []
compiled: 1.1.34
loaded: 1.1.34
other_libraries:
zlib: 1.2.11
```

**Additional context**

The file which causes this error can be found under http://download.elexis.info/download/nokogiri_error.xml

I tried to reproduce the bug via script like this
```
#!/usr/bin/env ruby
require 'nokogiri'
FileName = 'nokogiri_error.xml'
FileSize = File.size(FileName)
puts "#{Time.now}: #{FileName} size is #{FileSize} bytes #{FileSize/1024/102} MB"
doc =  Nokogiri::XML.parse(File.read('error_5.xml'))
# grep -c "/PRD" error_5.xml -> 17333
unless /RESULT/.match(doc.root.elements.last.name)
puts "#{Time.now}: Unable to find RESULT was #{doc.root.elements.last.name} of #{doc.root.elements.size} elements"
else
puts "#{Time.now}: Found RESULT #{doc.root.elements.last.name} having  #{doc.root.elements.size} elements"
end

require 'rexml/document'
string = IO.read(FileName)
doc2 = REXML::Document.new(string)
puts "#{Time.now}: /#{doc.root.name}/RESULT"
result = REXML::XPath.first(doc2, "/#{doc.root.name}/RESULT").to_s
puts "#{Time.now}: REXML found \n#{result}"
```

Then I tried to load only the first (approximatly) half of the PRD elements. Then my script showed no error.
Using the rest of the PRD elements, did not show the error.

It must be something weird. I wish you good luck.

**Comment by flavorjones** [comment]
@ngiger Thanks for opening this issue, and thanks for asking this question.

Have you tried parsing this using the `HUGE` parse option that libxml2 makes available? https://nokogiri.org/tutorials/parsing_an_html_xml_document.html#parse-options

**Comment by ngiger** [comment]
No. I was not aware, that this option did exit.
Setting it fixed my problem.
Thanks a lot for your quick answer!
