### ISSUE TITLE
[install] arm64-linux version question

### ISSUE THREAD

**Issue by piotr-sokolowski** [sparklemotion/nokogiri#2190]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x ] Yes!

If Linux or a BSD variant, please note:
- the distro you're using
Ubuntu 18.04.5 LTS
- the output of `uname -a`
`aarch64 aarch64 aarch64 GNU/Linux` - AWS Graviton 2 instance

Hi, are there any plans to include arm64-linux version of gem ?

**Comment by flavorjones** [comment]
Hi @piotr-sokolowski, thanks for asking this question.

I'd have no problem supporting this architecture if `rake-compiler` and `rake-compiler-dock` provided the tooling for it out-of-the-box. Can I ask you to open an issue at https://github.com/rake-compiler/rake-compiler-dock where we can both participate in a conversation with the maintainers?
