### ISSUE TITLE
Consider editing repository setings to remove "Packages" section

### ISSUE THREAD

**Issue by matkoniecz** [sparklemotion/nokogiri#2197]
"Packages No packages published" is displayed right now, fortunately this pointless section duplicating releases info can be removed.

Edit repo page config to remove it (cog next to the description).

I am not making a PR as it is defined in proprietary github settings, not in a git repository - and I have no rights to modify repo settings.

![Peek 2020-10-25 09-10](https://user-images.githubusercontent.com/899988/97102018-3a168700-16a2-11eb-8c18-7bd9a88922eb.gif)

**Comment by flavorjones** [comment]
Hi, thanks for bringing up this topic. Although we're not currently publishing any packages, we may do so in the future. I can think of a use for:

- nightly or experimental releases
- OCI images for building or running nokogiri

In the meantime, I don't perceive that this is a problem that needs fixing. Thanks for your understanding.
