### ISSUE TITLE
[bug] Maintainability badge show gray ?

### ISSUE THREAD

**Issue by matkoniecz** [sparklemotion/nokogiri#2198]
**Please describe the bug**

https://github.com/sparklemotion/nokogiri#status

![screen01](https://user-images.githubusercontent.com/899988/109955427-c2f19f00-7ce2-11eb-8c70-7828dee50362.png)

**Help us reproduce what you're seeing**

clear browser cache and go to https://github.com/sparklemotion/nokogiri#status

**Expected behavior**

Badges present there provide some info or entertainment or other benefit

**Environment**

Do not apply.

**Additional context**

I would expect badge to be fixed or removed.

**Comment by matkoniecz** [comment]
https://codeclimate.com/github/sparklemotion/nokogiri/builds 

> This repo hasn't had a successful analysis for its default branch yet.

Is it a victim of branch renaming?

**Comment by flavorjones** [comment]
Thanks for pointing this out, definitely it's related to branch renaming. I've updated the Code Climate config and the badge is back.
