### ISSUE TITLE
[bug] Tutorials link in Readme can be missed

### ISSUE THREAD

**Issue by matkoniecz** [sparklemotion/nokogiri#2199]
**Please describe the bug**

Maybe my search ability is poor today, but locating https://nokogiri.org/tutorials/modifying_an_html_xml_document.html took me an embarrassingly long time

![screen02](https://user-images.githubusercontent.com/899988/109962825-f7b62400-7ceb-11eb-834b-0e89792a4b34.png)

Once I found tutorial I started to finally progress with my plan to write proper code to merge multiple SVG files into one.

**Help us reproduce what you're seeing**

Try to parse and edit SVG using ruby without memory how it can be done.

**Expected behavior**

Tutorials are existing and easy to find. Note that once I found tutorial my problems become solved, despite not finding solution for previous 40 minutes.

**Environment**

Not relevant

**Additional context**

Yes, now that I create this issue I see tutorials being mentioned in https://github.com/sparklemotion/nokogiri#reading Not entirely sure why I missed this particular mention, maybe I got distracted by Tidelift.

I propose 

(1)
linking relevant tutorials in 

> reading, writing, modifying, and querying documents

in header of readme ( https://github.com/sparklemotion/nokogiri#nokogiri )

(2)
adding "good documentation and tutorials" in https://github.com/sparklemotion/nokogiri#features-overview with word tutorials linking to https://nokogiri.org/tutorials/toc.html

**Comment by flavorjones** [comment]
Hi! If you'd like to submit some suggestions in a PR I'd be happy to take a look. Thanks!

**Comment by matkoniecz** [comment]
> Hi! If you'd like to submit some suggestions in a PR I'd be happy to take a look. Thanks!

Done!
