### ISSUE TITLE
Extend nokogiri API to support libxml API call xmlSchemaValidateStream

### ISSUE THREAD

**Issue by gjeudy** [sparklemotion/nokogiri#222]
this would allow validating the xml schema as the stream is parsed with SAX parsing method for example. Currently one has to validate/parse the whole xml schema upfront and then re-parse to do the actual processing.

**Comment by flavorjones** [comment]
I apologies for not responding for so long, but I honestly didn't know where to start with this feature request.

I'm going to close this, as this isn't a problem I've encountered personally and so I'm unlikely to do the exploration and research necessary to understand how this function could and should be used.

I'm happy to consider working on this if you can help me understand a bit better. Can you provide some C code demonstrating how this function works, and a bit more of an explanation of your use case and what you think the API should look like?

**Comment by flavorjones** [comment]
(Note that I did do some initial exploration which resulted in upstream fixes: https://gitlab.gnome.org/GNOME/libxml2/-/issues/530)
