### ISSUE TITLE
Schema validation in `1.11.3`

### ISSUE THREAD

**Issue by 3b7** [sparklemotion/nokogiri#2231]
A recent rails upgrade bumped the nokogiri dependency from `1.10.10` to `1.11.3`. Some specs failed and after digging through I came across this change in behavior. I am not sure if there is now a different way to do schema validation or if I am missing something. 

Let me know. 
```
# nokogiri-1.10.10

[2] pry(main)> xsd = Nokogiri::XML::Schema(URI.open('http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd'))
=> #<Nokogiri::XML::Schema:0x00007f869bda5948 @errors=[]>
```

```
# nokogiri-1.11.3-x86_64-darwin

[1] pry(main)> xsd = Nokogiri::XML::Schema(URI.open('http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd'))
Nokogiri::XML::SyntaxError: 1167:0: ERROR: attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration.
from /Users/3b7/.rvm/gems/ruby-2.7.2/gems/nokogiri-1.11.3-x86_64-darwin/lib/nokogiri/xml/schema.rb:47:in `from_document'
```

**Comment by flavorjones** [comment]
Hi, @3b7, thanks for opening this issue. Sorry you're having trouble.

You've happened upon a breaking change we introduced in v1.11.x to address security concerns. You can read more about it at:

- the changelog entry: https://nokogiri.org/CHANGELOG.html#changed_1
- the CVE public disclosure: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-vr8q-g5c7-m54m

In those announcements, we provide some instructions on how to opt into the insecure/trusted document behavior. TL:DR, you should be able to unset the NONET parse option (by setting the double-negative `nononet` parse option) to restore this behavior.

I hope this helps? I'm going to close this issue, but if you have trouble, please comment and we'll reopen it to help you out.
