### ISSUE TITLE
[bug] Duplicated `lang` attribute after serialization/deserialization if `remove_namespaces!` is used

### ISSUE THREAD

**Issue by gioele** [sparklemotion/nokogiri#2265]
**Please describe the bug**

The `lang` attribute is duplicated after serialization/deserialization if `remove_namespaces!` is used.

```xml
<html xmlns="http://www.w3.org/1999/xhtml" lang="x" lang="x" lang="x" xml:lang="x"></html>
```

**Help us reproduce what you're seeing**

Here is a reproduction script:

```ruby
#!/usr/bin/env ruby

require "nokogiri"

def from_xml(str)
	parse_options = Nokogiri::XML::ParseOptions::DEFAULT_XML
	doc = Nokogiri::XML::Document.parse(str, nil, nil, parse_options)
	doc.remove_namespaces! # <<< the bug disappears if this line is commented out
	return doc
end

doc = from_xml("<html lang='x'/>")
doc_str = doc.to_xhtml; puts doc_str

doc2 = from_xml(doc_str)
doc2_str = doc2.to_xhtml; puts doc2_str

doc3 = from_xml(doc2_str)
doc3_str = doc3.to_xhtml; puts doc3_str

raise "Different serialization" unless doc_str == doc2_str
```

**Expected behavior / Actual behavior**

One would expect the document to not change after a serialization/deserialization cycle.

The reproduction script should output the following lines:

```xml
<html xmlns="http://www.w3.org/1999/xhtml" lang="x" xml:lang="x"></html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="x" xml:lang="x"></html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="x" xml:lang="x"></html>
```

Instead it produces this output:

```xml
<html xmlns="http://www.w3.org/1999/xhtml" lang="x" xml:lang="x"></html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="x" lang="x" xml:lang="x"></html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="x" lang="x" lang="x" xml:lang="x"></html>
Traceback (most recent call last):
./lang-test.rb:24:in `<main>': Different serialization (RuntimeError)
```

**Environment**

```
$ nokogiri -v
# Nokogiri (1.11.7)
    ---
    warnings: []
    nokogiri:
      version: 1.11.7
      cppflags:
      - "-I/[RBENV]/versions/2.6.2/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.7-x86_64-linux/ext/nokogiri"
      - "-I/[RBENV]/versions/2.6.2/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.7-x86_64-linux/ext/nokogiri/include"
      - "-I/[RBENV]/versions/2.6.2/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.7-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.6.2
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/[RBENV]/versions/2.6.2/lib/ruby/gems/2.6.0/gems/nokogiri-1.11.7-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
```

**Comment by flavorjones** [comment]
Hi! Thanks for reporting this. The behavior you're describing comes from libxml2, which is the parsing library that Nokogiri wraps. As a result, there's nothing we can easily do to change this behavior; and the [guiding principles](https://nokogiri.org/#guiding-principles) of the project mean that we don't generally try to fix these behaviors.

It's *also* worth noting that the `remove_namespaces!` method is not really intended to be used in scenarios where you want to rigorously parse documents. The documentation for it suggests it's useful for "developers who either don't understand namespaces or don't care about them", and it seems that you are neither! It also suggests that use of this method is probably not a good thing to do.

Can you suggest wording for that method's doc strings that more specifically warns people away from it when desiring consistent behavior?

**Comment by gioele** [comment]
Hi @flavorjones. In this case I still believe it is a bug.

I think it is reasonable to expect that Nokogiri (libxml2) will produce well formed XML. It would be a bug if Nokogiri (libxml2) generated something like `<html></HTM>`, regardless of which transformations the document went through.

If I understand correctly, the problem is that [`xmlSetNs` inside `recursively_remove_namespaces_from_node`](https://github.com/sparklemotion/nokogiri/blob/051b1939ddd3ae902d4ed1cd89f5c6fcdfa1cb6d/ext/nokogiri/xml_document.c#L97) does not check if a similarly named attr/elem exists. This creates an inconsistent state that would not be possible to create starting with an empty doc.

Do you think that this consistency check should be in libxml2 rather than in Nokogiri?

**Comment by flavorjones** [comment]
:thinking: Let me take a look. I should have time in the next day or so to go deeper on it.

**Comment by gioele** [comment]
Thanks @flavorjones! In the meantime I filed a bug upstream: https://gitlab.gnome.org/GNOME/libxml2/-/issues/271

**Comment by flavorjones** [comment]
Can you help me understand why you're calling `remove_namespaces!`? You seem to care about well-formedness and namespaces, so I'm a little mystified and that additional context will help me wrap my head around what you're trying to do.

**Comment by flavorjones** [comment]
After giving it some thought, this isn't something I'm willing to spend time to fix. If you want to spend some time to describe the behavior you think Nokogiri should have in this case, and write a PR for it, I'd be happy to review.
