### ISSUE TITLE
Update html5lib-tests test to official repo

### ISSUE THREAD

**Issue by stevecheckoway** [sparklemotion/nokogiri#2282]
Blocked on:

- [x] https://github.com/html5lib/html5lib-tests/pull/136

If the tests end up [moving to the WPT](https://github.com/html5lib/html5lib-tests/issues/127) then we should switch to tracking that instead.

**Comment by flavorjones** [comment]
I updated the format of the description to try out the new github task lists, which are supposed to help track dependencies on other tickets. :shrug:

**Comment by stevecheckoway** [comment]
Nice, thanks!
