### ISSUE TITLE
.inner_html= causing memory issue

### ISSUE THREAD

**Issue by vanboom** [sparklemotion/nokogiri#2349]
**Please describe the bug**
We are hunting down an issue in a Ruby on Rails application that uses Nokogiri to substitute some XML elements in the content.xml of a MS Word document.

Calling `inner_html=` repetitvely appears to have memory consequences that appear as a leak.  The process memory continues to increase.   This can be tested by simply setting inner_html to itself. 

**Help us reproduce what you're seeing**
Pseudocode: 
1. Load some XML
2. Iterate through all of the children nodes and call `inner_html` to replace the node's content. 
3. Check process memory along the way

We did this in our application IRB in development which includes the memory_profiler gem and nokogiri 1.12.5. 

```ruby
n = Nokogiri::XML(File.read('/tmp/test.xml'))
50000.times do n.children.map{|c| c.inner_html = c.inner_html}; end;
GetProcessMem.new.gb
```
```
irb(main):082:0> GetProcessMem.new.gb
=> 13.417617797851562
```
**Expected behavior**
We would expect that memory would not continue to increase with each call to `inner_html=`.  
It seems that Nokogiri is not freeing up memory as it parses the string given to inner_html, or as it replaces the node's contents.  

See attached XML file that we used for testing.  Our appilication performs a similar work flow on a much larger XML document so the memory consumption issue grows much faster. 

**Environment**

```# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/opt/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nokogiri-1.12.5-x86_64-linux/ext/nokogiri"
      - "-I/opt/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nokogiri-1.12.5-x86_64-linux/ext/nokogiri/include"
      - "-I/opt/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nokogiri-1.12.5-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.5.0
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/opt/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nokogiri-1.12.5-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libgumbo: 1.0.0-nokogiri
```

[loremtest.zip](https://github.com/sparklemotion/nokogiri/files/7406104/loremtest.zip)

**Comment by flavorjones** [comment]
Closing, but please do let me know if you need any help or advice.

**Comment by vanboom** [comment]
Thanks for your advice and for documenting the memory model in more detail here.  Not sure I am smart enough yet with this code to attempt a PR but will do so if something becomes clearer to me.  I find it concerning that a simple node replacement causes such a memory issue.  Seems memory should be freed when the node is replaced if there is no variable to hold it in scope.

**Comment by flavorjones** [comment]
> Seems memory should be freed when the node is replaced if there is no variable to hold it in scope

Yes, but as I tried to explain above, this is challenging to determine given the current memory management model. I agree this needs to be improved and in fact said so above, at length, in the section of my response entitled "Doing Better."
