### ISSUE TITLE
set up aarch64-linux runner for github actions

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2362]
I'd like some level of testing on ARM64 Linux if we're going to start shipping `aarch64-linux` native gems (see #2332). 

Azure / Github Actions don't appear to support ARM64 Linux, so I guess AWS EC2 Graviton instances are the best bet?

Some docs about setting up an EC2 self-hosted runner are here:

> https://github.com/machulav/ec2-github-runner

though there may be other (more official?) ways to do it.

**Comment by larskanis** [comment]
I made good experience by using docker with qemu-user-static like here in rake-compiler-dock: https://github.com/rake-compiler/rake-compiler-dock/blob/8b75537c41fc4287211f8780cc05dc125eedcfa3/.github/workflows/ci.yml#L170

The big advantage is that you can build and execute many architectures on your local computer. Not just on some specialized CI environment. And it is almost as fast as native.

**Comment by flavorjones** [comment]
@larskanis :exploding_head: Thanks for that pointer, I think this may solve a whole class of problems for me.

**Comment by flavorjones** [comment]
For posterity: a kind note from an Actions PM with advice on how he does this for his own project: https://github.com/actions/runner/issues/1491#issuecomment-970418408

**Comment by flavorjones** [comment]
PR #2425 adds this test coverage.
