### ISSUE TITLE
[bug] missing exception handling

### ISSUE THREAD

**Issue by Tableator** [sparklemotion/nokogiri#2392]
Good morning.
I use nokogiri in diverse scripts to extract information from Web-Sites, notably translations from online-dictionaries, conjugations of French verbs and synonymes in German or French.
nokogiri 1.12.5 crashed upon a call to `nokogiri -e [expression]` in one script but not in another. This points at **an ill-composed expression**, but the only error I got to see is

```
cat ccaen.html | nokogiri -e "puts $_.at_css("div.result")"
Traceback (most recent call last):
	4: from /usr/local/bin/nokogiri:25:in '<main>'
	3: from /usr/local/bin/nokogiri:25:in `load'
	2: from /var/lib/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/bin/nokogiri:112:in `<top (required)>'
	1: from /var/lib/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/bin/nokogiri:112:in `eval'
<main>:1:in `<top (required)>': undefined local variable or method `getmail' for main:Object (NameError)`
```

Before I understood my own error, with each of my new attempts, a variety of NameErrors were raised, instead of **a really informative message which could have been helpful do point me at the real problem!**

TY for reading. Continue as you please.

**Help us reproduce what you're seeing**

**Expected behavior**

**Environment**

**Additional context**

**Comment by stevecheckoway** [comment]
Hi @Tableator,

I take it from your message that you figured out that your problem stems from using `$_` inside double quoted strings on the command line.

I can trigger this crash with
```
$ echo getmail
getmail
$ bundle exec nokogiri -e "$_.at_css" </dev/null
<main>:1:in `<top (required)>': undefined local variable or method `getmail' for main:Object (NameError)
	from .../vendor/ruby/3.0.0/gems/nokogiri-1.12.5-x86_64-darwin/bin/nokogiri:112:in `eval'
	from .../vendor/ruby/3.0.0/gems/nokogiri-1.12.5-x86_64-darwin/bin/nokogiri:112:in `<top (required)>'
	from .../vendor/ruby/3.0.0/bin/nokogiri:23:in `load'
	from .../vendor/ruby/3.0.0/bin/nokogiri:23:in `<main>'
```

The problem here is that the shell is the thing performing the variable expansion. When nokogiri is run, it sees the command line argument `puts getmail.at_css(div.result)` which it is running as ruby code. And that's where the error is coming from.

I'm not really sure what better error message Nokogiri could give here (or even how it could detect the problem since the variable substitution occurred before Nokogiri even started running.

**Comment by Tableator** [comment]
@stevecheckoway
The example in my OP is entirely constructed for the purpose, but NameErrors and uninitialized Variables where the authentic information I got from a similar call to Nokogiri.

As regards the  “better error message”, I will take the risk now to talk without having seen the code. But I feel rather safe, anyway:
Put a begin-rescue around the call to eval. Anything is better than the message which is there to trigger a Nokogiri-**developer** to take a look at the code, be it something like “_PSE verify that the given expression blabla..._”

But hey. I *will* take a look at the code and if – by chance – I can put more knowledge and detail into my rants, I will do that. Today I am driving a tractor around some apple-trees and try desperately to not destroy most of them, but I will come back here, be it with a mea culpa, should I not understand what I see in the code.

**Comment by stevecheckoway** [comment]
Adding a message that the problem came from the expression passed to `-e` is a good suggestion, thanks! I'll bet @flavorjones would be open to a pull request which improves the error message.

Thinking about it, printing out the argument Nokogiri received would probably help future users diagnose the issue.

**Comment by flavorjones** [comment]
I'm genuinely sorry you are encountering error messages that weren't clear to you.

I can reproduce this without Nokogiri using just `ruby -e`:

```text
$ echo getmail
getmail
$ ruby -e "$_" < /dev/null
-e:1:in `<main>': undefined local variable or method `getmail' for main:Object (NameError)
```

I don't think it's Nokogiri's responsibility to trap errors like this. The exception trace tells you exactly what Ruby thinks is wrong, and on which line; I don't think I could be more clearer by rescuing this exception.

@stevecheckoway the `-e` option is intended to mirror/mimic the `ruby -e` option. I believe that changing the behavior of the script to emit ruby code would break existing scripts; and violates the ["silence is golden"](http://www.linfo.org/rule_of_silence.html#:~:text=The%20Rule%20of%20Silence,say%2C%20it%20should%20say%20nothing.&text=That%20is%2C%20silence%20in%20itself%20is%20a%20virtue.) philosophy.

I would be open to a pull request that improved the stack walkback emitted by nokogiri under failure conditions; but I'm not open to rescuing all exceptions and trying to provide a more-readable interpretation of them.

**Comment by stevecheckoway** [comment]
@flavorjones To be clear, I was suggesting adding a line of context if an exception is raised during `eval`. Something like
```
$cat ccaen.html | nokogiri -e "puts $_.at_css("div.result")"
Exception raised while evaluating 'puts getmail.at_css(div.result)'
Traceback (most recent call last):
	4: from /usr/local/bin/nokogiri:25:in '<main>'
	3: from /usr/local/bin/nokogiri:25:in `load'
	2: from /var/lib/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/bin/nokogiri:112:in `<top (required)>'
	1: from /var/lib/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/bin/nokogiri:112:in `eval'
<main>:1:in `<top (required)>': undefined local variable or method `getmail' for main:Object (NameError)`
```

**Comment by Tableator** [comment]
> I don't think it's Nokogiri's responsibility to trap errors like this. The exception trace tells you exactly what Ruby thinks is wrong, and on which line; I don't think I could be more clearer by rescuing this exception.

Wait a moment.
You use a software inside your own project. By chance, it is some gem that you use in a program called nokogiri. 
Now you tell me that, if the developer of the gem or library or other piece of code that you use chose her/himself to inform future “_users_” – developers – of their code about possible pitfalls.., then what you think is needed is :
**To inform the users of your own program about what the developer of some tiny piece of utility-code thought pertinent to convey in order to improve the quality of potential future  – but yet unknown – uses of that tiny (or big) piece of utility-code.**

**No.** 

Exceptions like this are part of the development-process, not the usage of a final software package.
We are not talking about OutOfMemory, here.

Thanks for relieving me of the task to dig into the code, myself. This has all been very clear. **Ω**

**Comment by flavorjones** [comment]
@stevecheckoway Oh, I quite like that idea, thanks for persisting and clarifying. I will do that.

@Tableator Again I'm sorry you've had trouble, and I can tell that you're upset; but I don't understand your response.

**Comment by flavorjones** [comment]
See #2394 for a PR to improve this
