### ISSUE TITLE
[bug] nokogiri v1.13.0 breaks backwards compatibility (should be v2.0. not v1.13.0)

### ISSUE THREAD

**Issue by Justin-W** [sparklemotion/nokogiri#2413]
**Please describe the bug**

[nokogiri v1.13.0](https://github.com/sparklemotion/nokogiri/releases/tag/v1.13.0) explicitly removed support for ruby versions < v2.6, which according to the [SemVer spec](https://semver.org/), should only be done in a Major release, not during a Minor or Patch release.

**Help us reproduce what you're seeing**

Bundle any gem which depends on nokogiri v1.x (e.g. `nokogiri (~> 1.11)` or `nokogiri (~> 1.6, < 2.0)`) using Ruby v2.5.1.

**Expected behavior**

This backwards incompatible change breaks existing automation which (correctly) has constraints pinning to nokogiri v1.x.

Existing gems which depend on nokogiri v1.x (e.g. `nokogiri (~> 1.11)` or `nokogiri (~> 1.6, < 2.0)`) should continue to function with the latest v1.x version of nokogiri, with all of the same Ruby version(s) which were previously supported by v1.12.x.

Therefore, I recommend fixing/removing/replacing v1.13.0 with a newer v1.x release (v1.13.1 or v1.14?) which restores backwards compatibility, and re-releasing v1.13.0 as v2.0.

**Environment**

Ruby v2.5.1.

**Additional context**

**Comment by Magisus** [comment]
We are hitting this also, and can pin if needed, but agree with @Justin-W that this is really a breaking change.

**Comment by flavorjones** [comment]
Hello and thank you for bringing up this topic! I'm sorry you're having problems with this.

I've tried hard to state clearly what our versioning policy is here:

- https://github.com/sparklemotion/nokogiri/blob/main/README.md#semantic-versioning-policy

Deprecating old versions of Ruby is something we've always done in patch releases in the past. Additionally I'll point out that SemVer (or at least my reading of SemVer) allows for this:

- https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

I realize that you probably disagree with this perspective, and I'm open to changing this in the future based on your (and others') input. But I'm not going to take action to address this right now in this version.

**Comment by flavorjones** [comment]
I'll also point out that modern bundler handles this case well. If I'm running Ruby 2.5.9, and this is my Gemfile:

```ruby
source "https://rubygems.org"
gem "nokogiri-diff"
```

then "bundle update" does the right thing and chooses the latest version of nokogiri that supports Ruby 2.5:

```
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using bundler 2.2.30
Using racc 1.6.0
Fetching tdiff 0.3.4
Using nokogiri 1.12.5 (x86_64-linux)
Installing tdiff 0.3.4
Fetching nokogiri-diff 0.2.0
Installing nokogiri-diff 0.2.0
Bundle updated!
```

I think that you may be able to manage your situation by upgrading to a modern bundler, and if necessary specifying your version of ruby in your Gemfile.

**Comment by Magisus** [comment]
Thanks for this tip, I'll look into it 🙂
