### ISSUE TITLE
[bug] Regression in 1.13.0 in XSLT.quote_params

### ISSUE THREAD

**Issue by jcoyne** [sparklemotion/nokogiri#2418]
In nokogiri 1.12 and before I was able to send integers to XSLT.quote_params:

```
Nokogiri::XSLT.quote_params(['foo', 123])
```

After upgrading to 1.13.0 this results in a TypeError:

```
*** TypeError Exception: no implicit conversion of Integer into String
```

**Comment by flavorjones** [comment]
@jcoyne Thanks for opening this! I'll take a look.

**Comment by flavorjones** [comment]
git bisect isolated this regression to 3099528 which is ... :thinking: 

Should be an easy fix, though.

**Comment by flavorjones** [comment]
Basically:

```ruby
1234 =~ /'/ # this is OK
/'/.match?(1234) # this is not OK
```

**Comment by flavorjones** [comment]
PR at #2420

**Comment by jcoyne** [comment]
Thank you @flavorjones !

**Comment by flavorjones** [comment]
I'm hoping to ship v1.13.1 today or tomorrow. Working on one other regression.

**Comment by flavorjones** [comment]
v1.13.1 is out now: https://github.com/sparklemotion/nokogiri/releases/tag/v1.13.1
