### ISSUE TITLE
publish patched NekoDTD to Maven Central

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2437]
## Problem summary

Currently Nokogiri's java native gem depends on patched versions of NekoDTD and NekoHTML. The binary artifacts only exist in Nokogiri's git repo and if I needed to reproduce them I would be starting from scratch.

## Historical context

In the past (e.g., 2e5ce32 in 2012 and 6166964 in 2015) we've patched NekoHTML and NekoDTD to fix bugs or parsing errors. These repositories live (I think) at:

- https://github.com/jvshahid/nekohtml
- https://github.com/jvshahid/nekodtd

A conversation at #1253 suggested using `jar-dependencies` to manage Java dependencies, and #2432 starting doing so for the artifacts listed on Maven Central.

## What do we want to do

This issue is intended to drive a conversation with the following potential outcomes:

- [x] ensure shared ownership of the patched NekoHTML and NekoDTD source repositories
- [x] set up a Maven Central groupId (@headius pointed us at https://central.sonatype.org/publish/publish-guide/)
- [x] https://github.com/sparklemotion/nekodtd/issues/1
- [x] ~https://github.com/sparklemotion/nekohtml/issues/3~ _this library is deprecated in nokogiri >= 1.14.0_
- [x] use `jar-dependencies` to manage those dependencies like our other ones

Doing all of the above would allow us to consider further patches on the Neko libraries, e.g., #2436.

cc @jvshahid whose support and assistance I will need

**Comment by flavorjones** [comment]
@jvshahid Would you be open to transferring ownership of those repositories to me or to the sparklemotion org? That would unblock me to do the rest of the work.

**Comment by flavorjones** [comment]
Thanks, @jvshahid! Repositories have been transferred to @sparklemotion/nokogiri-core

- https://github.com/sparklemotion/nekohtml
- https://github.com/sparklemotion/nekodtd

**Comment by flavorjones** [comment]
I've created a JIRA account at OSSRH and requested a new project with the groupId `org.nokogiri`: https://issues.sonatype.org/browse/OSSRH-77736

**Comment by headius** [comment]
@flavorjones As always let me know if I can help. I get a lot of notifications so I don't always see updates here, but I support this move and will try to help as time permits.

**Comment by flavorjones** [comment]
@headius Thanks for checking in! I will be respectful of your time, but may ask for advice or a code review here and there as I work through this and a handful of other JRuby issues for v1.14.0.

**Comment by flavorjones** [comment]
Note that on `main`, we get our HTML parser from `neko-htmlunit` and not the fork of nekohtml mentioned above. I've updated the title and description to reflect that we don't need to do that work anymore.

**Comment by flavorjones** [comment]
See https://github.com/sparklemotion/nokogiri/pull/2538 and https://github.com/sparklemotion/nekodtd/issues/1. This is basicall done, just waiting for CI to go green.
