### ISSUE TITLE
Run upstream html5lib-tests once weekly (not on every PR)

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2449]
@stevecheckoway This week the upstream html5lib-tests we run in CI started failing, see for example:

- https://github.com/sparklemotion/nokogiri/runs/5169938003?check_suite_focus=true

It seems like this is probably not useful to run on every PR, but would be helpful to run periodically (once a week?) to give us some signal on whether there might be work for us to do on the gumbo parser. What do you think?

**Comment by stevecheckoway** [comment]
Running once per week sounds totally reasonable to me.

With regard to the failing tests, I hope to take a look at this this week, probably Wednesday.

**Comment by flavorjones** [comment]
OK, I'll move these tests (as well as the upstream libxml2 job) to a once-weekly schedule like truffleruby.

**Comment by flavorjones** [comment]
Done.
