### ISSUE TITLE
[install] Nokigiri M1 problems with Rails has to stop

### ISSUE THREAD

**Issue by romaingibs13** [sparklemotion/nokogiri#2452]
Opening this issue just to have some feedback on the issues targeting M1 processors, I'm just fed up of having to specify everyday to my numerous vs code workspaces which nokogiri version needs to be removed and then installed to have the bundle working.

I mean this can't be automatised in some way on your side ? Why do I have to `bundle lock --add-platform arm64-darwin` then `bundle update` several times a day ?

**Comment by flavorjones** [comment]
Hi @romaingibs13,

We're sorry that you're having problems. We've tried very hard to precompile gems for each platform, and so if you're having problems we'd like to help.

As Steve mentioned, it's hard to help you diagnose what's going on without more information. The ["installation difficulty" issue template](https://github.com/sparklemotion/nokogiri/issues/new?assignees=&labels=topic%2Finstallation&template=1-installation-difficulties.md&title=%5Binstall%5D) asked some questions that you've declined to answer. Perhaps you could try to help us understand what's going on more deeply?

One thing to consider is that `bundler` is a tool that controls the installation of gems -- so there's very little we can do from _within_ the gem to control `bundler`'s behavior. Have you taken a look at the [Installation docs](https://nokogiri.org/tutorials/installing_nokogiri.html) and the guidance there?
