### ISSUE TITLE
[bug] `node.replace` method reorders the document position automatically if nesting a tag with the same tag

### ISSUE THREAD

**Issue by yhagio** [sparklemotion/nokogiri#2472]
`node.replace` method reorders the document position automatically if nesting a tag with the same tag  (see example below)

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "Node#css" do
    it "should replace top level <div> with <p> tag" do
        test_value = '<div><p>Hello</p></div>'
        
        doc = Nokogiri::HTML::DocumentFragment.parse(test_value)
        doc.search('div').each do |node|
            node.replace("<p>#{node.children}</p>")
        end
        actual_result = doc.to_html
        
        expected_result = '<p><p>Hello</p></p>'
        assert_equal expected_result, actual_result
    end
  end
end
```

Output
```
  1) Failure:
Node#css#test_0001_should replace top level <div> with <p> tag [test_nokogiri.rb:18]:
Expected: "<p><p>Hello</p></p>"
  Actual: "<p></p><p>Hello</p>"
```
It should output like the expected result but ending up replaced the `div` with `p` tag but added it to the beginning 😢 

**Expected behavior**
`node.replace` should replace the node `<div>` with `<p>` without changing the order of the position.

**Environment**

Environment doesn't seem to matter but

ruby 3.0.3
nokogiri 1.13.2

**Comment by flavorjones** [comment]
@yhagio Thank you for opening this issue. I'll try to help!

In the example you've provided, the replacement HTML string being passed to `Node#replace` is `"<p><p>Hello</p></p>"` which is invalid HTML. We can see this by examining the syntax errors created during parsing:

```ruby
html_fragment = "<p><p>Hello</p></p>"
fragment = Nokogiri::HTML::DocumentFragment.parse(html_fragment)

fragment.to_html # => "<p></p><p>Hello</p>"
fragment.errors # => [#<Nokogiri::XML::SyntaxError: 1:32: ERROR: Unexpected end tag : p>]
```

We can also see this in the [HTML4 spec section 9.3.1](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1):

> The [P](https://www.w3.org/TR/html401/struct/text.html#edef-P) element represents a paragraph. It cannot contain [block-level elements](https://www.w3.org/TR/html401/struct/global.html#block-inline) (including [P](https://www.w3.org/TR/html401/struct/text.html#edef-P) itself).

If you use a tag combination that's valid then this approach works as expected:

```ruby
class Test < MiniTest::Spec
  describe "Node#replace" do
    it "should replace top level <div> with <p> tag" do
      test_value = "<div><em>Hello</em></div>"

      doc = Nokogiri::HTML::DocumentFragment.parse(test_value)
      doc.search("div").each do |node|
        node.replace("<p>#{node.children}</p>")
      end
      actual_result = doc.to_html

      expected_result = "<p><em>Hello</em></p>"
      assert_equal expected_result, actual_result
    end
  end
end
```

You have a few options that would modify the DOM tree structure directly, if you like. For example,

```ruby
      doc.search("div").each do |node|
        node.name = "p"
      end
```

or

```ruby
      doc.search("div").each do |node|
        node.replace(node.children.wrap("<p></p>").first)
      end
```

Does any of that help?

**Comment by yhagio** [comment]
@flavorjones Ohhhhh I see, thank you so much for your explanation and the details 🙏🏼 
It's very helpful and makes sense! 🙇🏼‍♂️
