### ISSUE TITLE
[help] different availability of EncodingHandler based on platform

### ISSUE THREAD

**Issue by jcsrb** [sparklemotion/nokogiri#2485]
**What problem are you trying to solve?**

use alpine linux based container to process html that has the `macintosh` encoding

debian based
```
❯ docker run  -it --rm ruby:bullseye bash
root@a70590422773:/# gem install nokogiri
Fetching nokogiri-1.13.3-aarch64-linux.gem
Successfully installed nokogiri-1.13.3-aarch64-linux
1 gem installed
root@a70590422773:/# irb
irb(main):001:0> require "nokogiri"
=> true
irb(main):002:0> Nokogiri::EncodingHandler['macintosh']
=> #<Nokogiri::EncodingHandler:0x0000ffff7d3ef530>
```

alpine based
```
❯  docker run  -it --rm ruby:alpine ash
/ # gem install nokogiri
Fetching nokogiri-1.13.3-aarch64-linux.gem
Successfully installed nokogiri-1.13.3-aarch64-linux
1 gem installed
/ # apk add gcompat
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
(1/3) Installing musl-obstack (1.2.2-r0)
(2/3) Installing libucontext (1.1-r0)
(3/3) Installing gcompat (1.0.0-r4)
OK: 20 MiB in 38 packages
/ # irb
irb(main):001:0> require "nokogiri"
=> true
irb(main):002:0>  Nokogiri::EncodingHandler['macintosh']
=> nil
```

I understand this **not** nokogiri fault in itself, but the likely the underlying iconv, but I am unclear how to make it work

Update 1
a related Stackoverflow question I found https://stackoverflow.com/questions/44143931/iconvlist-inconsistency-on-alpine-linux

Update 2
related I found an old mastodon commit but was not able to make it work 
https://github.com/mastodon/mastodon/pull/4494/files

I tried adding the way described in the mastodont commit without success
as well as adding `gnu-libiconv` to alpine and installing using local system libs
`gem install nokogiri --platform=ruby -- --use-system-libraries --with-iconv-lib=/usr/local/lib --with-iconv-include=/usr/local/include`
but seeing the same EncodingHandler missing

**Comment by flavorjones** [comment]
@jcsrb Thanks for opening this issue. After about 10 minutes of poking around, I'm pretty sure this is not something Nokogiri can control directly, but is something that we might be able to figure out.

Here's where I'm at. I build libxml2 with `-DDEBUG_ENCODING` to see what's going on when `macintosh` is successfully loaded, and see this:

```
$ ruby -Ilib -rnokogiri -e "pp Nokogiri::EncodingHandler['macintosh']"
Registered encoding handler for UTF-8
Registered encoding handler for UTF-16LE
Registered encoding handler for UTF-16BE
Registered encoding handler for UTF-16
Registered encoding handler for ISO-8859-1
Registered encoding handler for ASCII
Registered encoding handler for US-ASCII
Registered encoding handler for HTML
Found iconv handler for encoding Windows-31J
closed the encoding handler
Found iconv handler for encoding macintosh
#<Nokogiri::EncodingHandler:0x00007fa4aec8c918>
closed the encoding handler
```

The line `Found iconv handler for encoding macintosh` comes from libxml2's `encoding.c` function `xmlFindCharEncodingHandler` and tells us that iconv is able to support `macintosh` -> `UTF-8` transcoding.

I need to start my day job shortly, so I'll have to follow up later. But I think we should take a look at how iconv resolves these encodings, it may be as simple as installing a particular locale package on alpine to make this work?

**Comment by flavorjones** [comment]
Supporting my statements above, running `iconv -l` to display all the supported character set encodings ...

On `ruby:bullseye`:

```
root@8e640b0acecd:/# iconv -l
The following list contains all the coded character sets known.  This does
not necessarily mean that all combinations of these names can be used for
the FROM and TO command line parameters.  One coded character set can be
listed with several different names (aliases).

  437, 500, 500V1, 850, 851, 852, 855, 856, 857, 858, 860, 861, 862, 863, 864,
  865, 866, 866NAV, 869, 874, 904, 1026, 1046, 1047, 8859_1, 8859_2, 8859_3,
  8859_4, 8859_5, 8859_6, 8859_7, 8859_8, 8859_9, 10646-1:1993,
  10646-1:1993/UCS4, ANSI_X3.4-1968, ANSI_X3.4-1986, ANSI_X3.4,
  ANSI_X3.110-1983, ANSI_X3.110, ARABIC, ARABIC7, ARMSCII-8, ARMSCII8, ASCII,
  ASMO-708, ASMO_449, BALTIC, BIG-5, BIG-FIVE, BIG5-HKSCS, BIG5, BIG5HKSCS,
<snip>
  MAC-IS, MAC-SAMI, MAC-UK, MAC, MACCYRILLIC, MACINTOSH, MACIS, MACUK,
<snip>
  UCS-4LE, UCS2, UCS4, UHC, UJIS, UK, UNICODE, UNICODEBIG, UNICODELITTLE,
  US-ASCII, US, UTF-7, UTF-8, UTF-16, UTF-16BE, UTF-16LE, UTF-32, UTF-32BE,
  UTF-32LE, UTF7, UTF8, UTF16, UTF16BE, UTF16LE, UTF32, UTF32BE, UTF32LE,
  VISCII, WCHAR_T, WIN-SAMI-2, WINBALTRIM, WINDOWS-31J, WINDOWS-874,
  WINDOWS-936, WINDOWS-1250, WINDOWS-1251, WINDOWS-1252, WINDOWS-1253,
  WINDOWS-1254, WINDOWS-1255, WINDOWS-1256, WINDOWS-1257, WINDOWS-1258,
  WINSAMI2, WS2, YU

root@8e640b0acecd:/# iconv -l | fgrep -i macintosh
CSMACINTOSH//
MACINTOSH//
```

On `ruby:alpine`:

```
/ # iconv -l
UTF-8, UTF-16BE, UTF-16LE, UTF-32BE, UTF32-LE, UCS-2BE, UCS-2LE, WCHAR_T,
US_ASCII, ISO8859-1, ISO8859-2, ISO8859-3, ISO8859-4, ISO8859-5,
ISO8859-6, ISO8859-7, ...
```

Let's focus efforts here.

**Comment by jcsrb** [comment]
additionally related I found this blogpost https://www.justinsilver.com/technology/linux/alpine-linux-php-iconv-fix/ 
saying that `gnu-libiconv` did used to ship with `preloadable_libiconv.so` which fixed a related php issue , but no longer does in newer version of that package/of alpine

**Comment by flavorjones** [comment]
OK, on my debian system, running `strace` on the ruby process running `Nokogiri::EncodingHandler['macintosh']` reveals that libxml2/libiconv are getting this information from `/usr/lib/x86_64-linux-gnu/gconv/MACINTOSH.so`

```
$ dpkg-query -S /usr/lib/x86_64-linux-gnu/gconv/MACINTOSH.so
libc6:amd64: /usr/lib/x86_64-linux-gnu/gconv/MACINTOSH.so
```

This tells us that this file is delivered by the `libc6` package (list of files [here](https://packages.debian.org/sid/amd64/libc6/filelist)).

I think the goal for us has to be figuring out what package ships the equivalent file for alpine/musl. I don't have any relevant expertise, so I'm not sure how much help I can provide from here.

**Comment by flavorjones** [comment]
It may be worth trying to get Nokogiri to build from source and use `gnu-libiconv` instead of musl's default (very limited) iconv implementation.

Unfortunately that may be tricky to get right because of how Ruby's `mkmf` looks for and resolves external libraries; and it doesn't look like that package provides any of the advanced encodings, anyway (file list [here](https://pkgs.alpinelinux.org/contents?branch=edge&name=gnu-libiconv&arch=armhf&repo=community)).

If you do figure this out, I would love to work with you on documenting it and adding it to nokogiri.org. But for me personally, this will be a lower priority than some of the security and 1.14-targetted fixes and features, and so I don't think I'll be able to make time to keep working on it.

**Comment by flavorjones** [comment]
Something like this seems like it will link and load the gnu libiconv if it's installed:

```
env LDFLAGS=-liconv gem install nokogiri --platform=ruby
```

But again, without the `MACINTOSH.so` file this isn't going to succeed in handling that encoding. It may be worth building a version of Nokogiri this way and then play around with copying `MACINTOSH.so` to your alpine system and see if you can get gnu libiconv to load it.

**Comment by jcsrb** [comment]
thank you so much for digging into this @flavorjones, I didn't reach a functional setup and cutting my losses.
I ma no longer pursuing this as I am have the possibility to use a non-alpine image for what I need.

for anything looking further into this there exist the following alpine package
