### ISSUE TITLE
[install] nokogiri 1.13.3 on latest stable truffleruby 

### ISSUE THREAD

**Issue by HoneyryderChuck** [sparklemotion/nokogiri#2488]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

**What is the complete output of `gem install` or `bundle install`?**

You can find the output of the gem install [here](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/jobs/2257936986).

**Tell us about your system!**

Reproducible using the [docker image ](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/master/.gitlab-ci.yml#L106)

**Comment by flavorjones** [comment]
I see this in the log:

```
Extracting libxml2-2.9.13.tar.xz into
tmp/x86_64-unknown-linux-gnu/ports/libxml2/2.9.13... ERROR, review
'/builds/honeyryderchuck/rodauth-oauth/vendor/truffleruby/3.0.2.22.0.0/gems/nokogiri-1.13.3/ext/nokogiri/tmp/x86_64-unknown-linux-gnu/ports/libxml2/2.9.13/extract.log'
to see what happened. Last lines are:
========================================================================
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
gtar: Child returned status 2
gtar: Error is not recoverable: exiting now
========================================================================
```

Looking at the installation docs at https://nokogiri.org/tutorials/installing_nokogiri.html this exact string appears with instructions: https://nokogiri.org/tutorials/installing_nokogiri.html#tar-child-xz-cannot-exec-no-such-file-or-directory

**Comment by HoneyryderChuck** [comment]
Indeed, what a blunder 🙈  thx for the heads-up!
