### ISSUE TITLE
upstream remaining truffleruby patches

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2491]
See #1882 and #2095 for previous threads.

Conversation also happening in slack at https://graalvm.slack.com/archives/CMY63522F/p1648917137877149

---

Nokogiri patches live in https://github.com/oracle/truffleruby/blob/master/lib/truffle/truffle/patches/nokogiri_patches.rb

This approach is brittle in the face of trivial changes in Nokogiri's C extension. For example, [this patch](https://github.com/oracle/truffleruby/blob/aeb95dc5f03dc4397b8bc83acfc36cd53eeec188/lib/truffle/truffle/patches/nokogiri_patches.rb#L78-L81) has been broken since [this commit](https://github.com/sparklemotion/nokogiri/commit/9c5eed5) renamed `thing` to `retval`  in Nokogiri v1.13.0. This is coming up again in https://github.com/sparklemotion/nokogiri/pull/2489 where the code using variadic args is being modified and breaking more patches

One option is to upstream all of those changes, which I think would be preferable because it's easier to see and reason about.

**Comment by flavorjones** [comment]
Note to self re: truffle dev env: comment out rbenv init in .bashrc and launch a new shell

**Comment by aardvark179** [comment]
I think I've now got an approach that works for completely disabling the patches when not building with system libraries, and allowing them to still be used by older version (https://github.com/oracle/truffleruby/issues/2639#issuecomment-1095302734).

**Comment by flavorjones** [comment]
@aardvark179 That's great! Can you tell me which of these patches is still needed so I can upstream them? (I imagine the varargs workarounds are still needed?)

**Comment by flavorjones** [comment]
OK, closing this for now. I'll take a look at the truffle CI job which is failing in interesting ways.
