### ISSUE TITLE
[help] Should I worry that contains() may disappear from the CSS selector syntax?

### ISSUE THREAD

**Issue by walterdavis** [sparklemotion/nokogiri#2492]
I am using a css pseudo-selector and I worry it will disappear at some point. 

```
# given a Nokogiri::HTML document or fragment @doc
@doc.css("*:contains('youtube:')").each do |tube|
  ...
```
...works perfectly. But when I search MDN and CSS-Tricks, I see that this selector is an accident of time. It used to work in browsers, and was removed. Is there a chance that it will also disappear from Nokogiri's CSS selectors?

I believe that under the hood, the CSS interface in Nokogiri is translating any given selector into XPath. Is that what is responsible for this selector currently working?

I tried to convert this to pure XPath, but I was not able to get any matches, while the CSS version works perfectly. I am willing to concede that my XPath knowledge is really really old and likely broken from non-use.

Thanks for any advice or alternatives!

**Comment by walterdavis** [comment]
I did a little more digging, and found that I could use the Nokogiri::CSS.xpath_for method to return the computed XPath for the CSS selector, and that it was different than what I had tried (it used `.` where I was using `text()`). So I do see how to get a working XPath selector. But would it be advisable to change everything to use that, or do you think that the CSS interface would remain stable over time?

**Comment by flavorjones** [comment]
Hey @walterdavis,

You should assume that all of the CSS extensions we currently support will continue to be supported. Looking at this particular pseudoselector, though, I'm not sure we have good test coverage for it, so I'd like to take this opportunity to double-check add coverage if necessary.

**Comment by flavorjones** [comment]
Test coverage added in #2493

Let me know if you have any other questions, @walterdavis!

**Comment by walterdavis** [comment]
Thanks, Mike. This is the best answer I can imagine!

Walter
