### ISSUE TITLE
Fuzzy selection by content with XPath (or CSS)

### ISSUE THREAD

**Issue by svoop** [sparklemotion/nokogiri#2520]
I have to manipulate an AIXM 4.5 (XML) document similar to this snippet:

```xml
<?xml version="1.0" encoding="utf-8"?>
<AIXM-Snapshot (...)>
  <Ase>
    <AseUid>
      <codeType>R</codeType>
      <codeId>LS-R2 HOHGANT</codeId>
    </AseUid>
    <txtName>LS-R2 HOHGANT</txtName>
    <codeDistVerUpper>STD</codeDistVerUpper>
    <valDistVerUpper>130</valDistVerUpper>
    <uomDistVerUpper>FL</uomDistVerUpper>
    <codeDistVerLower>STD</codeDistVerLower>
    <valDistVerLower>100</valDistVerLower>
    <uomDistVerLower>FL</uomDistVerLower>
  <Ase>
    (...)
  </Ase>
  <Obs>
    (...)
  </Obs>
</AIXM-Snapshot>
```

The challenge is to select e.g. the first `Ase` node which contains an `AseUid` node which contains a `codeId` node with specific content:

`xpath("//Ase/AseUid/codeId[contains(text(), 'LS-R2 HOHGANT')]")`

This works fine, however, the name part `HOHGANT` is not known, so the search has to be shortened to:

`xpath("//Ase/AseUid/codeId[contains(text(), 'LS-R2 ')]")`

The space is necessary to prevent false positives e.g. with `LS-R26`.

Unfortunately, it gets messy. There are nodes which omit the name part and look like `<codeId>LS-R26A</codeId>`. The space trick above prevents them from being found.

XPath 2 impements a `matches` function to harness the power of regular expressions, but Nokogiri (or rather the underlying libxml2) doesn't seem to support this.

The CSS `contains()` selector has the same limitations.

Is there a way to perform such searches or even use regular expressions with XPath, CSS selectors or some other technique with Nokogiri?

(Plan B is to accept false positives and then eliminate them using Ruby. However, I still have hope that I missed something in the vast possibilities of Nokogiri.)

Thanks a lot for your help!

**Comment by svoop** [comment]
Found the silver bullet: custom pseudo classes

https://rubydoc.info/gems/nokogiri/1.13.4/Nokogiri/XML/Searchable#css-instance_method

**Comment by flavorjones** [comment]
@svoop Exactly right, this is sort of use case that the XPath custom functions (and CSS custom pseudo-classes) are intended to handle. Glad you figured it ou!

**Comment by dvergeylen** [comment]
[Doc for Xpath](https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri%2FXML%2FSearchable:xpath)

To elaborate a bit, one can provide methods defined in a custom class, and call them within the Xpath statement.

For instance:
```ruby
handler = Class.new {
  def my_custom_search_method(node_set, attr, regex)
    node_set.find_all { |node| node[attr] =~ /#{regex}/ }
  end
}.new

node.xpath('.//title[my_custom_search_method(., "name", "\w+")]', handler)
```

You can use the defined method(**s**) multiple times in the xpath statement.
