### ISSUE TITLE
[bug] Segmentation fault on "transform"

### ISSUE THREAD

**Issue by svoop** [sparklemotion/nokogiri#2536]
I'm trying to pretty print a large (some MB) XML file using the following stylesheet:

```xml
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" encoding="UTF-8" indent="yes"/>
  <xsl:strip-space elements="*"/>
  <xsl:template match="/">
    <xsl:copy-of select="."/>
  </xsl:template>
</xsl:stylesheet>
```

The transformation:

```ruby
Nokogiri::XSLT('pretty.xsl')).transform(xml)
```

While this works for small XML files, the big one causes a segfault:

```
"exception" : {
  "codes":"0x0000000000000001, 0x6b72616d2065676c",
  "rawCodes":[1,7742357830726149996],
  "type":"EXC_BAD_ACCESS",
  "signal":"SIGABRT",
  "subtype":"KERN_INVALID_ADDRESS at 0x6b72616d2065676c -> 0x0000616d2065676c (possible pointer authentication failure)"
},
  
"path" : "\/Users\/USER\/*\/nokogiri.bundle",
"name" : "nokogiri.bundle"
```

I'm not pasting the whole rap here, but I can send it e.g. by email if necessary.

Could this be a memory problem such as the process running out of available memory to perform the transformation on a big file?

macOS 12.3.1 (M1)
Ruby 3.1.2
Nokogiri 1.13.6
libxml2 2.9.14

**Comment by flavorjones** [comment]
Hi, @svoop. Thanks for reporting this, and sorry you're having issues.

I'll need to be able to reproduce this in order to understand what's going on. Email would be fine, if you're comfortable sharing the data file that way. I'm at mike.dalessio@gmail.com, and please put "nokogiri" in the subject line so I see it.

**Comment by svoop** [comment]
Hello @flavorjones, thanks for your reply!

I'm having a hard time extracting a failing example. The background: I'm building an XML document with Nokogiri's Builder, then apply the stylesheet, kaboom. If I skip the last step, write the XML to a file, then read the XML and apply the stylesheet, it works fine. (Besindes maybe the fact, that the 17-some-MB file takes almost 3 minutes to open on my new M1 MacBook.)

Marshalling the Nokogiri document is not possible, do you see another option?

Otherwise, you can quite easily install the my code (it's all gems) and I provide you with the source document and CLI which leads to the dump. It'll take a little more explaining I'm afraid compared to a clean and isolated test case. 

By the way: I've tried smaller junks, but they never segfault. Only the full document exposes this problem.

**Comment by flavorjones** [comment]
@svoop I'm not sure how to help if I can't reproduce the issue. While I appreciate you taking the time to report the problem, there isn't enough information here to even guess at where the problem could be. Can you provide _any_ more detail or working code?

**Comment by svoop** [comment]
@flavorjones I've tried to pin down the exact cause of the segfault, but so far, it looks as if the mere size triggers it. This said, I can tell you how to reproduce it or at least reproduce the exact situation. I just need a moment since it's a busy week, maybe later today or tomorrow.

**Comment by flavorjones** [comment]
@svoop Ping - can you do anything to help me reproduce this? If not, I'd like to close.

**Comment by svoop** [comment]
@flavorjones Thanks for calling back, in fact, I've worked around this issue by only applying the transformation to the segments which require it. 99% of the documents I build are pretty printed by the builder already, only included raw XML snippets have to be beautified. Closing...
