### ISSUE TITLE
Change html5lib parser to accommodate out-of-order test metadata

### ISSUE THREAD

**Issue by stevecheckoway** [sparklemotion/nokogiri#2555]
Regarding https://github.com/html5lib/html5lib-tests/pull/148, one possibility is we could change our parser for these tests to either give a warning when the test format is wrong or just handle out of order sections (or both).

As I recall, the code I wrote to parse these is…not great. I think I just cobbled a parser together that worked and then never revisited it.

**Comment by flavorjones** [comment]
I am about to submit a pull request to skip the test and emit a warning.

(I had started working a real racc-based parser earlier today but then punted because it was turning into a deep yak-shave.)

**Comment by stevecheckoway** [comment]
Yeah, understandable. It's a simple format…except it has some strange warts. My initial thought was to break up each test by section (or whatever it calls the lines that start with `#`), but I seem to recall that you really have to parse line by line.
