### ISSUE TITLE
Cut a v1.14.0 release

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2564]
[View current status of the miletstone here](https://github.com/sparklemotion/nokogiri/milestone/24).

Other chores needed for this release:

- [x] thank sponsors when v1.14.0 drops
  - [x] review https://github.com/sponsors/flavorjones/dashboard/your_sponsors?tier_id=125132
  - one time
    - [x] @dvrensk acknowledgement - https://twitter.com/dvrensk/status/1496056705511309318
    - [x] @daragiu acknowledgement
    - [x] @github acknowledgement
    - [x] @Julian88Tex acknowledgement
    - [x] @csimonmeunier acknowledgement
    - [x] @benSlaughter acknowledgement
    - [x] @gjtorikian acknowledgement
  - recurring
    - [x] @GoetzGoerisch acknowledgement
    - [x] @airbnb changelog acknowledgement
    - [x] @kyo-nanba acknowledgement
    - [x] @biximilien acknowledgement
    - [x] @renuo acknowledgement
    - [x] @dbootyfvrt acknowledgement - https://twitter.com/jbt122172/status/1568630069018460163
    - [x] @kyoshidajp acknowledgement
    - [x] @Homebrew acknowledgement
- [x] sponsor info on nokogiri.org
  - [x] update tidelift description
  - [x] add a github sponsors link
  - [x] add a link to opencollective
- [x] update dependency info
  - [x] update `LICENSE_DEPENDENCIES.md`
  - [x] update the jruby dependencies
  - [x] add `aarch64-linux` and `arm-linux` platform names
  - [x] collapse nokogumbo mention into libgumbo
  - [x] update gem description to mention libgumbo alongside libxml

**Comment by flavorjones** [comment]
Note that I've cut a release candidate: [Release 1.14.0.rc1 / 2022-12-29 · sparklemotion/nokogiri](https://github.com/sparklemotion/nokogiri/releases/tag/v1.14.0.rc1)

**Comment by larskanis** [comment]
I opened https://github.com/ruby/setup-ruby/pull/435 for adding RubyInstaller-3.2.0-1 for Windows to the CI.

**Comment by xfalcox** [comment]
Hey @flavorjones, do you plan to promote the current RC to a release anytime soon?

**Comment by flavorjones** [comment]
@xfalcox as noted in the release notes were waiting for a final release of rake-compiler-dock and that's what I'm working on today. Nokogiri release should be in the next day or so.

**Comment by flavorjones** [comment]
[Release 1.14.0 / 2023-01-12 · sparklemotion/nokogiri](https://github.com/sparklemotion/nokogiri/releases/tag/v1.14.0) :champagne:
