### ISSUE TITLE
Elaborate on meaning of NOBLANKS option.

### ISSUE THREAD

**Issue by keithrbennett** [sparklemotion/nokogiri#2570]
It would be nice to see the meaning of NOBLANKS elaborated on in the docs. I web searched and there was some confusion as to what it meant (e.g. at https://stackoverflow.com/questions/18040423/how-to-use-nokogiris-noblanks). Does it mean something like this (I'm sure you could say it better):

NOBLANKS - resuts in _not_ creating Text elements for text containing _only_ whitespace (anything matching `\s`), when that text is not inside an element

**Comment by flavorjones** [comment]
This "feature" simply exposes libxml2's feature of the same name. Libxml2's documentation is also lacking -- it literally only says "remove blank nodes". (Presumably only `text` nodes.)

I'd be happy to consider merging any documentation you wanted to contribute, either here or in https://github.com/sparklemotion/nokogiri.org !
