### ISSUE TITLE
[help] How do I use Noko_Node_Get_Struct in another project?

### ISSUE THREAD

**Issue by radar** [sparklemotion/nokogiri#2594]
**What problem are you trying to solve?**

[This commit](https://github.com/sparklemotion/nokogiri/commit/720d6f49ce2630f2e8b2b0a7aeda4fd8d8176734) from Nokogiri caused our application to start failing on SAML requests.

This is due to the `saml2` gem that we use, and a transitive dependency there called [nokogiri-xmlsec-instructure](https://github.com/instructure/nokogiri-xmlsec-instructure). This project uses `Data_Get_Struct`, but since this commit in Nokogiri, it will now make that data an incorrect type, causing a `TypeError`:

```ruby
      TypeError:
        wrong argument type Nokogiri::XML::Element (expected Data)
```

You can see this happen when running the tests on `nokogiri-xmlsec-instructure`.

I've attempted to submit [a pull request])(https://github.com/instructure/nokogiri-xmlsec-instructure/pull/13) to fix this issue, but I am unsure if what I'm doing is correct or even possible. I'm more of a Ruby-guy than a C-guy.

How can I change this gem so that I can continue using the latest and greatest Nokogiri releases that you all keep producing? ❤️

**Comment by flavorjones** [comment]
Whoa, sorry you're having problems, that's unexpected.

I will add the saml2 and/or xmlsec-instructure projects to the [set of downstream projects we run CI against](https://github.com/sparklemotion/nokogiri/blob/main/.github/workflows/downstream.yml) so that I have good signal on this going forward.

Let me take a look -- it may take a few hours though, today's a bit busy for me.

**Comment by flavorjones** [comment]
https://github.com/sparklemotion/nokogiri/pull/2595 is going through CI now which adds xmlsec to the suite

**Comment by flavorjones** [comment]
I submitted PR https://github.com/instructure/nokogiri-xmlsec-instructure/pull/14 upstream

**Comment by flavorjones** [comment]
I'm not sure what else I can do at this point, how can I help?

**Comment by radar** [comment]
Wow that's more than I expected. Thank you for helping out here :) We will use a fork with your commit in it -- that'll suit for our purposes.

**Comment by flavorjones** [comment]
> Wow that's more than I expected

Well, I feel bad that we broke something, we try pretty hard not to.
