### ISSUE TITLE
[bug] NokoGiri CVE requires a version that doesn't exist

### ISSUE THREAD

**Issue by gpinkham** [sparklemotion/nokogiri#2674]
The latest CVE for Nokogiri requires that we upgrade to 1.13.19.  I think there is a typo in the CVE database.  Not sure who is responsible for that

**Please describe the bug**

Bundle audit shows this: 
ruby-advisory-db:
  advisories:	611 advisories
  last updated:	2022-10-18 14:21:10 -0700
  commit:	ce18a9bafc805bd633a30cbe7c76f80261f4b6e7
Name: nokogiri
Version: 1.13.9
GHSA: GHSA-2qc6-mcvw-92cw
Criticality: Unknown
URL: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2qc6-mcvw-92cw
Title: Update bundled libxml2 to v2.10.3 to resolve multiple CVEs
Solution: upgrade to '>= **1.13.19**'

**Comment by darrenterhune** [comment]
https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2qc6-mcvw-92cw shows correct version but an upgrade produces the same error. Lines are crossed with 2 tyee chinooks and you're the only one in the boat 😂

**Comment by epinault** [comment]
Same here

**Comment by royalpeasantry** [comment]
+1 - It also seems that I can't ignore it either since it doesn't seem to have a CVE linked correctly and that seems to be the only way bundle audit allows you to ignore advisories.

![image](https://user-images.githubusercontent.com/8637162/196564470-2acad2bf-e05a-484f-bb86-ddaf6b5f9932.png)

**Comment by tjwp** [comment]
Looks like there is a PR to fix it here: https://github.com/rubysec/ruby-advisory-db/pull/519

**Comment by royalpeasantry** [comment]
PR just got merged - our audit is now passing with version `1.13.9`

**Comment by flavorjones** [comment]
As has been discussed, this is not an issue with nokogiri but with the ruby-advisory-db project.
