### ISSUE TITLE
[bug] nokogiri.h includes ruby.h after other headers

### ISSUE THREAD

**Issue by eregon** [sparklemotion/nokogiri#2696]
**Please describe the bug**

See https://github.com/sparklemotion/nokogiri/blob/cd2700ab2a8b981d555e40c9f355ed22cbf5f161/ext/nokogiri/nokogiri.h#L68
So ruby.h is included after many other headers.

One issue I noticed with that is that for instance `_GNU_SOURCE` is defined by Ruby headers but not by nokogiri or the headers before, and so as a result e.g. `_DEFAULT_SOURCE` (which would be set if `_GNU_SOURCE` was defined at the time, in `/usr/include/features.h`) and as a result `__USE_MISC` are not defined, which means the first include of `sys/select.h` does not define `fd_mask` and `NFDBITS`, which means `rb_fdset_t` is the one from [`intern/select/posix.h`](https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/select/posix.h) and not the expected one from https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/select/largesize.h.
This means if rb_thread_fd_select() would be used by nokogiri it would most likely segfault or behave incorrectly.

A solution seems to include `ruby/defines.h` or `ruby.h` before other headers, then everything should be consistent.

I noticed this because I added a `#error` in TruffleRuby if `intern/select/posix.h` gets included as that would be a bug if rb_thread_fd_select() gets used with an inconsistent definition of `rb_fdset_t`.

This seems an unfortunate pitfall of C, because the first include of `features.h` decides features for all future-included headers.

**Help us reproduce what you're seeing**

Adding `#error "this file should not be indluded"` manually in ruby's `intern/select/posix.h` should reproduce this when installing nokogiri from source.

**Environment**

Fedora 35

**Comment by flavorjones** [comment]
PR at #2698.

**Comment by eregon** [comment]
FYI what I ended up doing in TruffleRuby to preserve the check that select/posix.h is not included is to not define `rb_fdset_t` and its `rb_fd_*` functions and `rb_thread_fd_select()` if `NFDBITS` is not set as expected. At least that should prevent using the wrong `rb_fdset_t`, at the cost of the behavior being possibly surprising.
