### ISSUE TITLE
in progress: ship native gem with precompiled Ruby 3.2 support

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2740]
This is an issue just to let folks know that this is on its way. Some last-minute changes were made in Ruby around how C extensions are linked on MacOS (Darwin) and we're working through the details.

If you're interested, you can read up a bit on those changes at https://github.com/rake-compiler/rake-compiler-dock/issues/87 or https://github.com/sparklemotion/nokogiri/pull/2732

I hope to have a version shipped within the next few days.

**Comment by kapso** [comment]
@flavorjones Also running into this issue on Linux...

`nokogiri-1.13.10-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is incompatible with the current version, 3.2.0`

**Comment by flavorjones** [comment]
We haven't shipped native 3.2 support for any platform yet. No need to comment to let me know, I'm the one working on it! Thanks for your patience.

**Comment by flavorjones** [comment]
Use the "Ruby" platform and compile upon installation, or use system libraries, if you need it to work with 3.2 right now

**Comment by edmz** [comment]
In case someone else needs this, the way to do it is with this in the Gemfile:

```ruby
gem 'nokogiri', force_ruby_platform: true
```

(let me know if I didn't get this right)

**Comment by kapso** [comment]
@edmz I tried this, and it did not work, at least not on Heroku

**Comment by flavorjones** [comment]
I've cut a prerelease: [Release 1.14.0.rc1 / 2022-12-29 · sparklemotion/nokogiri](https://github.com/sparklemotion/nokogiri/releases/tag/v1.14.0.rc1)

Please let's move conversation about Ruby 3.2 support there. Thank you!
