### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by Mac8899** [sparklemotion/nokogiri#2754]
**What problem are you trying to solve?**

**Please show your code!**

**Environment**

**Additional context**

Please I need help
Each time I try MSFCONSOLE it says could not find nokogiri 1.8.0 in any source
And each time I try to run  
bundle install 
Could not locate Gemfile
Please someone should help me I have been try this for the past 3days and am getting sick concerning it please I need help

**Comment by flavorjones** [comment]
I'd like to help. You haven't provided enough information for me to understand your problem.  I don't know what MSFCONSOLE is, I don't know why you're trying to use a version of Nokogiri that is five years old, and four years past end-of-life.

Please help me help you by providing enough information for me to reproduce what you're seeing.

**Comment by Mac8899** [comment]
This command helped me install metasploit into my termux app
cd $HOME;wget https://raw.githubusercontent.com/efxtv/Metasploit-in-termux/main/metasploit-6-termux.sh -q;bash metasploit-6-termux.sh

 
And when I ran the command "bundle install"
It was unable to install nokogiri 1.8.0 
And that what metasploit 6 needed and when I ran nokogiri base on my phone system it was v 1.13.10 and metasploit need 1.8.0

But I manage to fix it by run some commands as stated here
Gem install bundle
Gem install bundler
Pip3 install bundler
Bundler install -j5
Bundle update 

After running this commands
Msfconsole started loading and once it has open it command page 
This error came out 
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb:342:in `<class:Code>': undefined method `=~' for class `Pry::Code' (NameError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb:32:in `<class:Pry>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb:5:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry.rb:70:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/rex/ui/text/shell.rb:126:in `run'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'
Please sir can you help me fix it

**Comment by flavorjones** [comment]
> when I ran nokogiri base on my phone system it was v 1.13.10

Seems like a recent version of Nokogiri is installed properly on your system.

> and metasploit need 1.8.0

Nokogiri 1.8.0 is no longer supported. It doesn't look like metasploit pins to this version (see https://github.com/rapid7/metasploit-framework/blob/master/metasploit-framework.gemspec#L83) so I'm not sure why you think that's the case.

```
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb:342:in <class:Code>': undefined method =~' for class Pry::Code' (NameError) from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb:32:in class:Pry'
```

This error message does not indicate Nokogiri is a problem. Please try asking for help on a metaploit forum.
