### ISSUE TITLE
[install] [1.14.0] Cannot install via Gradle

### ISSUE THREAD

**Issue by boris-petrov** [sparklemotion/nokogiri#2762]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

Sorry I'm not using the rest of the issue template but it doesn't fit my case. Reproduction:

```gradle
plugins {
	id 'com.github.jruby-gradle.base' version '2.0.2'
}

repositories {
	mavenCentral()
	ruby.gems()
}

dependencies {
	gems 'rubygems:nokogiri:1.14.0'
}
```

If you put that in `build.gradle` and run `gradle jrubyPrepare`, it will fail:

```
exception thrown for request to /rubygems/nokogiri/1.14.0/ivy.xml
com.github.jrubygradle.api.gems.GemVersionException: 'isorelax' does not look like a GEM version requirement
```

And a big stack-trace. Using Gradle 7.6, Java 19.0.1 on Linux.

Downgrading to `1.13.0` fixes the issue. I've got no idea what that error is, probably some issue in `nokogiri` or in Gradle's JRuby plugin. Let me know what you think. Thanks!

**Comment by flavorjones** [comment]
Thanks for reporting. I'll take a look after the weekend. I'm not familiar with Gradle but maybe someone from the JRuby team can lend a hand.

**Comment by flavorjones** [comment]
@mkristian @headius Do either of you understand what's going on here? I'm inclined to close this and ask for an upstream issue to be created.

**Comment by mkristian** [comment]
This is for sure a gradle-jruby-plugin problem. At least nothing we can solve from nokogiri, especially as the version of isorelax is not controlled by us.

**Comment by boris-petrov** [comment]
Opened an issue there. Thanks for the support!

**Comment by flavorjones** [comment]
Thanks, all!
