### ISSUE TITLE
Nokogiri gem install [help]

### ISSUE THREAD

**Issue by petchen123** [sparklemotion/nokogiri#2766]
**What problem are you trying to solve?**

Hello, I want to know if all Nokogiri versions require Ruby version >= 2.7, < 3.3.dev. In my gemfile, I specified that I want to install nokogiri 1.13.10, but it still shows me the following error message when I try to run gem install bundler -v 1.17.3 && gem install rails -v 6.1.3

```
Building native extensions. This could take a while...
ERROR:  Error installing rails:
	The last version of nokogiri (>= 1.8.5) to support your Ruby & RubyGems was 1.13.10. Try installing it with `gem install nokogiri -v 1.13.10` and then running the current command again
	nokogiri requires Ruby version >= 2.7, < 3.3.dev. The current ruby version is 2.6.6.146.
Successfully installed racc-1.6.2
The command '/bin/sh -c gem install bundler -v 1.17.3 && gem install rails -v 6.1.3' returned a non-zero code: 1

```

**Please show your code!**

Gemfile

```ruby
ruby '2.6.6'

gem 'nokogiri', '1.13.10'
```

**Environment**

```
Nokogiri (1.13.10)
```

**Additional context**

**Comment by flavorjones** [comment]
Sorry you're having problems. I'll try to help.

(In the future, please fill out the  "Installation difficulties" issue template when reporting installation problems. That template prompts you for more information about your system which helps us diagnose problems. Thank you!)

In summary, I'd advise you to upgrade rubygems to the most recent version possible and try again.

The details behind this recommendation:

- When you run `gem install X` you're not running bundler, so your Gemfile is irrelevant, unfortunately. No matter what it says, `gem` doesn't look at it, so you're experiencing behavior specific to the `gem` command (and not the `bundler` command).
- Nokogiri v1.13.x supports Ruby 2.6. Nokogiri v1.14.x does not. This error message is likely reporting problems installing Nokogiri v1.14.x with Ruby 2.6.
- There have been many rubygems bugfixes over the last few months related to choosing the right gem for your version of Ruby and your architecture. The version you're running is likely not new enough to have these bugfixes. I want to suggest that you run `gem update --system` and try again.

I'll keep this open for a bit in case you have more questions, but please do let me know if this advice works for you or not.

**Comment by petchen123** [comment]
the issue is fixed now. thank you very much!
