### ISSUE TITLE
Content removed after single tag (hr) without self closing forward slash [bug]

### ISSUE THREAD

**Issue by Laykou** [sparklemotion/nokogiri#2834]
When having HTML with `<hr>` without self-closing tag like `<hr />`, the content afterward is removed.

```ruby
Nokogiri.parse('<div>foo<hr>bar</div>').root.inner_html
 => "foo<hr>"
```

In this case 'bar' was removed.

When using `<hr />` it works:
```ruby
Nokogiri.parse('<div>foo<hr />bar</div>').root.inner_html
 => "foo<hr>bar"
```

**Expected behavior**

Parsing should return `'foo<hr>bar'` in both cases.

**Additional context**

Tested on versions 1.14.0 and 1.14.2

**Comment by stevecheckoway** [comment]
You're parsing that HTML fragment as XML but it's not well-formed XML.
```ruby
irb(main):012:0> doc = Nokogiri.parse('<div>foo<hr>bar</div>')
=>
#(Document:0x3b4e8 {
...
irb(main):013:0> doc.errors
=>
[#<Nokogiri::XML::SyntaxError: 1:22: FATAL: Opening and ending tag mismatch: hr line 1 and div>,
 #<Nokogiri::XML::SyntaxError: 1:22: FATAL: Premature end of data in tag div line 1>]
```

If you parse it using `Nokogiri::HTML.parse()` or `Nokogiri::HTML5.parse()`, you won't get any errors, but you won't get your expected output because you're parsing a fragment as a document.

This should do what you want:
```ruby
irb(main):022:0> Nokogiri::HTML5.fragment('<div>foo<hr>bar</div>').to_html
=> "<div>foo<hr>bar</div>"
```

**Comment by Laykou** [comment]
Thank you. We have a use case where we're putting either a whole document or a partial HTML fragment.

In such case fragment does not work well on full HTML documents then.

Is there some method which could work well for both?

**Comment by stevecheckoway** [comment]
If you want to parse a fragment, you should use `Nokogiri::HTML5.fragment()`, if you want to parse a full document, you should use `Nokogiri::HTML5.parse()`. The HTML standard specifies how fragments and documents should be parsed and the methods in `Nokogiri::HTML5` try to follow that precisely. However, there are slight differences between a fragment parse and a document parse and no way to distinguish the two cases based on their content.

**Comment by Laykou** [comment]
Thank you for explanation 👍🏻

**Comment by stevecheckoway** [comment]
You're welcome!
