### ISSUE TITLE
[journal] tracking (likely spurious) `ruby_memcheck` errors in CI

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2838]
On occasion, the `ruby_memcheck` job in CI raises a failure that isn't obviously fixable within Nokogiri.

My memory is soft, so I'm creating this issue to track these when they show up to see if there's a pattern that we can either

1. identify as an issue that is fixable within Nokogiri
2. if it's something we can ignore (e.g., a memory pool within Ruby) then we can updated `ruby_memcheck` to skip that function / those functions.

I really feel like I need to collect more data before I go back to Peter with a PR for `ruby_memcheck`, so this is where we'll keep that history for now.

**Comment by flavorjones** [comment]
https://github.com/sparklemotion/nokogiri/actions/runs/4580734520/jobs/8089726674#step:7:4483

```
160 bytes in 1 blocks are definitely lost in loss record 29,850 of 40,713
  malloc (vg_replace_malloc.c:307)
  objspace_xmalloc0 (gc.c:11462)
  ary_heap_alloc (array.c:329)
  ary_heap_alloc (array.c:320)
  ary_resize_capa (array.c:453)
  ary_double_capa (array.c:507)
  ary_ensure_room_for_push (array.c:654)
  rb_ary_push (array.c:1311)
 *__xmlRaiseError (error.c:604)
 *htmlParseErr (HTMLparser.c:101)
 *htmlParseEndTag (HTMLparser.c:4201)
 *htmlParseContentInternal (HTMLparser.c:4742)
 *htmlParseDocument (HTMLparser.c:4998)
 *htmlDoRead (HTMLparser.c:6921)
 *rb_html_document_s_read_memory (html4_document.c:111)
  vm_call_cfunc_with_frame (vm_insnhelper.c:3037)
  vm_sendish (vm_insnhelper.c:4751)
```

My memory is soft, but I think the past warnings have also been this. It seems like we're appending to the `errors` array while parsing a file, and ruby increases the capacity of the array to do do.

This isn't obviously something that Nokogiri can do anything about, and my suspicion is that we should consider adding `rb_double_capa` (or a related function) to `ruby_memcheck`'s `DEFAULT_SKIPPED_RUBY_FUNCTIONS`.

**Comment by flavorjones** [comment]
Got another one in https://github.com/sparklemotion/nokogiri/actions/runs/5003753830/jobs/8965429361?pr=2879

```
56 bytes in 2 blocks are definitely lost in loss record 22,856 of 42,925
  malloc (vg_replace_malloc.c:307)
  objspace_xmalloc0 (gc.c:11465)
  str_new0 (string.c:900)
  rb_enc_str_new (string.c:946)
 *Nokogiri_wrap_xml_syntax_error (xml_syntax_error.c:53)
 *Nokogiri_error_array_pusher (xml_syntax_error.c:33)
 *__xmlRaiseError (error.c:632)
 *htmlParseErr (HTMLparser.c:105)
 *htmlSkipBogusComment (HTMLparser.c:2540)
 *htmlParseContentInternal (HTMLparser.c:4865)
 *htmlParseDocument (HTMLparser.c:5040)
 *htmlDoRead (HTMLparser.c:6945)
 *rb_html_document_s_read_memory (html4_document.c:111)
```

**Comment by flavorjones** [comment]
Ah, seeing this again in https://github.com/sparklemotion/nokogiri/actions/runs/5109807473/jobs/9184996846#step:9:4666

```
37 bytes in 1 blocks are definitely lost in loss record 14,780 of 40,712
  malloc (vg_replace_malloc.c:307)
  objspace_xmalloc0 (gc.c:11465)
  str_new0 (string.c:900)
  rb_enc_str_new (string.c:946)
 *Nokogiri_wrap_xml_syntax_error (xml_syntax_error.c:53)
 *Nokogiri_error_array_pusher (xml_syntax_error.c:33)
 *__xmlRaiseError (error.c:632)
 *htmlParseErr (HTMLparser.c:105)
 *htmlParseComment (HTMLparser.c:3517)
 *htmlParseContentInternal (HTMLparser.c:4863)
 *htmlParseDocument (HTMLparser.c:5041)
 *htmlDoRead (HTMLparser.c:6954)
 *rb_html_document_s_read_memory (html4_document.c:111)
```

**Comment by flavorjones** [comment]
Here's a new one: https://github.com/sparklemotion/nokogiri/actions/runs/5331554430/jobs/9659562905

```
240 (120 direct, 120 indirect) bytes in 1 blocks are definitely lost in loss record 31,456 of 40,765
  malloc (vg_replace_malloc.c:381)
  objspace_xmalloc0 (gc.c:11465)
 *xmlNewNodeEatName (tree.c:2315)
 *xmlNewDocNodeEatName (tree.c:2390)
 *xmlSAX2StartElementNs (SAX2.c:2287)
 *xmlParseStartTag2.constprop.0 (parser.c:9419)
 *xmlParseElementStart (parser.c:9796)
 *xmlParseContentInternal (parser.c:9664)
 *xmlParseElement (parser.c:9734)
 *xmlParseDocument (parser.c:10588)
 *xmlDoRead (parser.c:14613)
 *read_memory (xml_document.c:378)
  vm_call_cfunc_with_frame (vm_insnhelper.c:3037)
```

**Comment by peterzhu2118** [comment]
I've debugged these issues and opened an issue at https://github.com/Shopify/ruby_memcheck/issues/23.

Unfortunately, I'm out of ideas for solutions.

**Comment by flavorjones** [comment]
I've merged #2944, so we shouldn't see the `rb_ary_push`/`ary_heap_alloc` from this point on in Ruby 3.3. If I don't see any other suspicious valgrind errors in the next few weeks, I'll probably close this.

**Comment by flavorjones** [comment]
@peterzhu2118 Here's one I don't recall having seen before:

https://github.com/sparklemotion/nokogiri/actions/runs/5973403817/job/16205611406#step:9:4649

```
3,024 bytes in 63 blocks are definitely lost in loss record 38,215 of 39,411
  malloc (vg_replace_malloc.c:381)
  objspace_xmalloc0 (gc.c:11465)
  rb_obj_transient_heap_evacuate (variable.c:1458)
  transient_heap_block_evacuate.constprop.0 (transient_heap.c:733)
  transient_heap_evacuate (transient_heap.c:807)
  rb_postponed_job_flush (vm_trace.c:1728)
  rb_threadptr_execute_interrupts (thread.c:2444)
  rb_threadptr_execute_interrupts (thread.c:2417)
  rb_vm_check_ints (vm_core.h:2003)
  rb_vm_check_ints (vm_core.h:1999)
  vm_pop_frame (vm_insnhelper.c:415)
  rb_vm_pop_frame (vm_insnhelper.c:424)
  vm_call0_cfunc_with_frame (vm_eval.c:152)
  vm_call0_cfunc (vm_eval.c:163)
  vm_call0_body (vm_eval.c:209)
  rb_vm_call0 (vm_eval.c:57)
  vm_call_super (vm_eval.c:326)
  rb_call_super_kw (vm_eval.c:334)
 *strio_initialize (stringio.c:203)
  vm_call0_cfunc_with_frame (vm_eval.c:149)
  vm_call0_cfunc (vm_eval.c:163)
  vm_call0_body (vm_eval.c:209)
  vm_call0_cc (vm_eval.c:86)
  rb_call0 (vm_eval.c:550)
  rb_call (vm_eval.c:876)
```

**Comment by peterzhu2118** [comment]
This is likely the same issue as Shopify/ruby_memcheck#23, however the source of allocation is hidden because it was allocated during an evacuation out of the transient heap. I think the only solution to this is to not use ruby_memcheck on Rubies < 3.3 (or add a suppression for `rb_obj_transient_heap_evacuate`, but you'll still run into other issues when the transient heap is filled, so this is not really a good solution).
