### ISSUE TITLE
[upstream] html5lib-tests head has failing tests

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2841]
Updates to upstream https://github.com/html5lib/html5lib-tests are failing in Nokogiri's "upstream" CI:

- https://github.com/sparklemotion/nokogiri/actions/runs/4594272018/jobs/8113098993

These failures are from one of these two commits:

- https://github.com/html5lib/html5lib-tests/commit/4f45c0211cf1d1f1af319470f77851f60f29914c
- https://github.com/html5lib/html5lib-tests/commit/1314b094ed2c4e418404576c24b88aae2ea4e0c1

Here's the output for the seven failing tests:

```
Failure:
TestHtml5TreeConstructionWebkit02#test_11 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
Minitest::Assertion: Wrong number of errors for <b><em><dcell><postfield><postfield><postfield><postfield><missing_glyph><missing_glyph><missing_glyph><missing_glyph><hkern><aside></b></em>.
Expected: 0
  Actual: 3

Failure:
TestHtml5TreeConstructionWebkit02#test_11__with_node [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
Minitest::Assertion: Wrong number of errors for <b><em><dcell><postfield><postfield><postfield><postfield><missing_glyph><missing_glyph><missing_glyph><missing_glyph><hkern><aside></b></em>.
Expected: 0
  Actual: 3

Failure:
TestHtml5TreeConstructionWebkit01#test_26 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
Minitest::Assertion: Wrong number of errors for <html><body></body>
   <!-- Hi there --></html>.
Expected: 0
  Actual: 1

Failure:
TestHtml5TreeConstructionWebkit01#test_27 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
Minitest::Assertion: Wrong number of errors for <html><body></body></html>
   <!-- Hi there -->.
Expected: 0
  Actual: 1

Failure:
TestHtml5TreeConstructionTemplate#test_107 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
Minitest::Assertion: Wrong number of errors for <body></body><template>.
Expected: 0
  Actual: 3

Failure:
TestHtml5TreeConstructionTemplate#test_106 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
Minitest::Assertion: Wrong number of errors for <html><head></head><template></template><head>.
Expected: 0
  Actual: 3

Failure:
TestHtml5TreeConstructionTemplate#test_110 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:24]
Minitest::Assertion: Expected: "template"
  Actual: "html"
```

**Comment by liyang1473** [comment]
> Updates to upstream https://github.com/html5lib/html5lib-tests are failing in Nokogiri's "upstream" CI:
> 
> - https://github.com/sparklemotion/nokogiri/actions/runs/4594272018/jobs/8113098993
> 
> These failures are from one of these two commits:
> 
> - https://github.com/html5lib/html5lib-tests/commit/4f45c0211cf1d1f1af319470f77851f60f29914c
> - https://github.com/html5lib/html5lib-tests/commit/1314b094ed2c4e418404576c24b88aae2ea4e0c1
> 
> Here's the output for the seven failing tests:
> 
> ```
> Failure:
> TestHtml5TreeConstructionWebkit02#test_11 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
> Minitest::Assertion: Wrong number of errors for <b><em><dcell><postfield><postfield><postfield><postfield><missing_glyph><missing_glyph><missing_glyph><missing_glyph><hkern><aside></b></em>.
> Expected: 0
>   Actual: 3
> 
> Failure:
> TestHtml5TreeConstructionWebkit02#test_11__with_node [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
> Minitest::Assertion: Wrong number of errors for <b><em><dcell><postfield><postfield><postfield><postfield><missing_glyph><missing_glyph><missing_glyph><missing_glyph><hkern><aside></b></em>.
> Expected: 0
>   Actual: 3
> 
> Failure:
> TestHtml5TreeConstructionWebkit01#test_26 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
> Minitest::Assertion: Wrong number of errors for <html><body></body>
>    </html>.
> Expected: 0
>   Actual: 1
> 
> Failure:
> TestHtml5TreeConstructionWebkit01#test_27 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
> Minitest::Assertion: Wrong number of errors for <html><body></body></html>
>    .
> Expected: 0
>   Actual: 1
> 
> Failure:
> TestHtml5TreeConstructionTemplate#test_107 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
> Minitest::Assertion: Wrong number of errors for <body></body><template>.
> Expected: 0
>   Actual: 3
> 
> Failure:
> TestHtml5TreeConstructionTemplate#test_106 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:120]
> Minitest::Assertion: Wrong number of errors for <html><head></head><template></template><head>.
> Expected: 0
>   Actual: 3
> 
> Failure:
> TestHtml5TreeConstructionTemplate#test_110 [/__w/nokogiri/nokogiri/test/html5/test_tree_construction.rb:24]
> Minitest::Assertion: Expected: "template"
>   Actual: "html"
> ```

**Comment by flavorjones** [comment]
Upstream PR: https://github.com/html5lib/html5lib-tests/pull/165

Nokogiri PR: https://github.com/sparklemotion/nokogiri/pull/2842

Presumptively closing this issue.
