### ISSUE TITLE
[bug] java.lang.UnsupportedClassVersionError: org/cyberneko/dtd/DTDConfiguration

### ISSUE THREAD

**Issue by malcolm-pro** [sparklemotion/nokogiri#2887]
We've been seeing this error under Java 8 starting with v1.14:

```
java.lang.UnsupportedClassVersionError: org/cyberneko/dtd/DTDConfiguration has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

That's a pretty common error when trying to run libraries compiled for Java 11 under Java 8. It looks like this is due to the newer [nekodtd jar](https://github.com/sparklemotion/nokogiri/blob/main/lib/nokogiri/jruby/org/nokogiri/nekodtd/0.1.11.noko1/nekodtd-0.1.11.noko1.jar). I might have missed something, but I don't see any minimum Java version requirements listed, so I've been assuming Nokogiri is still compatible with Java 8. If this is the case, maybe this jar needs to be recompiled under Java 8? If this is _not_ the case, and Nokogiri 1.14+ needs Java 11:

1) could that be listed in the main Readme?
2) is there a way to recompile just this library locally for Java 8 and use that in the gem?
3) if not, will `force_ruby_platform: true` in the Gemfile/gemspec avoid loading this JAR?

FWIW, JRuby did mention in the 9.3.0.0 release notes that they're considering dropping Java 8 support, and Java 8 is quite long in the tooth, but afaik Java 8 is still supported (and as of last year [was still quite widely used](https://newrelic.com/resources/report/2022-state-of-java-ecosystem)).

**Comment by flavorjones** [comment]
@malcolm-pro Sorry you're having problems!

I will admit to a very low level of knowledge around Java version support in JRuby and in the vendored Java libraries.

That said, the vendored `nekodtd.jar` that's is built by the Nokogiri maintainers from https://github.com/sparklemotion/nekodtd, though -- see https://github.com/sparklemotion/nokogiri/issues/2437 and https://github.com/sparklemotion/nekodtd/issues/1 for context -- so I may be able to build it in such a way that it still supports Java 8.

cc @headius in case you're able to point me in the right direction.

**Comment by flavorjones** [comment]
OK, so I rebuild nekodtd.jar with Java 8 and ran into more issues:

```
ext/java/nokogiri/internals/NokogiriXPathFunction.java:33: error: NokogiriXPathFunction is not abstract and does not override abstract method evaluate(List) in XPathFunction
public class NokogiriXPathFunction implements XPathFunction
       ^
ext/java/nokogiri/internals/NokogiriXPathFunction.java:55: error: name clash: evaluate(List<?>) in NokogiriXPathFunction and evaluate(List) in XPathFunction have the same erasure, yet neither overrides the other
  evaluate(List<?> args) throws XPathFunctionException
  ^
ext/java/nokogiri/internals/dom2dtm/DOM2DTM.java:482: warning: [deprecation] isWhiteSpace(String) in XMLCharacterRecognizer has been deprecated
          suppressNode &= XMLCharacterRecognizer.isWhiteSpace(n.getNodeValue());
                                                ^
2 errors
```

which again are under the Nokogiri maintainers' control, but I'm not excited about doing this work since I'm not a JRuby user and don't honestly know if this is actually a problem for anyone (you're the first person to ask about Java 8 support).

@headius WDYT about restoring support for Java 8? Is it worth the additional maintenance burden?

**Comment by flavorjones** [comment]
@headius Thanks for the context and the offer.

I have a CI pipeline that I'm trying to get working at https://github.com/sparklemotion/nokogiri/pull/2889.

The above error may be a red herring -- it happens if I compile Nokogiri with Java 8 ... however I think I can still compile with Java 11 and it will run on Java 8. The CI pipeline will tell me if I'm wrong, and in that case I'll need your help.

**Comment by malcolm-pro** [comment]
@flavorjones I'd also be happy to work on this if you can give me the build/test steps that you're using; I've been de-facto managing the JVM ecosystem (JRuby/Java/Scala) at our company for several years now and have a little cross-compatibility experience.

**Comment by flavorjones** [comment]
New org.nokogiri:nekodtd version cut, v0.1.11.noko2, Information at https://github.com/sparklemotion/nekodtd/issues/2

**Comment by flavorjones** [comment]
https://github.com/sparklemotion/nokogiri/releases/tag/v1.15.2

**Comment by headius** [comment]
Great news, thanks @flavorjones!

**Comment by flavorjones** [comment]
@headius You're welcome! It was an easier fix than I'd anticipated :tada:

**Comment by malcolm-pro** [comment]
@flavorjones This was a mini-masterclass in efficient & well-covered project management. Thank you!
