### ISSUE TITLE
Non-reproducible crash when pressing Ctrl-C

### ISSUE THREAD

**Issue by forthrin** [sparklemotion/nokogiri#3052]
**Please describe the bug**

Nokogiri 1.15.5, Ruby 3.2.2, macOS Sonoma, MacBook Air M1

Let me know if this is relevant, and what parts of the crash logs to provide, if any.

```
^C
-- nokogiri-1.15.5-arm64-darwin/lib/nokogiri --
xml/document.rb:181:in `initialize': Interrupt
html5/document.rb:130:in `initialize'
html5/document.rb:123:in `parse'
html5/document.rb:123:in `do_parse'
html5/document.rb:95:in `parse'
html5.rb:31:in `HTML5'

-- libruby.3.2.dylib --
rb_vm_bugreport
rb_bug_for_fatal_signal
sig_do_nothing
finalize_deferred_heap_pages
finalize_deferred_heap_pages
rb_objspace_call_finalizer
rb_ec_cleanup
ruby_run_node
```

**Comment by flavorjones** [comment]
Hi @forthrin, thanks for opening this issue.

I think what you're seeing is related to a bug that has been reported upstream already: https://bugs.ruby-lang.org/issues/19865 (Note that Ctrl-C generates a `TERM` signal) and has a proposed fix: https://github.com/nobu/ruby/commit/69ef8fa9762d74c93a2218e66037d92ad4ebc414

I don't think there's anything we can easily do within Nokogiri to prevent this, so I'm going to close this. If you have followup questions, please do feel free to ask!

**Comment by forthrin** [comment]
Yep, I remember now. Just very annoying to break scripts and have to scroll hundreds of lines back past the crash to see output. So patching below and compiling should fix the issue? Any idea why the fix hasn't been committed?

https://github.com/ruby/ruby/compare/master...nobu:ruby:signal-at-cleanup

**Comment by flavorjones** [comment]
I have zero context, please feel free to ask upstream.

**Comment by forthrin** [comment]
Don't have a Ruby issue tracker account, unfortunately. Will just have to wait it out, I guess. If you can drop a quick link there to these issues, I'd really appreciate it.

**Comment by flavorjones** [comment]
If you can confirm that the patch in that ticket addresses the problem for you, I'd be happy to follow up with ruby-core. But again, I cannot reproduce and so I cannot validate the fix.

**Comment by forthrin** [comment]
I'm actually not able to reproduce the crash with a compiled version, even when going back to and beyond the Homebrew release (ruby 3.4.5 2025-07-16 revision 20cda200d3).

This means that anyone using the Homebrew version will be stuck with the crash unless the cause can be pinpointed.

Any idea how the Homebrew version could be built differently that could provoke this?

**Comment by flavorjones** [comment]
I have no context on this, so I cannot give you an answer.

If you decide to open an issue with Homebrew, please link it here so I can follow along.

**Comment by forthrin** [comment]
Yes, it makes sense that they might be the culprit, or at least give a comment.
