### ISSUE TITLE
Nokogiri::XML::NodeSet#to_xhtml adds invalid CDATA tags

### ISSUE THREAD

**Issue by JonCrawford** [sparklemotion/nokogiri#311]
Run the following gist: https://gist.github.com/f1ec33937642648a78cb

Notice the `<![CDATA[ ]]>` tag that is created inside the `<style>` tag.  This is bad because `CDATA` tags inside `<style>` tags require CSS comments around them or they have they cause the CSS to not be parsed by the browser.

Info here about `CDATA` tags: http://en.wikipedia.org/wiki/CDATA#Use_of_CDATA_in_program_output

Fixies?

**Comment by flavorjones** [comment]
Confirmed bug still present upstream in libxml 2.9.4.

**Comment by flavorjones** [comment]
I believe this behavior was introduced in libxml 2.6.31 in https://github.com/GNOME/libxml2/commit/dbd6105 and appears to be intentional. Closing.
