### ISSUE TITLE
clone & singleton classes

### ISSUE THREAD

**Issue by marcandre** [sparklemotion/nokogiri#316]
If a specific Nokogiri::HTML::Document extends a module M, a clone of that document won't.

I expected otherwise, since in Ruby all builtin classes, as well as user created classes will copy the singleton_class when cloning.

Thakns!

require 'nokogiri'
require 'open-uri'

module M; def foo; end end

doc = Nokogiri::HTML(open('http://www.google.com/search?q=tenderlove'))
doc.extend M
doc.clone.respond_to? :foo # => false, should be true

**Comment by flavorjones** [comment]
Description of differences between `dup` and `clone` [here](https://stackoverflow.com/questions/10183370/whats-the-difference-between-rubys-dup-and-clone-methods) and [here](https://ruby-doc.org/core-2.5.1/Object.html#method-i-dup-label-on+dup+vs+clone)

**Comment by flavorjones** [comment]
Picked up this work yesterday, see progress in https://github.com/sparklemotion/nokogiri/pull/3117

"Better late than never" as they say :sweat_smile:
