### ISSUE TITLE
Feature Request: Option to Treat `noscript` Tags as Script Enabled

### ISSUE THREAD

**Issue by taisehub** [sparklemotion/nokogiri#3178]
Nokogiri parses `<noscript>` tags as script disabled mode.
Could you consider adding a option in the parsing settings to handle `<noscript>` tags as script is enabled mode?
 This could allow for more flexible parsing depending on the user's needs.

Ref: https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element

**Comment by flavorjones** [comment]
@taisehub Thanks for opening this issue. We'll look into it!

**Comment by flavorjones** [comment]
@stevecheckoway Any thoughts on whether this is a good idea and/or how challenging it would be to support script mode?

**Comment by stevecheckoway** [comment]
@flavorjones I think this should be easy to do. The parsing change itself should be completely straight forward. I think there are three places it matters: in head, in body, and fragment parsing with a `noscript` element as the context.

Adding a new option makes me think we should consider cleaning up the [parse](https://github.com/sparklemotion/nokogiri/blob/main/ext/nokogiri/gumbo.c#L325) and [fragment](https://github.com/sparklemotion/nokogiri/blob/141568888242f801a1afd1dcf22adb6846eff8a1/ext/nokogiri/gumbo.c#L418) functions so as to not keep adding additional arguments. That said, these functions are purely internal so maybe that doesn't matter so much. Do you have an opinion on that?

**Comment by flavorjones** [comment]
@stevecheckoway I've got a draft branch that cleans up those methods to use keyword arguments, I should be able to clean it up and create a PR in the morning (along with a few other smaller pieces of HTML5 fragment cleanup I also had on a branch).
