### ISSUE TITLE
html5lib test suite should run tests with the scripting flag enabled and disabled unless one is specified

### ISSUE THREAD

**Issue by stevecheckoway** [sparklemotion/nokogiri#3242]
I don't want this to slip my mind. See
https://github.com/sparklemotion/nokogiri/pull/3231#pullrequestreview-2116034091 for details.

**Comment by flavorjones** [comment]
#3231 was merged and will be shipped in v1.17.0!

**Comment by flavorjones** [comment]
Whoops, reopening.
