### ISSUE TITLE
Give Nokogiri::HTML::Document a parent which always returns nil

### ISSUE THREAD

**Issue by mfn** [sparklemotion/nokogiri#325]
Hi,

take any node somewhere in a document and (for whatever reason) traverse up its parent chain. Inevitably when getting to the Nokogiri::HTML::Document node an error will be raised, because there's no parent method.

This makes traversing the parent cumbersome, because one can't simply rely on the parent method itself, e.g.

```
$ ruby -r pp -r nokogiri -e 'Nokogiri::HTML("<html><div><span></span></div></html>").search("span").each { |s| while s = s.parent; puts s; end }'
<div><span></span></div>
<body><div><span></span></div></body>
<html><body><div><span></span></div></body></html>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div><span></span></div></body></html>
-e:1:in `block in <main>': undefined method `parent' for #<Nokogiri::HTML::Document:0x00000000d28180> (NoMethodError)
        from /opt/ruby-1.9.1-p378/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.3.1/lib/nokogiri/xml/node_set.rb:239:in `block in each'
        from /opt/ruby-1.9.1-p378/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.3.1/lib/nokogiri/xml/node_set.rb:238:in `upto'
        from /opt/ruby-1.9.1-p378/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.3.1/lib/nokogiri/xml/node_set.rb:238:in `each'
        from -e:1:in `<main>'
```

It requires a check whether .parent is availabile

```
$ ruby -r pp -r nokogiri -e 'Nokogiri::HTML("<html><div><span></span></div></html>").search("span").each { |s| while s.respond_to?("parent") and s = s.parent; puts s; end }'
```

I can't foresee the implication if document would have a parent method which simply always returns nil, but I think it could be a useful addition.

thanks

**Comment by Anyoks** [comment]
Got into a similar problem. I need to traverse all parent DOMS but i can't move beyond the first element because a document has no parent. I second @mfn . Addition of the parent = nil for the document will be very useful.

**Comment by mfn** [comment]
> @mfn Where did you add this? i'd like to do the same.

Since in Ruby you can open up any class, I *think* I just threw it into the script which did the parsing. But I'm not using ruby at the moment so there may be other/better best practices.
