### ISSUE TITLE
[bug] /path/to/nokogiri-1.17.0/lib/nokogiri/xml/document_fragment.rb:117: [BUG] YJIT panicked

### ISSUE THREAD

**Issue by yahonda** [sparklemotion/nokogiri#3365]
Recently Rails CI with YJIT enabled raises these exceptions.

https://buildkite.com/rails/rails-nightly/builds/1434#0193a813-c727-4191-8e3b-b5d977beb27f/1241-1302

```
/usr/local/lib/ruby/gems/3.4.0+1/gems/nokogiri-1.17.0/lib/nokogiri/xml/document_fragment.rb:117: [BUG] YJIT: panicked at /usr/src/ruby/yjit/src/cruby.rs:432:13:
```

https://buildkite.com/rails/rails/builds/114565#0193ad65-402e-4e1f-bdb3-6e4becad6827/1251-1303
```
/usr/local/bundle/gems/nokogiri-1.17.0/lib/nokogiri/xml/document_fragment.rb:117: [BUG] YJIT panicked
```

I have attempted to reproduce it locally as follows, I have NOT able to reproduce it yet.

```ruby
git clone https://github.com/rails/rails
cd rails
git clone https://github.com/rails/buildkite-config .buildkite/
RUBY_IMAGE=rubylang/ruby:master docker-compose -f .buildkite/docker-compose.yml build base
CI=1 docker compose -f .buildkite/docker-compose.yml run -e RUBY_YJIT_ENABLE=1 -e SEED=4940 --rm default runner actiontext 'rake test'
```

**Expected behavior**

All of Action Pack Unit test should pass

**Environment**
`nokogiri -v` command is not available from Rails CI. Here is the nokogiri version and Ruby version used:

https://buildkite.com/rails/rails-nightly/builds/1434#0193a813-c727-4191-8e3b-b5d977beb27f/201-814
```
    nokogiri (1.17.0)
```

https://buildkite.com/rails/rails-nightly/builds/1434#0193a813-c727-4191-8e3b-b5d977beb27f/201-207
```
Ruby          3.4.0p-1 (2024-12-08 revision dd43af3be7eddb832c77ef367456fa023fed7d7a) [x86_64-linux]
```

**Additional context**

**Comment by flavorjones** [comment]
There were known issues with v1.17.0. Please upgrade to v1.17.1 and if you still have issues, comment and I'll re-open.

**Comment by flavorjones** [comment]
Context: https://github.com/sparklemotion/nokogiri/issues/3359
