### ISSUE TITLE
builder namespaces are broken

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#384]
this code:

    Nokogiri::XML::Builder.new { |xml| xml['foo'].bar }

results in this error:

    /home/miked/.rvm/gems/ruby-1.8.7-p302/gems/nokogiri-1.4.4/lib/nokogiri/xml/builder.rb:315:in `[]': undefined method `namespace_definitions' for #<Nokogiri::XML::Document:0x3f9e4ccf7fe0 name="document"> (NoMethodError)

when it should result in a tag like:

    <foo:bar />

**Comment by ccutrer** [comment]
This is fixed in 1.5.8
