### ISSUE TITLE
Nokogiri adds 'default' Namespace to elements

### ISSUE THREAD

**Issue by nickcanz** [sparklemotion/nokogiri#391]
I have a situation where I'm using nokogiri to do the following:

1. Extract some nodes from a generated xml file
2. Put extracted nodes into a simple template file
3. Save the template file out as a new file

# My Ruby code

    require 'nokogiri'
    
    input = "input.wxs"
    template = "template.wxs"
    output = "output.wxs"
    
    input_file = Nokogiri::XML(File.open(input))
    template_file = Nokogiri::XML(File.open(template))
    
    #get stuff from input file 
    stuff = input_file.at_css("Directory[Id='TARGETDIR']")
    
    #where to insert in template file 
    insert_point = template_file.at_css("DirectoryRef[Id='InstallDir']")
    
    insert_point.children= stuff.children()
    
    #write out filled template to output file
    File.open(output, 'w') { |f| template_file.write_xml_to f }

# input file

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
        <Product>
            <Package />
            <Directory Id="TARGETDIR" Name="SourceDir">
                <Component>
                    <File />
                </Component>
            </Directory>
        </Product>
    </Wix>

# template file

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns='http://schemas.microsoft.com/wix/2006/wi'>
      <Fragment Id='MSIComponents'>
          <DirectoryRef Id='InstallDir'>
          </DirectoryRef>
      </Fragment>
    </Wix>

# Actual Output

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
      <Fragment Id="MSIComponents">
          <DirectoryRef Id="InstallDir">
                <default:Component>
                    <File/>
                </default:Component>
            </DirectoryRef>
      </Fragment>
    </Wix>

### Expected output 

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
      <Fragment Id="MSIComponents">
          <DirectoryRef Id="InstallDir">
                <Component>
                    <File/>
                </Component>
            </DirectoryRef>
      </Fragment>
    </Wix>

### Nokogiri -v

warnings: []

nokogiri: 1.4.4.1
ruby:
  version: 1.9.2
  platform: i386-mingw32
  engine: ruby
libxml:
  binding: extension
  compiled: 2.7.7
  loaded: 2.7.7

**Comment by ylecuyer** [comment]
:+1: Any update on this ? @flavorjones

**Comment by flavorjones** [comment]
Confirmed this is still an issue with Nokogiri 1.6.8.rc3.

**Comment by flavorjones** [comment]
Updated example code:

```
#! /usr/bin/env ruby

require 'nokogiri'

input = <<EOX
<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
    <Product>
        <Package />
        <Directory Id="TARGETDIR" Name="SourceDir">
            <Component>
                <File />
            </Component>
        </Directory>
    </Product>
</Wix>
EOX

template = <<EOX
<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns='http://schemas.microsoft.com/wix/2006/wi'>
  <Fragment Id='MSIComponents'>
      <DirectoryRef Id='InstallDir'>
      </DirectoryRef>
  </Fragment>
</Wix>
EOX

input_file = Nokogiri::XML(input)
template_file = Nokogiri::XML(template)

# get stuff from input file, put into template
stuff = input_file.at_css("Directory[Id='TARGETDIR']")
insert_point = template_file.at_css("DirectoryRef[Id='InstallDir']")
insert_point.children = stuff.children()

puts template_file.to_xml
```

**Comment by mpsuzuki** [comment]
@jrochkind , have you filed a separate issue? I've in the similar trouble and trying to find the root of the problem is too old nokogiri or still some workarounds for this issue are needed.

**Comment by jrochkind** [comment]
No, I think I just gave up on my approach, can't recall sorry.

**Comment by mpsuzuki** [comment]
thanks! still it's helpful info.
