### ISSUE TITLE
pure java version re-orders html attributes unnecessarily

### ISSUE THREAD

**Issue by tmm1** [sparklemotion/nokogiri#445]
MRI version returns the same string as passed in:

```
$ ruby -rubygems -ve' require "nokogiri"; p Nokogiri::VERSION; p Nokogiri::HTML::DocumentFragment.parse("<a href='/test' class='test'>test</a>").to_html '
ruby 1.8.7 (2010-12-23 patchlevel 330) [i686-darwin10.5.0]
"1.5.0.beta.4"
"<a href=\"/test\" class=\"test\">test</a>"
```

on JRuby however, the output has the attributes swapped:

```
$ ruby -rubygems -ve' require "nokogiri"; p Nokogiri::VERSION; p Nokogiri::HTML::DocumentFragment.parse("<a href='/test' class='test'>test</a>").to_html '
jruby 1.6.0 (ruby-1.8.7-p330) (2011-04-06 aa7d946) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_24) [darwin-x86_64-java]
"1.5.0.beta.4"
"<a class=\"test\" href=\"/test\">test</a>"
```

**Comment by brauliobo** [comment]
MRI's nokogiri seems to order ascending alphabetically, while JRuby's Nokogiri order descending, see https://travis-ci.org/github/opener-project/property-tagger/jobs/742428723

**Comment by headius** [comment]
@brauliobo It seems like that is not the case to me. The first result is descending but almost all the others are ascending. As far as I know we do not impose any ordering and allow the XML library to render as it chooses. I have also looked into this in the past and found that libxml does not impose any ordering either, but many small examples may appear to be ordered.

I would recommend creating a larger test case with more attributes of different names and values to test this theory. XML attribute ordering is not defined by any spec, but if you can prove that libxml or the CRuby logic in Nokogiri are imposing a sorted order on attributes where the JRuby version does not, that may be worth opening a new issue.
