### ISSUE TITLE
:last css selector not working in DocumentFragment

### ISSUE THREAD

**Issue by brain-geek** [sparklemotion/nokogiri#454]
Test to reproduce bug:

      def test_last_fragment
        text = '<p>Lorem ipsum</p><p>Second paragraph</p><div>Not paragraph</div>'
        fragment = Nokogiri::HTML.fragment text
        
        assert_equal(1, fragment.search('p:last').size)
        assert_equal(1, fragment.css('p:last').size)
      end

Looks like this works with document, but fails in fragment.

**Comment by flavorjones** [comment]
Folding this into #572, the underlying issue is the same.
