### ISSUE TITLE
CSS3 :not() with children selectors

### ISSUE THREAD

**Issue by rrivas** [sparklemotion/nokogiri#528]
When I attempt to use nokogiri with doc.css('.r .l:not(.mslg .l)') I receive the error

```
Nokogiri::CSS::SyntaxError: unexpected ' ' after '#<Nokogiri::CSS::Node:0x007fb4ab5f4940>'
```

I am simply trying to get urls from a google search page.  This is what I'm doing

```
doc = Nokogiri::HTML(open("http://www.google.com/search?sourceid=chrome&ie=UTF-8&q=Honda+Cerritos+CA"))
doc.css('.r .l:not(.mslg .l)')
```

**Comment by flavorjones** [comment]
I'm open to accepting a pull request for this functionality, but am unlikely to do that work myself. Closing.
