### ISSUE TITLE
XML line limit

### ISSUE THREAD

**Issue by leejarvis** [sparklemotion/nokogiri#533]
I'm having issues parsing and fetching the line numbers for a feed of XML which exceeds 65535 lines. Of course the limit of an unsigned short integer is 65535 which is why I assume this fails. Once this limit is hit the line number doesn't increase, which screws our return info. I haven't been able to look into this any further or to see if it's reasonable to change this type of integer (or whether this is an libxml issue?), but thought I'd post it anyway. Thanks!

**Comment by fulldecent** [comment]
Sample implementation for storing higher numbers:

https://github.com/rubys/nokogumbo/pull/55/files

Saving here for reference.

**Comment by flavorjones** [comment]
This will be fixed in v1.13.
