### ISSUE TITLE
xmlMemSetup should not be used even in module inialization.

### ISSUE THREAD

**Issue by obache** [sparklemotion/nokogiri#545]
xmlMemSetup() is used in Init_nokogiri() of ext/nokogiri/nokogiri.c, except MacRuby.
But xmlMemSetup has to be called before any other libxml routines, so I feel it should not be used in ext library.

For example, I want to use Ruby/RSVG (a part of Ruby-GNOME2) together with Nokogiri:
  require "rsvg2"
  require "nokogiri"

With just above two lines, it always crash for me, because librsvg-2.0  is using libxml-2.0 internally.

**Comment by flavorjones** [comment]
Closing, pending a test case that reproduces the reported error.
