### ISSUE TITLE
HTML includes XML declaration and DOCTYPE on JRuby

### ISSUE THREAD

**Issue by dnagir** [sparklemotion/nokogiri#590]
When using with Capybara and JRuby 1.6.5 (1.9 mode) the `page.html` returns something that looks like:

```ruby
> page.html

"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"...."
```

We can clearly see that `<?xml version="1.0" encoding="UTF-8">` has been inserted which changes the resulting output.
Also the DOCTYPE is transitional HTML 4.01, but this is not correct either because the page was generated with DOCTYPE for HTML5.

This doesn't happen on MRI 1.9.3.

Any clues how to fix/workaround it?

(Originally [opened on the Capybara](https://github.com/jnicklas/capybara/issues/570) but was pointed to the Nokogiri).

**Comment by flavorjones** [comment]
This doesn't appear to be a problem at this point in time, so I'm closing. Please let me know if you feel it should remain open.
