### ISSUE TITLE
Should support .css("+xyz") and .css(">abc")

### ISSUE THREAD

**Issue by dlee** [sparklemotion/nokogiri#621]
In jQuery, it's convenient to try looking for a node that follows another by doing:

``` html
<div>
  <dt>blah
  <dd>blah
  <dt>blah
  <dd>blah
</div>
```

``` javascript
$("dt").find("+dd")
```

_The above example is contrived, but it's just an illustration_

It would be nice if nokogiri also supported +sibling notation on the current node.

_**Update:_\* Nokogiri should also support .css(">abc") as well, and it'd probably be the same fix, so I'm adding it to this bug.*

**Comment by tenderlove** [comment]
#623 was merged, so I think we can close this.
