### ISSUE TITLE
XML::Schema#validate(filename) returns 0 errors for malformed documents

### ISSUE THREAD

**Issue by bts** [sparklemotion/nokogiri#642]
It seems that `Nokogiri::XML::Schema#validate` for filenames (not `Nokogiri::XML::Document`s) does not return any errors for malformed XML documents: only for well-formed documents that do not conform to the provided schema.

``` ruby
require 'nokogiri'

Nokogiri::VERSION
# => "1.5.3.rc3"

RUBY_VERSION
# => "1.9.3"

bad_xml_data = 'xyz'
xsd_data = <<-XSD
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.example.org/contactExample"
  xmlns:tns="http://www.example.org/contactExample"
  elementFormDefault="qualified">
  <xs:element name="Contacts"></xs:element>
</xs:schema>
XSD

malformed_xml_path = '/tmp/malformed.xml'

File.open(malformed_xml_path, 'w') { |f| f.write(bad_xml_data) }
# => 3

schema = Nokogiri::XML::Schema.new(xsd_data)
# => #<Nokogiri::XML::Schema:0x007feea9c40c80>

schema.validate(malformed_xml_path)
# => []

schema.valid?(malformed_xml_path)
# => true
```

**Comment by flavorjones** [comment]
This is still a valid bug, and we should probably figure out how to better handle this case.

**Comment by flavorjones** [comment]
The above example does return an error if we call `#validate` on a `Document` ... but the error is "The document has no document element" which is actually returned by `xmlSchemaValidateDoc` before it even gets around to the actual schema validation.

The JRuby implementation exhibits the same behavior as `validate_file` regardless of whether we are passing a `Document` or a file path ... which makes me think maybe this behavior is actually OK?

That said, there's some real code debt here in the CRuby implementation. Some things to research:

* what is the return value of `xmlSchemaValidateDoc` and `xmlSchemaValidateFile`? Are we incorrectly considering the absence of errors to indicate validity? Should we be also using the return value?
* look at the JRuby implementation and understand why it's considering a malformed doc to be valid
* if a file is passed, should we parse it into a `Document` (likely with the `strict` or `norecover` parse options set) and fail if there are errors on that? should we raise that error to signal malformedness, or should we simply indicate that the document is invalid?

**Comment by flavorjones** [comment]
PR #3261 should fix this.
