### ISSUE TITLE
HTML::DocumentFragment.parse strips newlines when used outside node context

### ISSUE THREAD

**Issue by tozz** [sparklemotion/nokogiri#668]
``` ruby
example = "<p>test</p>\n"
test = Nokogiri::HTML::DocumentFragment.parse(example)
ap test.to_html(:save_with => 0)
"<p>test</p>"
```

As you can see Nokogiri erroneously strips a newline that is part of the string, newlines are just as valid as any other letter and shouldn't pointlessly be removed.

**Comment by flavorjones** [comment]
I'll note for posterity that the change to use unclosed `html` and `body` tags was to address #315.

Further, it does appear that with modern versions of libxml2 (e.g., 2.9.9) that the newline is no longer dropped:

```
#! /usr/bin/env ruby

require 'nokogiri'

example = "<p>test</p>\n"
test = Nokogiri::HTML::DocumentFragment.parse(example)
test.to_html(:save_with => 0)
# => "<p>test</p>\n"
```

so I'll go ahead and close this.
