### ISSUE TITLE
Specifying encoding on a SAX parser does not work

### ISSUE THREAD

**Issue by soulcutter** [sparklemotion/nokogiri#671]
If you try to specify any encoding other than UTF-8 or ASCII, the encoding does not appear to 'take'. As far as I can tell it's an issue with libxml2 . I suspect that it's not just the SAX parser, but I haven't dug any deeper at this point.

Easy way to show the problem:

``` ruby
Nokogiri::XML::SAX::ParserContext.io(StringIO.new('<a>sdf</a>'.encode('utf-16be')), Nokogiri::XML::SAX::Parser::ENCODINGS['UTF16BE'])
parser error : xmlSwitchToEncoding : no input
```

**Comment by flavorjones** [comment]
This error is being emitted here:

```
#0  xmlSwitchToEncodingInt (ctxt=0x947800, handler=0x9146f0, len=90) at parserInternals.c:1268
#1  0x00007ffff5f35016 in xmlSwitchEncoding (ctxt=0x947800, enc=XML_CHAR_ENCODING_UTF16BE) at parserInternals.c:1100
#2  0x00007ffff5f356e1 in xmlNewIOInputStream (ctxt=0x947800, input=0x947710, enc=XML_CHAR_ENCODING_UTF16BE) at parserInternals.c:1391
#3  0x00007ffff5f5a9dc in xmlCreateIOParserCtxt (sax=0x0, user_data=0x0, ioread=0x7ffff5f16950 <io_read_callback>, ioclose=0x7ffff5f16a70 <io_close_callback>, 
    ioctx=0xb1d780, enc=XML_CHAR_ENCODING_UTF16BE) at parser.c:12656
#4  0x00007ffff5f12a42 in parse_io (klass=6626360, io=11655040, encoding=<optimized out>) at ../../../../ext/nokogiri/xml_sax_parser_context.c:30
```

where `ctxt->input` is NULL. I believe that `xmlNewIOInputStream` is supposed to be setting `ctxt->input` with the newly-created `inputStream` but is not. This looks like a big in libxml2 that we should send back upstream.

Tagging as `libxml`

**Comment by flavorjones** [comment]
Noting that this issue still exists in libxml 2.9.9.

**Comment by flavorjones** [comment]
Similar to #918

**Comment by nwellnhof** [comment]
This might be fixed in libxml2 now.

**Comment by flavorjones** [comment]
@nwellnhof Indeed it is! :heart:
