### ISSUE TITLE
Let us mock HTTP Requests in XSD validation

### ISSUE THREAD

**Issue by dmathieu** [sparklemotion/nokogiri#706]
Hello,

I'm using nokogiri in my tests to validate generated XML documents with a schema.
My schems imports namespaces available online, like [dublincore's dcterms](http://dublincore.org/schemas/xmls/qdc/dcterms.xsd) for example.
As it is intended to do, validating the document makes calls to these namespaces urls. They are, however, not subjected to changes.

And it makes my tests very slow and impossible to run without an internet connection.
Would it be possible to mock these http calls, like I could do with [webmock](https://github.com/bblimke/webmock) if the calls were made with NET::HTTP ?

**Comment by cwant** [comment]
Just encountered the same issue. A test suite (that I didn't write) tries to validate a MODS document. The schema definition references external resources, so the test only works with a functioning internet connection. I'd hoped WebMock would make it good, but no luck.

**Comment by flavorjones** [comment]
@cwant if you could, please open a new issue with this request, and perhaps a description of how you'd like it to work. it's unlikely i'll have time to work on it, and in all honesty it will likely require hacking the underlying XML engine(s), but I'm open to ideas and definitely open to pull requests.
