### ISSUE TITLE
Integer attribute value gets SyntaxError

### ISSUE THREAD

**Issue by crystalneth** [sparklemotion/nokogiri#711]
doc = Nokogiri::HTML("")
doc.css("img[width=200]")

Gives

Nokogiri::CSS::SyntaxError: unexpected '200' after 'equal'

**Comment by vstange** [comment]
same problem, any suggestion for this specific case?

**Comment by ar7max** [comment]
But the correct example should be
`page.css("li[data-category='news']")`

Take a look at quotes

**Comment by flavorjones** [comment]
Workaround is to quote the string, but we can fix this in the CSS parser.

**Comment by vstange** [comment]
Thanks
