### ISSUE TITLE
Possible crash in nokogiri

### ISSUE THREAD

**Issue by romanbsd** [sparklemotion/nokogiri#714]
I'm not 100% sure that it's Nokogiri to blame, and I was unable to reproduce this "in vitro". The crash happens in heavily threaded environment (sidekiq), and this is the C-level dump:

<pre>
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x17c1e5) [0x7f181d6a51e5] vm_dump.c:796
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x5d13b) [0x7f181d58613b] error.c:258
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(rb_bug+0xb7) [0x7f181d586fe7] error.c:277
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x11081f) [0x7f181d63981f] signal.c:609
/lib/x86_64-linux-gnu/libc.so.6(+0x364c0) [0x7f181d1a24c0] array.c:1586
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(st_lookup+0xe) [0x7f181d64163e] st.c:326
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x1686c7) [0x7f181d6916c7] vm_method.c:374
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(rb_check_funcall+0x74) [0x7f181d69df84] vm_eval.c:274
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(rb_check_convert_type+0xc7) [0x7f181d5d7287] object.c:2055
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(rb_ary_to_ary+0x9) [0x7f181d55e819] array.c:1249
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x16ae35) [0x7f181d693e35] vm_insnhelper.c:1646
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x171a9a) [0x7f181d69aa9a] vm.c:1220
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x172f43) [0x7f181d69bf43] vm_eval.c:66
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(rb_funcall+0xc5) [0x7f181d69cab5] vm_eval.c:456
/usr/lib/x86_64-linux-gnu/libxml2.so.2(+0x42de3) [0x7f17ee196de3] bignum.c:234
/usr/lib/x86_64-linux-gnu/libxml2.so.2(+0x49cf6) [0x7f17ee19dcf6] complex.c:164
/usr/lib/x86_64-linux-gnu/libxml2.so.2(xmlParseChunk+0x219) [0x7f17ee19f449] complex.c:404
vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.4/lib/nokogiri/nokogiri.so(+0x99ca) [0x7f17ee9089ca] xml_sax_push_parser.c:38
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x175941) [0x7f181d69e941] vm_insnhelper.c:404
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/lib/libruby.so.1.9(+0x16b609) [0x7f181d694609] insns.def:1015
...
</pre>

The libxml used is: libxml2-2.7.8.dfsg-5.1ubuntu4

On the ruby level, the crash is always in:

    vendor/bundle/ruby/1.9.1/gems/celluloid-0.11.0/lib/celluloid/internal_pool.rb:48:in `block in create'

which simply does proc.call

**Comment by flavorjones** [comment]
Closing, pending more information from the original poster.
