### ISSUE TITLE
How can i parse current page??

### ISSUE THREAD

**Issue by geun** [sparklemotion/nokogiri#746]
im using nokogiri in rails app.

i wanna do parse current page. 

so i search many article but nobody say answer.

only parse open(url) or open(file)..

anybody know how to parse current page?

**Comment by mmlumba** [comment]
I've been looking for the answer for this as well, and the current docs don't mention anything in the search HTML/XML page....http://www.nokogiri.org/tutorials/searching_a_xml_html_document.html

**Comment by flavorjones** [comment]
http://www.nokogiri.org/tutorials/parsing_an_html_xml_document.html#from_the_internets
