### ISSUE TITLE
Adding #fetch support to XML::Node ?

### ISSUE THREAD

**Issue by andyw8** [sparklemotion/nokogiri#765]
The docs say

```
A Nokogiri::XML::Node may be treated similarly to a hash with regard to attributes.
```

but one thing I miss from this hash-like behaviour is `#fetch`, which would raise an error if the given key doesn't exist. This can be helpful for avoiding nils being inadvertently passed around, leading to hard-to-find bugs.

Would this be worth adding?

**Comment by flavorjones** [comment]
I've noted this in the ROADMAP doc and as I approach what might be a 2.0 release later this year or early next year, I'm keeping this topic top-of-mind. However, in the meantime to lower the cognitive overhead of the backlog, I'm going to close this.
