### ISSUE TITLE
Parsing HTML5 with <time> element generates error

### ISSUE THREAD

**Issue by gkellogg** [sparklemotion/nokogiri#800]
Running Nokogiri 1.5.5 on Ruby 1.9.3p327 try the following:

```
Nokogiri::HTML.parse(%{<time datetime="2011-11-28"></time>}).errors
```

It generates the following:

```
[#<Nokogiri::XML::SyntaxError: Tag time invalid>] 
```

This worked in a previous version. The time element is valid, although at one time it was removed. Any variation using <time> fails.

**Comment by flavorjones** [comment]
Nokogiri's underlying HTML parsers (libxml2 for CRuby, nekoHTML for JRuby) are HTML4 parsers, and so for some time there hasn't been much we can do to help with HTML5 other than to recommend that people use the Nokogumbo gem, which extends Nokogiri's API and provides an HTML5 parser.

I'm happy to let you know that #2204 is driving the merger of Nokogumbo and its HTML5 parser, and so Nokogiri v1.12 will support HTML5 once it is release. Please follow that issue for status updates.
