### ISSUE TITLE
jruby byte order marker bug

### ISSUE THREAD

**Issue by pkieltyka** [sparklemotion/nokogiri#807]
Hello,

I've found an issue when using nokogiri 1.5.5 or 1.5.6.rc3 on JRuby.

Example..

data = IO.read("somefile.xml")
doc = Nokogiri::XML.parse(data)

.. this will just stall or raise an exception. The issue is that data[0] is actually a byte order marker in jruby, depending how the data is read.. so to resolve this, I have done:

data = data[1..-1] if data[0] && data[0].unpack('U') == [65279]

.. it works

**Comment by flavorjones** [comment]
Closing in favor of #1768 which has a pretty good discussion of why this behavior exists in the JRuby implementation, a potential workaround, and a potential path forward.
