### ISSUE TITLE
Bad XML causes Nokogiri to crash under JRuby 1.7.1

### ISSUE THREAD

**Issue by DanElbert** [sparklemotion/nokogiri#824]
Given this example of bad markup:
<pre>
&lt;?xml version='1.0'?&gt;<br/>&lt;root&gt;<br/>&lt;element&gt;&lt;![CDATA[<br/>]]&gt;&lt;/element&gt;<br/>&lt;<br/>]]&gt;&lt;/element&gt;<br/>&lt;/root&gt;
</pre>

Nokogiri will crash when attempting to parse it on JRuby 1.7.1.  This problem does not occur with MRI or JRuby 1.6.5.1.

This is the stack trace:
<pre>
null:-1:in `popElement': java.lang.ArrayIndexOutOfBoundsException: -1
	from null:-1:in `scanEndElement'
	from null:-1:in `dispatch'
	from null:-1:in `scanDocument'
	from null:-1:in `parse'
	from null:-1:in `parse'
	from null:-1:in `parse'
	from null:-1:in `parse'
	from NokogiriDomParser.java:94:in `parse'
	from XmlDomParserContext.java:249:in `do_parse'
	from XmlDomParserContext.java:236:in `parse'
	from XmlDocument.java:325:in `newFromData'
	from XmlDocument.java:339:in `read_memory'
	from XmlDocument$INVOKER$s$0$0$read_memory.gen:-1:in `call'
	from CachingCallSite.java:296:in `cacheAndCall'
	from CachingCallSite.java:72:in `call'
	from FCallManyArgsNode.java:60:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from IfNode.java:118:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:75:in `INTERPRET_METHOD'
	from InterpretedMethod.java:112:in `call'
	from DefaultMethod.java:154:in `call'
	from CachingCallSite.java:286:in `cacheAndCall'
	from CachingCallSite.java:81:in `callBlock'
	from CachingCallSite.java:85:in `call'
	from CallManyArgsBlockPassNode.java:57:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from ASTInterpreter.java:75:in `INTERPRET_METHOD'
	from InterpretedMethod.java:182:in `call'
	from DefaultMethod.java:188:in `call'
	from CachingCallSite.java:326:in `cacheAndCall'
	from CachingCallSite.java:170:in `call'
	from ./test.rb:8:in `__file__'
	from ./test.rb:-1:in `load'
	from Ruby.java:779:in `runScript'
	from Ruby.java:772:in `runScript'
	from Ruby.java:649:in `runNormally'
	from Ruby.java:498:in `runFromMain'
	from Main.java:375:in `doRunFromMain'
	from Main.java:264:in `internalRun'
	from Main.java:230:in `run'
	from Main.java:214:in `run'
	from Main.java:194:in `main'
</pre>

And here is Nokogiri's version output:

<pre>
$ nokogiri -version
# Nokogiri (1.5.6)
    ---
    warnings: []
    nokogiri: 1.5.6
    ruby:
      version: 1.9.3
      platform: java
      description: jruby 1.7.1 (1.9.3p327) 2012-12-03 30a153b on Java HotSpot(TM) 64-Bit Server VM 1.7.0_10-b18 [darwin-x86_64]
      engine: jruby
      jruby: 1.7.1
    xerces: Xerces-J 2.9.0
    nekohtml: NekoHTML 1.9.12
</pre>

Thanks,

--
Dan

**Comment by flavorjones** [comment]
Can't reproduce with modern JRubies and Nokogiris. Closing (and apologies for the lack of response for so long).
