### ISSUE TITLE
Nokogiri::HTML::Document.new("") produces different results in MRI vs JRUBY

### ISSUE THREAD

**Issue by wrightling** [sparklemotion/nokogiri#847]
In pursuing a bug with how [loofah](https://github.com/flavorjones/loofah) handles an empty HTML::Document in Jruby, I notice that Nokogiri::HTML::Document#new produces a different document in MRI than it does in Jruby.

Code to reproduce:
```
require 'nokogiri'
doc = Nokogiri::HTML::Document.new
doc.inspect
```

Run under MRI 1.9.3-p194, #inspect returns:
```
"#<Nokogiri::HTML::Document:0xba6ecc name=\"document\" children=[#<Nokogiri::XML::DTD:0xc0de74 name=\"html\">]>"
```

Run under Jruby 1.7.2 (1.9.3p327), #inspect returns:
```
"#<Nokogiri::HTML::Document:0x7d4 name=\"document\">"
```

Both cases were with Nokogiri v1.5.6.

The difference is not because of inspect, to be clear.  Inspect just highlights that in the MRI a blank document has one child, whereas in Jruby it has none.

When the same test is performed on Nokogiri::XML::Document, there is no difference between MRI and Jruby (both have zero children).

**Comment by flavorjones** [comment]
Closing, as it's not clear what, if any, real-world impact this difference has.
