### ISSUE TITLE
Nokogiri libxml2 error

### ISSUE THREAD

**Issue by derektono** [sparklemotion/nokogiri#850]
WARNING: Nokogiri was built against LibXML version 2.9.0, but has dynamically loaded 20900.0.0

this happens in ruby 1.9.2 and 1.9.3 .. it looks ilke its complaining about nothing as the versions look the same 2.9.0  && 20900.00  usual the error would be like  >=2.7.3 

Ive got the latest libxml2 as you can see  while this error can be ignored with some programs but with others it causes a lot of trouble and crashes spitting out errors

**Comment by flavorjones** [comment]
Closing, pending more information from original poster.
