### ISSUE TITLE
Nokogiri segfaults on OS X with libXML 2.9

### ISSUE THREAD

**Issue by davidinjc** [sparklemotion/nokogiri#855]
To reproduce using Ruby 1.9.3, run rake on OS X with libXML 2.9 installed. Works fine under libXML 2.7.8.

# Nokogiri (1.5.7.rc1)
    ---
    warnings: []
    nokogiri: 1.5.7.rc1
    ruby:
      version: 1.9.3
      platform: x86_64-darwin12.2.0
      description: ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.2.0]
      engine: ruby
    libxml:
      binding: extension
      compiled: 2.9.0
      loaded: 2.9.0

**Comment by flavorjones** [comment]
Closing, pending more information from OP.
