### ISSUE TITLE
Removing a namespaced attribute

### ISSUE THREAD

**Issue by retorquere** [sparklemotion/nokogiri#857]
Is it possible to remove a namespaced attribute? I can get the attribute using attribute_with_ns, but remove_attribute doesn't take a namespace parameter

**Comment by flavorjones** [comment]
Hi! Apologies for not responding for such an embarrassingly long time.

`Nokogiri::XML::Attr` inherits from `Nokogiri::XML::Node` and so you can use `Node#remove` to unparent the attribute just like you'd unparent any other node or element in the DOM.

Example of usage:

```ruby
#! /usr/bin/env ruby

require "nokogiri"

xml = <<~EOF
  <root xmlns:a="http://example.com/a">
    <foo a:size="large" />
  </root>
EOF

doc = Nokogiri::XML(xml)

attr = doc.at_css("foo").attribute_with_ns("size", "http://example.com/a")
attr.remove

puts doc
# => <?xml version="1.0"?>
#    <root xmlns:a="http://example.com/a">
#      <foo/>
#    </root>
```
