### ISSUE TITLE
CSS class selectors are not working with special characters

### ISSUE THREAD

**Issue by the8472** [sparklemotion/nokogiri#922]
Using nokogiri 1.5.9

```ruby
doc = Nokogiri::HTML("<html><body><div class='foo/bar'></div></body></html>")
doc.css('.foo\2F bar') #  => []
doc.css('.foo\/bar') #  => []
doc.css('.foo\00002Fbar') #  => []
```

According to the HTML5 spec any unicode sequence not containing space characters is a valid class name. And according to the CSS spec it should be possible to use escapes in selectors to match such sequences.

http://www.w3.org/TR/CSS2/syndata.html#characters
http://www.w3.org/TR/2011/WD-html5-20110525/elements.html#classes

**Comment by twalpole** [comment]
PR #1303 should fix this - been waiting for a while though

**Comment by flavorjones** [comment]
PR #1303 is targetted for 1.6.8, so labeling this story with that milestone.

**Comment by flavorjones** [comment]
PR merged to master.
