### ISSUE TITLE
NodeSet#dup needs deep/recursive option

### ISSUE THREAD

**Issue by Wardrop** [sparklemotion/nokogiri#924]
I library of mine has a requirement to duplicate a NodeSet before performing an operation on it, as to not modify the original document/NodeSet. I've found that it's virtually impossible to reliably clone a NodeSet, as the NodeSet instance itself, as well as the Node's it contains, all have a document reference which needs to be manually updated.

How difficult would it be to provide a deep/recursive option for NodeSet#dup, like what Node#dup has?

**Comment by flavorjones** [comment]
Please see the conversation at https://github.com/sparklemotion/nokogiri/issues/1678. If you need a deep copy, please duplicate the Document before creating the NodeSet.
