### ISSUE TITLE
Nokogiri::XML::Reader - Inconsistent Handling of Closing Tag for Empty Elements 

### ISSUE THREAD

**Issue by quoideneuf** [sparklemotion/nokogiri#928]
MRI and Java implementation do not seem to handling closing tags for empty elements the same way.

https://gist.github.com/lcdhoffman/5810508

(My 2c would go toward the MRI behavior, in which the closer does generate an event.)

**Comment by flavorjones** [comment]
Sorry I didn't respond to this before now. The gist no longer exists, so I don't know what the original issue was describing.

However, a few changes have been made to closing tags -- specifically XHTML -- in #2356 and #2326.

If there are still issues here, please open a new issue using the bug report template!
