### ISSUE TITLE
Not using system libraries by default

### ISSUE THREAD

**Issue by richo** [sparklemotion/nokogiri#936]
https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L87

This seems baffling, I would have thought that you'd surely need to opt into building a local copy of a library that has a reasonable history of security issues (that are fixed in a timely manner), unless there's a new nokogiri release after each one you're probably left with a broken lib.

**Comment by flavorjones** [comment]
@richo - Please check out #1220 which proposes some behavior changes to address these concerns.

**Comment by flavorjones** [comment]
I believe the concerns in this issue are covered in #1220 which is being worked on now. I'd like to close this and redirect conversation over to that issue. Please let me know if you have objections, else I'll close in a day or two.

**Comment by flavorjones** [comment]
Please keep in mind that you can install nokogiri using the `--use-system-libraries` option to force the use of installed system libraries. Currently this is opt-in, and I understand the objections to that behavior.

This behavior is being changed to not be strict opt-in or opt-out, but some nuance that is posted at #1220.

**Comment by fulldecent** [comment]
Recommend closing issue in favor of discussion in #1220.

**Comment by flavorjones** [comment]
Agree.
