### ISSUE TITLE
XSLT transformation not correct in JRuby (because of XPath?)

### ISSUE THREAD

**Issue by gioele** [sparklemotion/nokogiri#953]
In the gem xml-focus (https://github.com/gioele/xml-focus), Nokogiri::XSLT is used to transform an XML document using a dynamically created XSLT. Everything is fine when MRI Nokogiri is used. Under JRuby, the transformation returns an incorrect result caused by the fact that some XPath selects element that should not be selected.

An example file and a failing transformation can be seen running rspec inside the xml-focus source tree.

**Comment by flavorjones** [comment]
I'm sorry I haven't responded to this issue for such an embarrassingly long time.

Unfortunately, I couldn't get the xml-focus spec suite to run (I'm seeing some errors related to, likely, now-out-of-date RSpec API usage). If you can help me understand and reproduce what you're seeing, I might be able to help. Feel free to comment on this issue or open a new one.
