### ISSUE TITLE
test_reader_blocking is hanging on Debian kFreeBSD/GNU

### ISSUE THREAD

**Issue by boutil** [sparklemotion/nokogiri#965]
Hi,

While building packages for Debian, I noticed that test_reader_blocking from test/test_reader.rb, line 51 hangs on Debian kFreeBSD/GNU.

When running this test supposed to prevent issue #831, the process hangs, and does not reach after 
`wr.puts "<bar/>" * 10000`

Debian kFreeBSD/GNU is running a GNU userland above a kFreeBSD kernel.

**Comment by flavorjones** [comment]
Hi, thanks for reporting this, and apologies for not responding for such a long time. I'm unable to reproduce this right now, because I don't have a kfreebsd system available to me. If this is still an issue, please let me know and we can talk about how to reproduce and diagnose what's going on.
