### ISSUE TITLE
Segmentation fault for 1.6.0rc1 when using sucker_punch(celluloid) in Rails 3.2.13, ruby 2.0.0

### ISSUE THREAD

**Issue by ghost** [sparklemotion/nokogiri#973]
Also fixed by https://github.com/sparklemotion/nokogiri/issues/713#issuecomment-14208330

Here's a gist of my gemfile, my Terminal dump, and the crash report for Ruby. There are several other crash reports and they all look the same(except for different hexes).

https://gist.github.com/ciorga/7c1f65665746ca95fac6

The crash happened when sending emails in test and development with 

  config.action_mailer.delivery_method = :test

set in both. 

It crashed identically in RSpec with anything more than ~~40 emails being sent or in the browser with more than 50 emails being sent. For 10ish emails it was fine.

At some point I required nokogiri 1.6.0rc1 in my gemfile, at the top. It was still crashing. As far as I can tell only the top of the Mac error report changed, the following line:
Sleep/Wake UUID: 65A01C0F-8896-477A-9BE5-05B2F70A02C1

no longer appeared in the later reports. The UUID varied between reports.

After doing the fix in the first link everything runs fine even with 4-500 emails sending.

Maybe it'll help someone else debugging celluloid(?) issues, or maybe it was a weird thing wrong with my machine. Hopefully this is an ok use of an issue report :)

**Comment by flavorjones** [comment]
Sorry for not responding to this issue. I'm going to close it, since this version of Nokogiri is ancient at this point.
