### ISSUE TITLE
Nokogiri::XML::Reader#encoding and  Nokogiri::XML::Reader#xml_version giving wrong output

### ISSUE THREAD

**Issue by aruprakshit** [sparklemotion/nokogiri#980]
Hi,

I tried below code : 

```
require 'nokogiri'

reader = (<<-eoxml)
<?xml version="1.0" encoding="ISO-8859-1"?>
<root>
<node label="Session">              
      <node id="session_query1" label="DTM Buffer Size" />
      <node id="session_query2" label="Buffer Block Size"/>
      <node id="session_query3" label="Enable Test Load"/>
</node>
<node label="Workflow" >
     <node id="workflow_query1" label="Enable HA Recovery"/>
     <node id="workflow_query2" label="Suspend on Error"/>
</node>
<node label="Mapping" >
     <node id="mapping_query1" label="SQL Override in SQ " />
     <node id="mapping_query2" label="SQL Override in lookup" />               
</node>
</root>
eoxml

reader.instance_of? Nokogiri::XML::Reader # => true
p reader.xml_version
p reader.encoding
# >> nil
# >> nil
```

**Comment by flavorjones** [comment]
Hi, apologies for not responding on this issue for such an embarrassingly long time.

The `xml_version` attribute is only set once the reader has started reading. So if you update the example above to first do a `#read` (or read via `#each`) you'll see this populated.

```ruby
p reader.read.xml_version # => "1.0"
```

```ruby
reader.each do |node|
  p node.xml_version # => "1.0"
end
```

As for `#encoding`, it's a little trickier. Today this simply returns whatever is passed into the constructor (as @JunaidBKirkire mentioned above). There is a libxml2 function that will return the document encoding, and I'll play with that a bit to see if it works as we expect.

**Comment by flavorjones** [comment]
PR #2377 has been created to improve the behavior of `#encoding`
