### ISSUE TITLE
JRuby: Nokogiri::HTML::Document#internal_subset getter has side-effects

### ISSUE THREAD

**Issue by Mange** [sparklemotion/nokogiri#985]
Parsing a HTML document does not get a DTD. Trying to access it will create one and attach it, however. It will also be at the end of the generated HTML(!).

Here's a sample IRb session:

```
jruby-1.7.5 :031 > d = Nokogiri::HTML.parse("<html></html>")
 => #<Nokogiri::HTML::Document:0x8aa name="document" children=[#<Nokogiri::XML::Element:0x8a8 name="html">]>
jruby-1.7.5 :032 > d.to_html
 => "<html></html>"
jruby-1.7.5 :033 > d.internal_subset
 => #<Nokogiri::XML::DTD:0x8ac name="html">
jruby-1.7.5 :034 > d
 => #<Nokogiri::HTML::Document:0x8aa name="document" children=[#<Nokogiri::XML::Element:0x8a8 name="html">, #<Nokogiri::XML::DTD:0x8ae name="html">]>
jruby-1.7.5 :035 > d.to_html
 => "<html></html>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"
```
1. The inspection of the parsed document does not refer to a DTD
2. Generating HTML from it does not include a DTD
3. Accessing DTD returns a new DTD instead of `nil`, however
4. Now the DTD is part of the inspection
5. The DTD is included in the HTML, but at the end(!) of the string

Another fun thing is that you cannot create your own DTD to the parsed document either:

```
jruby-1.7.5 :036 > d = Nokogiri::HTML.parse("<html></html>")
 => #<Nokogiri::HTML::Document:0x8b2 name="document" children=[#<Nokogiri::XML::Element:0x8b0 name="html">]>
jruby-1.7.5 :037 > d.create_internal_subset "html", nil, nil
RuntimeError: Document already has internal subset
    from nokogiri/XmlNode.java:970:in `create_internal_subset'
    from (irb):37:in `evaluate'
    from org/jruby/RubyKernel.java:1121:in `eval'
    from org/jruby/RubyKernel.java:1517:in `loop'
    from org/jruby/RubyKernel.java:1282:in `catch'
    from org/jruby/RubyKernel.java:1282:in `catch'
    from /Users/mange/.rvm/rubies/jruby-1.7.5/bin/irb:13:in `(root)'
jruby-1.7.5 :038 > d
 => #<Nokogiri::HTML::Document:0x8b2 name="document" children=[#<Nokogiri::XML::Element:0x8b0 name="html">, #<Nokogiri::XML::DTD:0x8b4 name="html">]>
```

I suppose that `#create_internal_subset` tries to access the getter first.

---

C version of Nokogiri attaches an HTML4 doctype by default when parsing HTML, so I guess that would be the expected behavior.

Version: Nokogiri 1.6.0, JRuby 1.7.5

**Comment by flavorjones** [comment]
There is a NekoHTML setting that inserts the doctype (see http://nekohtml.sourceforge.net/settings.html) which we can try to use: `http://cyberneko.org/html/features/insert-doctype`. But there is a comment in the java implementation noting that this overrides the declared doctype declaration in some circumstances, so we should explore what this setting does.

**Comment by flavorjones** [comment]
OK, I mentioned this under #984, but Xerces does not allow users to modify the doctype, which greatly limits what we can do for your use case.

I'm going to close this as "wontfix", but I'm happy to revisit if someone can describe behavior that Xerces supports!
