### ISSUE TITLE
Nokogiri should include parser & writer implementations for stdlib RSS & XML-RPC

### ISSUE THREAD

**Issue by nogweii** [sparklemotion/nokogiri#990]
In the stdlib, RSS and XML-RPC both have interfaces for alternative XML parsers to be included. Right now, they both default to REXML and don't know about Nokogiri at all.

**Comment by flavorjones** [comment]
If someone who wants to maintain these interfaces wants to draft a PR and commit to long-term maintenance, I'm open to it. But really, these interfaces can exist just fine as separate gems.

In either case, I'm not planning to work on this, so closing as "not planned".
